### ISSUE TITLE
【调整】vip功能说明

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#1022]
@azothli commented on [Tue Jun 26 2018](https://github.com/tatfook/KeepWorkDesgin/issues/75)

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/482f0a85-0c9d-4182-9e48-fecba88628a2)
红色部分去除
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/760c45de-f7ab-493a-ada6-cdf5edd6b722)

**Comment by ZhangKaitlyn** [comment]
https://release.keepwork.com/wiki/vip
