### ISSUE TITLE
【Bug-layout】布局样式需要与布局参数配套对应，请优化调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1027]
## Detail:
   目前布局样式与布局参数不一致，会导致手机上的显示存在问题，请调整
![布局问题.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/9d0c3ed6-c4a3-4e5f-b158-a9b24ab320c6)

**Comment by ZhangKaitlyn** [comment]
解决方案：
![image](https://user-images.githubusercontent.com/18642919/41951438-86911198-79fd-11e8-9071-1f41ee811a4b.png)

**Comment by Sandu1213** [comment]
stage环境验证通过
