### ISSUE TITLE
[Lesson 系统] 功能完善-Package Mod：课程包Mod，编辑窗口，课程列表中，点击URL预览课程内容时，预览页将当前页面覆盖了。请修改为：弹出新的预览页面。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1037]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/8b0e828b-0912-4423-9aec-22b48ac8a14f)

**Comment by Sandu1213** [comment]
lessons-stage环境已经验证通过，会在新窗口进行预览
