### ISSUE TITLE
【lesson系统】功能完善-课程包详情页：未登录状态，点击“ADD”按钮时，弹出提示框“学习该课程包课程需花费1知识币”，点击“确认”后，又提示：请登录！该流程有误，应修改为：未登录状态，点击“ADD”按钮，直接提示：Sorry, please login! 点击课程封面图或课程标题时，也出现类似的情况。需修改为：未登录状态，点击课程封面图或课程标题时，直接提示：Sorry, please login! 

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1044]
未登录状态，点击“ADD”按钮时，弹出提示框“学习该课程包课程需花费1知识币”，点击“确认”后，又提示：请登录！该流程有误，应修改为：未登录状态，点击“ADD”按钮，直接提示：Sorry, please login!
点击课程封面图或课程标题时，也出现类似的情况。需修改为：未登录状态，点击课程封面图或课程标题时，直接提示：Sorry, please login! 

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/abb1ca39-ed98-4b87-a043-029827e620e5)

**Comment by shirleyluo1130** [comment]
@leopoldchen  @kevinxft  修改为：课程包详情页，未登录状态，点击“ADD”按钮/课程封面图/课程名称，都直接弹出“登录”窗口，无需提示“请登录”。

**Comment by Sandu1213** [comment]
直接弹窗登录窗口的功能还未实现，需要再调整

**Comment by shirleyluo1130** [comment]
redesign
