### ISSUE TITLE
【lesson系统】UI样式和文字修改-课程包详情页：已学完该课程包的所有课程时，按钮名称 Continue 修改为 Finished，按钮“View Summary”的样式修改，去掉下划线。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1047]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/6c921bb1-ee1d-4713-8dcd-a33dfbe2eea7)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/42443032-f0122a3a-839e-11e8-9994-b5c663a1767e.png)

**Comment by Sandu1213** [comment]
![lesson_packpage4](https://user-images.githubusercontent.com/21214285/42443075-11bc7ca8-839f-11e8-9626-bc01dfd067cd.png)
