### ISSUE TITLE
【lesson系统】功能完善-课程详情页：教师上完一堂课后，Summary菜单下内容显示如下：① 按钮“Print”点击后无反应，② 按钮“Change All”、“Change”点击后无反应，且提示文字缺失，③ 按钮“View Details”样式修正。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1050]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/26f5205a-36ad-481a-a4ea-ea756ff7fa17)

**Comment by leopoldchen** [comment]
print已修复

**Comment by Sandu1213** [comment]
还存在如下问题：
1.勾选学生后，点击“change"按钮，还未确定是否修改，数据已经调整了，请修改
2.修改数据后，再次查看detail信息，发现里面的内容没有变化，请调整

**Comment by shirleyluo1130** [comment]
补充：
未勾选学生，点击change按钮，提示如下，不合理，应先判断是否勾选学生，若勾选则弹出如下提示框，若未勾选，则提示为：Please select students. 请选择学生。
![image](https://user-images.githubusercontent.com/40385277/42616117-9894b3de-85df-11e8-8709-5b754b44d74c.png)

**Comment by Sandu1213** [comment]
问题依然没有解决。（release环境验证的）
预期情况：
1.没有勾选student，点击change,则提示“Please select students. 请选择学生”。
2.勾选student后，点击change，则提示“Are you sure you want to give full marks to the selected students?”，中文模式下提示：“您确定要将选中学生的准确率设置为100%吗？";
如果点击确定，则修改准确率，如果点击取消，则不做处理。（目前只要出现弹窗，数据就被修改了）
3.查看详情view Details，里面的数据还是未调整

**Comment by shirleyluo1130** [comment]
redesign
