### ISSUE TITLE
【lesson系统】功能完善-课程详情页：教师上完一堂课后，将summary菜单下内容发送到邮箱，点击“Send to Mailbox”按钮后弹出邮箱输入框，该输入框不可操作。详情如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1051]
① 输入框的“X”按钮点击无反应；
② “Send”按钮不可用：邮箱地址未输入或输入正确或输入错误时，点击 “Send”按钮后，该输入框会消失，但邮箱中没有收到对应邮件。
请修改为：
若邮箱地址未输入，点击“Send”，提示：Email address is required. 邮箱地址不能为空。
若邮箱地址不合法，点击“Send”，提示：Please enter a valid email address. 不是有效的邮箱地址，请重新输入。
若邮箱地址有效，点击“Send”，提示：The summary has been successfully sent to your mailbox. 课堂总结已成功发送至邮箱。
③ 色块蒙版建议覆盖整个页面。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/08b98e6e-882a-4d3c-b7ca-854c1fb7b89f)

**Comment by leopoldchen** [comment]
@shirleyluo1130 

若邮箱地址未输入，点击“Send”，提示：Email address is required. 邮箱地址不能为空。
若邮箱地址不合法，点击“Send”，提示：Please enter a valid email address. 不是有效的邮箱地址，请重新输入。
若邮箱地址有效，点击“Send”，提示：The summary has been successfully sent to your mailbox. 课堂总结已成功发送至邮箱。

部分验证功能后续迁到keepwork再做

**Comment by shirleyluo1130** [comment]
redesign
