### ISSUE TITLE
【lesson系统】UI样式-课程详情页：上课状态下，菜单“Students’ Performance”下显示实时答题情况，鼠标放置于测试题序号上时，显示对应测试题的文本内容，如下图：文本匹配题的内容超出了显示框。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1052]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/54a8fb76-0f1b-477f-ab67-3d4da449c561)

**Comment by leopoldchen** [comment]
![image.png](https://images.zenhubusercontent.com/59bb76d4b0222d5de477d44e/76b57287-7dbf-4764-9005-1cc92497ac50)

**Comment by Sandu1213** [comment]
stage验证通过

**Comment by shirleyluo1130** [comment]
@leopoldchen  @Sandu1213   文本匹配题的内容仍显示为超出了文本框，且未设置字体样式。其他题型都未出现该情况。
![image](https://user-images.githubusercontent.com/40385277/42615381-995c2052-85dc-11e8-80b6-6f32aef351d9.png)

**Comment by leopoldchen** [comment]
@kevinxft 
这个地方之所以样式失调，原因是里面这串文本自带样式。
有两种改法，一个是在录入试题的地方去除html标记；另一个是在显示的位置（图中）去除html样式

**Comment by Sandu1213** [comment]
stage验证通过
