### ISSUE TITLE
【lesson系统】功能完善-课程详情页：上课状态下，学生使用客户端答题的情况没有实时反馈给教师端。详情如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1053]
教师开了一个课堂后，学生通过Class ID进入客户端页面答题，如下图，共4道测试题，已全部答题完毕：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/d3485a48-f586-4ba1-a295-7887e9c65576)

但，在教师端的“Students’ Performance”菜单下显示学生的答题进度，只显示已答前3道题，Quiz 4显示未答。如下图：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/bddcf9e8-b549-44c6-a281-256dfe19a1a4)

**Comment by Sandu1213** [comment]
同问题 #1054
