### ISSUE TITLE
【lesson系统】功能完善-课程详情页：教师上课后，“Summary”菜单下显示的课堂总结数据与“Students' Performance”菜单下的数据不统一。详情如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1054]
教师开了一个课堂后，点击下课按钮，菜单“Students’ Performance”下显示最终的实时答题情况。如下图：（一个学生答了3道题，总题数为4道题）

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/5fede52d-f8fd-496e-bcde-5b87583405f1)

但，在菜单“Summary”下显示该学生4道题均未作答，如下图：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/62eb7047-46a7-4da0-9c89-eb8708cbef6d)

**Comment by leopoldchen** [comment]
![image.png](https://images.zenhubusercontent.com/59bb76d4b0222d5de477d44e/03719dfb-1c8b-4ba1-a90a-addb033da26d)

**Comment by Sandu1213** [comment]
答题信息可以准备反馈，但还不清楚studentNo如何生成？待确认
![image](https://user-images.githubusercontent.com/21214285/42555148-df3b1074-8519-11e8-84f5-c023a17099f1.png)

**Comment by shirleyluo1130** [comment]
学生在客户端输入CLASS ID，然后输入Name和Student No.，才能成功进入课堂。

Name和Student No.数据反馈给教师端。

**Comment by Sandu1213** [comment]
完成所有答题则统计正确；完成部分答题统计有误，请再排查
![image](https://user-images.githubusercontent.com/21214285/42555678-acf17f8e-851b-11e8-99ee-78ac923d42eb.png)

**Comment by leopoldchen** [comment]
@shirleyluo1130 

如果学生在考试中，应该无法查看统计的吧？
如果教师强制结束课程，那么那些quiz没做完的同学该怎么处理？强制交卷，还是停止交卷？

**Comment by shirleyluo1130** [comment]
@leopoldchen  下课后才可以查看summary。
如果教师点击“下课”按钮，统计中只记录学生在下课最后一刻的答题情况，学生可以继续在客户端答题，但是教师端不会统计之后的数据了。

**Comment by shirleyluo1130** [comment]
redesign
