### ISSUE TITLE
【lesson系统】UI样式-首页：首页内容注意排版，详情如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1063]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/ee3b0037-bc7d-4c92-80eb-ccd9d0ee9bab)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/321f7acd-624d-47ae-92ef-26b78845edc6)

**Comment by leopoldchen** [comment]
![image.png](https://images.zenhubusercontent.com/59bb76d4b0222d5de477d44e/919d7840-68bc-46bb-b56a-e38e67fce2c5)

图片资源比例不一致，请ui修改一下

**Comment by shirleyluo1130** [comment]
@leopoldchen   图片比例已修改好。
PS：student 和 teacher 的两个切图没有将文字切进去，文字样式请见源文件。另，注意中英双语。
![image](https://user-images.githubusercontent.com/40385277/42372293-71e75a10-8144-11e8-97f8-9de829a250d6.png)

**Comment by Sandu1213** [comment]
stage已验证

**Comment by shirleyluo1130** [comment]
@leopoldchen  @Sandu1213   漏掉了2个字段，2个图有白色色块。见下图：
![1](https://user-images.githubusercontent.com/40385277/42567957-096f9116-853e-11e8-9207-74a0436d0898.png)

正常是长这样 
![image](https://user-images.githubusercontent.com/40385277/42567924-f4457dbe-853d-11e8-80e1-886c70a7a810.png)

**Comment by leopoldchen** [comment]
@shirleyluo1130 

图中的白色色块是图片资源没有加透明通道，可以让ui设计师改一下

**Comment by shirleyluo1130** [comment]
@leopoldchen   teacher和student的2个切图已改好，请查收。切图中没有把文字切进去，文字样式见源文件。
![image](https://user-images.githubusercontent.com/40385277/42620001-4699e416-85ec-11e8-80b5-c6bb963e4b85.png)

**Comment by shirleyluo1130** [comment]
redesign
