### ISSUE TITLE
KEEPWORK部分页面修改

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#1065]
欧阳琛_项目 16:54:28
http://keepwork.com/official/pac2017ruwei/index
http://keepwork.com/official/pac2017jingxuan/index
http://keepwork.com/official/ultrashortvideo/index

欧阳琛_项目 16:54:42你好，这三个页面，修改好了吗

**Comment by lsx18** [comment]
部分页面
https://stage.keepwork.com/wiki/wikieditor/#/testv2/adsfhdfsh/index

**Comment by yq33z3069** [comment]
https://stage.keepwork.com/testv2/asdfhdfshsdh/index

**Comment by Sandu1213** [comment]
@ouyc  请帮忙验证，确定无误后就可以直接关闭。

**Comment by ouyc** [comment]
修改完成
