### ISSUE TITLE
【bug】打开编辑器，本账号浏览的应该是本账号的记录

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#1070]
![image](https://user-images.githubusercontent.com/28430070/42028844-1a4edc96-7b00-11e8-9a07-628a628984d4.png)

操作步骤：同一个浏览器 1.登录stage账号，浏览一二三，三个网页。然后退出账号。2.登录stage1账号，浏览三四五，退出账号。3.重新登录stage账号，打开编辑器，页面显示的是，不同账号的浏览记录

**Comment by Sandu1213** [comment]
操作：
1.分别打开不同的页面
2.在页面直接进行编辑，然后通过全部关闭按钮进行关闭
3.观察欢迎页上的文件打开记录
![image](https://user-images.githubusercontent.com/21214285/42146959-c218cc48-7dfd-11e8-95a2-7da452baec56.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/42317948-33d0390a-8080-11e8-9f05-2e534e129003.png)
