### ISSUE TITLE
【lesson系统】功能完善-顶部导航：增加登录/注册（个人中心）、切换语言 功能

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1073]

**Comment by leopoldchen** [comment]
@shirleyluo1130 设计好的话，在这边回复一下

**Comment by shirleyluo1130** [comment]
@leopoldchen  lesson导航已设计好 
![image](https://user-images.githubusercontent.com/40385277/42301704-5c7f7d8e-8049-11e8-8a52-00c6259dc295.png)

**Comment by shirleyluo1130** [comment]
@leopoldchen  导航重新调整了一下，请查收！见： https://assets.npl.lan:4403/svn/UI_resource/Lesson项目/lesson UI/补充页面/how.psd
![image](https://user-images.githubusercontent.com/40385277/42566220-7fa32f88-8538-11e8-9d97-498f68b32977.png)

**Comment by Sandu1213** [comment]
还需要完善：
![image](https://user-images.githubusercontent.com/21214285/42742173-747f2c2c-88eb-11e8-8eb0-8cc7538c2cf8.png)
![image](https://user-images.githubusercontent.com/21214285/42742200-aa53699e-88eb-11e8-822e-2ce33ce70aa9.png)

**Comment by shirleyluo1130** [comment]
redesign the system of lessons
