### ISSUE TITLE
【bug-导航路径】上传world后，paracraft网站名显示不对，显示为“用户名”了，请尽快修改

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#1074]
![image](https://user-images.githubusercontent.com/28430070/42071314-3d341b80-7b8d-11e8-98cf-1c1bb953f9ea.png)
![image](https://user-images.githubusercontent.com/28430070/42071337-543dbda4-7b8d-11e8-8626-162e8c199828.png)

**Comment by Sandu1213** [comment]
导航路径已经可以了。
但页面编辑器里的数据还需要刷新过来，目前全都是显示用户名了。
