### ISSUE TITLE
【lesson系统】功能完善-首页“热门课程”

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1077]
显示3个热门课程包，即据课程包的购买量显示TOP3的热门课程包。
由于暂无用户量，初版采用自定义设置的方式。初版一共只有3个课程包（动画、编程、NPLCAD），这里显示这3个课程包即可。

**Comment by leopoldchen** [comment]
这个得等发版新建好课程后才能做

**Comment by shirleyluo1130** [comment]
redesign
