### ISSUE TITLE
【bug】创建文件夹过多时，如图显示，需找产品确认文件夹创建过多时，如何显示

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#1097]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/03315877-a8ca-4f65-889a-a0cbd1f9e70c)

**Comment by Kvaya** [comment]
解决方案，建议按这样做：
![image](https://user-images.githubusercontent.com/39363297/45524395-c6d29380-b800-11e8-9e97-1bc23dbe482e.png)

**Comment by Kvaya** [comment]
优化建议补充：支持对左侧菜单面板进行宽度拉伸收缩功能，具体操作是：鼠标悬停在左侧菜单面板与中间预览区的中间空白区域，出现拉伸键，支持向左收缩向右拉伸菜单面板

**Comment by Kvaya** [comment]
创建文件夹过多时，不采用在网站菜单栏底部加滚动条的方式，用鼠标hover的方式，鼠标hover到文件夹或网页名称上，用hover把名称显示完。如：
