### ISSUE TITLE
WorldShare Mod PWD版本升级

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#1098]
PWD版本升级

**Comment by Sandu1213** [comment]
切换环境，文件不会丢失，但却无法进行登陆了
操作：
1.先登入keepwork账号，
2.切换到stage进行登入

**Comment by onedou** [comment]
stage for worldshare stage环境损坏使用online环境
stage for worldshare环境看这个issue #1153

**Comment by Sandu1213** [comment]
验证通过
