### ISSUE TITLE
小屏幕的左侧目录占用布局比值

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#1103]

**Comment by leopoldchen** [comment]
@wanglin727 @azothli 

百分比显示的话在小屏幕下，左侧工具栏可能就直接崩了。
如果左侧宽度可以手动变化，那么也需要有最小值设定，否则页面会很可怕。

另外，web版编辑器不需要支持手机，手机应该使用app来创作

**Comment by wanglin727** [comment]
屏幕宽度在1024px-----1920px内，左侧最小保持宽度320px
屏幕宽度    大于1920px 左侧宽度保持现有宽度

**Comment by Sandu1213** [comment]
同理，mod的显示也需要进行调整，请调整

**Comment by Sandu1213** [comment]
mod显示问题由 #1294 跟进
