### ISSUE TITLE
keepwork需在cookie中存储用户locale信息

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#1105]
为方便在后端获得当前用户的locale信息，需在cookie中添加此字段

**Comment by yuanoook** [comment]
![image](https://user-images.githubusercontent.com/7521814/42260581-9178c0de-7f97-11e8-9fbd-3b4916497f3b.png)

**Comment by Sandu1213** [comment]
local国内环境已经验证，海外环境待上线后再验证
![image](https://user-images.githubusercontent.com/21214285/42263788-9df75cee-7fa1-11e8-832e-0e62e92290ce.png)

**Comment by Sandu1213** [comment]
正常用户都是在首页就已经进行语言切换了，所以需要进入页面后就有对应的lang和locale信息

**Comment by yuanoook** [comment]
进入内容渲染页的时候，就会自动设置，可供 iframe 内嵌的 lesson 服务使用

**Comment by Sandu1213** [comment]
stage环境验证通过
