### ISSUE TITLE
文件管理器 - 调整复制及插入等操作的交互

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#1106]
由于我们把资源的应用调整为授权操作，即一个文件被应用到一个网站时，会生成一个唯一的链接，其他用户只能通过此链接来访问资源。也就是说，资源与网站是一种授权关系，而网站的权限由keepwork控制，因此我们就做到了资源的隐私限制，非常安全

**Comment by leopoldchen** [comment]
@azothli 

设计调整好后，直接 @yuanoook

**Comment by yuanoook** [comment]
复制操作已经调整如下

![image](https://user-images.githubusercontent.com/7521814/42368023-889550a2-8138-11e8-8560-82b4ac9af357.png)
