### ISSUE TITLE
【bug】具有编辑权限的用户，点击网站进行编辑，无法打开，编辑页面

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#1108]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/fa1aef42-6aee-4bf6-8e51-d2f6fd952bfd)

**Comment by Sandu1213** [comment]
stage环境验证通过，该问题仅出现下，用户没有创建网站但却拥有编辑网址权限的情况下
