### ISSUE TITLE
账户安全--修改密码

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#1116]
- 新密码验证：密码最少6位
![image.png](https://images.zenhubusercontent.com/59df33a4b0222d5de47b5b3c/fc4e5912-9c4c-41c3-b9dd-b2784a7c1d95)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/42440534-98fb315c-8398-11e8-9a33-55e38c756cb8.png)
