### ISSUE TITLE
实名认证

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#1118]
#### 已实名
![image.png](https://images.zenhubusercontent.com/59df33a4b0222d5de47b5b3c/29f60d01-8dc5-444b-b249-a516c8d724f4)
#### 未实名
![image.png](https://images.zenhubusercontent.com/59df33a4b0222d5de47b5b3c/10201a3f-b9b9-4507-aef9-bdfc0b2607f1)
![image.png](https://images.zenhubusercontent.com/59df33a4b0222d5de47b5b3c/c526e280-b216-4692-a9f5-1f4e44e72fb4)

**Comment by duting1993** [comment]
release 已验证
