### ISSUE TITLE
【Bug-bigfile mod】bigfile mod里没有选择视频或者图片的入口，请添加

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1120]
## The problem
bigfile mod里没有选择视频或者图片的入口，请添加

## Environment

* OS Info: Window10
* browser Info: chrome 67.0.3396.99
* URL: [keepwork.com](https://keepwork.com) 
* Model:  大文件

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入含有大文件的页面，选中大文件mod，对大文件进行设置，观察页面显示情况

* Expected Result:
1.可以正常的选择大文件，页面设置后显示合理
* Actual Result:
1.缺少大文件选择入口
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/132193d7-bfdb-45cb-9d2a-e524413cd373)

**Comment by onedou** [comment]
需要设计文件卡片
类似这样
![image](https://user-images.githubusercontent.com/3422640/42356040-badd5130-8102-11e8-9556-3372b540457e.png)

**Comment by onedou** [comment]
@wanglin727

**Comment by wanglin727** [comment]
https://github.com/users/wanglin727/emails/54923523/confirm_verification/80cef35a6e3b3fc003f0832d4b9d765fb08cc7d8

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/42367087-9674806a-8135-11e8-873a-883bccaefaf8.png)


svn源文件地址：![image](https://user-images.githubusercontent.com/33826048/42367175-e1bfea28-8135-11e8-9654-d35062a6f307.png)

**Comment by Sandu1213** [comment]
等#945 完成后再验证

**Comment by Sandu1213** [comment]
目前文件都可以以bigfile mod来插入，该问题关闭
