### ISSUE TITLE
添加多语言支持

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#114]
### 背景

旧版KeepWork已支持中英文，新版也需要提供相应的支持

### 目标
添加多语言支持

### 指标
- [ ] 当用户选择好语言之后，下次登录也能继续保持
- [ ] 所有的非用户内容一定在对应语言下显示对应内容

**Comment by leopoldchen** [comment]
@azothli @yuanoook                                               

在wikicraft的登录注册页面也需要处理中英文，并且在英文场景下需要调整第三方登录。

基本思路是在英文环境下，把Facebook、google等账号登录提前。建议参考为第三方登录设置一级和二级显示，把非当前语言环境的登录放入二级菜单。

另外，目前在登录注册时加了实名认证，这对于海外用户而言不现实，针对海外用户应该取消实名。这里存在一个难题，怎么判断用户是海外用户？（IP？）

**Comment by yuanoook** [comment]
多语言支持已经添加了，后面添加文字的地方，注意使用 $t("editor.save") 这种标记，并在 i18n 的对应翻译文件里面添加翻译 @onedou @ZhangKaitlyn

**Comment by onedou** [comment]
怎么添加？

**Comment by Sandu1213** [comment]
**1.mod 分类/显示代码/操作相关的提示语等还未处理**   
 @azothli  请确认是否满足需求，还有需要调整的地方么？
![multi_language](https://user-images.githubusercontent.com/21214285/39112567-736a4bd6-470b-11e8-9066-c9cbdb740625.png)

**Comment by azothli** [comment]
切换到英语模式下，要求没有中文显示
