### ISSUE TITLE
【lesson系统】内容完善

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1154]
1、首页-合作对象  ，内容已确定（原型和UI已同步更新）；footer使用keepwork的即可。如下图：
![footer](https://user-images.githubusercontent.com/40385277/42436054-4e94103c-838b-11e8-9f6f-5938efa717be.png)

2、“教师专栏”模块，获取激活码的联系方式为 lixizhi@paraengine.com 
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/1ae16642-50a0-4884-bee8-903a8c3aa8f7)

3、footer，使用keepwork的footer即可，每个页面都需加上footer

4、初次使用lesson系统赠送300知识币，程序上数值修改+提示文字中数值修改
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/d86fd7a6-ef0a-4439-bc69-b132f637fef8)
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/27f4fc32-1882-45a8-8072-005620363bdc)

**Comment by leopoldchen** [comment]
已完成2和4

**Comment by shirleyluo1130** [comment]
redesign the system of lessons
