### ISSUE TITLE
【lesson系统】功能完善 - lesson mod：课程详情页，菜单 Students' Performance 和 Summary 的位置反了，Students‘ Performance应在前，Summary应在后

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1157]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/be32ef51-b206-4205-8ec4-7060ca7f203e)

**Comment by Sandu1213** [comment]
stage环境验证通过
![image](https://user-images.githubusercontent.com/21214285/42442755-1cd1c338-839e-11e8-8511-6d50ea332c2f.png)
