### ISSUE TITLE
【lesson系统】功能完善 - 未登录时，点击“我的课程”/“教师专栏”两个模块时，直接弹出“登录”窗即可。当前的展现如下图所示，不合理。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1158]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/99c5a9e5-d352-4cdd-8301-2ae2d1a363d7)

**Comment by leopoldchen** [comment]
目前可以直接跳到登录页面，登录成功后会直接跳转回来

**Comment by shirleyluo1130** [comment]
redesign the system of lessons
