### ISSUE TITLE
Dashboard1.0 - 添加重置密码的功能

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#1168]
@azothli @William0911 

因目前用户密码重置功能不够便利，导致部分哈奇用户在忘记密码时只能找客服。
而在运营管理平台上又没有可以重置密码的功能，只能通过修改数据库来解决这个问题。

究其原因，一个是哈奇用户的密码重置流程需要调整，要清楚为什么会出现这种问题；第二个是在dashboard添加账号密码重置功能，在必要的时刻，可以由运营人员帮忙重置密码。

目前可以先在账户管理处添加重置密码功能，运营人员可以直接设置新密码。

**Comment by Sandu1213** [comment]
最近客服又反馈了使用忘记密码功能无法找回密码的问题。该功能完善的同时，请处理下找回密码的问题。
相关wikicraft issue #982

**Comment by leopoldchen** [comment]
在dashboard 2.0里完善，基于新版api

**Comment by William0911** [comment]
big已经在做2.0

**Comment by leopoldchen** [comment]
@Sandu1213 @ouyc 
这个issue是否可以关闭？
