### ISSUE TITLE
editor - 视频选择器

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#1177]
@azothli 

目前左侧编辑框里只支持通过图片管理器插入图片，缺少视频插入。
在lesson mod或者bigfile mod中都需要支持选择视频插入，因此需要新增此功能。

此处需要考虑的问题有：
1. 某些url即允许是视频也允许是图片，比如轮播。而某些可能只允许为视频或者只允许为图片。比如课程视频。
2. 如果视频选择器与图片选择器合并在一起，那么界面上怎么呈现，需要有设计。

**Comment by leopoldchen** [comment]
![image.png](https://images.zenhubusercontent.com/59bb76d4b0222d5de477d44e/f7185b81-3f3d-4e41-9dd1-f7ca9dece8df)

**Comment by azothli** [comment]
之前我们一直强调用外部视频，现在7牛可以很好的支持了，我们可以用自己的，增加一个视频的专门的mod吧
