### ISSUE TITLE
git page viewer完善

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#120]
### 背景

目前该页面footer样式存在问题，内容区也确实之前设计的navbar，需要一一修复。

### 目标

修复viewer页面

### 指标

- [ ] navbar
- [x] footer
- [x] mod列表显示
- [ ] 结合layout显示

**Comment by leopoldchen** [comment]
@ZhangKaitlyn @azothli 

直接按照旧的产品设计来实现

**Comment by leopoldchen** [comment]
旧的设计貌似不包含footer @ZhangKaitlyn

**Comment by Sandu1213** [comment]
1.菜单栏 ：功能/我的主页/网站管理/我的网盘 待实现（补充链接）
2.页面编辑器 路径跳转不对
3.点赞收藏功能不可用

**Comment by duting1993** [comment]
点赞功能可以使用，页面编辑器，跳转问题，见issue313
