### ISSUE TITLE
【Bug-海外版】海外版样式相关的问题汇总

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1203]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/113683d1-b2c7-45ac-b69b-2871808c9b83)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/e95f3d3d-a36c-4d1a-9d59-f505f2bd51f4)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/7f157ce1-2621-4ea8-9d23-19d51f151b7b)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/e61c4666-bc1d-4afb-bd80-8814cbf197f4)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/9c4d3d0b-437a-40f8-a686-d84a0a89ba74)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/e3258598-04d2-4b34-8c22-a3d8cc80b3bf)

**Comment by duting1993** [comment]
https://github.com/tatfook/keepwork/issues/1134
根据1134改
