### ISSUE TITLE
【Bug-lessons】已上课的课程再去编辑时，会出现多余的弹窗，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1239]
### 操作：
1.在课程页选中课程进行上课
2.再新开窗口，进入编辑器页面对课程内容进行编辑，进入编辑页面，打开课程
![lesson_source3.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/9c6f9d12-89e5-4738-93a2-a4d3c68f4bba)

**Comment by shirleyluo1130** [comment]
redesign the system of lessons
