### ISSUE TITLE
【bug】设置layout，添加布局参数，新添加的，面板里，不显示字样，只有默认的显示字样

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#1248]
![image](https://user-images.githubusercontent.com/28430070/42622784-cb688326-85f3-11e8-9ba0-31931d6fe22f.png)
![image](https://user-images.githubusercontent.com/28430070/42622802-d5fcc4aa-85f3-11e8-853c-7f4951e4b6db.png)

**Comment by yuanoook** [comment]
测试环境，release
