### ISSUE TITLE
【lesson系统】lesson在keepwork的入口调整

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1264]
1、将IICC的logo和文字替换为lesson的logo和文字，位置不变。
lesson的logo见：https://assets.npl.lan:4403/svn/UI_resource/Lesson项目/lesson UI/补充页面/lesson logo
文字为；Lessons  课程

2、轮播图中，增加lesson的banner，并放在第一显示。

**Comment by leopoldchen** [comment]
增加了登录登出

**Comment by Sandu1213** [comment]
描述的问题暂未处理，待稍后再验证

**Comment by shirleyluo1130** [comment]
redesign
