### ISSUE TITLE
APIService - Qiniu API 封装

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#128]
将旧的qiniu API重新封装

**Comment by yuanoook** [comment]
测试同学等 大文件的界面做好之后，再通过 UI 测试咯

**Comment by Sandu1213** [comment]
七牛部分功能已经可用，稍后根据验证情况进行补充说明

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/40635675-c76f8fd2-632d-11e8-9a2a-17884ef6a209.png)
