### ISSUE TITLE
【lesson系统】文字+样式：图1，文本匹配题，英文文本中使用了中文状态下的符号；图2，lesson mod，课程目标文本的第1行默认空了好几格

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1287]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/29b23c15-ef52-4d27-960c-523f20f6bd01)

![课程目标处，第一行文字自动空了好几格.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/0243f310-c5d7-4f7a-b239-1c080d492513)

**Comment by Sandu1213** [comment]
😢 , 问题依然存在

**Comment by Sandu1213** [comment]
空格问题已经解决，中英文字符的问题还需调整
