### ISSUE TITLE
新建网站

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#129]


**Comment by Sandu1213** [comment]
1.新建网站完成后，再次新建的时候不需要记录上次新建的网站名称
![image](https://user-images.githubusercontent.com/21214285/39032441-16084d66-44a0-11e8-8a41-baab4b154c12.png)

2.新建网站成功后的提示语不合理，请调整
![site_labels](https://user-images.githubusercontent.com/21214285/39032506-6a208454-44a0-11e8-9d19-ab30141c9131.png)

3.新建网站成功后，提示框的样式建议优化
![image](https://user-images.githubusercontent.com/21214285/39032588-c0071bda-44a0-11e8-9769-1cd109319116.png)

**Comment by yuanoook** [comment]
@Sandu1213 空白过多 这种主观感受就不要写在里面了 :D 参照设计稿
