### ISSUE TITLE
全新UI风格设计

### ISSUE THREAD

**Issue by yuki1206** [tatfook/keepwork#13]
在目前手机版的基础上，计划参照当下流行的WIN10扁平化风格重新设计，草图如下

**Comment by yuki1206** [comment]
![img_5442](https://user-images.githubusercontent.com/19921244/26930889-57796efe-4c91-11e7-96dc-d6fb520340a4.PNG)
![img_5443](https://user-images.githubusercontent.com/19921244/26930892-580c45d0-4c91-11e7-8f9d-8a97f0d6df2b.PNG)
![img_5444](https://user-images.githubusercontent.com/19921244/26930890-579af95c-4c91-11e7-9a11-af9d8cc212dd.PNG)

**Comment by yuki1206** [comment]
明天会议中希望确定是使用现在的风格，还是统一成WIN10风，如果确定了我们就着手修改全部UI，预计一个月内完成@LiXizhi 
![image](https://user-images.githubusercontent.com/19921244/26931833-596eed44-4c94-11e7-8694-00d2fa9be499.png)

**Comment by LiXizhi** [comment]
Effie你综合考虑各种因素来定。
