### ISSUE TITLE
创建新项目 git apiBaseUrl 使用配置地址

### ISSUE THREAD

**Issue by yuanoook** [tatfook/keepwork#1303]
stage-en 环境的用户，创建网站不成功

![ut5p7h8r wk0kf fv n](https://user-images.githubusercontent.com/7521814/42747286-667c52da-890e-11e8-9725-542b43a31156.jpg)

**Comment by wxaxiaoyao** [comment]
已经修改， stage-en创建项目成功即表示修改正确
