### ISSUE TITLE
【Bug-layout】新网站未设置logo时，进入查看，页面显示不美观，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1345]
### Details:
1.切换为英文模式，进入editor页面，然后选中一个网站进行网站设置操作
2.观察未设置logo时，页面的显示情况

**Expected Result:**
1.页面显示合理，没有大片空白

**Actual Result:**
1.页面显示不合理，请优化

**Attachment:**
![image](https://user-images.githubusercontent.com/21214285/42863867-1d060120-8a97-11e8-9008-fd4a096c9e37.png)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/42939064-085dbcc2-8b87-11e8-850f-2849b59e81eb.png)
![image](https://user-images.githubusercontent.com/33826048/42939175-50f846be-8b87-11e8-835b-f1319f3412f6.png)
原图svn

**Comment by yuanoook** [comment]
wikicraft 项目里面的文件已经替换，需要等上线生效

**Comment by Sandu1213** [comment]
请再确认
![image](https://user-images.githubusercontent.com/21214285/43066502-6a2aa8b2-8e97-11e8-9b92-3ef319199ff6.png)
![image](https://user-images.githubusercontent.com/21214285/43066458-4a6bd5c8-8e97-11e8-9200-97fc2be152dd.png)
