### ISSUE TITLE
【Bug-个人主页】个人主页相关问题汇总

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1349]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/79cae4f6-0b89-4ec2-bfcc-664910edd2f9)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/e4046075-4e3c-4f89-9dc6-7edddd96b22f)

**Comment by leopoldchen** [comment]
profile页面将重写
