### ISSUE TITLE
第三方登录功能

### ISSUE THREAD

**Issue by DDXY1230** [tatfook/keepwork#1361]

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/43175546-47587894-8ff2-11e8-8a1b-8bea316b14c2.png)

**Comment by Sandu1213** [comment]
还存在如下问题：
1.wikicraft页面第三方登录时，未绑定直接以空账号进入了
2.keepwork页面第三方登录时，绑定失败
- 备注：待wikicraft迁移后集中处理
