### ISSUE TITLE
【Bug-editor】markdown的锚点显示不对，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1362]
### Details:
1.进入editor，添加不同的标题，观察显示
2.在editor里添加锚点，观察显示

**Expected Result:**
1.添加为标题的，就只显示为标题
2.添加成锚点的，才显示链接图标

**Actual Result:**
1.只要是含“#”都被当成锚点了，实现不合理

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/b399ca7f-4471-4dcf-8d96-d8c860e03347)

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/42923575-b5e153e2-8b58-11e8-93a4-713f61ae25a6.png)

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/42926497-314ae1b4-8b64-11e8-96fd-65a80238b06d.png)

**Comment by Sandu1213** [comment]
release里面也是需要修改的呀
