### ISSUE TITLE
Dashboard1.0 - 用户管理 （修复）

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#137]
@azothli  @William0911 @wxaxiaoyao    
                                                                  
目前封号功能貌似存在问题，并且封号状态下的一些产品功能也需要确认

**Comment by William0911** [comment]
测试地址:   http://10.27.2.117:8099/

**Comment by Sandu1213** [comment]
@duting1993 验证的时候注意同步验证下账号关联的应用，如：魔法哈奇，paracraft，道峰科技等。
还有就是禁用后是否是立即生效，还是直到退出后下次登录才会生效。

**Comment by William0911** [comment]
魔法哈奇，paracraft，道峰科技等应用，如果通过 user/login 接口，且使用keepwork帐号登录的，在被封号的情况下，会返回错误信息(该帐号已被封禁)，无法获取token。但可能需自行对错误信息进行处理，否则用户可能不知道不能登录的原因。
