### ISSUE TITLE
更新worldshare模板

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#1428]
根据#510 提供的模板，更新worldshare上传模板

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/43821328-7ec074ce-9b1b-11e8-9784-f1cf1eddb8f8.png)

**Comment by Sandu1213** [comment]
新模板支持正常分享了
![image](https://user-images.githubusercontent.com/21214285/45148658-5cb36080-b1fa-11e8-8f47-5fa643ae4cc9.png)

**Comment by Sandu1213** [comment]
v0.7.388版本验证通过
