### ISSUE TITLE
【bug】全屏模式下无法对模块进行删除操作，弹窗不能显示在最前端

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#143]
图一全屏时
![image](https://user-images.githubusercontent.com/28430070/38543078-26a2b0ca-3cd6-11e8-9a57-302b12a532fa.png)
图二正常时
![image](https://user-images.githubusercontent.com/28430070/38543112-3c829266-3cd6-11e8-99cd-a0171c4d3487.png)

**Comment by ZhangKaitlyn** [comment]
去掉全屏功能，用自带的F11全屏代替
