### ISSUE TITLE
【lesson】课程包详情页，根据是否购买，教师身份（是否授课）/学生身份（是否学习），显示对应的页面。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1460]
见原型中：英文版

![image](https://user-images.githubusercontent.com/40385277/43263035-ae7bf708-9114-11e8-8886-25a214d838c2.png)

![image](https://user-images.githubusercontent.com/40385277/43953025-4f1ac138-9cca-11e8-81d1-b5517d88b189.png)

**Comment by leopoldchen** [comment]
Url: /students/market/packages/:id
local url: /student.html#/market/packages/:id

**Comment by shirleyluo1130** [comment]
课程包购买采用双定价方式，RMB价格+知识币价格，其中RMB价格由课程创建时设置，知识币价格由后台按RMB价格的10倍配置。

**Comment by shirleyluo1130** [comment]
![2](https://user-images.githubusercontent.com/40385277/44577803-8dd86d80-a7c4-11e8-877f-e57f5677f4bd.png)

**Comment by Sandu1213** [comment]
1.该页面信息展示还是不对，请调整
![image](https://user-images.githubusercontent.com/21214285/45196649-d9dce500-b28f-11e8-818f-4ae22d5baec6.png)

**Comment by ZhangKaitlyn** [comment]
view summary 在  issue #2008  处理
