### ISSUE TITLE
【Bug-Toc mod】toc mod导致页面显示有误，请处理

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1466]
### Details:
1.对含有toc mod的页面进行查看，观察页面显示是否正确 
2.对菜单列表点击查看，观察跳转是否正确

**Expected Result:**
1.页面显示正确，跳转合理

**Actual Result:**
1.页面跳转错误且页面显示不合理

ps:
[页面地址](https://keepwork.com/lixizhi/note/MovieInAI#deep-learning-%E4%BA%BA%E5%B7%A5%E7%A5%9E%E7%BB%8F%E5%85%83%E7%BD%91%E7%BB%9C)

**Comment by onedou** [comment]
测试地址
https://stage.keepwork.com/testv2/aaa/123123

**Comment by Sandu1213** [comment]
release环境已经验证通过
https://release.keepwork.com/release/1/12/14
