### ISSUE TITLE
【Bug-mod】添加一个board mod后，再添加第二个，无法使用

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#150]
## The problem
添加一个board mod后，再添加第二个，无法使用

## Environment

* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:  editor -> mod

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor页面，选择一个页面进行编辑，添加board mod 1成功后，再添加board mod 2,观察是否可以添加成功

* Expected Result:
1.提交成功，可以正常编辑
* Actual Result:
1.无法进行编辑，整个白屏
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/025d4085-cfff-4f3d-9009-6b2a34de83f9)

**Comment by onedou** [comment]
已更新master，请测试
