### ISSUE TITLE
【lesson】About 页面

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1500]
见原型：英文版-About
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/316f6beb-0095-47f0-81a1-be4b32b89531)

**Comment by shirleyluo1130** [comment]
![about](https://user-images.githubusercontent.com/40385277/44577868-bf513900-a7c4-11e8-9bcb-1a5fe20378c3.png)

![about2](https://user-images.githubusercontent.com/40385277/44577879-c710dd80-a7c4-11e8-8453-7600b05bc9d7.png)

![about3](https://user-images.githubusercontent.com/40385277/44577890-cd9f5500-a7c4-11e8-8f55-ea9f302ba990.png)

**Comment by Sandu1213** [comment]
stage环境验证通过，轮播图中文版显示问题已另外提单跟进，单号 #1773
