### ISSUE TITLE
【Bug-markdown】打开页面，直接选中代码区“markdown”内容时，左侧列表显示不合理，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1504]
### Details:
1.进入editor页面，打开有多个mod的文件，在代码区选中markdown mod，观察左侧列表展示
2.在代码区选中其他mod，再切换回markdown mod，观察左侧列表展示
3.关闭文件，重新打开，再次在代码区选中markdown，观察左侧列表展示
4.再在预览区选中markdown mod,观察左侧列表展示

**Expected Result:**
1. markdown mod只在预览区中选中及从其他mod切换过来时，才在左侧展示markdown属性栏

**Actual Result:**
1.直接在代码区选中markdown mod，左侧就显示了属性栏，处理不合理，请优化

**Attachment:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/dbd5fa52-10a1-4be0-aefb-54d11bca52c0)

**Comment by kevinxft** [comment]
@Sandu1213  release环境
