### ISSUE TITLE
【bug】添加图文叠加模块，点击预览，没有显示效果

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#153]
![image](https://user-images.githubusercontent.com/28430070/38547910-ec7757a4-3ce2-11e8-8e63-775d8c6a0006.png)
![image](https://user-images.githubusercontent.com/28430070/38547928-f9d2d626-3ce2-11e8-8f6c-69ea7519c912.png)

**Comment by ZhangKaitlyn** [comment]
@onedou 
![default](https://user-images.githubusercontent.com/18642919/38667210-6e812928-3e73-11e8-8e21-2741b0fb9662.png)

**Comment by onedou** [comment]
已经解决，但是full width的问题还在处理
