### ISSUE TITLE
board中英文问题

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#1532]
旧的版本支持中文，新版本只有英文

![image.png](https://images.zenhubusercontent.com/59bb76d4b0222d5de477d44e/e7b1d5b4-357a-4f83-85ea-608b74e331c1)

**Comment by Sandu1213** [comment]
Minimal theme还需要调整下
![image](https://user-images.githubusercontent.com/21214285/43710006-f59819a2-99a0-11e8-85c9-65e609713a4a.png)
