### ISSUE TITLE
【Bug-mod】添加board mod成功后，如果不添加内容，在预览页面及新窗口页都显示不对

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#154]
## The problem
添加board mod成功后，如果不添加内容，在预览页面及新窗口页都显示不对

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor页面后，创建新的页面,添加board mod，添加成功后进行保存，分别在预览页和新页面进行查看

* Expected Result:
1.页面信息显示正确
* Actual Result:
1.显示不合理
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/b06eec30-43ef-484d-afd3-3ee9221ea0ca)

**Comment by onedou** [comment]
已更新master请测试

**Comment by Sandu1213** [comment]
stage环境验证通过
