### ISSUE TITLE
网页模板功能

### ISSUE THREAD

**Issue by yuanoook** [tatfook/keepwork#1544]
新建网页支持选择网页模板，网页模板的库和图标，由产品和设计提供。

**Comment by yuanoook** [comment]
已经给到李宇看了，具体的模板和图片，需要李宇提供

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/43812958-4a04447e-9af6-11e8-88d2-81b5a6ed1385.png)

**Comment by Sandu1213** [comment]
release环境验证通过
