### ISSUE TITLE
【bug】添加图文叠加或者图片轮播大的mod，再添加qqmod ，保存，预览，qq会图片覆盖

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#156]
![image](https://user-images.githubusercontent.com/28430070/38548722-08708ea6-3ce5-11e8-9a1b-55064d59288d.png)
预览时
![image](https://user-images.githubusercontent.com/28430070/38548740-16a29564-3ce5-11e8-8a59-95c5918dd3cc.png)
保存，打开时
![image](https://user-images.githubusercontent.com/28430070/38548784-2fc9f758-3ce5-11e8-9662-ad9f3e079823.png)

**Comment by Sandu1213** [comment]
stage环境验证通过
