### ISSUE TITLE
【lesson】mod-lesson mod

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1570]
原型见：
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/60b3df0d-2bbd-42b6-a10c-24f9ff44a6bb)

**Comment by Sandu1213** [comment]
课程内容含图片或者大文件信息时，展示不对，请调整

**Comment by Sandu1213** [comment]
目前图片已经支持，但视频还不支持，看看是否够用 @shirleyluo1130

**Comment by shirleyluo1130** [comment]
要支持Paracraft 世界

**Comment by kevinxft** [comment]
现在已经支持Paracraft以及其他全部组件，但是在lesson中存在样式问题，暂时未找到原因
