### ISSUE TITLE
UndoManager base on text diff 

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#1620]
目前的undo manager一般都是直接保存完整内容，在undo和redo的时候直接返回对应版本的内容。
在简单的操作记录里是足够使用的，但是如果每次保存的是长篇文档，那就非常夸张了。比如一篇万字长文，如果在undo stack里存了100份，那就是100万字，很费内存。这个时候使用diff，只存储diff数据就会合算很多。

**Comment by kevinxft** [comment]
没有找到合适的方式提取diff，和根据diff还原文本
