### ISSUE TITLE
【Bug-mod】缺少markdown mod 入口，请补充

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#164]
## The problem
缺少markdown mod的入口，请补充

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor页面后，创建新的页面,添加markdown mod，观察添加是否成功

* Expected Result:
1.存在markdown mod
* Actual Result:
1.缺少markdown mod

**Comment by onedou** [comment]
margin 是什么mod? 是你之前做的那个吗？ @leopoldchen

**Comment by leopoldchen** [comment]
@azothli  markdown mod属于哪个分类？

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/38909392-0896ac18-42f7-11e8-9680-16c0c07f2917.png)
![image](https://user-images.githubusercontent.com/22001356/38909405-163926ac-42f7-11e8-93d1-414b1984f2ee.png)
