### ISSUE TITLE
【Bug-comment mod】但用户留言的数量大于10条后，只能查看最近的10条留言，实现不合理，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1661]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/70dc3330-8c62-4767-8d4d-7123683e6209)

**Comment by Sandu1213** [comment]
还存在以下问题：
1.输入空数据时，应该不允许提交。目前可以提交
2.当刚超过10条时，无法进行翻页操作，必须手动刷新页面
![image](https://user-images.githubusercontent.com/21214285/44249993-23a05580-a225-11e8-8b42-3a25bfceec22.png)
![image](https://user-images.githubusercontent.com/21214285/44249997-2b5ffa00-a225-11e8-959b-7a8a785ae9eb.png)

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/44456856-49b66300-a634-11e8-9b82-b9738f00a590.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/44457158-0b6d7380-a635-11e8-9de7-6f008a8a7e10.png)
