### ISSUE TITLE
消息队列 research

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#168]
@leopoldchen commented on [Tue Apr 10 2018](https://github.com/tatfook/KWPM/issues/3)

目前考虑试用kafka，但是对于其他的消息队列解决方案也需要有所了解。

### 目标

整合消息队列服务，解决md文件的es解析问题。后续考虑解决邮件等delay job问题。

### 指标

- [ ] 研究结果报告

**Comment by William0911** [comment]
关于消息队列的调查报告  http://keepwork.com/william0911/mq
