### ISSUE TITLE
【lesson】学生专栏 - 查看学习总结

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1705]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/66fff78c-e40a-48b7-b92a-b7a9dfec1f62)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/84b1dd87-195b-4cb9-a5fe-7b224745e942)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/45399547-10917180-b67b-11e8-89d4-9a523930b5e2.png)
