### ISSUE TITLE
【Bug-editor】在含有paracraft mod的两个markdown区域进行切换操作，切换卡顿太明显，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1709]
### Details:
1.新建一个页面，添加大量的markdown内容，然后通过paracraft mod将markdown分为2份。再分别在两个markdown区域进行切换，观察切换速度。

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/e95b83e7-c183-47cc-8c89-3a6a99e26343)

**Comment by leopoldchen** [comment]
应该是旧版的paracraft mod造成的，我这边加一下更新逻辑

**Comment by Sandu1213** [comment]
stage环境已验证，验证地址：https://stage.keepwork.com/functest/91bij/oldparacraft。

**Comment by Sandu1213** [comment]
release环境验证通过
