### ISSUE TITLE
TableDB Raft 集成测试

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#171]
### 背景

KeepWork后端在考虑逐步微服务化，旧是内嵌式tabledb不适合这种开发场景，因此需要尽快测试tabledb raft。可以借此机会测试tabledb raft，使之尽快投入使用。

### 目标
集成tabledb raft到wikicraft

### 指标
- [ ] tabledb raft可以部署在独立的微服务中，与KeepWork分离
- [ ] KeepWork可以正常的访问数据库，KeepWork服务可用
- [ ] raft集群稳定，部分slave宕机的情况下，依然可用。

**Comment by Xuntian** [comment]
已经部署在内网服务器，使用方法已告知 @William0911

**Comment by William0911** [comment]
以成功连通远程tableDB。下一步进行原tableDB功能测试。

**Comment by William0911** [comment]
tableDB Raft增删查改等功能已测试，下一步将模拟wikicraft场景进行测试
