### ISSUE TITLE
上传世界中断时Runtime error

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#1710]
[string "Mod/WorldShare/sync/SyncGUI.lua"]:66: attempt to call method 'SetBroke' (a nil value) <Runtime error>

![image.png](https://images.zenhubusercontent.com/59df2959b0222d5de47b59a3/eebdc58e-ea60-478c-bec0-cbbbe3152a43)

**Comment by Sandu1213** [comment]
在V0.7.386版本已验证，验证通过
