### ISSUE TITLE
【Bug-editor】打开页面后，第一次点击代码区，处理不合理，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1711]
### Details:
1.随意打开一个页面，将鼠标在代码区里进行滚动，滑动到下侧后点击进行编辑，观察是否可以正常编辑

**Expect Result:**
1.可以正常在指定区域进行编辑

**Actual Result:**
1.页面总数返回到了最前端，请处理

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/e394c6f6-a372-4a86-bc62-8f85601cb9cc)

**Comment by LiXizhi** [comment]
yes, this is urgent. I almost encounter it every time I edit a long article, pretty buggy.

**Comment by Sandu1213** [comment]
stage环境验证通过

**Comment by Sandu1213** [comment]
release环境验证通过
