### ISSUE TITLE
【bug】创意空间公众号链接错误问题

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#1729]
1.自动回复中文章链接引导错误
![image](https://user-images.githubusercontent.com/28430070/44453494-b8db8980-a62b-11e8-9081-317687a60a44.png)
![image](https://user-images.githubusercontent.com/28430070/44453516-c09b2e00-a62b-11e8-9528-3942edb18f1b.png)
2.每期作品发布文章链接引导错误
![image](https://user-images.githubusercontent.com/28430070/44453542-d4df2b00-a62b-11e8-91cd-127d3f70f4bb.png)

**Comment by LiXizhi** [comment]
www.paracraft.cn 会自动转到paracraft.keepwork.com 
所以并没有错
