### ISSUE TITLE
【bug】哈奇链接错误问题

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#1730]
![image](https://user-images.githubusercontent.com/28430070/44453578-ef190900-a62b-11e8-9dae-b8ba670b841f.png)
![image](https://user-images.githubusercontent.com/28430070/44453587-f5a78080-a62b-11e8-8970-d0a56ba0e9fd.png)

**Comment by LiXizhi** [comment]
暂时不修复了，因为魔法哈奇和并行世界,paracraft会合并掉。
