### ISSUE TITLE
text/mixLayer/mixPosition等使用markdown的mod默认文字无法显示

### ISSUE THREAD

**Issue by yq33z3069** [tatfook/keepwork#1760]
如题
![image.png](https://images.zenhubusercontent.com/59f2d0a58a75884b908506d6/1f00e034-2349-4dc9-bb9d-705202d7fc0b)
![image.png](https://images.zenhubusercontent.com/59f2d0a58a75884b908506d6/ea45c226-e37c-434f-9e2d-13bbe0830982)

**Comment by onedou** [comment]
清华好像已经修复

**Comment by Sandu1213** [comment]
stage环境不存在该问题，foshan环境还是存在，请知悉
