### ISSUE TITLE
去除 Media Component 宽度设置

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#1763]
![qq 20180827105237](https://user-images.githubusercontent.com/3422640/44638194-2ef33e00-a9e8-11e8-80bf-7c6b683c5e8f.png)

**Comment by leopoldchen** [comment]
这个是产品提的要求吗？其实宽度应该可以自适应的吧？

**Comment by onedou** [comment]
宽度设置是因为之前icon无法宽度，因为img mod和title mod 都是用的同一个media component，目前需要这连个分开，这样就可以宽度auto了

**Comment by Sandu1213** [comment]
stage.foshan已调整
