### ISSUE TITLE
Media Component UI更新

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#1764]
![image](https://user-images.githubusercontent.com/3422640/44638146-df147700-a9e7-11e8-9a61-4ed37d89650e.png)

**Comment by Kvaya** [comment]
建议：
1.建立统一的editor 设计系统，包括设计框架、UI工具包、组件库等设计规范集。用户快速了解产品结构及功能操作。
2.页面导航、宽屏图像、交互/调用QQ	聊天、混合搭配/页首导航、混合搭配/图文拼接、混合搭配/图文叠加、混合搭配/Paracraft作品、其他/Paracraft作品这些mod 元素图片更改统一按
![image](https://user-images.githubusercontent.com/39363297/44639103-ab881b80-a9ec-11e8-9f8d-45d14c386993.png)
修改
3.url设置有两个方式：①输入链接地址（和现在一样，用户可以直接输入）②下拉链接地址（本站网址各个选项进行选中）

**Comment by Kvaya** [comment]
上传的图片效果不扭曲 周边不留白 图片宽高跟mod尺寸需自适应 上传的图片跟mod无边距

**Comment by Sandu1213** [comment]
默认图片需要展示出来，而不是全灰显示
![style](https://user-images.githubusercontent.com/21214285/45532592-3b202d80-b827-11e8-9874-67212c1d2c9f.png)

**Comment by Sandu1213** [comment]
由 #2159 跟进
