### ISSUE TITLE
【Bug-lessons】lessons首页显示不合理，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1770]
### Details:
1.未登录状态下，进入lessons页面，观察页面显示情况
2.登陆状态下，进入lessons页面，观察页面显示情况

**Expected Result:**
1.页面显示合理

**Actual Result:**
1.页面显示不合理

**Attachment files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/c3c51197-09d5-46c6-86a4-17938c656885)

**Comment by Sandu1213** [comment]
问题依旧，请排查。

**Comment by Sandu1213** [comment]
![display_notall](https://user-images.githubusercontent.com/21214285/44964817-fd88ee00-af64-11e8-9ca7-2f3136784932.png)

**Comment by Sandu1213** [comment]
问题依旧：
可直接访问 [https://stage.keepwork.com/l/#/](https://stage.keepwork.com/l/#/)
如果本地可以验证通过，可以截图看下~

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/44970494-8ebb8d00-af84-11e8-9d50-78d08989a30e.png)

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/44973254-810b0500-af8e-11e8-90b5-fbf9d31496fc.png)

**Comment by Sandu1213** [comment]
stage环境依然存在，该问题稍后再验证。
![image](https://user-images.githubusercontent.com/21214285/44974820-5b342f00-af93-11e8-8db6-16396b4ae07e.png)

**Comment by Sandu1213** [comment]
stage环境验证通过
