### ISSUE TITLE
【Bug-Lessons】About页面的中文版，轮播图信息显示不合理，需调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1773]
### Details:
![2](https://user-images.githubusercontent.com/21214285/44699143-667bec00-aab5-11e8-9e31-964714a07055.png)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/44768749-e9c03f00-ab94-11e8-851d-f06b6470463e.png)

svn中文海报地址

**Comment by Sandu1213** [comment]
stage环境验证通过
