### ISSUE TITLE
【Bug-lessons】生成的课堂总结内容信息显示不合理，需调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1785]
![lessons_summary](https://user-images.githubusercontent.com/21214285/44705375-0b57f280-aad1-11e8-934a-fcf2da123dbb.png)

**Comment by shirleyluo1130** [comment]
![image](https://user-images.githubusercontent.com/40385277/44717493-b4154a80-aaef-11e8-894e-c2132a198eb3.png)

![image](https://user-images.githubusercontent.com/40385277/44717761-87adfe00-aaf0-11e8-90d0-84dcd2fd3211.png)

![image](https://user-images.githubusercontent.com/40385277/44717917-fee39200-aaf0-11e8-9d4f-2ba01c67b397.png)
