### ISSUE TITLE
【Bug-目录树】选中文件进行刷新操作，刷新效果与预期不符

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#180]
## The problem
打开多个文件后，将文件A进行关闭，然后在已打开列表下选择文件B进行刷新，刷新效果不对

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor页面后，选中多个文件进行打开操作，将其中的一个文件进行关闭，然后再文件B进行刷新操作，观察刷新是否成功

* Expected Result:
1.刷新操作仅影响操作的文件
* Actual Result:
1.刷新操作影响了所有文件

## Attachments (eg:logs/video/screenshot)
![refresh](https://user-images.githubusercontent.com/21214285/38613980-33239ac4-3dbe-11e8-9fae-c037299f1486.gif)

**Comment by leopoldchen** [comment]
@azothli 此处的交互需要梳理

**Comment by duting1993** [comment]
stage已验证
