### ISSUE TITLE
【Bug-editor】editor里需要对Enter 键进行支持的地方汇总

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1803]
### Details:
     考虑到用户使用的便捷性，需要支持Enter键的响应，目前editor 里处理不合理，请调整。
![enter_noreply7](https://user-images.githubusercontent.com/21214285/44768457-f42e0900-ab93-11e8-9e67-f49299f27fa5.png)

![enter_noreply5](https://user-images.githubusercontent.com/21214285/44768460-f55f3600-ab93-11e8-80f2-b0d2bf4cc2bb.png)
![enter_noreply4](https://user-images.githubusercontent.com/21214285/44768461-f5f7cc80-ab93-11e8-8cf5-62d3a201adbb.png)
![enter_noreply3](https://user-images.githubusercontent.com/21214285/44768463-f6906300-ab93-11e8-806c-918deda25d63.png)

![enter_noreply](https://user-images.githubusercontent.com/21214285/44768466-f728f980-ab93-11e8-8563-be46de134594.png)

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/50760160-f91d6a80-12a1-11e9-8e36-c44afe1994f9.png)

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/50760281-4994c800-12a2-11e9-8f3c-ed685a371197.png)

**Comment by DDXY1230** [comment]
除了上述的情况，其他的回车事件已添加
