### ISSUE TITLE
【Bug-lessons】学生的课程详情页（自学+进入课堂）：学生作答文本匹配题时，应禁用 复制粘贴  功能。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1806]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/e944433e-6b2f-4d5b-9393-7193c6647d1e)

**Comment by Sandu1213** [comment]
问题依旧，而且该问题需要考虑不同的浏览器。请重新调整

**Comment by kevinxft** [comment]
@Sandu1213 大哥，不行你也说下是什么浏览器啊😂😂
