### ISSUE TITLE
【Bug-目录树】在不同的文件中切换时，中间的预览区显示不对

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#181]
## The problem
在不同的文件中切换时，中间的预览区显示不对

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor页面后，选中多个文件，在不同的文件之间进行切换，观察效果

* Expected Result:
1.切换后效果显示正确
* Actual Result:
1.切换后效果显示不对
 

## Attachments (eg:logs/video/screenshot)
![selectdiffpage](https://user-images.githubusercontent.com/21214285/38614403-9adb85c2-3dbf-11e8-881b-d7eb3b90aded.gif)

**Comment by duting1993** [comment]
stage验证通过
