### ISSUE TITLE
【Bug-menu mod】采用menu style1的菜单栏出现不合理的点击区域，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1811]
### Details:
 对paracraft[介绍页](https://keepwork.com/official/paracraft/index)进行访问,选中“教学视频大全”进行查看，观察menu 样式实现是否合理

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/5148280c-2579-4090-a0f8-b858b1ea6461)

**Comment by yq33z3069** [comment]
https://stage.foshan.cf

**Comment by Sandu1213** [comment]
stage.foshan 环境验证通过，非文字区域点击后也可正常跳转
