### ISSUE TITLE
【Bug-lessons】自学答题完成后，查看答题情况的浮窗显示不美观，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1813]
![page](https://user-images.githubusercontent.com/21214285/44777782-087eff80-abae-11e8-88c6-df5a07f53d69.png)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/45743055-df421400-bc2d-11e8-9dd5-8fef18a82b62.png)
