### ISSUE TITLE
【Bug-lessons】目前添加的课程视频还是无法播放，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1814]
![image](https://user-images.githubusercontent.com/21214285/44778252-14b78c80-abaf-11e8-924a-9c52b0d92e8a.png)

**Comment by Sandu1213** [comment]
与 #2032 有关，待解决后一起验证

**Comment by Sandu1213** [comment]
外部链接验证不通过，测试了优酷及youtube的视频链接
附：
https://v.youku.com/v_show/id_XMzgwNjg4Mzc2NA==.html?spm=a2hww.11359951.m_26673_c_32078.5~5!2~5!3~5~5~A

**Comment by kevinxft** [comment]
不能用外部链接的吧，这不就是盗链了？

**Comment by Sandu1213** [comment]
优酷视频可以，youtube视频暂时不行。
