### ISSUE TITLE
【bug-lessons】About 页面-样式问题

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1816]
热门课程包的显示有问题。建议与课程中心的课程包展现统一下，
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/e18f6237-06c3-4755-94e8-939eb6d1b685)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/c3b7c00a-5d9a-44a4-9b11-758c6cafecd2)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/8db0efc9-f409-4966-8f1d-2e41dce3426d)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/f52723d3-d924-4be2-9ceb-597c5a5b0aee)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/b207ec33-f54a-4285-a6b8-f60756f43b6a)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/44972512-02ad6380-af8c-11e8-9fc6-f64d490d96c4.png)
![image](https://user-images.githubusercontent.com/21214285/44972525-09d47180-af8c-11e8-8513-cd0edeb74e05.png)

**Comment by Sandu1213** [comment]
stage环境已验证，因为白底，所以目前图片都是没有水印的。
