### ISSUE TITLE
【Bug-lessons】学生在学习过程中切出课堂，随后课堂下课后，学生无法再查看其他的课程信息，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1825]
![dismiss_lesson141](https://user-images.githubusercontent.com/21214285/44783372-c610ef00-abbc-11e8-8441-8decae5f8b0b.png)

**Comment by Sandu1213** [comment]
问题依然存在 😞

**Comment by kevinxft** [comment]
不存在的

**Comment by Sandu1213** [comment]
目前有课堂结束通知，该问题已解决
