### ISSUE TITLE
【bug-lessons】不同浏览器，页面显示的字体不一样。请排查。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1826]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/c25a6cff-986f-46c4-a518-564799d9aa57)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/6df9b052-b490-4038-86c0-2ef84a12e40b)

**Comment by Sandu1213** [comment]
![font_family34](https://user-images.githubusercontent.com/21214285/45272746-b01afc80-b4e1-11e8-8321-1666827d3c58.png)
