### ISSUE TITLE
【lesson】教师专栏-Lesson Management-lessons：课程管理

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#1839]
![image.png](https://images.zenhubusercontent.com/5ac352dc4b5806bc2bcd6b02/5aceeb4d-4324-4bad-85eb-63d90f317fad)
![image.png](https://images.zenhubusercontent.com/5ac352dc4b5806bc2bcd6b02/35a7c90f-ac1f-45d5-8d7a-73cd84b04438)

**Comment by Sandu1213** [comment]
1.已移除还存在问题
