### ISSUE TITLE
【lesson】打印的内容

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#1845]
见原型图框出部分：
![image.png](https://images.zenhubusercontent.com/5ac352dc4b5806bc2bcd6b02/42bc301b-5cdc-4cff-a097-5befb1feaf91)

**Comment by Sandu1213** [comment]
目前打印内容是死的，稍后需要调整；
直接从课堂结束页面无法打印，需调整（目前必须进入评估的课堂总结才能打印）
