### ISSUE TITLE
【WorldShare-bug】当世界为zip文件时，进入世界不默认是提示信息，分享时才显示

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#1861]
![image.png](https://images.zenhubusercontent.com/59df2959b0222d5de47b59a3/21474fa5-e5ce-4d70-a274-21560335096d)

**Comment by Sandu1213** [comment]
目前提醒如下：
![image](https://user-images.githubusercontent.com/21214285/45147829-6fc53100-b1f8-11e8-9c2e-0b68e1b9c9de.png)
