### ISSUE TITLE
【Bug-lessons】新建课程包时，设置课程包的封面采用选择文件的方式设置不成功

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1879]
![set_cover_pac.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/ddb79350-eb19-4c0e-91e5-7e5364366ad9)

**Comment by leopoldchen** [comment]
由于旧的组件实现不够好，这个功能目前做起来比较费时，先往后放

**Comment by Sandu1213** [comment]
stage环境验证通过
