### ISSUE TITLE
【Bug-lessons】hit mod采用文本框进行内容输入时，会出现存储的内容与设置的不符，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1880]
![text_discontect6.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/afba8fd4-4aa8-4e54-a0bb-ca54228fc10b)
![text_discontect5.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/fb42d039-91dd-4fa8-a54f-b6fe73c8011b)

**Comment by onedou** [comment]
与 #2034 冲突

**Comment by Sandu1213** [comment]
通过 #2034 来跟进，该issue关闭
