### ISSUE TITLE
【lesson】免费课程包的详情页如下图展示，点击“ADD”后，直接提示：The package is successfully added. (课程包添加成功。)即可。不需进入购买信息确认页。

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#1899]
![image.png](https://images.zenhubusercontent.com/5ac352dc4b5806bc2bcd6b02/2fee2283-8e5f-4608-96cc-efecb1cfc5fe)

**Comment by Sandu1213** [comment]
请再排查
![image](https://user-images.githubusercontent.com/21214285/45288157-964adb00-b51c-11e8-8197-3f593f353e35.png)
