### ISSUE TITLE
【需求】登录检查、提示调整

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#190]
@azothli commented on [Tue Feb 27 2018](https://github.com/tatfook/wikicraft/issues/1677)

登录keepwork，验证是否有用户名，没有则提醒创建。

---

@wanglin727 commented on [Mon Mar 05 2018](https://github.com/tatfook/wikicraft/issues/1677#issuecomment-370383739)

设计已完成  dai待开发

---

@wanglin727 commented on [Tue Mar 06 2018](https://github.com/tatfook/wikicraft/issues/1677#issuecomment-370635032)

![image](https://user-images.githubusercontent.com/33826048/37010236-961875e2-2125-11e8-804e-687918eea73c.png)

**Comment by azothli** [comment]
为了满足第三方注册的账号登录kp的问题
