### ISSUE TITLE
【Bug-lessons】自学完成后进行分享操作，分享无法预览大图

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1901]
### Details:
![share_normalsize.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/38420172-4283-4694-a2ac-0af76f043b95)

**Comment by Sandu1213** [comment]
目前已经可以预览看到大图，但样式有点丑，请看看是否符合要求  @shirleyluo1130

**Comment by shirleyluo1130** [comment]
建议最好在当前弹框页面可直接预览大图。若考虑到小屏幕无法实现的问题，可将小图中的文本内容稍微调大一些，增加可读性，去掉预览功能也可。
![image](https://user-images.githubusercontent.com/40385277/45074712-1e914080-b117-11e8-8701-3e5ea0bf0c15.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/45405462-860a3b80-b695-11e8-93c7-7cd9a2087c41.png)
![image](https://user-images.githubusercontent.com/21214285/45405510-be117e80-b695-11e8-86d2-5bf5b7afb93b.png)

**Comment by Sandu1213** [comment]
问题依然存在，请完善

**Comment by Sandu1213** [comment]
请微调
![image](https://user-images.githubusercontent.com/21214285/45484834-0d37dc00-b788-11e8-907c-7bfd020bcd92.png)
