### ISSUE TITLE
【Bug-lessons】课程包提交失败及被拒绝后的处理不合理，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1905]
### Details:
![package_submit.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/ed044625-9041-4efe-8090-a2991b4ac588)

**Comment by leopoldchen** [comment]
添加了extra.message

**Comment by Sandu1213** [comment]
失败提交的情况还是缺少提醒，另外提单跟进
