### ISSUE TITLE
【Bug-lessons】学生未答完题，直接退出lessons系统时，提示语存在歧义

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1910]
### Details:
1.学生进入课堂进行答题，答完一半题目后，直接退出系统，观察结果

**Expected Result:**
1.退出成功，答题记录正确，页面无其他提醒

**Actual Result:**
1.退出时提示课堂已结束，但实际课堂还在继续中，存在歧义

![image](https://user-images.githubusercontent.com/21214285/44978951-722c4e80-af9e-11e8-896c-b23efb5214fa.png)

**Comment by Sandu1213** [comment]
@shirleyluo1130 请帮忙看看，这种情况下退出是否直接默认退出成功即可还是需要给个响应的提醒？

**Comment by shirleyluo1130** [comment]
可直接退出成功，不需要提示。（因为再次登录，进入该课堂后，之前的作答记录会保留。）

**Comment by Sandu1213** [comment]
登陆态有问题，无法正常验证，待登陆态问题调整好了再验证。
