### ISSUE TITLE
【Bug-lessons】中文模式下，进入课堂，输入名字框请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1912]
### Details:
![enter_classroom.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/98d5c5a2-6be4-4b71-ac28-5c80f409b41a)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/45017040-15da3500-b059-11e8-93d1-8e1534cf0295.png)

**Comment by Sandu1213** [comment]
stage环境验证通过
