### ISSUE TITLE
【bug-lessons】TEACHER COLUMN-REVIEW：文字问题+实现问题，详见下

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1936]
![2、功能实现.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/89d6923b-a4ce-47c7-b7f8-818244fe049c)

![1、文字.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/4dbd3732-e481-4d56-8f70-1e4bb4d7957b)

**Comment by Sandu1213** [comment]
- 问题1：文字描述错误
![image](https://user-images.githubusercontent.com/21214285/45077846-e262dd80-b120-11e8-887b-c71ad96b0b93.png)
- 问题2：课程封面图显示不对
![image](https://user-images.githubusercontent.com/21214285/45077934-2b1a9680-b121-11e8-96f8-a750daa16c17.png)

- 问题3：点击“课程名称”后，直接跳转课程详情页面页首，目前直接跳转答题区域
![image](https://user-images.githubusercontent.com/21214285/45078107-b2680a00-b121-11e8-80ae-798f946e3c2e.png)

**Comment by DDXY1230** [comment]
问题2，之前的课程显示的封面是课程包的封面，以后的课显示的是课程的封面

**Comment by Sandu1213** [comment]
问题3依然存在，其他问题已解决，待稍后观察
