### ISSUE TITLE
【Bug-lessons】教师专栏里的授课记录重复了，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1945]
### Details:
![record_repeat.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/63d039d3-a024-4799-b3ab-58becccc3b3d)

**Comment by duting1993** [comment]
操作步骤：1.教师建立一个课程包，建立成功后，显示在授课里
2.点击，课程中心，在买之前建立的课程包
3.购买完成后，上课，就会出现，有两个课程包，两个相同的时间

**Comment by duting1993** [comment]
已解决
