### ISSUE TITLE
【lesson-bug】课程发送email，提示语，需产品确定

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#1947]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/1cd60097-4daf-4926-a9a8-c7c9a07de950)

**Comment by shirleyluo1130** [comment]
两个提示语可合并：
The summary has been successfully sent to the mailbox (465279293@qq.com).

**Comment by Sandu1213** [comment]
stage验证通过
