### ISSUE TITLE
【Bug-lessons】课程包和课程菜单名缺少英文版，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1969]
### Details:
![package_language.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/19f6bf7a-d90a-469d-b579-401ef2af257e)

**Comment by shirleyluo1130** [comment]
![image](https://user-images.githubusercontent.com/40385277/45146371-579fe280-b1f5-11e8-8c99-dd2d784233a5.png)
