### ISSUE TITLE
【bug-lessons】About-致家长和教师的一封信：如下

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1973]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/0b7f7cc4-27a3-4b5c-a28a-8d4c39b76a53)

点击显示如下：
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/a336cd5f-61a7-4ccc-a238-667b57434cfe)

**Comment by shirleyluo1130** [comment]
英文版，点击“here”，跳转到了 About 顶部。请修改。
![image](https://user-images.githubusercontent.com/40385277/45194009-b90e9280-b283-11e8-9c2c-71b780ed3230.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/45288485-5df7cc80-b51d-11e8-982a-ff3acdc744c2.png)

**Comment by Sandu1213** [comment]
release is ok
