### ISSUE TITLE
【Bug-paracraft】新建world进行分享，分享后打开，发现远端的版本总是比本地的少一个版本，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1985]
### Details:
1.用户登陆后，打开一个wolrd，然后打开菜单栏，再新建一个world，新建成功后，去分享，分享成功后，直接打开，然后观察上传的世界与实际世界的差别
![world_no_same](https://user-images.githubusercontent.com/21214285/45148419-d139cf80-b1f9-11e8-8939-26199657cc51.png)

**Comment by onedou** [comment]
是没有保存世界的原因，在分享前提示用户保存世界

**Comment by Sandu1213** [comment]
问题依旧，请再排查

**Comment by Sandu1213** [comment]
之前由于worldshare包未更新到，更新成功后，验证通过
