### ISSUE TITLE
【bug-lessons】学生的课程详情页-进入课堂：姓名编辑状态的展现不对，请调整。如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1992]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/01d5e120-b9f2-4d64-a964-1d34ddc0fc00)

**Comment by leopoldchen** [comment]
取消是否需要保留?

**Comment by shirleyluo1130** [comment]
只需要 保存按钮（√） 即可。

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/45419316-93d1b800-b6b9-11e8-85dd-a9df1b834667.png)
