### ISSUE TITLE
【bug-lessons】教师的课程详情页：上课中，教师端无法正常读取学生的答题数据。如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#1994]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/5d489151-2fe6-4aa8-956f-bfdc9cf3ee6e)

**Comment by leopoldchen** [comment]
结束课程时需要刷新数据 @kevinxft

**Comment by leopoldchen** [comment]
需重现一下 @Sandu1213
