### ISSUE TITLE
【bug-lessons】教师专栏-课程管理：编辑课程页，未做任何修改，点击“保存”，提示：课程包名称已经存在。？？？（当前，该课程还未加入任何课程包）

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2004]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/1ce569d5-b95c-453b-95f6-bc543b56483c)

**Comment by Sandu1213** [comment]
问题依然存在，请再调整
