### ISSUE TITLE
【bug-lessons】TEACHER COLUMN-Lesson Management：课程管理，删除课程，弹出如下提示框，按钮有误，请修改。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2011]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/1ff98860-9cd8-4a99-b03c-5d737d1c541b)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/45468943-dcd94900-b759-11e8-954c-25e16739daa6.png)
