### ISSUE TITLE
【bug-lessons】TEACHER COLUMN-Lesson Management：新建课程/编辑课程页，如下图，请调整。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2014]
![image](https://user-images.githubusercontent.com/40385277/45203897-2e905800-b2b0-11e8-9542-6522c71a5228.png)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/53788264-447b8e80-3f5c-11e9-92a7-85c8c9208c85.png)
![image](https://user-images.githubusercontent.com/28430070/53788273-4ba29c80-3f5c-11e9-86dc-bec094117ef4.png)
没有翻译
