### ISSUE TITLE
【Bug-mod】VIP mod实现不对，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#202]
## The problem
VIP mod实现不对，请调整

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor

## Step To Reproduce Issue [ Good To Have ]
* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.添加VIP mod,添加后将阅读开关关闭，观察显示情况，再将开关打开，观察显示情况
2.添加新的内容，在新页面观察VIP是否生效。

* Expected Result:
1.页面信息显示正确，是VIP用户才能正常查看。
* Actual Result:
1.页面显示不合理
 

## Attachments (eg:logs/video/screenshot)
![vipread_issues](https://user-images.githubusercontent.com/21214285/38723578-1de2681c-3f34-11e8-80bb-14690f68760c.gif)

**Comment by Sandu1213** [comment]
问题依然存在，请调整。
问题1：自己创建的信息，自己无法查看，请调整
![image](https://user-images.githubusercontent.com/21214285/38793911-b28b8edc-4185-11e8-936e-62e92391edf3.png)

问题2：已是VIP用户，且已经在另一个页面进行了登陆，无法查看到全部信息。
![image](https://user-images.githubusercontent.com/21214285/38793983-f6dcda3c-4185-11e8-8069-7ffe0dba8936.png)

**Comment by Sandu1213** [comment]
问题3： 将VIP 开关关闭后，页面不应该再显示“VIP查看更多”，请调整
![image](https://user-images.githubusercontent.com/21214285/38797337-b73383da-4190-11e8-8090-39697ed1a2ff.png)

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/38925144-54808af6-4331-11e8-8aea-25580a89b56b.png)
@yuanoook
