### ISSUE TITLE
【lesson-bug】教师自己创建课程，显示在授课栏里，在课程中心买自己创建的课程，显示如图

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#2029]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/ab63d180-9dc6-477b-bd5a-4b838031a145)

**Comment by leopoldchen** [comment]
再测试确认一下

**Comment by Sandu1213** [comment]
与 #2033 有关，待问题解决后再验证。
正常情况：自己创建的课程包，审核通过后汇总授课和课程中心里展示，且在课程中心无需购买。
