### ISSUE TITLE
【bug-lessons】TEACHER COLUMN-Lesson Management：课程包管理页，提示文字，如下

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2030]
一、课程包提交成功的提示文字，修改为：
Successfully submitted. The result will be informed within 5 workdays. 
提交成功。系统将在5个工作日内反馈审核结果，请耐心等待。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/5bc479f1-27ea-415f-9095-d5485e1b209c)

二、课程包撤销审核的提示文字，修改为：
Successfully recalled.

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/0cbabdfb-b8a7-430f-89bd-88f6a6d8289d)

**Comment by Sandu1213** [comment]
撤销还需调整
![image](https://user-images.githubusercontent.com/21214285/53476943-8e70fa00-3aae-11e9-8024-6f6c063baf3b.png)
