### ISSUE TITLE
【bug-lessons】TEACHER COLUMN-Lesson Management：课程管理页，“点击课程名称，进入编辑器”的功能目前缺失。如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2031]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/4504be14-77f5-4b1a-a736-b84cf84c3cad)

1、mouse over 在课程名称上时，显示文字：
Click to view the lesson in Keepwork Editor.
点击在编辑器中查看课程内容

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/c38ceea9-c598-4881-b449-b3e18598ae9d)

2、点击课程名称：
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/d9d1bc3d-68ad-4ee8-80eb-578ce3cce032)

**Comment by Sandu1213** [comment]
1.路径跳转存在问题，缺少”username“
2.当该课程归属于的课程包存在”审核中“状态时，应该禁止编辑和删除，目前还是可以编辑
