### ISSUE TITLE
【keepwork-bug】static 迁移到 assets 下面

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#2042]
static 迁移到 assets 下面

**Comment by Sandu1213** [comment]
static 下的adi 迁移到src/assets 文件夹下，验证相关ADI功能是否正常即可。

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/45344729-06b63280-b5d7-11e8-9e54-30c6a63edf5f.png)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/45345333-a7592200-b5d8-11e8-97c0-496b4daf4404.png)

**Comment by onedou** [comment]
https://github.com/tatfook/keepwork/issues/1847 此issue已更新board相关问题 @duting1993
