### ISSUE TITLE
【Feature-lessons】需增加“学科名称”、“技能名称”的英文字段，如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2046]
一、学科名称
中文：计算机科学
英文：Computer Science

二、技能名称
1、包含3个技能名称，如下：
代码阅读量  Lines of code to read
代码书写量  Lines of code to write
学习指令数  Commands to learn
2、对应的学习总结文本，如下：
中文：今天，我读了【X】行代码，写了【Y】行代码，学习了【Z】个计算机指令。
英文：Today, I read【X】 lines of code, wrote 【Y】 lines of code, and learned 【Z】 computer commands.
（说明：X —— 【代码阅读量】的数值，Y —— 【代码书写量】的值 ，Z —— 【学习指令数】的值）

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/1692c8c6-9913-48a3-b2ac-ff22ec07b44d)

**Comment by Sandu1213** [comment]
release env is ok
