### ISSUE TITLE
【需求】网站文件重命名

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#207]
@azothli commented on [Mon Dec 04 2017](https://github.com/tatfook/wikicraft/issues/1096)

已经创建的文件，需要提供重命名功能

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/40041133-91b2300e-584f-11e8-82ed-0c81dfb210af.png)
文件夹、文件 增加一个 重命名的按钮
点击后，目录树中的对应项变为文本输入模式，显示当前的文件名
![image](https://user-images.githubusercontent.com/22001356/40041219-d7a7bc28-584f-11e8-9506-6b41cff9a11b.png)
用户可以修改其中的文件名，在回车或者切换焦点的时候保存（检测是否合法：命名规则、是否有重名，如果不是合法可用的，不进行修改，同时在系统提示区域给出修改失败与原因的提示）

**Comment by ouyc** [comment]
Issue moved to [tatfook/KeepWorkDesgin #35](https://github.com/tatfook/KeepWorkDesgin/issues/35) via [**ZenHub**](https://www.zenhub.com/)
