### ISSUE TITLE
【Bug】对多个文件进行编辑操作，想批量关闭文件时，缺少该功能，请优化调整

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#211]
@Sandu1213 commented on [Thu Nov 30 2017](https://github.com/tatfook/wikicraft/issues/1084)

## The problem
对多个文件进行编辑操作，想批量关闭文件时，缺少该功能，请优化调整 

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.94
* URL: [keepwork.com](http://keepwork.com) 
* Model:  页面编辑器->全部关闭

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，打开多个文件进行编辑操作，编辑完成后未保存时，点击”全部关闭“按钮，观察
结果

* Expected Result:
1.关闭失败，提示用户保存，保存成功后，再次关闭，关闭成功
* Actual Result:
1.缺少批量关闭功能

**Comment by Sandu1213** [comment]
@azothli  宇哥，请补充下新编辑器上的设计交互效果

**Comment by azothli** [comment]
设计已有，还没加
save all
close all
功能

**Comment by leopoldchen** [comment]
@azothli 

是否有相关交互设计稿，如果有为保存的文件该如何处理？

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/40964947-f992ae66-68de-11e8-836d-949817a1054f.png)
![image](https://user-images.githubusercontent.com/33826048/40964953-fcdf8832-68de-11e8-8edd-6ebb3f90091f.png)

**Comment by wanglin727** [comment]
源文件 svn
