### ISSUE TITLE
【Bug-lessons】存在视频的课程，需要生成一个视频封面图，请完善

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2139]
### Details:
![video_cover.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/afdd2653-dbc7-4534-84fc-89a992c92dcb)

**Comment by kevinxft** [comment]
显示视频封面不好实现，现在改成显示课程封面+播放按钮

**Comment by Sandu1213** [comment]
@shirleyluo1130 评估是否可以接受?

**Comment by shirleyluo1130** [comment]
可以，直接使用课程封面图+播放按钮即可。
