### ISSUE TITLE
新建网页 界面功能实现

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#214]

**Comment by yuanoook** [comment]
2018/04/16 更新

新建页面划分为三块功能目标：
1. **名称** 确定新建页面名称【必须】
2. **位置** 可更改页面位置【优化体验】
3. **模板** 可以使用预设的模板 【功能，尚未设计，依赖模块库整理完】

当前阶段需要做什么？
实现功能一 **名称** 填写输入，添加格式要求及错误提示；
功能二优先级降低；
功能三待产品和设计输出确定后，再同开发同步，然后实施。

**Comment by Sandu1213** [comment]
@azothli  @wanglin727 请关注功能2,3; 给出回复，谢谢~

**Comment by yuanoook** [comment]
@Sandu1213 后面两个， 重新提单吧

**Comment by Sandu1213** [comment]
OK
