### ISSUE TITLE
【Bug-lessons】课程预览时，缺少教师提醒和素材信息的展示

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2143]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/8d1ac877-5447-48b5-983e-a8abd25b31ec)

**Comment by leopoldchen** [comment]
@kevinxft @shirleyluo1130 @Sandu1213 

课程预览与发布后的预览是完全不同的，改动应该很大，建议降低优先级

**Comment by shirleyluo1130** [comment]
好的，可以之后与 “添加素材” 功能一起处理。（目前，添加素材 功能暂未开发）

**Comment by kevinxft** [comment]
素材暂时先不处理，教师提醒已经解决
