### ISSUE TITLE
iframe mod样式添加，用户可添加内联框架样式

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#2145]
在菜单栏中添加iframe mod 样式，用户点击该mod，可使用内联框架功能，方案如下，可按这样做
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/7dfa9b13-04a9-4c83-8e75-7fd43fff1bb2)

**Comment by Kvaya** [comment]
在输入链接后，加个“确定”按钮
![image](https://user-images.githubusercontent.com/39363297/50146072-ea204980-02ed-11e9-825e-614967dd0151.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/50213780-8a8f7000-03b9-11e9-8793-e56641290f24.png)
