### ISSUE TITLE
国际版本的第三方登录调整

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#215]
@azothli @yuanoook

在wikicraft的登录注册页面也需要处理中英文，并且在英文场景下需要调整第三方登录。

基本思路是在英文环境下，把Facebook、google等账号登录提前。建议参考为第三方登录设置一级和二级显示，把非当前语言环境的登录放入二级菜单。

另外，目前在登录注册时加了实名认证，这对于海外用户而言不现实，针对海外用户应该取消实名。这里存在一个难题，怎么判断用户是海外用户？（IP？）

**Comment by azothli** [comment]
这个实现方式会有几种：
1.技术上的，通过ip地址识别（构建库，可能不准确，还有代理的问题），系统语言识别（不准确），来判断用户是CN用户，还是国际用户，创建不同的用户类型。
展示不同的注册登录ui
收费方式
实名策略
内容过滤策略（因为数据在CN，应该符合CN的政策，所以我们应该要求外国人也符合我们的规矩，这点应该很难被接受）

还有未来内容在一个平台上面会有风险。（例如互相之间的推荐、关注都会有潜在风险，除非我们把外国人也都关键字了）

2.粗暴的架设海外服务器（服务器不一定在海外），用两套数据

**Comment by leopoldchen** [comment]
@azothli                        

技术方案已经确定会在亚马逊云上单独做部署。
现在需要海外第三方登录相关的设计，即修改旧版KeepWork的登录等功能，方便海外用户使用

**Comment by ouyc** [comment]
已创建新的issues
