### ISSUE TITLE
Paracraft Mod

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#216]
url protocol

**Comment by onedou** [comment]
已在新版中加入了urlprotocol的支持

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/38984994-c543510a-43fa-11e8-8fae-a51e53a4a1f0.png)

**Comment by Sandu1213** [comment]
添加Urlprotocol后的效果：
![image](https://user-images.githubusercontent.com/21214285/39027322-f68df2cc-4483-11e8-962b-e3e1302c5265.png)
