### ISSUE TITLE
PBL - 项目设置

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#2161]
keepwork改版设计稿/kp改版/index.html#g=1&p=项目设定

**Comment by leopoldchen** [comment]
提交到工作室先不做，后续版本再加

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/46198669-98e06980-c33f-11e8-88da-94d5cdb3e25d.png)

**Comment by leopoldchen** [comment]
#2158 

描述写到这个issue里去了……
