### ISSUE TITLE
首页改版 - 学习页

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#2168]
keepwork改版设计稿/kp改版/index.html#g=1&p=kp首页：学习

@ouyc  @azothli 

这块的跳转链接需要描述一下，比如计算机科学和paracraft的跳转页面是？

**Comment by shirleyluo1130** [comment]
学习页，UI已重新设计，原型中已备注跳转说明。请见：
![image](https://user-images.githubusercontent.com/40385277/46651712-7964fe80-cbd3-11e8-9955-c405ed11c9a0.png)

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/46798964-0ea7f480-cd86-11e8-880e-4ec0d93e0a12.png)
