### ISSUE TITLE
现有Mod样式调整

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#217]
### 目标
UI配色方案调整

### 指标

@onedou  @wanglin727 

请根据调整内容，补充相关指标

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/38805172-79921ffc-41a7-11e8-8958-06c3683aed68.png)


![image](https://user-images.githubusercontent.com/33826048/38805185-87b4c184-41a7-11e8-9018-80ba88cdc0e5.png)
