### ISSUE TITLE
【bug-lessons】教师的课程详情页：hint mod中的内容不显示，如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2178]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/3825a83c-acac-4740-b626-59ed5b731019)

**Comment by Sandu1213** [comment]
目前显示，但与设置不符
![image](https://user-images.githubusercontent.com/21214285/45729734-67112980-bc00-11e8-9e75-f5cf20b51017.png)
