### ISSUE TITLE
mod default settings issue

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#218]
目前将系统default数据直接写入用户的md文件中，这是不合理的，应该从程序上处理

**Comment by Sandu1213** [comment]
@onedou  Big，需要把默认的链接（http://keepwork.com）也去掉，请再调整一下

**Comment by onedou** [comment]
应该都去掉了

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/38969097-2330cd4a-43c1-11e8-8f33-eacdcc946e13.png)
![image](https://user-images.githubusercontent.com/21214285/38969102-28680954-43c1-11e8-8084-7914b5e6f570.png)

menu mod里还有，请调整下

**Comment by onedou** [comment]
menu 和 title mod 都已经调整了

**Comment by Sandu1213** [comment]
stage环境验证不过，请再调整
![image](https://user-images.githubusercontent.com/21214285/38983583-3f20ee3c-43f7-11e8-889f-4126cda1ef54.png)

**Comment by Sandu1213** [comment]
验证通过
