### ISSUE TITLE
【Bug-lessons】学习总结里的学习天数统计不对，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2215]
![share10.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/d409b79c-d39b-4cd9-916b-fc876676ea66)

**Comment by Sandu1213** [comment]
请再完善

**Comment by kevinxft** [comment]
现在是后端返回学习天数，所以之前学习记录不会产生学习天数，需要现在重新算
