### ISSUE TITLE
【Bug- 账户退出】从wiki/home页面进行退出操作，账户无法退出，请处理。

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#222]
## The problem
从wiki/home页面进行退出操作，账户无法退出，请处理。

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.从wiki/home页面，退出账户，观察退出结果
2.从个人主页页面，退出账户，观察退出结果

* Expected Result:
1.都能退出成功，页面信息显示正确
* Actual Result:
1.从wiki/home页面无法退出，请排查处理
 

## Attachments (eg:logs/video/screenshot)
![wiki_home](https://user-images.githubusercontent.com/21214285/38794674-8fa21960-4188-11e8-95ca-ff59ffa3d588.gif)

**Comment by yuanoook** [comment]
keepwork token 的问题，需要把 keepwork.com 手动退出了

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/39103247-3d0b2bc0-46dc-11e8-93a1-d65d0a2c9950.png)
还是存在问题

**Comment by Sandu1213** [comment]
token清理后可以正常退出，但再次操作后又无法退出了，请再调整

**Comment by yuanoook** [comment]
老 bug 了，现在没法复现，交由 QA，如果 QA 不能复现就关单吧
