### ISSUE TITLE
【bug-lessons】课程详情页：素材弹框，增加素材为空的展现。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2225]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/e95b765f-dcaf-4518-a033-26274102e633)

**Comment by shirleyluo1130** [comment]
UI设计中。

**Comment by ouyc** [comment]
![v k1x oiwzo61yyki3c3_bg](https://user-images.githubusercontent.com/38035998/45866814-8486f480-bdb4-11e8-8b6f-f65568f1d1ca.png)

**Comment by kevinxft** [comment]
现在只是做了个显示，因为素材这个功能还没有做。
