### ISSUE TITLE
【bug-lessons】教师专栏（未激活状态下）：页面中增加 学校信息 的输入区（必填项）。同时后台需记录学校信息。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2227]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/ec1be7bc-9b21-40ca-9b2c-3c384add09b4)

**Comment by shirleyluo1130** [comment]
UI设计中。

**Comment by ouyc** [comment]
![0 f9c 3 8z 5u1u hl5d r](https://user-images.githubusercontent.com/38035998/45866574-e430d000-bdb3-11e8-8292-854d2d91034f.png)

**Comment by Sandu1213** [comment]
release验证通过
