### ISSUE TITLE
导航菜单，对居中菜单样式设置，导航栏中添加菜单，菜单项不完全显示，效果是超过一栏的菜单另起一栏显示

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#2262]
问题如图：![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/0b829194-8e50-4938-879e-39bf8d1fc53a)
效果如图：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/a3574b29-cbd9-4985-8e02-e720de6247f5)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/49720370-8ddc7a80-fc9a-11e8-9d65-a238fc73bd6e.png)

**Comment by Sandu1213** [comment]
样式排列的问题，后续再调整
