### ISSUE TITLE
【Bug-lessons】当文本类型的答案只有一个时，改分后答案显示不对，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2270]
### Details:
**ENV:** keepwork环境

![answer_record.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/bcfe006a-7479-4a8a-9d75-232ff6353aa2)

**Comment by DDXY1230** [comment]
新数据会有默认的答案
