### ISSUE TITLE
【Bug-keepwork】keepwork在百度的引流地址显示不合理，请处理

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2275]
### Details:
![opmtimze.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/3be0c4ab-7a1b-4bc1-bcf0-237c2bb34436)

**Comment by leopoldchen** [comment]
![image](https://user-images.githubusercontent.com/1396883/57599076-20ee4900-7588-11e9-8781-c2e819b0f60b.png)

**Comment by leopoldchen** [comment]
@Kvaya 
关于keepwork网站的搜索引擎优化也需要处理一下

**Comment by Kvaya** [comment]
![image](https://user-images.githubusercontent.com/39363297/58448894-e5cd4780-813b-11e9-8117-6888b42b6d01.png)

**Comment by Kvaya** [comment]
以上7点：
第1点不用处理，目前是这样；
第3点按下图处理：
![keepwork网站所有页面上传的视频和图片增加alt属性情况](https://user-images.githubusercontent.com/39363297/58689262-1e2d8980-83b9-11e9-9520-16d30f85e311.png)
第4-6点目前不处理；
第7点

**Comment by dalin00** [comment]
![logo图片](https://user-images.githubusercontent.com/24222876/59011058-fb422000-8865-11e9-9488-e913cc0ef63a.jpg)
