### ISSUE TITLE
在媒体库中想快速选中视频，播放热键比较大，易点中播放键

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#2283]
建议如下：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/7dbfc25d-b43f-4e6a-8c08-9f6370ec7dae)

**Comment by Sandu1213** [comment]
播放图标与删除图标不在同一个水平线上，且需要图标大小一致（便于美观）
![image](https://user-images.githubusercontent.com/21214285/46062057-3189b480-c19b-11e8-80cc-62db2986fa6b.png)
