### ISSUE TITLE
【Bug-paracraft】请增加一个兼容world index的mod

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2286]
### Details:
1.老的keepwork用户上传世界后，无法从index页查看到上传世界的列表情况，请做兼容处理
2.待该功能完善后，请按照之前流程，允许新用户也可以创建index页（前期隐藏index主要是方便新用户
快速找到自己创建的世界，附：#1885）

![image](https://user-images.githubusercontent.com/21214285/45991760-eb5c2480-c0b8-11e8-9b7e-939c8d369aea.png)

**Comment by onedou** [comment]
需求不再需要，此issue关闭
