### ISSUE TITLE
【lesson-十一活动】“知识豆兑换”页面

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2295]
原型：
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/ca71e31a-ffed-4827-9d94-5238a6314fe2)

说明：
1、鼠标放置于“如何获得？”按钮上，显示如下文字：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/de3cba16-50df-4e2a-8e32-b45c188a3cdd)

2、默认选中第一个物品，数量默认设置为1，可修改数量。物品暂定2个：能量石、仙豆礼包。之后会增多。每次只能买一种物品。

3、若知识豆不足时，点击“立即兑换”，提示：知识豆不足！（Your beans are insufficient.）

若知识豆充足，兑换成功，提示：兑换成功！（Successfully paid.）

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/46118989-972d7d80-c23b-11e8-86f2-ce42293706d4.png)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/46119013-ae6c6b00-c23b-11e8-9ac5-6aff3d589f54.png)
