### ISSUE TITLE
【lesson-十一活动】：学生的课程详情页，如下

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2300]
1、“获取知识币”的功能可先不展示，待课程包需付费使用时再展示。

2、增加“获取知识豆”的功能，

知识豆的获取要求：（1）、课程学习时长不低于5分钟；（2）、测试题全部作答正确 ；（3）每个课程限领一次；（4）自己创建的课程不可领取

如何使用知识豆：可用于兑换哈奇中的绑定类物品。
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/e865dcbd-2e35-4334-95a4-9d8a883af21a)

3、获得知识豆时，弹出框：（加上声音效果+动画效果，发光、知识豆飞入“学生专栏”）
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/5d9465f1-e174-4fc0-8c5d-5b904ac18d14)

**Comment by Sandu1213** [comment]
上课模式下知识豆领取还存在问题

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/46134517-a3363100-c275-11e8-9a85-d451c6d61eeb.png)

**Comment by Sandu1213** [comment]
上课领豆还是不对，请调整
