### ISSUE TITLE
【lesson-十一活动】：学生专栏：增加“知识豆统计数据”的显示。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2301]
知识豆的统计数据，放在“学生专栏”显示，如下：
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/2c37f42b-215d-4a63-9adf-b1a3326de5df)

知识豆明细：
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/7332370d-2890-425e-8514-305a8c4eca29)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/3ef73650-5f89-4e16-aa0f-a756f2d33839)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/46118875-4027a880-c23b-11e8-90ac-321ad8d78558.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/46187322-ada80780-c315-11e8-9d14-3e1c27489b36.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/46192565-1c915a80-c32e-11e8-8bbf-3e2a6f70d59b.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/46198089-30dd5380-c33e-11e8-98e5-c8c1c7845fa9.png)
