### ISSUE TITLE
用户在“网站设置”中的"基本信息"进行“保存”操作，应和“网站布局”、“网站样式”页面的保存功能一致，保存并关闭的意思，

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#2302]
1.用户点击“网站设置/基本信息”页面上的‘保存’，是保存并关闭的意思

2.点开网站设置页面，“基本信息”中网站名称应该是默认显示网站名。如图：
![image](https://user-images.githubusercontent.com/39363297/48826825-68003c00-eda6-11e8-8d91-a63edc4c9499.png)

补充：第一次打开时默认显示 "t"

**Comment by Kvaya** [comment]
补充：
当点击的是“paracraft”的网站设置，基本信息中网站名是“paracraft”。
![image](https://user-images.githubusercontent.com/39363297/48106166-49ae2280-e275-11e8-87a6-0828095da41e.png)

**Comment by Sandu1213** [comment]
stage验证不过
![image](https://user-images.githubusercontent.com/21214285/48193665-f37cd480-e385-11e8-8221-1d715c2c5435.png)

**Comment by Kvaya** [comment]
网址地址是唯一的，URL不变；网站名称跟左侧网站目录上一致，且弹开网站设置页面时默认显示

**Comment by Kvaya** [comment]
点保存按钮，功能做好了；
网站名称处还需再处理下：网站名称跟左侧网站目录上是一致的，点开网站设置页面，网站名称处默认显示左侧网站目录上的网站名；网站地址是唯一的，URL不会变

**Comment by Sandu1213** [comment]
release is ok
