### ISSUE TITLE
【优化】视频封面

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#2331]
@azothli commented on [Fri Sep 21 2018](https://github.com/tatfook/KeepWorkDesgin/issues/88)

目前视频载入后会展示第一帧，视频如果没有特意处理，效果不好。
添加设置封面的功能

---

@azothli commented on [Fri Sep 21 2018](https://github.com/tatfook/KeepWorkDesgin/issues/88#issuecomment-423391475)

![image](https://user-images.githubusercontent.com/22001356/45856368-bf723380-bd86-11e8-8284-402a3a5488f4.png)

---

@Kvaya commented on [Wed Sep 26 2018](https://github.com/tatfook/KeepWorkDesgin/issues/88#issuecomment-424591604)

在“SVN/editor mod/新增mod ”文档中，“视频属性”及“点击添加视频封面”原型页中标明视频属性及添加视频封面效果等。参考开发

**Comment by Kvaya** [comment]
建议如下：
1.网站上是图片的属性都可图片切换成视频
2.逻辑如下图：
![image](https://user-images.githubusercontent.com/39363297/46664679-3ff0bb00-cbf4-11e8-9b08-d5ab96bb4c10.png)
![image](https://user-images.githubusercontent.com/39363297/46664824-ad045080-cbf4-11e8-822b-f40d3c905724.png)
![image](https://user-images.githubusercontent.com/39363297/46665088-63683580-cbf5-11e8-8bb2-c27a940fc132.png)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/47830397-ab2e4700-ddc6-11e8-80fa-1fd63aeee275.png)
