### ISSUE TITLE
【lesson-十一活动】课程自学时，作答完毕，有题目作答错误时，自动弹出如下答题卡，并显示“重新学习”按钮，点击“重新学习”刷新该页面，重新学习。（未答完，不显示“重新学习”按钮）

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2374]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/2335621c-130e-4ccc-872b-b30290a60ddc)

**Comment by Sandu1213** [comment]
规则：当完成所有答题且存在错误的答题时，立即弹出该提醒。

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/46256651-2064de80-c4e0-11e8-8136-dd9db3c16173.png)
