### ISSUE TITLE
【lesson-十一活动】测试题作答，进度显示不对。如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2378]
动画课程——课程27体验：课堂进度记录有误，问题已全部答完提交，课程进度在提交第三个问题后就不再更新。返回课程目录，该课程是还未完成状态

动画课程——课程28体验：课堂进度记录有误，问题已全部答完提交，课程进度在提交第五个问题后就不再更新。返回课程目录，该课程是还未完成状态（这个问题从课程28到课程31，课程34都存在）

**Comment by Sandu1213** [comment]
release已验证
