### ISSUE TITLE
【Bug-mod】img mod无论如何配置链接打开窗口，总是在本窗口打开链接，设置无效，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#239]
## The problem
img mod无论如何配置链接打开窗口，总是在本窗口打开链接，设置无效，请调整

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor页面后，创建新的页面,添加img mod,分别设置链接打开的窗口为本窗口、新窗口，观察打开情况

* Expected Result:
1.页面打开位置正确，可以正常跳转
* Actual Result:
1.页面打开位置不合理,请调整

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/38966832-bafcf050-43b6-11e8-8172-67e82f4b1976.png)

**Comment by onedou** [comment]
以为是 img loop 搞错了，这个issues已解决
