### ISSUE TITLE
课程中心页面缺少标题（title）

### ISSUE THREAD

**Issue by beyondliu** [tatfook/keepwork#2391]
https://keepwork.com/l/#/
手机分享该网页的时候，缺少合适的标题（title）。考虑添加个html的title，分享效果更好。

**Comment by Sandu1213** [comment]
因目前课程中心已经改版，跟产品沟通后，
需要将[该页面](https://keepwork.com/s/lesson)的页面名调整为“在线课程",目前显示的为“keepwork”
