### ISSUE TITLE
在代码区中编辑，在已有的一个mod下面一行添加新的mod，新的mod对应的样式和代码应该在原mod的下方

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#2393]
![image](https://user-images.githubusercontent.com/39363297/46591175-8c040880-caeb-11e8-825b-326ecb264b33.png)

1.鼠标在已有的mod下一行，这个时候添加的新mod，代码应该在已有的mod的下方，并不是在已有mod的上方；
![image](https://user-images.githubusercontent.com/39363297/46591221-da190c00-caeb-11e8-8705-444a9a4f9b93.png)
现新增的样式和对应的代码在已有mod的上方去了，这个跟交互、预设操作场景不一样，应在下方

2.点击代码区中，某个mod，需与预览区对应的mod样式一一对应

**Comment by onedou** [comment]
请测试看看此bug是否还存在

**Comment by Kvaya** [comment]
这个问题还是存在

**Comment by duting1993** [comment]
操作步骤
第一步：添加一个mod，添加后，代码区域按回车
第二步：在列表里直接点任一mod添加，最右侧代码区域的代码会显示在第一排

**Comment by kevinxft** [comment]
没发现问题

**Comment by Kvaya** [comment]
上面问题是在之前版本上的基础上：左侧列表上有“模块”icon，在右侧代码区可直接点击左侧列表导航栏处的“模块”icon，进行添加模块，可能会出现乱序
