### ISSUE TITLE
当属性面板所有的开关closed，预览区对应的mod被隐藏，现空白显示不是被隐藏了

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#2399]
当属性面板所有的开关closed，预览区对应的mod被隐藏，这块区域需给用户提醒，该区域是被隐藏的；在新的窗口浏览时，这块区域是不被显示的，且下面内容上移覆盖该区域。

**Comment by ouyc** [comment]
Issue moved to [tatfook/KeepWorkDesgin #89](https://github.com/tatfook/KeepWorkDesgin/issues/89) via [**ZenHub**](https://www.zenhub.com/)
