### ISSUE TITLE
IMGLOOP MOD需要增加一个指定长宽比例的选项

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#2429]
![image.png](https://images.zenhubusercontent.com/59df2959b0222d5de47b59a3/d575ba2c-c0df-407d-b8c3-ab59023e43d7)

**Comment by Kvaya** [comment]
所有有图片元素的mod的属性面板用下面优化方案逻辑做。
优化方案：
![image](https://user-images.githubusercontent.com/39363297/46843725-b49b4380-ce06-11e8-801a-16304ed48d77.png)

**Comment by Kvaya** [comment]
单击并将“图片n”相关属性面板上下拖动至列表中所需位置，以让图片轮播中重新排序图片。
备注：
![image](https://user-images.githubusercontent.com/39363297/47007200-450cb780-d16a-11e8-9c9d-c1829abe0312.png)s是位置是固定不变的

**Comment by Kvaya** [comment]
"?"文字提示：按图片实际比例显示。显示效果不按上面图，显示效果还是现在按编辑器文字提示，效果如下：
![image](https://user-images.githubusercontent.com/39363297/47152222-a4a3c800-d30e-11e8-84a5-24a9f701cef3.png)

**Comment by Kvaya** [comment]
新的设计详细：
在图片轮播样式添加21:9、16:9、4:3、1:1的样式，并每个分别做100%、80%两种宽。如图：

![image](https://user-images.githubusercontent.com/39363297/48105262-ba534000-e271-11e8-955a-e27c0322b79e.png)

备注：
1.现图片轮播样式中的两个样式可直接更换成21:9、16:9、4:3、1:1其中两个样式；
2.宽度80%的图片样式是之前100%样式**等比**缩小至80%。

**Comment by onedou** [comment]
此issue信息过多并将关闭，将迁移至新的issue  #2779
