### ISSUE TITLE
【Bug-lessons】学生状态页面需要增加对学生学习时长的统计信息

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2478]
### Details:
     为了提高课堂质量，需要清楚的了解每个学生花在学习上的时间是多少，故需要增加统计信息
（paracraft端会每个15s返回一个是否在前端的信息回来，请根据情况进行统计）

**Comment by LiXizhi** [comment]
@shirleyluo1130 

需要先和技术探讨一下解决方案

**Comment by shirleyluo1130** [comment]
课程教学流程调整，关闭该issue
