### ISSUE TITLE
路径导航功能

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#250]
UI 已经OK了，需要数据支持
![图片.png](https://images.zenhubusercontent.com/59df33a4b0222d5de47b5b3c/b4e6362b-51ff-45dc-b6ea-e0b1acac890d)

**Comment by Sandu1213** [comment]
stage环境验证不通过
![image](https://user-images.githubusercontent.com/21214285/40417560-9bbd3bb6-5eb2-11e8-8e1e-2e196194eee0.png)

**Comment by Sandu1213** [comment]
修改不彻底，请再完善
![image](https://user-images.githubusercontent.com/21214285/40596439-56e99eb2-626d-11e8-9ada-47947b4ef040.png)
