### ISSUE TITLE
新标签页浏览网站时，给编辑、分享、赞icon mouse over时分别显示图标的文字提示

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#2503]
详细：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/43fb08e9-1656-42de-a238-f2288cd3078f)

解决方案：
1.首先根据下图进行判断
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/97af3712-35c0-4a5a-930c-6239f8beb55e)

2.
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/c7811e03-aebe-42e2-ac05-f0e4e7ffb8f2)
优先级的优化

3.展示效果
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/445fe6f2-8ebe-410a-a28c-c90bd810cd94)
“查看代码”时，图标换成![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/ca19c974-3f3a-45f1-a7f7-160c7c8fe65d)

**Comment by Kvaya** [comment]
现问题：当用户A浏览的网站是用户B的私有网站，且用户A只有这个网站的浏览权限，
![image](https://user-images.githubusercontent.com/39363297/48828882-dbf11300-edab-11e8-8c52-cb34c0bba736.png)因显示“查看代码”，且用户A点击“查看代码”跳转到editor编辑器中，用户A在编辑器中的操作只能是浏览代码，浏览该网页编辑器中的内容，但不可编辑

逻辑是这样：
1.当这个网站是共有网站时，他人可以编辑查看，就算他没有登录；当点编辑时，提醒他登录。
2.当这个网站是私有网站，对某账户设置了编辑权限，该账户用户可以对该网站进行编辑；对某账户设置浏览权限，该账户用户只能浏览，不能编辑该网站

**Comment by lsx18** [comment]
![image](https://user-images.githubusercontent.com/35092757/49055095-564ce780-f231-11e8-80aa-d25eed092a26.png)
该issue由 #3118 处理

**Comment by Kvaya** [comment]
补充：如果有查看权限，都是允许用户查看代码的，只是不能编辑

**Comment by onedou** [comment]
> 补充：如果有查看权限，都是允许用户查看代码的，只是不能编辑

权限相关请在 #3118 回复，此issue只解决icon问题

**Comment by Kvaya** [comment]
好的

**Comment by onedou** [comment]
此 issue 只需测试icon显示相关逻辑即可，如果没有问题，请测试通过

**Comment by Sandu1213** [comment]
具体情况说明：
![image](https://user-images.githubusercontent.com/21214285/49071097-2c62e780-f268-11e8-9863-1134082035dc.png)

目前是没有实现的，请调整

**Comment by Kvaya** [comment]
#4443 跟进
