### ISSUE TITLE
在“我创建的网站”右侧添加“新建网站”功能

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#2510]
设计稿如下：

![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/2379b858-7ee2-44f4-8d58-7f9c00ac35a4)

备注：mouse over显示文字提示：新建网站

**Comment by enya-i** [comment]
![image](https://user-images.githubusercontent.com/37529364/47211105-4129a100-d3c7-11e8-8b99-f94ad2eb4c4e.png)
![a4edb2a107c9babe4270e186158cb8db](https://user-images.githubusercontent.com/37529364/47211114-45ee5500-d3c7-11e8-8ae7-8091af09e8c7.png)
图标已上传，设计文件位置看上图。

**Comment by onedou** [comment]
同 #2511 重复
