### ISSUE TITLE
预览区和代码区添加左右切换功能

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#2512]
解决方案如下：

![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/4162c327-3199-4c49-9640-2b2112dc22cf)

备注：中间的预览区和右侧代码区进行左右互换

**Comment by enya-i** [comment]
![image](https://user-images.githubusercontent.com/37529364/47210882-b8126a00-d3c6-11e8-80d1-b080410e473f.png)
图标已上传至iconfont，该处功能样式和其他功能样式一致
