### ISSUE TITLE
editor中“chinese simplifed”这个功能翻译不准确 

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#2516]
现调整效果如下：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/be81475f-d86e-48e4-8373-6cc0363291c5)

1.添加icon，更容易标识
2."chinese simplified"更改为“Switch to Chinese（中文）”，Chinese 要大写首字母
3.“切换为英文”更改为“切换为英文(English)”

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/47135800-406c0e80-d2e4-11e8-9252-68d5057928df.png)


keepwork官方iconfont
