### ISSUE TITLE
【bug-lesson手机版】点击全部更改，全部更改，部分更改两个按钮，会编程，上下样式

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#2537]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/80cf7eb9-8c8d-4808-a5d4-93f7d68dc3d0)

**Comment by DDXY1230** [comment]
手机上不好出现这个问题，导致这个问题是电脑上的模拟器滚动条的影响所致，这个问题可以关了
