### ISSUE TITLE
在“菜单编辑器”、“绘图板”“文本（Markdown）”“评论留言”“调用QQ聊天”的属性面板增加“？”，mouse over时有文字提示

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#2548]
**需求详细：**
在“菜单编辑器”、“绘图板”“文本（Markdown）”“评论留言”“调用QQ聊天”的属性面板增加“？”，以便给用户更好理解和使用这个mod。

效果图如下:

![image](https://user-images.githubusercontent.com/39363297/47213849-cf555580-d3ce-11e8-9ac5-110fd031ea8b.png)

备注：

1.在这指定的5个属性面板上，如上图位置添加“？”，mouse over时显示文字提示，提示内容如上图；

2.“评论留言”现属性面板上“评论”改为“评论留言”、“评论是否开启”改为“允许发表评论”；
  效果如下：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/08b8004f-6a0e-44ed-bd32-17c239c8e13b)

3.“调用QQ聊天”中的“QQ号”属性面板上，“QQ号”改为“设定QQ号”，“数字”改为“请输入联系人QQ号”，字体颜色和现在的字体颜色一样；

4.“文本（Markdown）”属性面板上，“markdown文档”改为“文本（Markdown）”，“数据”改为“请输入内容”
     
5.mouse over"文本(Markdown)"上的“？”，显示文字提示，用户点击“了解更多>"跳转到”帮助“页，这个具体做的时候，我们可以沟通下

**Comment by Kvaya** [comment]
**”？“图标采用这个http://www.iconfont.cn/上的**

![image](https://user-images.githubusercontent.com/39363297/47214611-0d537900-d3d1-11e8-8480-351f3c4bd4a2.png)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/47409098-566e4900-d794-11e8-9d6a-f4d30a9b2bcf.png)
![image](https://user-images.githubusercontent.com/28430070/47409151-7998f880-d794-11e8-8a21-4c3a34dff7ae.png)
![image](https://user-images.githubusercontent.com/28430070/47409196-9f260200-d794-11e8-9083-7a120993cee0.png)

**Comment by Kvaya** [comment]
![image](https://user-images.githubusercontent.com/39363297/47409484-74887900-d795-11e8-83db-1bc3112ceb98.png)

**Comment by Kvaya** [comment]
文本（Markdown）提示中最后面“了解更多>”
![image](https://user-images.githubusercontent.com/39363297/47426305-6f402400-d7bf-11e8-9b52-2c234dffb450.png)

点击“了解更多>”跳转至“https://keepwork.com/official/help/yufa”

**Comment by Sandu1213** [comment]
- markdown mod 
![image](https://user-images.githubusercontent.com/21214285/48048625-14eb8e00-e1d7-11e8-9a4c-2ba3b569ec5c.png)

- comment mod
![image](https://user-images.githubusercontent.com/21214285/48048708-4d8b6780-e1d7-11e8-8e2d-220491c42ce8.png)

**Comment by Sandu1213** [comment]
stage验证通过，请合入release环境

**Comment by Kvaya** [comment]
https://keepwork.com/wiki/wikieditor/#/shirley123/personal/editor%E6%8F%90%E7%A4%BA%E7%9A%84%E8%8B%B1%E6%96%87%E7%BF%BB%E8%AF%91
英文按代码区写。注意不要从浏览界面看，不标准。

英文详细如下：
1.为页面添加一组按钮，可以使用“菜单编辑器”来进行内容管理
1.Add a set of buttons and use Menu Editor to manage contents.
2.为页面添加绘图，支持基本图形、各种图表、工程图、流程图、网络拓扑图、UML、Venn等
2.Add drawing function supporting  basic graphics, various diagrams, engineering diagrams, flow charts, network topology diagrams, UML, Venn, etc 
3.为页面添加评论功能，方便大家参与讨论
3.Add commenting feature to facilitate discussion.
4.评论留言
4.Comment
5.允许发表评论
5.Allow comments
6.设定QQ号
6.QQ account settings
7.请输入联系人QQ号
7.Please input QQ account
8.为页面添加QQ聊天功能，方便访问者联系指定QQ
8.Add QQ chatting feature to facilitate visitors' contacting the specified QQ account.
9.文本（Markdown）
9.Text(Markdown)
10.请输入内容
10.Please input...
11.Markdown是一种简单的、轻量级的标记语言。
11.Markdown is a simple and lightweight markup language.
常用示例：
Common examples:
字体
Font
**这是加粗的文字** 
**Bold**
*这是倾斜的文字*
*Italics*
***这是斜体加粗的文字*** 
***Bold italics***
~~这是加删除线的文字~~
~~Strikethrough text~~ 


引用
Quote
>这是引用的内容
>This is a quote.

标题
Heading
# 这是一级标题
# First level heading
## 这是二级标题 
## Second level heading
注意：#跟标题之间都要有一个空格
Note: Include a space between # and headings.

无序列表：在内容前加“- + *”任何一种即可
Unordered list: Add one symbol (- + *) before the content.
+ 列表内容
+ Content
- 列表内容
- Content
* 列表内容
* Content

注意：- + *跟内容之间都要有一个空格
Note: Include a space between symbols (- + *) and the content.
了解更多>
View More>
