### ISSUE TITLE
打字的地方需做关键词过滤，有问题需提示

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#2612]
例如：
![RF@$VQRMI6MECA3TNVX(RPJ.png](https://images.zenhubusercontent.com/5ac352dc4b5806bc2bcd6b02/3d1af743-24fd-486b-85d0-9129685a8fee)

**Comment by Sandu1213** [comment]
验证无效，请再优化

**Comment by Sandu1213** [comment]
功能可用了，但还需要优化
![image](https://user-images.githubusercontent.com/21214285/48259258-618ecd80-e452-11e8-8dc3-d535e7917c08.png)
