### ISSUE TITLE
【Bug-PBL】实名认证接口返回认证成功，实际上没有实名成功

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#2653]

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/47775694-54bffa80-dd2b-11e8-9fb8-424bddb9d16f.png)

![image](https://user-images.githubusercontent.com/18642919/47775724-7325f600-dd2b-11e8-9c49-bbfb32d36196.png)

**Comment by wxaxiaoyao** [comment]
目前实现, 注册,手机,实名三者无关联,互不影响.  仅在注册时手机号一定会实名该注册用户, 手机号尝试绑定注册用户(手机号未绑定则绑定).   其它绑定与实名操作互不干扰与影响.
