### ISSUE TITLE
【Bug-文件树】文件树下创建多个同级文件夹后，无法完整打开文件树，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#266]
## The problem
文件树下创建多个同级文件夹后，无法完整打开文件树，请调整

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor页面后，在新建网站下面添加文件夹A，再在文件夹A添加多个同级文件夹，观察添加效果

* Expected Result:
1.添加成功，展示正确
* Actual Result:
1.添加成功，显示不对
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/631046b9-076d-4791-b2b9-02e593ed93fe)

**Comment by Sandu1213** [comment]
问题依然存在，请排查

**Comment by yuanoook** [comment]
问题：纯数字的文件夹有 Bug

原因：src/lab/utils/gitlab.js gitTree2NestedArray 用了 _.set
_.set will handle number in setKeys with Array, that's not what we want

解决方案：用 _.setWith Object 换掉 _.set
