### ISSUE TITLE
【Bug-PBL】白板里的标签添加逻辑实现不合理

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2670]
### Details:
补充： **应该不允许添加重名标签**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/3c3b4561-b349-459c-a247-d40e10b0e76b)

**Comment by DDXY1230** [comment]
标签组件按回车建操控，确定取消用于提交你的修改或者取消修改，这个组件是失焦来判断的，暂时还没有更好的组件

**Comment by DDXY1230** [comment]
试试用回车键添加标签

**Comment by DDXY1230** [comment]
试试用回车键添加标签

**Comment by Sandu1213** [comment]
@azothli  @Kvaya  请确认，目前的设计很容易让用户产生误导的行为。

**Comment by azothli** [comment]
那就把取消按钮去掉好了，用户可以用那个删除 来达到目的

**Comment by Kvaya** [comment]
不允许重名标签
