### ISSUE TITLE
【Bug-PBL】白板查看和编辑权限添加

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#2684]
![image.png](https://images.zenhubusercontent.com/59df33a4b0222d5de47b5b3c/bed05f47-04bb-424a-b414-729a4766cef2)

**Comment by Sandu1213** [comment]
回归不通过，请重新调整

**Comment by Sandu1213** [comment]
- 允许任何人编辑时，其他用户编辑后，保存不成功
![image](https://user-images.githubusercontent.com/21214285/48107395-6b5dd880-e27a-11e8-945f-09b70fbee0ac.png)

-
