### ISSUE TITLE
【lesson-bug】学生学习教师未审核通过的课程包，学完了一课。在学生专栏，查看这课的学习总结，总结显示为空。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2711]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/8a2b6ea0-fd25-448b-8ca5-074f803a5986)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/2189f891-0de2-405a-b4ff-4c8167d30772)

**Comment by Sandu1213** [comment]
reelase验证通过
