### ISSUE TITLE
【Bug-PBL】白板里创建的任务需要允许指派给自己

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2718]
### Details:
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/78ef9bfe-b893-4261-bfcd-5709d7e4ca54)

**Comment by DDXY1230** [comment]
新建的项目可以指派给自己

**Comment by DDXY1230** [comment]
最好用新用户，旧用户可能不行
