### ISSUE TITLE
【Bug-lessons】教师专栏里的授课-课程数量统计不对，且图片封面存在裁剪

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2721]
### Details:
**Env:** [keepwork](https://www.keepwork.com)

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/4a4075e2-fe69-4d94-bd18-343204b5fc75)

**Comment by DDXY1230** [comment]
以新版为主

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/49560089-129e6000-f94c-11e8-89dd-e6c8285d20a6.png)

**Comment by Sandu1213** [comment]
release验证ok
