### ISSUE TITLE
【Bug-Env】代码合入相关issue记录

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2746]
### Details:
1. lesson 学生专栏/教师专栏不能正常查看
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/3eb6cc1a-44de-4e35-9d9e-132453e29315)

2. lesson 课程详情页不能正常打开，无法自学
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/0533dca7-474d-48cc-8235-1183a8ec166a)

3. editor里的board mod不能正常使用了
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/5ca9a462-a362-4352-97bb-31e1ea21d290)

4. editor里当光标停留在预览区时，ctrl+s不能正常保存
![image](https://user-images.githubusercontent.com/21214285/48049223-ec649380-e1d8-11e8-899e-7d4d4ad94186.png)

5. editor里的img mod无法正常使用
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/431dd1b0-e2a9-4f4c-b68e-f95648996618)

6. editor里的comment mod无法使用
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/02774529-b9f8-491b-bc14-863b4c4b3c11)

7. editor里的mixlayer mod设置图片后，无法查看
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/fa5f834a-3cc9-4b53-a709-0e12fc951dbd)

8. editor里paracraft mod和mixPositon mod设置封面后，看不到图片
 
9. 无法打开网站基础设置
![image](https://user-images.githubusercontent.com/21214285/48049767-ac061500-e1da-11e8-9a91-2bcebc6c8a90.png)

10. 菜单栏里的刷新和删除当前页面功能不可用
![image](https://user-images.githubusercontent.com/21214285/48049912-2cc51100-e1db-11e8-9b53-c96859996b70.png)

**Comment by leopoldchen** [comment]
@onedou 3\5\6\7

**Comment by leopoldchen** [comment]
@kevinxft 4\9\10

**Comment by kevinxft** [comment]
editor里当光标停留在预览区时，ctrl+s不能正常保存 ，这个问题暂时没有找到合适的解决方法

**Comment by kevinxft** [comment]
5,6已经改了

**Comment by Sandu1213** [comment]
- comment mod不能正常评论
- web setting设置封面失败
