### ISSUE TITLE
【Bug-template】新建网站的模板取用地址不统一，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#276]
## The problem
新建网站的模板取用地址不统一，请调整

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:  website->template

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor页面，创建新的网站，选择不同的模板进行预览操作，观察预览效果

* Expected Result:
1.命名合理，取用地址合理
* Actual Result:
1. 选取的地址不统一
 

## Attachments (eg:logs/video/screenshot)
![preview_url_issue.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/11026b11-6f45-465b-9220-5c856d3498a6)

**Comment by leopoldchen** [comment]
使用新版本layout后，此问题应该可以解决，届时再确认
