### ISSUE TITLE
【Bug-PBL】白板允许任何人查看时，其他用户查看的白板信息不对，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2762]
### Details:
1.用户B去打开用户A的项目，查看项目相关的白板信息，观察信息显示是否正确

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/e9ddfb9e-e3d7-42e5-a615-53dd9cacbda5)

![image](https://user-images.githubusercontent.com/21214285/48107562-19698280-e27b-11e8-885d-b0b06f05605e.png)

**Comment by Sandu1213** [comment]
问题依然存在，请调整
![image](https://user-images.githubusercontent.com/21214285/48118260-bdb4ee80-e2a6-11e8-8637-2ffd0f869013.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/48127981-1349c500-e2c0-11e8-86c6-2c900a9f642f.png)

**Comment by DDXY1230** [comment]
显示时间几秒那个单独提个issue，那个不急，我缓缓再改
