### ISSUE TITLE
【Bug-PBL】当issue数量过多时，白板显示不合理问题，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2766]
### Details:
- 项目首页展示不合理   （请调整为8个，已与产品确认）
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/c6275670-6184-469b-b56f-28d09a8388c6)

- 白板页面需要做分页处理， 每页25个
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/13536339-debb-4a33-a558-76a8a9adaacc)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/48117224-8133c380-e2a3-11e8-9b33-51a2d8c5e448.png)
![image](https://user-images.githubusercontent.com/21214285/48117324-cb1ca980-e2a3-11e8-9ba1-b0a521a8b424.png)

**Comment by Sandu1213** [comment]
模糊搜索的问题和筛选查询后分页数量不对的问题还需调整

**Comment by Sandu1213** [comment]
搜索关键字或id，  这里的关键字只针对issue标题即可

**Comment by Sandu1213** [comment]
搜索的问题还是存在，请完善

**Comment by DDXY1230** [comment]
描述下存在的问题
