### ISSUE TITLE
【Bug-PBL】项目的评论时间记录不对，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2769]
### Details：
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/20725353-fec8-4425-9379-e7484c879fd1)

**Comment by Sandu1213** [comment]
@azothli 建议以哪种为准呢？

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/48115341-8c83f080-e29d-11e8-98d5-1dd011dd4e73.png)
