### ISSUE TITLE
【Bug-editor】编辑器预览区的效果与代码区不符，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#277]
## The problem
编辑器预览区的效果与代码区不符，请调整

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor页面后，创建新的页面,添加不同的mod,观察预览区展示效果与代码区的设置是否相同

* Expected Result:
1.页面信息显示正确
* Actual Result:
1.显示不合理

**Comment by Sandu1213** [comment]
![code_preview](https://user-images.githubusercontent.com/21214285/39035098-67204298-44ab-11e8-87c6-da4b93fbc526.png)

**Comment by onedou** [comment]
img loop mod 有问题，但是markdown的显示应该是对的

**Comment by Sandu1213** [comment]
验证通过
