### ISSUE TITLE
Core API proxy for wikicraft

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#2781]
### 背景

因核心api迁移，导致wikicraft旧版api不可用。
然而哈奇等应用还在使用旧版api，而且短期内不好做api迁移。
因此，需要解决旧版api的兼容问题。

### 解决方案

经讨论，介于仍在使用的wikicraft api并不多，可以直接做api adaptor，将旧版api对接到新版

注： 这个问题直接影响发版，优先级最高。

**Comment by wxaxiaoyao** [comment]
coreserver代理注册接口 /api/wiki/models/user/register,并同步用户数据到wikicraft以保证wikicraft相关功能正常.

**Comment by Sandu1213** [comment]
register接口已验证，可正常使用。
新注册的用户也可以正常进行购买操作。
