### ISSUE TITLE
【bug-pbl】目前给网站创建一个分组需要请求多个接口。需要改成一个接口完成

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#2784]
![image](https://user-images.githubusercontent.com/18642919/48174098-7f204200-e341-11e8-8438-e35847c31bcb.png)

1. 创建分组
![image](https://user-images.githubusercontent.com/18642919/48174129-a1b25b00-e341-11e8-9358-943b6c34c5b0.png)

2. 添加成员到分组（添加几个成员就需要发几次请求）
![image](https://user-images.githubusercontent.com/18642919/48174164-c7d7fb00-e341-11e8-8df1-25949ae70118.png)

**Comment by wxaxiaoyao** [comment]
![image](https://user-images.githubusercontent.com/11922085/48254753-d4457c00-e445-11e8-8053-1e65f56ee16a.png)
