### ISSUE TITLE
【Bug-多地登录】登录态检查有误，用户A在机器A上登录后，再切换到机器B上，修改密码后再次使用机器A进行操作，应该提示需要重新登录

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#2787]
@Sandu1213 commented on [Mon Mar 26 2018](https://github.com/tatfook/wikicraft/issues/1748)

# The Problem:
登录态检查有误，用户A在机器A上登录后，再切换到机器B上，修改密码后再次使用机器A进行操作，应该提示需要重新登录

# Environment:
* Devices info: PC
* OS system: windows
* Browser : chrome  65.0.3325.181
* Model:  登录

# Reproduces:
* Pre-conditions:
  1.网络正常，有2台以上设备
  2.已注册过Keepwork账号
* Details:
  1.账号A在机器A上进行登录操作，操作完成后未退出，即切换登录到机器B上
  2.再机器B上进行修改密码的操作，修改密码完成以后，再切换到机器A上进行操作
  3.进行充值VIP或者删除网站等操作，观察操作是否成功
* Actual Result:
  1.可以操作成功
* Expected Result:
  1.操作失败，用户需要重新进行登录后才能再进行操作

# Attachments (eg: Video/png/log)
  无

---

@ExerciseBook commented on [Wed Apr 04 2018](https://github.com/tatfook/wikicraft/issues/1748#issuecomment-378423726)

更换密码后删掉现有的这个账号的session就可以简单解决问题？

**Comment by leopoldchen** [comment]
这个是JWT的技术实现问题，在wikicraft完整完整迁移后，可以添加机制废弃旧token，或者可以改用session的实现方式。

**Comment by leopoldchen** [comment]
@wxaxiaoyao 
是否考虑添加redis来处理失效token

**Comment by wxaxiaoyao** [comment]
考虑下做必要性吧, 感觉为了一种偶然情况去增加代码的复杂性已降低性能不是很可取...  用jwt就是避免做网络请求以及相关验证.  而且上述的bug期望值是否是正确的也需要考虑清楚, 可以研究其它产品这类情况是怎么处理的.

**Comment by Sandu1213** [comment]
修改不彻底，当B修改好密码以后，A在编辑器页面还是可以正常的编写文件并进行存档

**Comment by wxaxiaoyao** [comment]
哎 ....   就不建议改...   上面不是我这边解决  前端和郑嘉标协商下吧

**Comment by wxaxiaoyao** [comment]
/api/wiki/models/oauth_app/agreeOauth
/api/wiki/models/oauth_app/getTokenByCode
此接口未做代理, 目前第三方程序都是从wikicraft中获取token, 导致此bug目前无法解决, 需先解决第三方程序登录走新逻辑, 需代理上述接口, 走新逻辑.

**Comment by William0911** [comment]
> 修改不彻底，当B修改好密码以后，A在编辑器页面还是可以正常的编写文件并进行存档

dev环境已修复，改好密码后token失效，无法编辑文档

**Comment by Sandu1213** [comment]
stage已经验证。
保存文件时，会提示保存失败。
返回到主页面，则会提示token过期，然后3秒后刷新页面
