### ISSUE TITLE
【bug-pbl-手机版】优先处理一级页面的适配

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#2793]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/bfcd9b2a-559f-4fde-8d33-b5ce75242137)

**Comment by shirleyluo1130** [comment]
手机端适配，优先如下1级页面：
- [ ] 1. 首页
- [ ] 2. 创造
- [ ] 3. 探索
- [ ] 4. 学习

**Comment by shirleyluo1130** [comment]
![image](https://user-images.githubusercontent.com/40385277/48759405-f2c93400-ecdd-11e8-8b2f-08ec3eec18c7.png)

**Comment by duting1993** [comment]
@kevinxft @ZhangKaitlyn @DDXY1230
