### ISSUE TITLE
【Bug-keepwork】一网乾坤调整为“个人作品网”

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2797]
### Details:
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/c03b2d3a-4761-42bc-8018-5183301419b2)

**Comment by azothli** [comment]
这个要看是什么为位置，可以有列表么？

**Comment by ZhangKaitlyn** [comment]
![2Q00(HZ9SPM6RZ7KO4(OE}W](https://user-images.githubusercontent.com/18642919/57599761-614ec680-758a-11e9-8bbc-9c5880da2451.png)

**Comment by ZhangKaitlyn** [comment]
![BLVYX)BKJRU~$1P`T@Q(HY2](https://user-images.githubusercontent.com/18642919/57599793-7592c380-758a-11e9-98b8-fd626633b328.png)
