### ISSUE TITLE
【权限管理】接口需要修改的

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#2818]
![image](https://user-images.githubusercontent.com/18642919/48246438-6cce0300-e42a-11e8-980d-83d2dd266c28.png)
获取分组列表需要先获取用户group列表，再循环group，在每个循环里获取该group的成员。 
**实际上应该一个接口返回所有分组以及成员**

--------

![image](https://user-images.githubusercontent.com/18642919/48246478-8a9b6800-e42a-11e8-841a-f777ade6abaa.png)
创建分组时，需要先新建分组（新建成功和失败的处理），若新建分组成功，再循环要添加的成员，把成员添加到分组里（有多少成员就要发多少请求，每个请求有成功和失败的处理）。
**实际上应该创建时附带成员列表。另外，更新分组信息时也应该更新成员信息（包括添加和产出）**

**Comment by wxaxiaoyao** [comment]
批量创建更新成员
![image](https://user-images.githubusercontent.com/11922085/48259057-c7c72080-e451-11e8-8b23-e5e4c51c661d.png)
一次性拉取所有组及成员
![image](https://user-images.githubusercontent.com/11922085/48259066-d1e91f00-e451-11e8-8f13-81594ac58c40.png)
组创建更新接口不变

**Comment by wxaxiaoyao** [comment]
![image](https://user-images.githubusercontent.com/11922085/48333297-d4d25280-e691-11e8-8024-fd597a401e2e.png)
