### ISSUE TITLE
【优化-pbl】视觉需要优化

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#2828]
![1 l4au7rm83 n9t0c hwpp5](https://user-images.githubusercontent.com/28430070/48255838-ca714800-e448-11e8-8dd7-a335832e5886.png)

**Comment by enya-i** [comment]
![79c7b03b32524d1cdd974572762f6843](https://user-images.githubusercontent.com/37529364/48324578-4c8d8680-e66c-11e8-97bd-1c657b9cdde8.png)
