### ISSUE TITLE
【需求-PBL】新建项目后，根据项目类型从默认给的五幅图中随机抽选一张当项目封面图

### ISSUE THREAD

**Issue by enya-i** [tatfook/keepwork#2869]
![50C8ECD6B3071A32C6F5943EF970F08A.png](https://images.zenhubusercontent.com/5aaf5b544b5806bc2bcb5c1a/1f9c263a-0d2e-4066-870b-66cd092cc966)

PS： 两种类型分别有5幅图

**Comment by azothli** [comment]
这个需求暂时可以不处理了
我们增加了是否设置封面对项目在排名展示中的影响。
5副随机解决不了问题。
