### ISSUE TITLE
【Bug-PBL】搜索-课程，新增的课程或者课程包都搜索不到，请排查

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2873]
### Details:
新增课程包及课程，审核上线后去搜索里查看，查看不到

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/05b74937-f45a-4db5-b779-84622e52ffd6)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/5f560e11-eb08-4f92-978d-ef53d4fee230)

**Comment by William0911** [comment]
@wxaxiaoyao lessons中的搜索接口是否已经对接？
