### ISSUE TITLE
【pbl-调整】paracraft项目，访问项目按钮的弹出UI

### ISSUE THREAD

**Issue by azothli** [tatfook/keepwork#2877]
为了解决用户没有安装paracraft，或者url protocol没有被正确的设置

用户点击访问项目的时候，同事弹出该窗口
如果项目被正确打开，paracraft在浏览器外层，本弹出窗其实就看不到了。
如果没有正确得开，用户则会看到相关的提示。

@enya-i  发下设计图

**Comment by enya-i** [comment]
![default](https://user-images.githubusercontent.com/37529364/48395032-c008c400-e750-11e8-97a8-97e4c23727f4.jpg)
![70b7b729f1d152dd22e589d6dffd7dc6](https://user-images.githubusercontent.com/37529364/48395076-e9295480-e750-11e8-93bb-f5dcdc0c83d7.jpg)
