### ISSUE TITLE
模型商城 demo

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#290]
### 目标

为爱致科技模型商城搭建基础代码环境，剩下页面样式部分交由爱致team的前端人员处理。

### 指标

- [ ] 基础运行环境，集成部署功能
- [ ] qiniu上传(api service层)
- [ ] 模型数据存储
- [ ] ES服务API集成(api service层)
- [ ] gitlab API 封装

**Comment by wxaxiaoyao** [comment]
[demo地址](http://esdemo.keepwork.com)
[esserver地址](http://es.keepwork.com)

[esdemo代码地址](https://github.com/tatfook/esdemo)
[esserver代码地址] (https://github.com/tatfook/esserver)

## 部署方式
cd projectDir; npm install; npm run dev;
