### ISSUE TITLE
【pbl-调整】paracraft 项目 访问3D世界按钮，在为创建世界的时候，调整文字

### ISSUE THREAD

**Issue by azothli** [tatfook/keepwork#2904]
paracraft 项目 访问3D世界按钮，在为创建世界的时候，调整文字为“创建中”

liyu  15:36:38
hi，big  paracraft的项目，如果用户没有创建世界，这个页面那面可以取得这个状态么？
[BIG]  15:36:54
可以呀
如果没有创建，就没有archiveUrl那个值
或者是空值
liyu  15:37:37
好，那按钮那面我调下，避免别的用户访问的时候卡住

**Comment by azothli** [comment]
访问项目  按钮文字 调整为  访问世界

**Comment by Sandu1213** [comment]
没有创建世界的问题还需要调整
