### ISSUE TITLE
【Bug-点赞】从编辑器里打开新页面，进行点赞操作，点赞失败

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2922]
### Details:
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/55209ec9-7a9e-40c2-8f54-c2d00b13c4ac)

**Comment by leopoldchen** [comment]
@azothli 
目前页面没有点赞功能，是否需要补充？

**Comment by Kvaya** [comment]
现可以把“点赞“功能去掉，后期假设需要获取网站/网页点赞数这个数据，再做

**Comment by Sandu1213** [comment]
点赞功能已经移除
![image](https://user-images.githubusercontent.com/21214285/53385752-7ae46700-39ba-11e9-9086-1d6e2a5981df.png)
