### ISSUE TITLE
【Bug-PBL】待优化问题汇总

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2960]
### Details:
- 错别字问题
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/8d098e9b-895b-43e0-8d63-07cae60dfa95)

- “个人知识” 调整为 “个人知识引擎”
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/e2a7fe8f-27da-4036-b31f-8b9dd1f7c27c)

-  工具里paracraft描述调整
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/5222e9b3-a7e2-429a-baf4-ef9a8c186fc1)

- 项目页显示问题
 ![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/c576a505-27d4-4225-b760-96989a66a9e5)

- 共有网站访问时不需要用户登录
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/10bbf627-86fd-4469-bbb7-0485d9c6a2aa)

- 搜索页调整
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/37d190cb-9b3a-4220-bde6-abd133cee2d1)

- 字体问题
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/cd850a01-39a9-431e-bf6a-965fcfaa1996)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/545dc727-6b5b-4033-bc58-c0724f4a86f8)

**Comment by Sandu1213** [comment]
- lesson 教师端课程及课程包打开没有一次显示全的问题
![image](https://user-images.githubusercontent.com/21214285/48596654-f767b280-e994-11e8-9df1-72ccf17d9073.png)

- 对于未审核通过的课程包进行查看时，跳转路径不对（需要跳转到课程包详情页面，目前跳转到了课程中心页面）

**Comment by kevinxft** [comment]
- [x] 错别字问题
- [x] “个人知识” 调整为 “个人知识引擎”
- [x] 工具里paracraft描述调整
- [x] 项目页显示问题
- [x] 共有网站访问时不需要用户登录
- [x] 搜索页调整（跟产品确认过，调整搜索到三个字为包含）
- [x] 字体问题
- [ ] 按钮颜色问题

**Comment by Sandu1213** [comment]
补充：
- 权限管理的用户名称显示需要统一
![image](https://user-images.githubusercontent.com/21214285/48603168-859d6200-e9b0-11e8-92eb-3d1baac14842.png)

**Comment by Sandu1213** [comment]
- footer底部的反馈链接不对，请调整
  调整为：https://github.com/tatfook/keepwork/issues
