### ISSUE TITLE
【学习板块】学习中心（教师身份）- 自主学习用户

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2965]
即，未激活时的显示页面。

**Comment by duting1993** [comment]
与设计图不符
左边是设计图，右边是现在显示情况
![image](https://user-images.githubusercontent.com/28430070/49271960-b7cbbb00-f4aa-11e8-85ee-b8dbd27398e6.png)

**Comment by DDXY1230** [comment]
没有激活码是禁用状态
