### ISSUE TITLE
【学习板块】解决方案 - 学生家长 - 线下导引课（查看更多）

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#2970]

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/49273076-c74d0300-f4ae-11e8-9089-b6425765b2b4.png)
点击了解更多，跳转如图二页面
![image](https://user-images.githubusercontent.com/28430070/49273097-d59b1f00-f4ae-11e8-92fd-4cd1fa72bbe9.png)
跳转的页面与设计图不符
