### ISSUE TITLE
lesson界面

### ISSUE THREAD

**Issue by wanglin727** [tatfook/keepwork#2986]
![image](https://user-images.githubusercontent.com/33826048/48603871-db730980-e9b2-11e8-985c-ca1aae7b0a6b.png)

![image](https://user-images.githubusercontent.com/33826048/48604030-74098980-e9b3-11e8-8a9b-0b4cba83fe64.png)

界面有部分出处，已表明问题点

![image](https://user-images.githubusercontent.com/33826048/48603796-9cdd4f00-e9b2-11e8-95bd-8067e6eb50e1.png)

**Comment by Sandu1213** [comment]
[效果页](https://release.keepwork.com/l/student/package/35/lesson/108)
![image](https://user-images.githubusercontent.com/21214285/53475085-01c43d00-3aaa-11e9-9f1f-35a89172fc7a.png)

**Comment by kevinxft** [comment]
![image.png](https://images.zenhubusercontent.com/59edff22a468affe6df7caf6/2c0b2136-422d-49e5-a772-b3213b960b5c)
没办法保证每台电脑显示效果完全一致
