### ISSUE TITLE
跳转到keepwork“创造”“探索”“学习”页面，“创造”“探索”“学习”字样可加高亮，提示用户是在该页面中

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#2988]
问题详细：
例如现在学习页，“学习”二字可做高亮
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/f80c3ba9-7837-4ed1-ac78-2f8c84282579)

**Comment by Sandu1213** [comment]
release已验证
