### ISSUE TITLE
拖拽文件到代码区中，目前有的格式是不支持，需支持；且对加载后的显示效果进行优化

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#2989]
**问题详细：**

1.格式图标有的能显示，有的不能；

2.文件名不是时间，应是文件名+格式后缀名

3.自适应。当浏览器窗口缩小，文件名、下载被遮盖

![image](https://user-images.githubusercontent.com/39363297/48607151-ccdd2000-e9bb-11e8-9973-d1e2d3cb5303.png)

**备注：**

1.现测exe、svg、svga、xmind这些文件是拖拽上传后，未显示具体哪种类型图标，需调整；

2.现支持有：rar、zip、doc、xls、xlsx、ppt。

**建议：**
1.图标离背景框左边距是24px，下载图标离背景框右边距是36px，如图：
![image](https://user-images.githubusercontent.com/39363297/48609038-36f6c480-e9be-11e8-8ddd-abf8eccc4b7e.png)

2.各个文件的图标、各个文件名+格式后缀名需显示，参考设计师做的
![image](https://user-images.githubusercontent.com/39363297/48609116-4c6bee80-e9be-11e8-8b26-b8efab002335.png)

3.文件名默认显示10个汉字、20个英文字母，超出10个汉字、20个英文字母，显示如设计师做的
![image](https://user-images.githubusercontent.com/39363297/48609374-8fc65d00-e9be-11e8-8042-c97551184a8a.png)

**Comment by Kvaya** [comment]
![image](https://user-images.githubusercontent.com/39363297/50148852-8e0cf380-02f4-11e9-89b5-7c9867361adc.png)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/50201037-7df82100-0393-11e9-8184-2fced0f5fa45.png)
iconfont 已更新

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/50201105-c1528f80-0393-11e9-8cfb-32985071c410.png)
iconfont已更新

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/50329671-327c7900-0533-11e9-8f24-5473d8075ca4.png)

**Comment by Kvaya** [comment]
额外说明：建议3中，十个汉字/20个字母+类型，一行显示；超过十个汉字/20个字母的，显示10个汉字/20个字母，超出部分省略
