### ISSUE TITLE
【Bug-mod】menu mod添加子菜单，就会出现预览区显示不对的情况

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#299]
## The problem
menu mod添加子菜单，就会出现预览区显示不对的情况

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:  website->mod

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor页面，创建新的页面，添加menu mod，给菜单A添加多个子菜单，观察显示情况
* Expected Result:
1.显示效果合理
* Actual Result:
1.显示效果不合理 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/6ba69b92-9065-43ee-8363-aeb9b8b3336b)

**Comment by onedou** [comment]
应该没有问题了
