### ISSUE TITLE
【Bug-网盘文件链接】网盘生成的URL地址不美观，需要优化调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#2990]
### Details:
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/bf788f22-ed76-4fa2-a420-93cc86a2906c)

**Comment by Sandu1213** [comment]
@leopoldchen  链接需要调整，请评估实施方案

**Comment by wxaxiaoyao** [comment]
![image](https://user-images.githubusercontent.com/11922085/53612264-99da3780-3c0c-11e9-807a-d962cde033a1.png)

fixed

**Comment by Sandu1213** [comment]
stage环境验证通过
![image](https://user-images.githubusercontent.com/21214285/53620354-9c00be00-3c2d-11e9-9aa0-37e31cfe2f59.png)
