### ISSUE TITLE
【Bug-lessons】lesson相关问题的

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3000]
### Details:
- 问题1：用户通过paracraft进入课程，无法通过URL打开课程，token信息是有效的。
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/07731746-f9c3-437c-b757-7ab0ee0d2720)

- 问题2：教师进行上课操作，会提示操作失败，应该跟生成课堂ID有关。刷新页面，实际已经开课成功
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/9bff4941-e81f-4ecf-959e-6c056767cd89)

- 问题3：用户加入课堂，用户的信息无法展示
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/70a98c70-c37f-4240-8768-b62867a4969d)

- 问题4：匿名自学和匿名上课的功能也不可用

**Comment by shirleyluo1130** [comment]
问题5：查看学习总结，应显示课程名称，当前显示为数字。如下：
![image](https://user-images.githubusercontent.com/40385277/48620241-5ac80380-e9da-11e8-9c51-65aee8f9dd6c.png)

**Comment by shirleyluo1130** [comment]
问题6：上课后，查看“学生状态”，显示为，只有1个学生进入课堂，如下所示：
![image](https://user-images.githubusercontent.com/40385277/48620486-45070e00-e9db-11e8-80ec-a2d04b250381.png)
下课后，查看课堂总结，显示为，有2个学生的课堂数据，如下：
![image](https://user-images.githubusercontent.com/40385277/48620527-6405a000-e9db-11e8-89a5-b934915d6c98.png)

**Comment by shirleyluo1130** [comment]
问题7：当前没有任何课程在学习中，在“学生专栏”页面，点击第一个课程包的“继续”按钮，弹出如下提示：
![image](https://user-images.githubusercontent.com/40385277/48620693-f3ab4e80-e9db-11e8-8c10-2fce09d484c1.png)

**Comment by Sandu1213** [comment]
问题2已经解决了

**Comment by Sandu1213** [comment]
问题7，验证的确不存在，请确认。 @shirleyluo1130

**Comment by shirleyluo1130** [comment]
去掉问题7
