### ISSUE TITLE
使用iframe方法打开 paracraft procotol

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#3002]
https://gist.github.com/aaronk6/d801d750f14ac31845e8

**Comment by LiXizhi** [comment]
其实如果某些浏览器可以检测到用户是否有url protocol, 则可以选择性的显示一句话。 

另外，下面的UI中是否考虑下增加一个直接下载的ZIP的方案。 如果有些机器确实无法启动protocol还可以有planB

![image](https://user-images.githubusercontent.com/94537/48683929-5f630680-ebea-11e8-917e-fb9b6bf23df2.png)

**Comment by azothli** [comment]
按钮 【下载存档】
然后最后再加一行说明
* 下载的存档请放在Paracraft安装目录下的\worlds\DesignHouse\中使用

**Comment by azothli** [comment]
按钮样式使用白色的就好
