### ISSUE TITLE
editor中代码区数据已一键删除，但中间预览编辑区相关内容还在显示

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3003]
详细，如图：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/4dce9ae1-f8e5-4f18-af3d-35f359bb1c11)

![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/d93048e9-14c2-45cf-9c18-1959dc37d0ba)

**Comment by Sandu1213** [comment]
release验证通过
