### ISSUE TITLE
editor代码区中上传一文件，已上传好且中间预览浏览区也显示了。还显示“正在上传。。。”

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3004]
详细：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/3e414d99-dc83-429c-8960-f95cc7483bd9)

**Comment by Sandu1213** [comment]
图片已经上传成功，代码区未将“正在上传。。。”提醒消除

**Comment by Sandu1213** [comment]
release环境验证通过
