### ISSUE TITLE
【profile】主页tab

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#3022]
请查看设计稿和[功能清单](https://keepwork.com/keepwork/pwiki/pm/profile/功能清单) 

- [ ] 1. 个人信息
- [ ] 2. 我的证书
- [ ] 3. 项目统计
- [ ] 4. 最近项目
- [ ] 5. 我的经历
- [ ] 6. 活跃度

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/48747459-766b2c80-ecae-11e8-934d-09fdb701f3a4.png)
![image](https://user-images.githubusercontent.com/18642919/48748041-72400e80-ecb0-11e8-9df4-d0db3b6be80c.png)


- 添加、编辑证书弹窗设计目前缺失 @enya-i

**Comment by enya-i** [comment]
![image](https://user-images.githubusercontent.com/37529364/48748525-2db57280-ecb2-11e8-813e-6db9258c85ca.png)

**Comment by ouyc** [comment]
6.活跃度
![q 1_og kd s0vx z1ama8](https://user-images.githubusercontent.com/38035998/48750660-3d858480-ecbb-11e8-8e03-d16d13a23f5d.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/49573300-a4bc5d80-f978-11e8-936b-3ecaa77b2394.png)
![image](https://user-images.githubusercontent.com/21214285/49573458-fe248c80-f978-11e8-9e2a-6a145263a5f6.png)
![image](https://user-images.githubusercontent.com/21214285/49573570-48a60900-f979-11e8-820b-6c1bddc88c00.png)
![image](https://user-images.githubusercontent.com/21214285/49573618-6d9a7c00-f979-11e8-8468-ba6f9d0324d7.png)

**Comment by Sandu1213** [comment]
- 入口问题
 ![image](https://user-images.githubusercontent.com/21214285/49632950-87e46080-fa32-11e8-9b44-359feb368067.png)

- 个人信息页错误
![image](https://user-images.githubusercontent.com/21214285/49634847-dbf24380-fa38-11e8-8b2c-e264717fc3b5.png)

- 获奖经历建议优化
![image](https://user-images.githubusercontent.com/21214285/49635037-69ce2e80-fa39-11e8-8e47-6a0208a9e640.png)

- 添加经历日期插件问题
![image](https://user-images.githubusercontent.com/21214285/49635132-bfa2d680-fa39-11e8-9c32-45aa76bcfcf3.png)

- 活跃度缺少月份
![image](https://user-images.githubusercontent.com/21214285/49635188-f1b43880-fa39-11e8-9c1d-afc85d80018f.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/49636365-5a50e480-fa3d-11e8-96a2-dc5726d7154b.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/49638484-36909d00-fa43-11e8-88b6-51bb77b0b8d6.png)

**Comment by shirleyluo1130** [comment]
关于profile的入口：

有用户头像和用户名显示的地方，都可以点击进入对应人的profile页面，全部做成新窗口打开（包括，探索用户的页面，点击头像/用户名，也做成新窗口打开）
