### ISSUE TITLE
【bug】editor 中代码区上面富文本编辑时不生效

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3048]
### 详细：
1.点“斜体”，该文本不变斜体，变红色；

2.输入一段文字，分别点“标题1、标题2、标题3”后，有反应，再一次分别点“标题1、标题2、标题3”后，该文本没有撤销“标题1、标题2、标题3”的功能

**Comment by Sandu1213** [comment]
问题1, 问题需要修改;
问题2, 最初就没有这样的需求，同理其他按钮操作也是添加行为，请评估是否需要?

**Comment by Sandu1213** [comment]
问题1已修复；
问题2暂不处理。
