### ISSUE TITLE
【bug】editor中markdown文本mod

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3050]
详细：
1.editor中markdown文本mod“点击添加”后，属性面板中的提示语不一致，有时候显示“请输入内容”，有时候不显示

2.点击中间预览编辑区中的“文本markdown”mod，无任何可点击的地方且没有反应

3.点击添加“文本markdown”，代码区中没有相应的代码

**Comment by Sandu1213** [comment]
问题1，是因为多添加几次后，存在换行符了，程序会当做已存在输入，故不会出现提示“请输入内容”
问题2,3都是非问题，可以找宇哥或者开发确认清楚。
