### ISSUE TITLE
【bug】editor中“菜单编辑器”中链接处输入不是URL，还可点确定保存下来

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3053]
**问题详细：**
1.editor中“菜单编辑器”中链接处输入不是URL，还可点确定保存下来

2.之前对“菜单编辑器”中名称、链接进行编辑，保存后的“菜单编辑器”再次打开，链接处为空

3.点击某个对象的时候，该处除开框变成蓝色框，框内内容也该是被选中状态

**建议：**
1.当输入的不是URL，灰色框变为红色，并同时出现提示框。如图:
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/0a909ec3-d589-474f-97e2-a9dbb9c11768)

当用户没有修改，编辑其他名称、链接时，那在输入不规范的URL框后面显示警示符号，如图
![image](https://user-images.githubusercontent.com/39363297/48823354-8280e800-ed9b-11e8-8a16-c941f3e2e93a.png)

补充：
1.当菜单编辑器页面URL输入不规范时，点“确定”不可被保存确定，并点“确定”的同时显示哪处内容不规范，
2.鼠标点击不规范链接
以上两点，显示如图：
![image](https://user-images.githubusercontent.com/39363297/48823545-2b2f4780-ed9c-11e8-9e6d-2fefc04bdf3b.png)

URL输入规范后，警示符合和提示语不出现，和现在正常输入效果一样

2.当用户对菜单编辑器中名称、链接中进行了编辑，保存后再次打开，直接显示他编辑的内容

3.当用户点击哪处时，该处内容该是被选中状态，如图所示：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/a0b7b813-4803-41d3-9de8-8571acc8c205)

**Comment by Sandu1213** [comment]
涉及问题：
- 如果用户Url不填，则会导致无法保存 (开发请调整)
- 当用户对菜单编辑器中名称、链接中进行了编辑，保存后再次打开，直接显示他编辑的内容  
  说明： 这里的目的是为了便于用户快速找到上次编辑的地方进行编辑，但开发目前没有实现，个人觉得意义不大，这块全是mod，如果需要又要加特殊处理，建议不用调整   @Kvaya 
- 当用户点击哪处时，该处内容该是被选中状态，如图所示： (开发请调整)

**Comment by Kvaya** [comment]
”当用户对菜单编辑器中名称、链接中进行了编辑，保存后再次打开，直接显示他编辑的内容“现可不用调整

**Comment by onedou** [comment]
当用户点击哪处时，该处内容该是被选中状态，如图所示： (目前内容没有被选中，开发请调整)
![image](https://user-images.githubusercontent.com/3422640/49631831-83b64400-fa2e-11e8-90a3-9598789cddb4.png)
已经显示选中哪里了，这个可先不用调整

**Comment by Kvaya** [comment]
当用户点击哪处时，该处内容该是被选中状态。
现已做出点击某框时，该框高亮
现调整成是：该框高亮+该框内内容被选中。如图
![image](https://user-images.githubusercontent.com/39363297/49632162-b6147100-fa2f-11e8-9313-65f4a9717ce9.png)

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/49634226-0a6f1f00-fa37-11e8-8813-b1c4a7ef810c.png)
此功能暂不调整，如有需要后续再发issue

**Comment by Kvaya** [comment]
补充说明：输入正确链接默认显示。
![e zq9g6r6 8 ee 1t p 5](https://user-images.githubusercontent.com/39363297/49709453-6de39180-fc6f-11e8-8f38-c35007285a87.png)
