### ISSUE TITLE
【bug】在谷歌浏览器中，editor代码区

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3055]
问题详细：
在谷歌浏览器中，editor代码区中有一些文本，鼠标点击任何地方，光标还是在这段文字最后处，这个不合理，用户是想改中间那句话，但光标还是在最后面，修改不了想改的部分

建议：参考火狐浏览器，火狐浏览器editor代码区中的操作是正常的

**Comment by Sandu1213** [comment]
请问是哪些文本，提供一下便于问题定位。

**Comment by Kvaya** [comment]
问题如图：
![image](https://user-images.githubusercontent.com/39363297/49006684-93b76380-f1a4-11e8-8e9c-957daf4e43da.png)

**Comment by kevinxft** [comment]
@Kvaya 😕并没有复现出来
