### ISSUE TITLE
【bug】在keepwork探索页面

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3070]
详细：
1.在用户那类别中，搜索用户名的一半字段，但搜索结果没有显示，如图：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/ec646c51-65fb-4578-a9cd-8fbf28bcec29)

![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/220c2a31-c977-4354-8efe-86fc43fd9710)

2.在课程类别中
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/26bc7720-f635-4da1-8059-1f07546bb6cc)

![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/a0bd10f2-614c-4cd4-96d7-717b56f55250)

![image](https://user-images.githubusercontent.com/39363297/48878831-1e662e80-ee44-11e8-8df2-ce683e473ca0.png)

补充：课程搜的关键字包含在名称、包含的课程数量、年龄、简介、价格中。含有的关键字该高亮

**Comment by leopoldchen** [comment]
@William0911 

模糊匹配问题

**Comment by William0911** [comment]
和产品沟通过后 数量、年龄、价格相关的高亮不需要做了
简介相关的匹配后端功能已经做了，但前端还没有做相应处理，导致页面产生bug。
请前端调整。

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/50469442-57fffb80-09e7-11e9-9c0d-f6c3df6983bf.png)

**Comment by DDXY1230** [comment]
release环境

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/50505176-2b161c00-0aad-11e9-8582-cd9cc4e3c27b.png)
![image](https://user-images.githubusercontent.com/21214285/50505212-5567d980-0aad-11e9-9823-95f11f6ff9e7.png)

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/50505372-2bfb7d80-0aae-11e9-8e32-95162127c1fb.png)

**Comment by Sandu1213** [comment]
请仔细看问题的描述，谢谢！
![image](https://user-images.githubusercontent.com/21214285/50507145-23f40b80-0ab7-11e9-8afe-3f53791fb5d1.png)

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/50509996-e6957b00-0ac2-11e9-91e4-580543375091.png)

**Comment by DDXY1230** [comment]
没有返回数据处理不了，肖凯文专用课程包根本没有简介，要我编一个？

**Comment by Sandu1213** [comment]
你没理解我的意思，我上面的图片已经反馈出该课程包有简介，但后端给你返回的信息里却没有，所以你应该去找对应的后端确认为啥没有返回。而不是回复我一个我编一个？
鉴于release环境可能存在脏数据，该问题就待线上环境再验证吧。

**Comment by William0911** [comment]
测试环境有些数据是以前的脏数据，可能是错的，可以建个新的，或者更新一下老的看看。
