### ISSUE TITLE
keepwork官网登录页面，用户点击“忘记密码”可重置密码，重置密码进行二次优化

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3078]
详细：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/65458468-48c8-455c-b30f-7add27290b32)

逻辑参考：
![image](https://user-images.githubusercontent.com/39363297/48888484-d1974d80-ee6d-11e8-87f4-a1ca730a2ceb.png)

**Comment by Kvaya** [comment]
设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/49000252-f2281600-f193-11e8-9b5a-d3db3a11b5c0.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/49559368-8f7c0a80-f949-11e8-8f1f-3a1ff29aa72d.png)
![image](https://user-images.githubusercontent.com/21214285/49559558-20eb7c80-f94a-11e8-8eea-1a04158c49eb.png)
![image](https://user-images.githubusercontent.com/21214285/49559623-57c19280-f94a-11e8-9a4d-e9effe6b46ea.png)

**Comment by Kvaya** [comment]
原型图：
![image](https://user-images.githubusercontent.com/39363297/49559800-f6e68a00-f94a-11e8-8452-05319714d2a0.png)

建议：把“返回首页”去掉
