### ISSUE TITLE
【Bug_PBL】项目设置视频为封面后，在我的项目页看不到对应的封面效果，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3100]
### Details:
**Env:**
Keepwork

**Steps:**
- 新创建一个项目，然后设置视频为其的封面，设置成功后查看视频是否可以正常播放
- 切换到创造页，查看我的项目，观察设置视频为封面的项目展示情况

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/c6010ab4-77d0-45f7-b8b0-85ab8513893a)

**Comment by Sandu1213** [comment]
@DDXY1230 可以先找产品确认好，是显示视频第一帧还是自定义的截图形式？

**Comment by azothli** [comment]
先维持当前的状态，后续观察
