### ISSUE TITLE
keepwork 英文版

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3107]

**Comment by shirleyluo1130** [comment]
![image](https://user-images.githubusercontent.com/40385277/48995363-7bcee800-f182-11e8-9e09-771dd7600eac.png)

**Comment by Sandu1213** [comment]
Need to optimize:
**翻译有误的地方：**
- 我参与的项目    
![image](https://user-images.githubusercontent.com/21214285/49195278-6267af00-f3c1-11e8-9407-83e12f726a1f.png)

- 官方公告  
![image](https://user-images.githubusercontent.com/21214285/49195520-6b0cb500-f3c2-11e8-8b80-6a68ea2431a1.png)

- 项目主页   
![image](https://user-images.githubusercontent.com/21214285/49196348-95ac3d00-f3c5-11e8-8fc4-479d08c4a280.png)
![image](https://user-images.githubusercontent.com/21214285/49196538-461a4100-f3c6-11e8-8341-d1207d917d36.png)

- 创建issue
![image](https://user-images.githubusercontent.com/21214285/49196798-5979dc00-f3c7-11e8-85fc-cc636122ea30.png)


**缺少翻译的地方：**
- 底部footer菜单栏
![image](https://user-images.githubusercontent.com/21214285/49196873-a6f64900-f3c7-11e8-95c9-9b34d38675a8.png)

- 搜索页->用户  
![image](https://user-images.githubusercontent.com/21214285/49195906-d440f800-f3c3-11e8-9880-9515a8ec7e37.png)

- 创建网站项目 
![image](https://user-images.githubusercontent.com/21214285/49196064-63e6a680-f3c4-11e8-8ae7-d1fb539d7ddc.png)

**Comment by Sandu1213** [comment]
**路由相关：**
- 项目页
 ![image](https://user-images.githubusercontent.com/21214285/49196972-048a9580-f3c8-11e8-80a3-5ef3dfe05cd3.png)

- 搜索页
![image](https://user-images.githubusercontent.com/21214285/49196985-15d3a200-f3c8-11e8-97ea-eccd70e3ac16.png)

**Comment by shirleyluo1130** [comment]
![image](https://user-images.githubusercontent.com/40385277/49206052-c7d09580-f3eb-11e8-8baa-67af782b4e4f.png)

**Comment by shirleyluo1130** [comment]
![image](https://user-images.githubusercontent.com/40385277/49207462-f2245200-f3ef-11e8-86fd-88e1d120ba84.png)

**Comment by shirleyluo1130** [comment]
补充 footer 翻译：

致社区 Letters To
致教育者 Educators
给父母的话  Parents
致开发者   Developers
对爱好编程的你说 Programming fans

用来做什么？What can you do?
创建自己的项目 Create personal projects
与老师一起完成项目  Complete projects with teachers
制作个人网站  Have your own portfolio site
拥有个人知识体系  Build up personal knowledge
学习在线课程  Learn online lessons

学习法 Learning Methodologies	
在项目中学习 Learning based on projects
在传授中学习 Learning from mentors
费曼学习法 Feynman Technique 
碎片化学习法 Fragmented learning 

Keepwork家族 Keepwork family
Keepwork 
IICC国际智能大赛 International Intelligence & Creativity Contest
Paracraft 
NPL语言 NPL Language
NPLCAD 
开放平台 Open platform
魔法哈奇  Haqi
魔法哈奇2  Haqi 2
Paracraft网络课程 Paracraft online lessons
Paracraft线下培训班 Paracraft offline training

支持 Support
联系我们 Contact us
加入我们 Join us 
网站统计 Website statistics 
更新信息 Update 
问题反馈 Feedback 


![image](https://user-images.githubusercontent.com/40385277/49282897-42bcad80-f4cb-11e8-9d48-a8b64c7cebe9.png)

**Comment by Sandu1213** [comment]
请将以上2个留言的问题也调整即可。
![image](https://user-images.githubusercontent.com/21214285/49355937-c2818c80-f704-11e8-871b-688977f6abb0.png)
