### ISSUE TITLE
【Bug-paracraft mod】需要优化paracraft mod里的下载、进入链接或者提供project mod功能

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3116]
### Details:

**Env:**
Keepwork

**Steps:**
    因目前课程创建人员需要提供world的直接访问功能，早期都是通过paracraft分享world成功后直接复制paracraft mod代码，但最新版本已经不提供paracraft网页功能，故课程人员无法取到achiveURL地址，则
手动填写paracraft mod时也不知道如何填写。故建议提供通过project id的方式访问，即填写project id则会自动转成对应的访问链接。
    请评估如何处理，并给出对应方案，谢谢。

**Attachment Files:**
![image](https://user-images.githubusercontent.com/21214285/49054306-c73ed000-f22e-11e8-8ea5-72eee4223ddd.png)

**Comment by LiXizhi** [comment]
支持下project id 或者新建一个mod, 多一些style

**Comment by leopoldchen** [comment]
建议设计新的project mod，可以包含project的基础信息，及两个操作，一个是打开项目，一个是查看项目。
打开项目延续现有功能，方便直接打开paracraft作品或者网站作品，与project中的打开项目功能类似。
查看项目则直接跳转到项目页面，方面做项目宣传。

这个mod应该只要设置project id即可，属性配置也简单。

**Comment by Kvaya** [comment]
调整方案：
![image](https://user-images.githubusercontent.com/39363297/49282574-777c3500-f4ca-11e8-9dfc-dc0543d6e40d.png)

说明：
1.项目ID除开可输入个人项目ID，还可以输入他人项目ID。
浏览项目数据需做个权限判断：
![image](https://user-images.githubusercontent.com/39363297/49282794-fa9d8b00-f4ca-11e8-9549-e8203c521b7f.png)
包括浏览编辑区和新窗口打开网页浏览时。

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/49843009-a793d400-fdf8-11e8-8649-0e64f8ae37c4.png)
![image](https://user-images.githubusercontent.com/21214285/49843236-6f40c580-fdf9-11e8-9354-596932f2a5a8.png)
