### ISSUE TITLE
私有网站用户权限设置

### ISSUE THREAD

**Issue by lsx18** [tatfook/keepwork#3118]
当这个网站是私有网站，默认不允许未登录用户浏览。对某账户设置了编辑权限，该账户用户可以对该网站进行编辑；对某账户设置浏览权限，该账户用户只能浏览，编辑后不能保存编辑的内容

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/49061244-37f3e580-f24b-11e8-828b-6ecab8e3ae5a.png)

**Comment by Kvaya** [comment]
现问题：何时显示“查看代码”和“编辑”？

逻辑是这样：
公有网站和私有网站旧逻辑，不管是公有网站还是私有网站，设置某些账户有编辑权限，即可编辑保存，显示“编辑”；设置有浏览权限，即可浏览编辑器中的代码，编辑一些内容后，不能保存该网站，显示“查看代码”。公有网站和私有网站的区别在于能不能浏览，因公有网站默认的是他人可以浏览；私有的网站默认的是拒绝，即不可浏览和编辑
