### ISSUE TITLE
editor布局调整：在editor中点击“仅显示代码”，需把左侧菜单栏显示

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3137]
问题详细：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/7cd04d18-0251-4e6f-a086-13453f3d0234)

建议做成这样：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/284f95f9-b33a-4db3-b4d8-2f3e36e8b4e7)

**Comment by Kvaya** [comment]
补充说明:
![image](https://user-images.githubusercontent.com/39363297/49625552-f7e1ef00-fa10-11e8-95ab-51d8098542c6.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/49781692-a8702b80-fd4e-11e8-92a6-913a4fd22af3.png)
-- @Kvaya  请对下图进行回复下，谢谢。
![image](https://user-images.githubusercontent.com/21214285/49781826-1ae10b80-fd4f-11e8-8dc2-7dbd1d21de02.png)
