### ISSUE TITLE
【Bug-editor】在指定的位置添加对应mod，添加位置与预期不符

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3143]
### Details:

**Env:** [Keepwork](https://www.keepwork.com)
**Ver:** V0.9.3

**Steps:**
- 进入编辑器里，新建一个网站，新增页面后，添加一段纯文字信息。然后将光标切换到文本的不同位置去添加不同的mod（如:mix_position/img_loop/text等）

- 观察添加情况

**Expected Result:**
  如在markdown的文本里添加，则直接添加到指定行位置;
  如果在mod的代码区里进行添加，则添加到该mod后面

**Actual Result:**
  在markdown区域里添加的，则添加到文本的最后了；
  在mod里添加的，则变成了最前面

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/51edc071-8005-42eb-97a6-e14d66621a8f)

**Comment by Sandu1213** [comment]
- 想要插入到指定的位置，必须在插入前先点击代码区上方的“模块”按钮
![image](https://user-images.githubusercontent.com/21214285/49577757-100b2d00-f983-11e8-9604-6e7e78fe21c8.png)

- 通过代码区的模块按钮打开mod列表，插入的mod都默认显示为隐藏了，需调整

**Comment by azothli** [comment]
了解了导致问题的原因，维持当前状态
后续调整

**Comment by Sandu1213** [comment]
release验证通过
