### ISSUE TITLE
【WorldShare】paracraft软件登陆页面上增加忘记密码功能

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3152]
调整详细：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/baf2b5bb-dc48-4aa1-9649-83a261294cd1)

说明：
1.在原有页面上把”还没有账号？点击注册“更换为”注册新账号“，点击”注册新账号“还是和现在注册逻辑一样
2.在页面上增加”忘记密码“，点击”忘记密码"跳转到keepwork.com页面并同时显示”重置密码'页面，“重置密码“跟现在keepwork.com官网上重置密码逻辑一样

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/49569229-55712f80-f96e-11e8-91e0-694f32dcce6a.png)

跳到keepwork的重置密码链接即可

**Comment by enya-i** [comment]
![image](https://user-images.githubusercontent.com/37529364/49572798-87d35a80-f977-11e8-8fe9-22e3af3d281e.png)

**Comment by Sandu1213** [comment]
已验证
