### ISSUE TITLE
gallery proptype card for imgLoop 

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#316]
Goal: gallery proptype card for img loop comp

Desc: Img loop component is lacking base gallery card. it's likes menu card

![image.png](https://images.zenhubusercontent.com/59df2959b0222d5de47b59a3/e06caf63-235c-4475-8cab-1336a8d30ed7)

![image.png](https://images.zenhubusercontent.com/59df2959b0222d5de47b59a3/f2e1b16d-5333-4927-9132-91d479d1326d)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/39284173-97b91252-4944-11e8-9ab7-bb0538cc1990.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/39511090-bb722560-4e1e-11e8-8459-b9bbe2c94832.png)

**Comment by Sandu1213** [comment]
stage环境验证通过
