### ISSUE TITLE
【Bug-Lesson】教学理念页面问题汇总

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3160]
### Details:

**Env:**  [release](https://release.keepwork.com)
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  点击“解决方案”，进入“教学理念”页面
-  分别对链接和内容进行查看

**Expected Result:**
  链接路径跳转正确；
  页面内容显示无误

**Actual Result:**
 页面链接指向错误;
 页面样式存在问题

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/abdbd7e7-7f46-4775-a791-e57c9efbb357)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/db88f849-3bf1-4812-8083-b66ad8049ac5)

**Comment by DDXY1230** [comment]
@shirleyluo1130 最下面那些段文字没有给链接，是需要链接还是不需要？？，原型图没链接

**Comment by shirleyluo1130** [comment]
Paracraft作者李西峙关于未来教育的思考     https://keepwork.com/lixizhi/note/design/future_education
以重要体验为基础的  http://blog.opensourcelearning.org/?p=122&lang=zh
了解开源学习  http://www.opensourcelearning.org/
美国自主教育联盟（ASDE)  https://www.self-directed.org/

**Comment by shirleyluo1130** [comment]
补充翻译：

Paracraft作者李西峙关于未来教育的思考

Xizhi Li, Paracraft author, put forward some ideas on future education.
![image](https://user-images.githubusercontent.com/40385277/49351506-c73b4600-f6ee-11e8-8af0-48865427165e.png)

**Comment by Sandu1213** [comment]
- 前面反馈的链接还是不对

- 首部出现多余的“a”
![image](https://user-images.githubusercontent.com/21214285/49359198-645aa680-f710-11e8-8751-02b67a3109f8.png)

- 请增加空格（间隔） 
![image](https://user-images.githubusercontent.com/21214285/49359257-9966f900-f710-11e8-90b7-50fb6ffd06fc.png)

-  少了25位助教（与中文版不一致，且25位助教请加粗处理）
![image](https://user-images.githubusercontent.com/21214285/49359286-b7ccf480-f710-11e8-865e-6c0c613bdacf.png)

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/49360792-24e28900-f715-11e8-88d4-e2b7c3a8cc55.png)

**Comment by Sandu1213** [comment]
还存在以下问题：
- 英文版缺少25位助教（如上补充）
- 英文版的学校教师访问更多链接不对
![image](https://user-images.githubusercontent.com/21214285/49365561-18186200-f722-11e8-8ec6-efddfc5c8ef5.png)
- 中文版的“CAD教学”和“为学校教师提供->了解更多”链接不对
- 中文版的“为学生家长提供->了解更多”链接不对（缺少了s，应该是parents）

**Comment by shirleyluo1130** [comment]
问题描述：点击“了解更多”打开的页面中，有多个字段的跳转链接无法访问，如下

![image](https://user-images.githubusercontent.com/40385277/49424751-7e5ebc80-f7d6-11e8-86ba-44201cdc51d8.png)

![image](https://user-images.githubusercontent.com/40385277/49424800-a0f0d580-f7d6-11e8-9f40-b70fd567a108.png)

**Comment by shirleyluo1130** [comment]
英文页面中，点击“View More” 打开的页面是空的。 
![image](https://user-images.githubusercontent.com/40385277/49424950-1a88c380-f7d7-11e8-8c0f-6d6b5ca468dd.png)

![image](https://user-images.githubusercontent.com/40385277/49425013-4e63e900-f7d7-11e8-9be2-ac491002e327.png)

**Comment by DDXY1230** [comment]
这个什么问题？？
