### ISSUE TITLE
【Bug-Lesson】学校教师页面问题汇总

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3164]
### Details:

**Env:**  [release](https://release.keepwork.com)
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  进入“学校教师”页面，对页面按钮和页面内容进行查看

**Expected Result:**
  页面内容显示正确且链接正确

**Actual Result:**
  页面内容显示有误且链接不对

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/afebeb16-45f5-4fc0-9f63-d55726d79209)
  ![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/0bbd5f6b-6743-40bd-9f87-fe2122cca74d)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/80392b70-0c5e-4dff-bb6f-a293194231a1)

**Comment by Sandu1213** [comment]
童靴，请严谨一点，谢谢~ 🍰 
---
 - 问题1：跳转还是不对;
 - 问题2：描述错误，见下图
![image](https://user-images.githubusercontent.com/21214285/49356245-193b9600-f706-11e8-9f1b-ff40d2cbcc0c.png)
- 问题3： 按钮点击问题
![image](https://user-images.githubusercontent.com/21214285/49356280-396b5500-f706-11e8-9a7c-b16e3b858c8b.png)

**Comment by shirleyluo1130** [comment]
英文版：
![image](https://user-images.githubusercontent.com/40385277/49358684-80f5df00-f70e-11e8-9971-aaa3bd3b48fb.png)

![image](https://user-images.githubusercontent.com/40385277/49358724-a551bb80-f70e-11e8-9427-9369796a06ef.png)
