### ISSUE TITLE
【Bug-Lesson】学生家长页问题汇总

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3165]
### Details:

**Env:**  [release](https://release.keepwork.com)
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  进入解决方案->学生家长页面，对页面内容和链接进行查看

**Expected Result:**
  页面信息显示正确

**Actual Result:**
  页面样式和链接存在问题

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/3d516d3a-f78b-475d-bfd5-30679962e4b1)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/5d6b88ad-920c-461a-9d03-e61baf481ce3)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/2f7f34af-1663-4684-a4dc-9a89df49ec16)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/9d62fdd9-dc7e-439d-840c-f2bf21bb5308)

**Comment by shirleyluo1130** [comment]
热门课程包需可点击，点击进入对应课程包详情页
![image](https://user-images.githubusercontent.com/40385277/49355211-84cf3480-f701-11e8-83fc-047efdf260a0.png)

**Comment by shirleyluo1130** [comment]
漏掉了小标题
![image](https://user-images.githubusercontent.com/40385277/49355291-e5f70800-f701-11e8-952b-8c54b1b4b26a.png)

**Comment by shirleyluo1130** [comment]
英文版问题：
![image](https://user-images.githubusercontent.com/40385277/49358162-b00b5100-f70c-11e8-9ad0-4ed6eee972af.png)

![image](https://user-images.githubusercontent.com/40385277/49358123-8e11ce80-f70c-11e8-8b52-67bf0f1bc631.png)

![image](https://user-images.githubusercontent.com/40385277/49358435-a3d3c380-f70d-11e8-8b16-f95e46adf35b.png)

![image](https://user-images.githubusercontent.com/40385277/49358520-eeedd680-f70d-11e8-8fee-a50b1dabbcc8.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/49417356-59f3e780-f7b8-11e8-9abd-5ca20e557745.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/49417433-a93a1800-f7b8-11e8-8f78-376ac26f4843.png)

**Comment by Sandu1213** [comment]
上面反馈的2个问题还存在

**Comment by shirleyluo1130** [comment]
![image](https://user-images.githubusercontent.com/40385277/49428063-fed5eb00-f7df-11e8-8453-17da6cdda39c.png)
