### ISSUE TITLE
【Bug-Lesson】作品和创意大赛问题汇总

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3167]
### Details:

**Env:**  [release](https://release.keepwork.com)
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  查看“作品和创意大赛问题”页面，验证链接是否都正常可用

**Expected Result:**
  页面链接跳转正确

**Actual Result:**
 页面链接不对

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/5701b121-3806-4902-add0-996465848011)

**Comment by Sandu1213** [comment]
请配置正确链接，可参考如下地址：
[https://keepwork.com/official/paracraft/contests](https://keepwork.com/official/paracraft/contests)

**Comment by shirleyluo1130** [comment]
下图所示的链接地址为：https://keepwork.com/pbl/project/569/

![image](https://user-images.githubusercontent.com/40385277/49369852-61ba7a00-f72d-11e8-90f7-b30a05961c49.png)
