### ISSUE TITLE
keepwork个人中心中修改头像，增加点击头像弹出媒体库，修改头像

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3209]
**问题详细：**
![image](https://user-images.githubusercontent.com/39363297/50416100-cadb6c00-0859-11e9-88ae-162eea49797d.png)
点击“点击修改头像”6个字可弹出媒体库，修改头像；但点击头像无任何反应

**调整为：**
点击“点击修改头像”6个字和![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/adbc4803-8cbc-4691-a475-8fbdf35ed7a3)头像，都可以弹出媒体库，修改头像

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/50416136-f52d2980-0859-11e9-9841-e835d3bd49a0.png)

**Comment by Sandu1213** [comment]
已上线。
