### ISSUE TITLE
页首导航/导航菜单中“菜单编辑器”调整

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3234]
**问题详细：**
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/c54822a0-31cc-4ed3-94b2-af41ca6a0f87)
1.删除之前的菜单mod（菜单已建8个），新增一个导航菜单mod，在“菜单编辑器”中添加菜单项，菜单项名的数字是之前菜单项名数字+1，重新新建一个菜单mod，新建的菜单项名数字应该是重新排序，从“1”开始

2.现子项跟菜单项现看起来区分不明显

**调整建议：**
1.现“菜单项n”(n表示数字几）调整成“菜单项”，不要数字；添加子项后显示“子项”。

2.
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/f347490c-3115-406f-90a9-e7fb46efc1a9)
调整成
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/4b2753e4-df7b-4468-9f38-504f1e874471)
说明：可以用现在的箭头做展开收起，但菜单项和子项用线连接，子项的背景框长度比菜单项的背景框长度短

**Comment by Kvaya** [comment]
![image](https://user-images.githubusercontent.com/39363297/50621943-6e0c3f80-0f44-11e9-90d2-b4dc72613e99.png)
这块不是要改里面一样的字，是建议参考子菜单跟菜单UI效果有所区分，子菜单项往里面缩进或往里面缩进，用线连接

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/50627688-a70dd980-0f6f-11e9-92cf-a9ea14f01db7.png)


无缩进的菜单编辑器优化为有缩进的菜单编辑器

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/50751458-c9139e80-1284-11e9-86b4-64d2b8634742.png)

@Kvaya  问题1是需要调整成如图描述的效果么？

**Comment by Kvaya** [comment]
按上面图显示可以，这样新增的项不会因为数字造成什么困扰
