### ISSUE TITLE
项目白板中时间后面加“更新”二字

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3247]
调整详细：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/f8513bdf-68a4-433f-9155-c6b54aa15ee3)

说明：项目白板，时间后面加“更新”二字

**Comment by DDXY1230** [comment]
@Kvaya

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/49781370-65618880-fd4d-11e8-84b7-609be68bca09.png)

**Comment by Sandu1213** [comment]
上图意思是： 这里的白板展示，缺少“更新”二字，请补充，谢谢
