### ISSUE TITLE
keepwork官网上的项目主页中“取消收藏”“取消点赞”改为“已收藏”“已点赞”

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3252]
调整详细：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/22fd5c11-1d75-42a2-a0d6-bb5d097b9a2f)

**Comment by enya-i** [comment]
![image](https://user-images.githubusercontent.com/37529364/49784304-cdb56780-fd57-11e8-9894-cadff3eb1f05.png)
![image](https://user-images.githubusercontent.com/37529364/49784311-d312b200-fd57-11e8-87b8-556efe8987e6.png)
