### ISSUE TITLE
探索App

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#3279]
@LiXizhi commented on [Thu Dec 06 2018](https://github.com/tatfook/WorldShare/issues/102)

我们本月要在WorldShare中做一个叫做`探索`的App
https://keepwork.com/lixizhi/note/design/paracraftmobile  

代替之前的
![image](https://user-images.githubusercontent.com/94537/49577511-84919c00-f982-11e8-9123-5bd1111707bb.png)

里面的内容和KeepWork网页版的探索很接近。 但是要适合手机和PC显示。 不用显示预览图了。 

重点是数据源和keepwork用同一个数据源和API。 但是通过Tag来过滤不适合Paracraft展示的project.

**Comment by Kvaya** [comment]
Issue moved to [tatfook/paracraft #59](https://github.com/tatfook/paracraft/issues/59) via [**ZenHub**](https://www.zenhub.com/)
