### ISSUE TITLE
KeepWork ReleaseV 0.1.0

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#330]
此版本是新版KeepWork的第一次Release，包含editor和常规的page显示

@Xuntian @DreamAndDead                                               

根据现在的部署方式，除了api和部分wiki逻辑，还有以下几个网站需要跳转到旧版本wikicraft服务器上：
 /official   /lesson /pac   /paracraft  /keepwork  /intro /lecture /kecheng  /tatfook  

版本部署之后，旧的页面会逐步更改使用新的MOD逻辑，当网站完成改版后，运维需要将对应的网站转到新版本KeepWork服务器。

**Comment by Xuntian** [comment]
把旧的wikicraft的editor映射到其他的url上
