### ISSUE TITLE
我的账户-去兑换

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3304]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/c0a453a9-95af-4214-9bfd-52597661f27f)

**Comment by Sandu1213** [comment]
缺少兑换商品，暂时无法验证

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/50431117-4fce9000-0903-11e9-816e-d1c96c08c624.png)
