### ISSUE TITLE
优惠券：包括 可使用、已使用、已过期 

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3307]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/85805ac1-be58-4018-a58b-c671d30f554e)

**Comment by shirleyluo1130** [comment]
无优惠券的UI见：

![image](https://user-images.githubusercontent.com/40385277/50621160-0ef7fc00-0f3f-11e9-947d-f26ce9c63835.png)



![image](https://user-images.githubusercontent.com/40385277/50621136-ee2fa680-0f3e-11e9-8cf8-4e3e7133f493.png)

**Comment by Sandu1213** [comment]
1.优惠券发放时缺少感知：
![image](https://user-images.githubusercontent.com/21214285/50752384-0bd77580-1289-11e9-9e65-c8bb31de9fd3.png)

2.

**Comment by shirleyluo1130** [comment]
“已过期（Expired）”、“已使用 （Used）”的英文版印章，见：
![image](https://user-images.githubusercontent.com/40385277/50758029-f586e500-129b-11e9-9d4c-25d2397df8aa.png)

“即将过期”标签，中英文版本，见：
![image](https://user-images.githubusercontent.com/40385277/50758240-9bd2ea80-129c-11e9-8d80-fcc8a5f7804f.png)
