### ISSUE TITLE
【Bug-profile】用户profile页信息展示不对，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3343]
### Details:

**Env:**  [keepwork](https://keepwork.com)
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录(账号为已存在站点但未创建项目的用户)

**Steps:**
-  登录成功后，打开个人profile页面,观察页面信息显示是否正确

**Expected Result:**
  页面信息显示合理

**Actual Result:**
  页面信息显示不合理

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/9ded3d68-5b30-43a3-8bf5-40bba826e963)

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/49921430-7266af00-fee8-11e8-89d2-921d9b7dbaeb.png)
