### ISSUE TITLE
【Bug-editor】通过命令行输入的mod，默认状态应该与属性里开关一致，目前不一致，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3350]
### Details:

**Env:**  [release](https://release.keepwork.com)
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  进入编辑器的代码区里，手动输入mod的命令，然后观察mod显示情况

**Expected Result:**
  mod显示正确，状态与属性里的开关状态一致

**Actual Result:**
 mod显示与属性开关设置不一致

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/40e3a1f0-b9b1-4773-bed7-e19c13d96b9c)

**Comment by kevinxft** [comment]
😀明明很一致
