### ISSUE TITLE
【Bug-editor】手动输入mod命令后，再通过预览区进行添加其他mod，mod的代码信息会存在一定误差

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3356]
### Details:

**Env:**  [release](https://release.keepwork.com)
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  进入编辑器的代码区，手动输入“imgloop” mod，然后再通过预览区的添加按钮进行添加，添加img mod
- 再单独添加img mod，对比代码差异

**Expected Result:**
  同一个mod，mod的代码格式一致

**Actual Result:**
  同一个mod，代码却不同

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/71a71e34-bc72-4f94-ba01-11a102d3b28f)

**Comment by onedou** [comment]
这个属正常现象
