### ISSUE TITLE
【Bug-用户头像】用户修改头像后，进入到编辑器里，发现头像没有变化（新页面也没有），必须登出后重新登录才生效

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#336]
## The problem
用户修改头像后，进入到编辑器里，发现头像没有变化（新页面也没有），必须登出后重新登录才生效

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.先进入editor页面，观察用户头像
2.返回首页，进入个人设置中心，修改个人头像，然后再进入editor页面，观察用户头像
3.打开新页面，观察用户头像情况
* Expected Result:
1.用户头像与设置的一致
* Actual Result:
1.修改的用户头像没有生效
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/80c1ccdd-2244-44e7-8831-fb8b1efd6fb0)

**Comment by ZhangKaitlyn** [comment]
出现原因： 编辑器页面有缓存profile的信息，而头像设置是旧项目里的，和编辑器页面的缓存不能共用。
等之后用户信息设置重构后，这个问题应该就不会存在了
