### ISSUE TITLE
【学习板块2期】学习中心（教师身份）（自主学习用户）- 课程管理-课程包

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3381]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/7da7fa44-4c06-49d3-b804-06db6d159fdc)

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/50435251-6ed91c00-091b-11e9-82ed-5a92577429cd.png)
