### ISSUE TITLE
【Bug-撤销功能】撤销功能在特定情况下，撤销有误，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#339]
## The problem
撤销功能在特定情况下，撤销有误，请调整

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor页面后，打开已有的网页，在空白行首添加 标题等，然后进行撤销操作，观察撤销结果

* Expected Result:
1,标题撤销完成，其他内容无影响
* Actual Result:
1.撤销过多，将正文内容也撤销了
 

## Attachments (eg:logs/video/screenshot)
![undo](https://user-images.githubusercontent.com/21214285/39289780-147c6350-4960-11e8-807a-6884400173a3.gif)

**Comment by Sandu1213** [comment]
补充一种情况：
1.修改页面后，多次撤销操作，会出现撤销成空白页面的情况，请一同调整~

**Comment by leopoldchen** [comment]
同时修改了ctrl+z和ctrl+y的undo redo逻辑 @Sandu1213

**Comment by Sandu1213** [comment]
stage环境还是存在问题，请调整。
问题是：
1.撤销最多是返回到编辑前的状态而不是清空全文
2.完全撤销后，左侧需要显示为文件树页面

**Comment by Sandu1213** [comment]
stage环境验证通过
显示文件树的问题由issue #476    跟进
