### ISSUE TITLE
【学习板块2期】解决方案 - 学校教师

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3394]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/3869ce6e-a534-4d25-8dc4-b3ff8b348f90)

**Comment by ZhangKaitlyn** [comment]
测试地址： 
-  [中文版](https://keepwork.com/official/paracraft/learn/educators-test)
-  [英文版](https://keepwork.com/official/paracraft/learn/educators-test_EN)
