### ISSUE TITLE
哈奇修改密码和忘记密码跳转页面形式更改

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3398]
哈奇修改密码和忘记密码跳转页面形式更改

跳转到新的keepwork官网，形式像现在的登录注册页面形式

**Comment by Sandu1213** [comment]
目前都已调整，待最新版本再验证
![image](https://user-images.githubusercontent.com/21214285/50075087-e53d9600-0218-11e9-8627-28753305d049.png)

**Comment by Sandu1213** [comment]
已在哈奇v0.7.426验证，验证通过
![image](https://user-images.githubusercontent.com/21214285/50128009-698e2880-02ae-11e9-8d26-6079be3a0bf7.png)
