### ISSUE TITLE
【Bug-editor】多媒体里上传视频或者较大图片时，如果上传错误，无法进行撤销操作，请提供

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3401]
### Details:

**Env:**  [release](https://release.keepwork.com)
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  登录成功后，点击右上方的工具->网站编辑器
-  选中任一一个站点文件，然后添加宽屏mod，然后更换图片
-  当出现媒体库后，上传较大视频或者较大图片，上传过程中发现上传错误，需要进行撤销操作

**Expected Result:**
   可以正常撤销，不用一直等待后再重新上传

**Actual Result:**
  必须等文件上传完

**Attachment Files:**
![image](https://user-images.githubusercontent.com/21214285/50063792-e2c34800-01e8-11e9-9cf1-423c08119e94.png)

**Comment by Sandu1213** [comment]
@azothli  @Kvaya  请评估一些这个调整是否需要加上

**Comment by Kvaya** [comment]
当上传错误图片或视频时，右下角添加一个“删除”按钮，点“删除”撤销上传操作

**Comment by azothli** [comment]
“取消”

**Comment by Kvaya** [comment]
当上传错误图片或视频时，右下角添加一个“取消”按钮，点“取消”撤销上传操作

**Comment by Sandu1213** [comment]
stage环境已验证通过
