### ISSUE TITLE
【Bug-创建项目】创建网站项目，选择已存在的网站时，需要该网站下必须存在文件，否则不用在可选列表里展示

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3402]
### Details:

**Env:**  [release](https://release.keepwork.com)
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  用户登录成功后，从工具-网站编辑器，进入编辑器里
-  通过新建网站按钮进行新建，新建站点A，然后再将站点A下的index文件删除
-  再返回到创建项目页面，选择网站项目进行创建，创建时选择已存在的站点，然后选择网站A
-  创建项目网站成功后，分别进行访问和编辑操作

**Expected Result:**
   选择站点时，找不到站点A，可选择站点必须是含有文件的站点

**Actual Result:**
   访问时，自动补齐了index，但实际没有index页；
   编辑时，站点实际没文件，会一直处于加载状态，容易误导用户

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/414bf89e-15da-4371-bf27-18993755ec80)

**Comment by Sandu1213** [comment]
该问题优先级低，可找产品评估好后再做调整。

**Comment by Kvaya** [comment]
建议方案：
1.进入“网站”类型的项目，访问网站，假设该网站下没有网页，访问网站的选择范围不包括没有网页的网站，即：
![image](https://user-images.githubusercontent.com/39363297/53325465-59ce3880-391e-11e9-9ba7-15c0bbd1efa8.png)

2.进入“网站”类型的项目，访问网站，假设该网站下没有index页，默认显示该网站的第一页；

**Comment by Sandu1213** [comment]
该问题出现的概率很低，暂不考虑。后续如果有用户反馈再考虑处理。
