### ISSUE TITLE
【Bug-search】搜索页面的精准度需要提高

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3406]
### Details:

**Env:**  [release](https://release.keepwork.com)
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  用户通过搜索栏进入搜索页面，进入页面后，选择用户进行搜索
-  在搜索框里输入搜索内容，如：“test1”
- 观察搜索结果

**Expected Result:**
  匹配度最高的，显示在最前面

**Actual Result:**
   匹配度高的不在最前，匹配规则可能有误（需要翻页才能找到用户）
   _ps:_其他搜索项同理

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/cff72675-918c-44d7-873e-2388b5dc9168)

**Comment by William0911** [comment]
接口返回的排序是对的，但是UI中设计的只有按照名气和时间排序，故前端没有按匹配度排序调用接口。

**Comment by Sandu1213** [comment]
因暂时无按匹配度作为首选排序的方式，故该问题待产品定义清楚后再跟进

**Comment by azothli** [comment]
按照接口的返回直接显示，默认不做排序处理
