### ISSUE TITLE
【bug-学习板块】学习中心-教师的课程详情页，如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3408]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/dbdfe938-2fcc-415c-b7fd-fec73e147cca)

**Comment by Sandu1213** [comment]
release已验证
![image](https://user-images.githubusercontent.com/21214285/50136682-81c46e80-02d3-11e9-95ae-ac630139795c.png)
