### ISSUE TITLE
WorldShare加入项目ID

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#3413]
@LiXizhi commented on [Tue Dec 18 2018](https://github.com/tatfook/WorldShare/issues/103)

![image](https://user-images.githubusercontent.com/94537/50134805-d31d2f80-02cc-11e9-8f96-febb6f9ec530.png)

无论离线， 还是在线，还是ZIP文件，  加入项目ID，点击后， 打开KeepWork PBL页面。 

项目ID可以记录在tag.xml中， using SetWorldTag, 项目分享时记录下来
```
function WorldCommon.SetWorldTag(field_name, value)
function WorldCommon.GetWorldTag(field_name)
```

---

@LiXizhi commented on [Tue Dec 18 2018](https://github.com/tatfook/WorldShare/issues/103#issuecomment-448106625)

![image](https://user-images.githubusercontent.com/94537/50134926-47f06980-02cd-11e9-9287-673cdd824212.png)
类似上图： 可以不要项目ID几个字， 只是数字， 鼠标放上去，显示：“项目ID：XXX， 点击打开项目页”

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/50419427-be600f00-086b-11e9-83ff-81a9687e6772.png)
