### ISSUE TITLE
【Bug-editor】编辑器里添加lesson mod，修改lesson mod内容后，预览区里没有同步变更，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3437]
### Details:

**Env:**  [release](https://release.keepwork.com)
**Version:** v0.9.6
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  进入学习页面，然后进入教师页->课程管理，然后选择课程进行新建操作
-  点击新建课程名称，跳转进入编辑器页面，对课程内容进行编辑
-  在页面里添加lesson mod，修改内容后，观察预览区的显示情况

**Expected Result:**
  预览区内容显示正确，与实际设置的一致

**Actual Result:**
  预览区内容为空

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/b35c88f2-ca89-4a68-aae2-50d5890f7a22)

**Comment by shirleyluo1130** [comment]
补充：lesson mod中设置完图片信息后，预览区里的图片显示如下。请按照原图显示，不要显示部分或显示多张。

情况 1

原图为：
![image](https://user-images.githubusercontent.com/40385277/50272768-bd963a00-0473-11e9-9c53-756304e5500a.png)

预览区显示为：
![image](https://user-images.githubusercontent.com/40385277/50272805-df8fbc80-0473-11e9-8fc9-46e69ebb77fd.png)

情况2

原图为：
![image](https://user-images.githubusercontent.com/40385277/50272979-4f9e4280-0474-11e9-9367-b763b7cfccfc.png)

预览区显示为：
![image](https://user-images.githubusercontent.com/40385277/50272922-31384700-0474-11e9-930b-9287b360cea0.png)

**Comment by Sandu1213** [comment]
图片封面自动填充的功能还是需要完善
![image](https://user-images.githubusercontent.com/21214285/50751216-cbc1c400-1283-11e9-8a2b-3e79ba5419fc.png)
