### ISSUE TITLE
【Bug-editor】editor里mouse over的提示框风格，请统一

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3453]
### Details:

**Env:**  [keepwork](https://keepwork.com)
**Version:** v0.9.7
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  用户通过工具-网站编辑器，进入编辑器页面，然后通过鼠标分别对代码区上方的菜单栏、左侧文件树相关的按钮及mod列表等进行mouse over操作，观察显示情况

**Expected Result:**
  提示信息显示正确，风格统一

**Actual Result:**
  提示信息显示正确，但风格不统一

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/51ad7a9b-5b59-4494-b4f0-1e7c8f4b4d30)

**Comment by Kvaya** [comment]
需统一成黑色背景的mouse over ，而不是
![image](https://user-images.githubusercontent.com/39363297/50333348-1206eb80-0540-11e9-9531-3dbd112da070.png)这样UI效果的mouse over。
现阶段需调整的：
![image](https://user-images.githubusercontent.com/39363297/50333435-52666980-0540-11e9-85a9-0a92427209f3.png)
备注说明：鼠标滑至头菜单的时候，显示应该是头菜单的文字内容，而不是其他的。比如，鼠标滑至“常用”上，显示的应是“常用”，而不是“绘图板”

**Comment by Kvaya** [comment]
![image](https://user-images.githubusercontent.com/39363297/50339117-8433fc00-0551-11e9-93e2-68f5a5923a71.png)
现是把“禅模式”、网盘操作三个改成element tooltip 文字提示效果；mod 面板处现有的mouse over的效果保留 后期再优化

**Comment by lsx18** [comment]
#3509
