### ISSUE TITLE
keepwork探索页面一级菜单新增“网页”菜单

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3460]
详细：
![image](https://user-images.githubusercontent.com/39363297/51225256-ab30f280-1984-11e9-9d05-c063a589595f.png)

关键词为空的时候，“网页”菜单下，显示是为空，如图显示：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/ef963381-c5ed-4f6b-8d7d-3d8c4be90e5e)

**Comment by William0911** [comment]
接口还没写，稍等

**Comment by Kvaya** [comment]
补充：
1.搜索结果，一页显示12条搜索结果；
2.一条搜索结果中的正文显示，最多不超过80个字。
备注：假设一段正文含有关键词，但没有80个字，显示它真实的字数就好。

**Comment by Kvaya** [comment]
建议网页URL把前缀也显示，把“https://keepwork.com/...”也带上，这样有时候来不及看网页，可以复制URL进行收藏后续再看

**Comment by Kvaya** [comment]
网页UI效果显示参考谷歌搜索，https://www.google.com/search?q=%E6%89%8B%E6%9C%BA&oq=%E6%89%8B%E6%9C%BA&aqs=chrome..69i57j69i61j69i60j69i61j0l2.1328j0j8&sourceid=chrome&ie=UTF-8

如：![image](https://user-images.githubusercontent.com/39363297/51369738-a8263580-1b2f-11e9-9a5c-28062506a9c2.png)

但每个搜索结果条条之间有间距，间距参考项目类别页中的一行项目与它下一行项目之间的间距。

**Comment by Sandu1213** [comment]
请跟进上面的需求再调整：
- 排序问题 (每页12条)
- 筛选维度问题(只有“综合”和“最新”)
- 显示问题(颜色区分/链接显示全地址/正文长度限制80字)

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/51377083-f09c1e00-1b44-11e9-9852-7d993265d34e.png)

**Comment by DDXY1230** [comment]
已讨论暂时不限80字，因为是截取搜索词前后的句子，不会大篇幅的

**Comment by DDXY1230** [comment]
排序暂时不做热门，产品那边确定了，样式进行了些许美化
