### ISSUE TITLE
【Bug-我的账户】我的账户问题汇总，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3469]
### Details:

**Env:**  [stage](https://stage.keepwork.com)
**Version:** v0.9.7
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  进入我的账户里进行冒烟测试
-  查看我的账户明细，进行充值操作，观察充值结果
-  查看交易明细，观察记录是否准确
-  查看优惠券相关

**Expected Result:**
  页面信息记录正确，充值完成后能够正常跳转

**Actual Result:**
  页面信息缺失记录，存在错别字

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/5e708ee2-11b4-4407-ad4e-54da5317f77e)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/50410823-6529b880-0836-11e9-9aa9-31e480f3d0b3.png)

**Comment by kevinxft** [comment]
似乎原型中并没有说明充值完成后需要跳转

**Comment by Sandu1213** [comment]
@shirleyluo1130  请补充一下，旧版本都是有跳转的。即完成充值操作后，引导用户进行之后的操作

**Comment by shirleyluo1130** [comment]
好的，会补充一个充值成功的页面，UI在设计了。
