### ISSUE TITLE
【Bug-editor】新建页面及新建网站的模板描述语言需要与系统语言一致

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3503]
### Details:

**Env:**  [release](https://release.keepwork.com)
**Version:** v0.9.7
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  设置语言为中文，进入页面编辑器，进行新建网站及新建页面的操作，观察新建结果
-  设置语言为英文，进入页面编辑器，进行新建网站及新建页面的操作，观察新建结果

**Expected Result:**
  页面显示语言与系统语言匹配， 新建成功

**Actual Result:**
  页面显示语言与系统语言不匹配

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/69d8c215-c8eb-435a-8540-dcd90fd5cdf2)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/7f51935d-f320-4b10-a81d-a55b9cb54b16)

**Comment by Kvaya** [comment]
网站模板、网页模板对应中文情况：
![image](https://user-images.githubusercontent.com/39363297/50500962-9ea93080-0a8f-11e9-8dec-6b81228de877.png)

补充：
已建好网页，网页设置里面的的英文也需要跟网站布局里面一一对应。
如：
![image](https://user-images.githubusercontent.com/39363297/50501083-6f46f380-0a90-11e9-8846-8817ecdf47d5.png)
其他的同理
