### ISSUE TITLE
【bug-学习板块】如下：“寻找导师”页面，菜单“学习中心”应为选中状态

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3519]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/e43ccecf-5b2d-42b1-95e7-94b7af2f219b)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/53456350-09afbd00-3a69-11e9-9d4b-2c58daf4f14c.png)
keepwork显示如图

**Comment by duting1993** [comment]
stage
