### ISSUE TITLE
【bug-学习板块】课堂总结页面，如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3520]
问题描述：
点击“全部更改”弹出如下提示框
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/35b3e727-b741-4170-a31d-64da67370e5a)

修改建议：
点击“全部更改”，自动选中全部学生，并弹出提示框。如下所示：
![image](https://user-images.githubusercontent.com/40385277/50534393-e5be2100-0b76-11e9-9b5b-e67f07328dce.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/50582568-7b6eee80-0e9e-11e9-8ea7-6ec0eaf0fdde.png)

**Comment by DDXY1230** [comment]
上的本身没有题目的课程，改不了满分

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/50621873-e7576280-0f43-11e9-8ede-55594c7dd788.png)

复现验证地址：[地址](https://release.keepwork.com/l/teacher/package/35/lesson/18/summary/344/18)
账号：dukes/xxxxxx
