### ISSUE TITLE
【Bug-editor】轮播mod设置自动播放后再取消自动播放，新页面打开后还是会自动播放(概率出现)

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3536]
### Details:

**Env:**  [keepwork](https://keepwork.com)
**Version:** v1.0.0
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  进入编辑器页面，创建一个新页面，然后在新页面添加轮播mod，设置视频为其封面，并启用自动播放功能
- 保存成功后，在新页面打开进行查看，观察视频是否正常自动播放
- 再次进入编辑器页面，编辑同一个文件，将视频设置为不自动播放，然后再次保存
- 进入新页面，观察视频是否会自动播放

**Expected Result:**
 设置自动播放时，则自动播放；设置非自动播放时，则不自动播放

**Actual Result:**
  设置为非自动播放时，还会概率性出现播放的情况

**Attachment Files:**

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/50671995-6914c200-1010-11e9-8cd9-d7fe6aa300c0.png)
