### ISSUE TITLE
【学习板块-优化】学习中心（教师）- 课程管理 - 课程 : 增加提示文字

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3544]
1、mouse over 在 >  上时，显示提示：
中文：   查看课程所属课程包
英文：  View packages the lesson was added into.

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/fcda42e7-b962-41b4-a53d-9abb97fd5ad4)

2、收起图标，mouse over 显示提示：
中文：     收起课程包信息
英文：     Fold the package information.

![image](https://user-images.githubusercontent.com/40385277/50537502-5ecf6f80-0b9b-11e9-99f1-111af69a22b3.png)

**Comment by leopoldchen** [comment]
预计技术实现比较麻烦，先降低优先级
