### ISSUE TITLE
【research】 Git delay service尝试对接Gitaly

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#3555]
### 背景

[Gitaly](https://gitlab.com/gitlab-org/gitaly)是gitlab对于git服务封装的新方案，具体请查看[gitaly架构](https://docs.gitlab.com/ce/development/architecture.html#system-layout)
直接使用gitaly服务可以绕开gitlab rails层的api封装，估计可以一定程度提高git服务访问效率。

### 思路

因此，建议做一下研究：

1. grpc api功能查看，确认是否可以满足当前delay service的应用需求
2. grpc api封装，确认独立部署的gitaly服务是否能够提供正常服务

完成以上research，可以考虑直接投入应用。

**Comment by William0911** [comment]
[gRPC protocol definitions for gitaly](https://gitlab.com/gitlab-org/gitaly-proto)

**Comment by William0911** [comment]
写文件/提交commit功能尝试过。基本可以运作，但要替换gitlab仍有不少功能需要自己实现。
