### ISSUE TITLE
【Bug-个人头像】旧用户的个人头像无法正常展示，请处理

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3579]
### Details:

**Env:**  [keepwork](https://keepwork.com)
**Version:** v1.0.0
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录（旧用户，默认头像）

**Steps:**
-  旧用户登录成功后，观察个人头像显示情况
-  通过设置中心->进入用户资料页，观察用户头像显示情况

**Expected Result:**
   个人头像显示正确

**Actual Result:**
   个人头像显示不全

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/28057cf0-f0bb-4909-baa1-1278d5965a00)

**Comment by wxaxiaoyao** [comment]
/wiki/xxx头像数据置空处理
