### ISSUE TITLE
【Bug-coupons】优惠券显示需要支持英文版

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3581]
### Details:

**Env:**  [release](https://release.keepwork.com)
**Version:** v1.0.0
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  用户进入我的账户，进行多次充值操作，以获取不同类型的优惠券
-  然后切换进入优惠券tab页，查看优惠券的展示情况
-  在底部切换语言，设置为英语，然后再次查看优惠券的展示情况

**Expected Result:**
  优惠券的信息展示合理，与设置的语言一致

**Actual Result:**
  优惠券缺少英语版

**Attachment Files:**
![image](https://user-images.githubusercontent.com/21214285/50754974-76d97a00-1292-11e9-9822-302e8a4d4b08.png)

![image](https://user-images.githubusercontent.com/21214285/50754941-632e1380-1292-11e9-9aba-7ada5a7d58c4.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/50807242-814c5000-1334-11e9-9d2a-bc804e20a934.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/50880473-70c1d580-1419-11e9-829d-1604e5397d03.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/50882225-090e8900-141f-11e9-879a-c73f1ba7f2ca.png)

**Comment by shirleyluo1130** [comment]
（英文状态下）购买商品时，显示的优惠券信息如下所示：
![image](https://user-images.githubusercontent.com/40385277/50884830-f9933e00-1426-11e9-94c4-c2da7a3c2559.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/50948887-273bbe00-14df-11e9-8788-24abf5e88cae.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/50949123-f14b0980-14df-11e9-8e79-8bd03987972a.png)
