### ISSUE TITLE
【Bug-vedio】视频在手机上，无法点击中间的播放按钮进行播放，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3585]
### Details:

**Env:**  [keepwork](https://keepwork.com)
**Version:** v1.0.0
**Devices:**  chrome  browser (Iphone SE)
**Pre-condtion:**
  手机网络正常

**Steps:**
-  用手机分别访问[链接1](https://keepwork.com/l/student/solution/teacher)和[链接2](https://keepwork.com/idreamtech/zhdq/zhsq)，然后点击中间的播放按钮，对视频进行播放，观察是否正常播放

**Expected Result:**
  视频正常播放了

**Actual Result:**
  视频无法进行播放

**Attachment Files:**

**Comment by onedou** [comment]
video那个插件在手机上用不到
要不要用用浏览器自带的
如果在手机上
或者直接让产品设计另外一种形式

**Comment by Sandu1213** [comment]
手机上还是无法点击“中间的播放键”进行播放

**Comment by Sandu1213** [comment]
stage验证通过
