### ISSUE TITLE
【Bug-我的账户】商品信息和优惠券信息的描述需要调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3594]
### Details:

**Env:**  [release](https://release.keepwork.com)
**Version:** v1.0.0
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  分别进入商品兑换页面及优惠券页面，观察页面显示
-  再从“学习中心”->寻找导师，购买导师服务，观察导师服务在英文情况下的显示情况

**Expected Result:**
  页面信息显示合理

**Actual Result:**
  页面信息显示需要完善

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/a27313b6-5211-4ebf-96fc-4af7aed46a0f)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/1084193a-d210-40d9-a7f0-37cd310bebd4)

**Comment by kevinxft** [comment]
导师服务跟兑换商品需要等后端做好后台，暂时不做处理
