### ISSUE TITLE
【Bug-搜索】首页查看更多，进入搜索页面，搜索页需要高亮显示

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3602]
### Details:

**Env:**  [release](https://release.keepwork.com)
**Version:** v1.0.0
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

**Steps:**
-  用户在首页进行查看，分别对“精选项目”、“热门课程”、“大家都觉得很赞”查看更多，观察页面切换和显示情况

**Expected Result:**
   页面切换到搜索页，搜索页高亮显示

**Actual Result:**
 搜索页缺少高亮显示

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/153f9f04-9f12-4c74-9cbe-d95982f98625)

**Comment by DDXY1230** [comment]
release环境
