### ISSUE TITLE
【Payment - bug】coupons页面，UI样式调整，如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3604]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/bd177bc8-26ad-4055-ac02-0dc6d7a820f9)

**Comment by dalin00** [comment]
![image](https://user-images.githubusercontent.com/24222876/50883071-e29e1d00-1421-11e9-9a2c-094dbbf8ce38.png)
