### ISSUE TITLE
【Dashboard】激活码管理，增加如下功能

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3609]
### **背景**
运营人员需查询激活码的激活时间、激活账号等信息，并可备注某个激活码给了谁。
目前的激活码管理页面（如下图），无法满足以上需求。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/e1e7c2f3-d37c-4008-ba27-fc36f6335935)

### **解决方案** 

激活码管理，需增加如下功能：

1、列表中补充显示 激活时间“、”激活用户名“、”学校/机构“、”备注“4项信息。其中，备注功能，是为了方便运营人员备注激活码给了谁。

2、增加筛选功能，按激活码、激活用户名、状态进行筛选。

原型图如下：

![image](https://user-images.githubusercontent.com/40385277/50948200-9bc12d80-14dc-11e9-9bda-ed61ddfa6089.png)

**Comment by leopoldchen** [comment]
@wxaxiaoyao 

确认一下是否存在这些字段

**Comment by Sandu1213** [comment]
**查询相关的问题：**
![image](https://user-images.githubusercontent.com/21214285/51599648-1e190b00-1f3b-11e9-9a34-b56172cd3d7d.png)
![image](https://user-images.githubusercontent.com/21214285/51599674-2ec98100-1f3b-11e9-9b1e-9aee826aeec3.png)

**展示相关的问题：**
缺少“学校机构信息的统计”
![image](https://user-images.githubusercontent.com/21214285/51599806-78b26700-1f3b-11e9-8852-8da0eebd8828.png)

**Comment by shirleyluo1130** [comment]
1、无法筛选“用户名” 
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/6607e481-c392-4f6d-8c99-1b9362da27d7)


2、点击表头名称后的升降序按钮，显示如下：
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/e08cf289-9b78-4d68-9d0a-772ae015570b)

**Comment by shirleyluo1130** [comment]
另提issue跟进。
