### ISSUE TITLE
【bug-payment】支付成功，提示文字样式调整。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3626]
赠送知识豆优惠券、知识币优惠券，都存在如下问题。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/99a2ddb5-5186-44d1-a954-d744cd191894)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/53384102-b845f600-39b4-11e9-84e1-8a61c8fc9a89.png)
