### ISSUE TITLE
【bug】搜索-项目-输入项目id号，点击该项目，显示如图二

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#3629]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/f5f925e5-d8a2-4c96-9927-356bfb34dc56)
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/b32eb3bc-cc73-42e2-9bee-0e51c2850f64)
操作步骤：浏览器中输入keepwork.com
第一步：点击探索
第二步：在输入框里，输入项目id号
第三步：点击该项目
显示结果：如图二

**Comment by azothli** [comment]
通过id搜索出来的结果，第一个结果的url有误。
