### ISSUE TITLE
TOC MOD

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#363]
### 背景

官网首页使用了toc，目前可以继续保留这个功能。
TOC适用于单个md页面，比如在Main Content区域使用。不会跨layout区域。

注:
toc的样式预览有些特殊，建议使用图片

**Comment by Sandu1213** [comment]
Toc mod没有找到，请确认下。

**Comment by onedou** [comment]
http://stage.keepwork.com/testv2/yyyuuuiii/bbbbbb

**Comment by onedou** [comment]
测试代码看bearychat

**Comment by Sandu1213** [comment]
请先解决这个问题，输入空格后，光标自动切换到最前端了
![spaces](https://user-images.githubusercontent.com/21214285/40338616-ab93984c-5da8-11e8-85d2-15fbb37dac1c.gif)

**Comment by Sandu1213** [comment]
待 #250 解决后再验证

**Comment by Sandu1213** [comment]
还有2个问题需要处理：
1随意选择一段，将光标移动过去，.切换的时候太卡
2.左侧的文件显示不合理
![image](https://user-images.githubusercontent.com/21214285/40605084-ba2a9b18-6293-11e8-98cc-3ff0fc05e4d1.png)

**Comment by Sandu1213** [comment]
stage环境验证通过
