### ISSUE TITLE
精选项目在keepwork页面上的显示

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3635]
背景：
运营人员对某些项目设定为精选项目，在首页精选项目中，点“查看更多”，直接能看到所有精选项目

解决方案：
1.在探索页面，一级菜单新增“精选项目”，排序是“综合、热门、最新”，排序还是按现在积分规则排序
2.项目主页上能看到“精选项目”这个特定icon

原型参考：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/18e1b49e-613e-497a-b3e3-677a5dff09b7)

**Comment by enya-i** [comment]
![d753e86bb09d14466bf0a00afccf9b4f](https://user-images.githubusercontent.com/37529364/51107153-ee764e80-1828-11e9-8f5c-8e0dd965fbaf.png)
![67791847cec04fa90dceb20fb1361251](https://user-images.githubusercontent.com/37529364/51107157-f209d580-1828-11e9-923d-de40b17daa22.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/51371173-5b912900-1b34-11e9-87b3-c3004ea083ec.png)

**Comment by Kvaya** [comment]
“精选项目”打开项目主页也需“精选项目”标识

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/51600012-f5dddc00-1f3b-11e9-806e-73bf88c46821.png)
