### ISSUE TITLE
【Bug-Dashboard】课程菜单下的表和字段汉化名字显示与预期不符，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3641]
### Details:

**Env:**  [Dashboard](https://dashboard.keepwork.com)
**Version:** v1.0.0
**Devices:**  chrome  browser
**Pre-condtion:**
  用户是管理员

**Steps:**
-  进入后台后，先进入课程菜单栏，对 热门课程包，课程包，学科，课程关联进行查看，对比信息显示情况

**Expected Result:**
  页面信息显示合理，便于使用者一眼进行区分

**Actual Result:**
 页面信息显示不合理

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/f29ef49e-dc84-414b-ad74-0cdb911bc95b)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/c0886ad0-540b-4e03-9c10-f81e1dec18cf)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/1aae7579-4b10-4d3b-91e6-8dfe30d415ac)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/59ea1f1f-6ecf-451b-a885-dd0ac99d4b12)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/8cf05894-b7a6-4099-aa40-ee50d4342020)

**Comment by shirleyluo1130** [comment]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/570062d4-4549-4ce1-92f3-3dc310af609a)

**Comment by shirleyluo1130** [comment]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/bdc2502e-6c73-4a4f-ba34-e3ad6a7327e1)

**Comment by Sandu1213** [comment]
课程包、课程、学科、用户名显示ID的问题还是没有调整。

**Comment by onedou** [comment]
这个交给凯文做了 @kevinxft

**Comment by Sandu1213** [comment]
release环境还是没有变化，请确认

**Comment by Sandu1213** [comment]
亲，环境是？release毫无变化

**Comment by Sandu1213** [comment]
请同步调整 一下课程包列表通过学科无法过滤查询的问题
![image](https://user-images.githubusercontent.com/21214285/53471977-6cbd4600-3aa1-11e9-8fdd-1c035256486c.png)

**Comment by kevinxft** [comment]
无法实现

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/54105891-65862880-440f-11e9-91f8-cdc7c396c8ab.png)
![image](https://user-images.githubusercontent.com/21214285/54105989-bb5ad080-440f-11e9-9bf7-d39359ae95d4.png)
