### ISSUE TITLE
支付-确认订单

### ISSUE THREAD

**Issue by dalin00** [tatfook/keepwork#3644]
![image](https://user-images.githubusercontent.com/24222876/51156985-efef5780-18b8-11e9-978b-4d1e817468f7.png)

**Comment by Sandu1213** [comment]
对齐问题还存在，但不影响使用，后续再优化
![image](https://user-images.githubusercontent.com/21214285/55855693-cafa4000-5b9a-11e9-9d59-62d3c24c868d.png)
