### ISSUE TITLE
【bug】command在代码区展开时， 代码区用灰色背景色显示

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#365]
如图
![image](https://user-images.githubusercontent.com/28430070/39342118-00a16cc8-4a09-11e8-8a11-3a2a997beed4.png)
![image](https://user-images.githubusercontent.com/28430070/39342127-0c346bb2-4a09-11e8-8fd9-e0a6e3e86e91.png)

**Comment by leopoldchen** [comment]
![image](https://user-images.githubusercontent.com/1396883/49498058-db28a880-f8a4-11e8-9556-dc5f84289e34.png)

由于codemirror的技术实现问题，给多行加背景的效率极低，故而改成只高亮mod的第一行和最后一行

**Comment by Sandu1213** [comment]
release验证ok
