### ISSUE TITLE
【bug-dashboard】网站-封停管理，新增，弹窗缺少网站URL

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#3677]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/3648fdd4-f21e-421a-baff-f898aaae454c)

**Comment by kevinxft** [comment]
![image.png](https://images.zenhubusercontent.com/59edff22a468affe6df7caf6/97733e9b-7738-4ebd-9b7d-7f923f043870)

修改成如图的效果（用户名/网站名称的形式），应该已经能满足使用

**Comment by Sandu1213** [comment]
stage环境：
![image](https://user-images.githubusercontent.com/21214285/57498018-a6fe5b80-730c-11e9-89cb-e3b58197a57c.png)

**Comment by kevinxft** [comment]
fix 选不中的问题, 样式不fix，请用大屏幕使用

**Comment by Sandu1213** [comment]
@Kvaya 已验证，请评估是否可以接受这种实现方式，并回复，谢谢

**Comment by Kvaya** [comment]
建议：
1.
![image](https://user-images.githubusercontent.com/39363297/57505483-108d6280-732b-11e9-970b-77237a2ded33.png)
2.上面实现方式可以的
