### ISSUE TITLE
【dashboard-bug】课程相关bug

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#3685]
课程-课程管理
![image](https://user-images.githubusercontent.com/28430070/51449427-ece7e180-1d66-11e9-8db9-d9112d13ac11.png)
课程-课程 ，修改为名字
![image](https://user-images.githubusercontent.com/28430070/51449446-0426cf00-1d67-11e9-9a7f-dd36ac581acc.png)
课程-课程包
![image](https://user-images.githubusercontent.com/28430070/51449479-2fa9b980-1d67-11e9-9f4a-ee11ce772f05.png)
课程-技能
![image](https://user-images.githubusercontent.com/28430070/51449533-6d0e4700-1d67-11e9-97a8-8ba573c40f70.png)
课程-学科
![image](https://user-images.githubusercontent.com/28430070/51449566-94fdaa80-1d67-11e9-8e2d-73de6b00d64c.png)

**Comment by kevinxft** [comment]
一点问题都没有
