### ISSUE TITLE
【bug-热门课程】首页查看更多热门课程，链接跳转不合理

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3689]
## Environment

* OS Info: Window10
* browser Info: chrome  71.0.3578.98
* URL: [keepwork.com](https://keepwork.com) 
* Model:  首页->热门课程->查看更多

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.从首页->热门课程，点击查看“更多”，观察页面跳转情况

* Expected Result:
1.跳转进入搜索页面，定位到“课程”搜索页
* Actual Result:
1.跳转进入了项目搜索页
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/d14b9c3d-16f8-4a39-94cc-0744181eef02)

**Comment by DDXY1230** [comment]
release
