### ISSUE TITLE
【学习板块】Quiz mod，通过复制粘贴的方式，ID会重复，造成答题时，无法准确记录答题进度。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3693]
目前的处理方式是：手动修改ID。不太方便。
建议做下特殊处理。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/8f676969-2400-4ace-8362-3aa832f248f3)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/9f3318c8-e59b-4518-92a2-6f98ff7e4a02)

**Comment by kevinxft** [comment]
调整为根据题目识别题目

**Comment by Sandu1213** [comment]
release环境验证通过，目前会根据title来进行判断

**Comment by Sandu1213** [comment]
显示环境存在问题，开发还在排查中
