### ISSUE TITLE
【Bug-paracraft评分】通过项目ID进入世界后，对世界进行评分，发现评分未生效，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3695]
## The problem
通过项目ID进入世界后，对世界进行评分，发现评分未生效，请调整

## Environment
* OS Info: Window10
* browser Info: chrome  71.0.3578.98 & paracraft
* URL: [keepwork.com](https://keepwork.com) 
* Model:  评分机制

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入搜索页面，随意找一个paracraft 项目，再打开paracraft 客户端，输入项目ID
2.等待评分弹窗出现后，对项目进行评分，评分完成后，回到keepwork项目页，进行查看

* Expected Result:
1.项目页面可以正常查看到评分

* Actual Result:
1.项目页缺少项目评分记录
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/52fd9b8f-61e5-4301-a7cd-427a44983057)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/d87d23f9-8507-48be-8ec1-df4e37a33509)

**Comment by leopoldchen** [comment]
@onedou 添加的参数名是什么， @ZhangKaitlyn 这边直接添加一下。 可以hotfix
