### ISSUE TITLE
【学习板块】课程管理-课程：从课程列表进入编辑器，跳转问题

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3699]
## 问题描述：

第一步：如下图，设置了url地址后，

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/13406dfd-38c4-406d-ab87-f761b874d979)

第二步：若该url页面暂未创建，点击课程名称

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/314036b9-8b0f-43e0-ab24-c4a6af0d37f5)

第三步：弹出如下提示框，

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/97faf859-c7b8-429d-b6e3-8e8b00ed396f)

第四步：点击“是”后，进入如下页面，且”点击添加模块“按钮无法使用，体验不太好。

![image](https://user-images.githubusercontent.com/40385277/53628085-0c670980-3c45-11e9-8c5a-d25ee1b29e42.png)

## 修改方案：
建议 第四步，点击 “是” 后，直接进入如下页面，即可。（与 未设置url 时的处理方式相同）

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/33d3386d-1569-4151-af11-552ae4bc384a)

**Comment by Sandu1213** [comment]
当Url未输入时处理正确，但Url存在输入时，release环境还是存在问题。

**Comment by Sandu1213** [comment]
stage环境验证通过
