### ISSUE TITLE
【Bug-导航】点击“home"🏠图标时，总是先出现”用户不存在“才会再跳转，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3701]
## The problem
点击“home"🏠图标时，总是先出现”用户不存在“才会再跳转，请优化

## Environment

* OS Info: Window10
* browser Info: chrome  71.0.3578.98
* URL: [keepwork.com](https://keepwork.com) 
* Model:  菜单导航

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.先进入个人主页页面，然后点击导航栏的”home"图标，观察跳转是否正确

* Expected Result:
1.跳转正确，不存在误导或者歧义的地方
* Actual Result:
1.总是会先出现“用户不存在”的提示才跳转，请调整
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/f665e89b-85e4-4a9a-ab18-b87400585eda)

**Comment by DDXY1230** [comment]
release环境

**Comment by Sandu1213** [comment]
问题依然存在，请排查
