### ISSUE TITLE
【Bug-账户解绑】解绑账号页面缺少对token有效的判断，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3709]
## The problem
解绑账号页面缺少对token有效的判断，请调整

## Environment

* OS Info: Window10
* browser Info: chrome  71.0.3578.98
* URL: [keepwork.com](https://keepwork.com) 
* Model:  设置中心->账号绑定

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.拥有2个keepwork账号(账号A未绑定邮箱；账号B已经绑定过邮箱)

* Details:
1.先登陆账号A，进入账号绑定页面，然后再复制绑定页面的Url地址在新页面打开，再登陆账号B
2.此时，再切换到账号A所在的页面，进行邮箱绑定操作，观察绑定结果

* Expected Result:
1.登陆账号B以后，再切换到账号A所在的页面时，token已经变更，页面自动更新
* Actual Result:
1.账号A所在的页面还能正常进行绑定操作，不合理
 

## Attachments (eg:logs/video/screenshot)
[查看视频详情](https://keepwork.com/dukes/1/bindingissues)

**Comment by DDXY1230** [comment]
先登录一个用户绑定页，然后再在新页面登录一个用户，之前那个用户的信息已经失效了返回进行操作就会更新成当前有效的用户信息， （同一个浏览器），

**Comment by Sandu1213** [comment]
release环境已验证
