### ISSUE TITLE
【Bug-搜索】目前只要访问查看项目，就会导致项目按最新更新排序错乱，请调整优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3710]
## The problem
目前只要访问项目，就会导致项目按最新更新排序错乱，请调整优化

## Environment

* OS Info: Window10
* browser Info: chrome  71.0.3578.98
* URL: [keepwork.com](https://keepwork.com) 
* Model:  搜索页面-项目排序

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入搜索页面，先按照最新的顺序进行排序查看，然后随意挑选其中一个项目进行查看
2.然后再切换回到搜索页面，按最新排序进行查看，观察排序顺序

* Expected Result:
1.排序顺序正确，不会因浏览而导致错乱
* Actual Result:
1.目前因浏览，会导致项目并不是按实际的更新情况来显示（需要以真实的项目内容更新时间为标准）
 

## Attachments (eg:logs/video/screenshot)
暂无

**Comment by Sandu1213** [comment]
Keepwork环境已经验证通过；
但Dashboard更新项目的系统标签时还是会影响到，建议增加一个对应的字段来解决该类问题，避免后续还有其他的影响

**Comment by wxaxiaoyao** [comment]
这个问题建议让它吧, 用排除法做, 排一些不想影响更新时间的, 比如访问不能影响. 目前这样没太大问题的

**Comment by Sandu1213** [comment]
如果使用排除法来做的话，目前存在的问题是：
运营人员后台操作，给项目打上系统标签，项目更新时间就变更了。目前不希望变更，希望的是涉及真实用户操作项目的才进行变更(如上图的思维图）。
--- 建议，先把后台操作而导致更新时间变更的问题解决。其他的请产品排期为新需求再考虑具体实现 @Kvaya

**Comment by Kvaya** [comment]
好的，其他情况随后看具体情况提issue

**Comment by wxaxiaoyao** [comment]
已屏蔽后台操作对更新时间的影响

**Comment by Sandu1213** [comment]
release环境已经调整
