### ISSUE TITLE
【Dashboard】“教师激活码”页面，无法筛选用户名。需加上，如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3721]
无法筛选“用户名” 
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/6607e481-c392-4f6d-8c99-1b9362da27d7)

**Comment by Sandu1213** [comment]
因功能调整，该功能弃用，已和产品沟通确认，该issue关闭
