### ISSUE TITLE
【bug】keepwork创造，跳转链接问题

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#3726]
操作步骤：第一步输入网址keepwork.com
第二步：点击创造，滚轮滑到底部
第三步：点击去探索更多好玩的项目
县结果：页面显示空白，链接跳转不对
![image](https://user-images.githubusercontent.com/28430070/51822656-f6012180-2317-11e9-9197-6c3c27984e2b.png)

跳转到此链接

https://keepwork.com/exploration?tab=allProjects

**Comment by DDXY1230** [comment]
release
