### ISSUE TITLE
kw editor里面的mod编辑改名字时，如公司名时必须额外打几个字后才能删原有默认的字。

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3728]
@beyondliu commented on [Mon Jan 28 2019](https://github.com/tatfook/Paraworld-Feedback/issues/3)

---

@azothli commented on [Mon Jan 28 2019](https://github.com/tatfook/Paraworld-Feedback/issues/3#issuecomment-458055309)

@Kvaya  优化交互

---

![image](https://user-images.githubusercontent.com/39363297/51829194-07522a00-2328-11e9-8274-5e112ad34513.png)

@Kvaya commented on [Mon Jan 28 2019](https://github.com/tatfook/Paraworld-Feedback/issues/3#issuecomment-458068066)

使用场景：
培训班的小孩子对editor 中一些mod属性进行编辑时，用回格键删掉默认数值，但操作后不成功

解决方案：
允许用户使用回格键删掉默认数值，添加自定义数值。假设未添加，还是默认数值；
现editor mod一些属性支持回格键操作成功的情况如下：
![image](https://user-images.githubusercontent.com/39363297/51828885-83983d80-2327-11e9-8b2a-074b363970ac.png)

**Comment by Kvaya** [comment]
补充说明：
当属性面板中参数用“
![image](https://user-images.githubusercontent.com/39363297/53059901-8ab00700-34f3-11e9-945a-da80993a07ae.png)
”

**Comment by Kvaya** [comment]
补充说明：
问题：
当属性面板中参数用“![image](https://user-images.githubusercontent.com/39363297/53059901-8ab00700-34f3-11e9-945a-da80993a07ae.png)”删除了，中间预览编辑区中对应的参数值还显示，交互上不合理

解决方案：
当属性面板中参数用“![image](https://user-images.githubusercontent.com/39363297/53059901-8ab00700-34f3-11e9-945a-da80993a07ae.png)”删除了，中间预览编辑区中对应的参数值隐藏，但对应的属性面板中的按钮是显示，对应的属性面板中的参数是空的

**Comment by Sandu1213** [comment]
release环境验证通过
