### ISSUE TITLE
【Bug-排行榜】排行榜里需要去掉私有项目，因为私有项目是无法进行查看评分的

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3730]
## The problem
排行榜里需要去掉私有项目，因为私有项目是无法进行查看评分的

## Environment

* OS Info: Window10
* browser Info: chrome  71.0.3578.98
* URL: [keepwork.com](https://keepwork.com) 
* Model:  排行榜

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.对排行榜里的项目进行查看，点击进入项目详情页进行查看评分操作

* Expected Result:
1.项目都可以正常打开进行查看及评分
* Actual Result:
1.还存在私有项目，项目无法进行打开操作，请调整
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/47fdbd84-ee54-4c86-932a-6ae9b0235160)

**Comment by wxaxiaoyao** [comment]
前端拉取的时候, 带上 visibility = 0 参数过滤

**Comment by Sandu1213** [comment]
release已验证通过
