### ISSUE TITLE
NPL大赛官网

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3733]
应运营要求，需为NPL大赛设置报名入口和后台管理功能，方便运营举办NPL大赛活动和对活动效果进行跟踪。

原型见：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/c0193fa4-f728-401a-9598-ff05a9492fff)

**Comment by leopoldchen** [comment]
@shirleyluo1130 這個是否可以關閉
