### ISSUE TITLE
editor中菜单编辑器中URL中支持输入链接及下拉选择链接

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3740]
**背景：**
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/d364fedc-f6db-431c-be76-7859481abe06)
在菜单编辑器中，链接处即可支持输入，又可支持下拉进行选择链接

**解决方案：**
现菜单编辑器中的链接支持输入链接进行跳转；
现可增加下拉进行选择链接
链接范围和“图片轮播”的链接处一样，是用户个人所有创建的网站、网页。
效果参考“图片轮播”属性面板中的“链接”属性：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/f0e30259-5c03-4f53-bd56-b87a15384e37)

**Comment by duting1993** [comment]
stage
