### ISSUE TITLE
【bug】二维码分享内容错误

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#3748]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/97516065-150d-4b53-8aa3-516bfe154d1b)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/52986913-3560f080-3434-11e9-98d1-19db8e984ef7.png)
![image](https://user-images.githubusercontent.com/21214285/52986924-3f82ef00-3434-11e9-98b3-4c8c02bd24a5.png)
