### ISSUE TITLE
【bug】图片过大，项目预览图加载卡的问题目前有些无解。 后台能否自动生存固定大小的缩略图，然后前端用缩略图显示。 目前很多图都500KB左右的超大无损图。

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#3750]
![image](https://user-images.githubusercontent.com/28430070/52933472-6dadf380-338e-11e9-81be-06efaf1e026d.png)

![image](https://user-images.githubusercontent.com/28430070/52933496-874f3b00-338e-11e9-934a-028bb0a0f49c.png)
![image](https://user-images.githubusercontent.com/28430070/52933518-98984780-338e-11e9-9b2b-d4f4835df8be.png)

**Comment by leopoldchen** [comment]
@wxaxiaoyao 
需要研究一下七牛的图片裁减机制，可以为图片定义多种规格，比如normal、large、small、tiny等，客户端只要在url结尾加扩展就可以选择不同规格的图片。
另外需要确认下之前已上传的图片是否同样可以转换。

**Comment by wxaxiaoyao** [comment]
![image](https://user-images.githubusercontent.com/11922085/52988104-ebc6d480-3438-11e9-85eb-3eec223872fc.png)
![image](https://user-images.githubusercontent.com/11922085/52988139-08fba300-3439-11e9-8c00-9a8e300fa5db.png)

**Comment by wxaxiaoyao** [comment]
![image](https://user-images.githubusercontent.com/11922085/52998945-78848900-345f-11e9-81bd-3b42065aa237.png)
前端此接口进行文件转换实现

**Comment by Kvaya** [comment]
建议图片尺寸压缩过后的大小是小于等于
![image](https://user-images.githubusercontent.com/39363297/53003429-e33ac200-3469-11e9-89cc-a7b322f00732.png)

**Comment by wxaxiaoyao** [comment]
https://developer.qiniu.com/dora/manual/1270/the-advanced-treatment-of-images-imagemogr2

这里有高级处理方式, 客户端自行加裁剪参数即可

**Comment by LiXizhi** [comment]
最后这种方式，好像解决了大部分问题：如果能将PNG变成JPG就更完美了。 PNG无损还是有些大。 

加入 `&imageMogr2/thumbnail/!480x270r`
2MB: 

http://qiniu.keepwork.com/8caaff40-2532-11e9-b3b5-43b7a658c47e.png?e=4702523543&token=LYZsjH0681n9sWZqCM4E2KmU6DsJOE7CAM4O3eJq:K6PBOcOAFRuQWcIysz5bK2XygyQ=

200KB：
http://qiniu.keepwork.com/8caaff40-2532-11e9-b3b5-43b7a658c47e.png?e=4702523543&token=LYZsjH0681n9sWZqCM4E2KmU6DsJOE7CAM4O3eJq:K6PBOcOAFRuQWcIysz5bK2XygyQ=&imageMogr2/thumbnail/!480x270r

**Comment by wxaxiaoyao** [comment]
七牛没有图片转换功能, 这个是可以从需求上控制下的, 最好是不要上传超过1M的图片.  图片太大有很多问题, 上传, 显示时间都会很长, 项目列表多图展示的时候更长.  若手机流量访问那更是打开第一次都不敢打开第二次啦.

**Comment by Sandu1213** [comment]
还有不少world的封面是用git存储的，这个如何处理？
![image](https://user-images.githubusercontent.com/21214285/53151784-f4f9a200-35ee-11e9-9d47-be18f54f5db9.png)
如下:[封面](https://git.keepwork.com/gitlab_rls_official/world_base32_4w4knzmixltzvbhexk5opfe7/raw/master/preview.jpg)

另外，目前的版本还没有添加 ```&imageMogr2/thumbnail/!480x270r```,请添加

**Comment by Sandu1213** [comment]
涉及git存储的，稍后会的手动处理下
