### ISSUE TITLE
【bug】添加多个mod，点击其中一个mod，要修改的部分，左侧无反应

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#3751]
操作步骤：1.添加多个mod
2.修改其中一个mod要修改的部分
显示结果：左侧无反应
![image](https://user-images.githubusercontent.com/28430070/52938259-32b2bc80-339c-11e9-8da3-a70a1817f8ff.png)

**Comment by kevinxft** [comment]
复现不出

**Comment by duting1993** [comment]
把mod中主标题删掉，点击另一个mod，在点击删掉主标题mod，会出现此情况

**Comment by kevinxft** [comment]
soga

**Comment by duting1993** [comment]
release
