### ISSUE TITLE
【bug】iPad竖屏时，要显示，创造，搜索，学习

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#3755]
![image](https://user-images.githubusercontent.com/28430070/52992714-8b419280-344c-11e9-8c1f-c384e8115143.png)

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/57745824-389d0d00-7701-11e9-8b36-8ba20c745b0a.png)
![image](https://user-images.githubusercontent.com/18642919/57745850-5cf8e980-7701-11e9-8876-4e5af929ae1d.png)
