### ISSUE TITLE
【Bug-search】课程搜索的内容显示不准确，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3759]
## The problem
课程搜索的内容显示不准确，请调整

## Environment

* OS Info: Window10
* browser Info: chrome   72.0.3626.109 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  搜索->课程

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.先进入搜索页面，搜索所有课程包，进行查看，观察搜索结果
2.再进入学习中心->全部课程，对比课程包数量和显示情况
3.对搜索课程包包含的课程数量进行查看，对比课程包详情页的课程数量

* Expected Result:
1.数量都是一致的
* Actual Result:
1.数量不一致，搜索页面存在遗漏的情况
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/1ae86188-1995-4621-90ba-d9ea3a5b7d31)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/9bdf4252-f682-4739-95a7-dcaebeef734f)

**Comment by William0911** [comment]
线上已修复

**Comment by Sandu1213** [comment]
线上验证通过
