### ISSUE TITLE
KeepWork官网搜索功能支持空格情况

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3760]
**背景：**
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/90771d8a-4f99-44d8-8197-212becbdcd49)
在eepWork官网搜索框输入“Hour Of Code”搜索不到，但输入“HourOfCode”，搜索结果是
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/4dd6c2ac-8383-4a96-8ab5-a10f5375e5f2)

 **预想结果：**
当搜索框输入“Hour Of Code”，搜索结果出现
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/4dd6c2ac-8383-4a96-8ab5-a10f5375e5f2)
搜索框把空格处理了

**Comment by William0911** [comment]
@Kvaya 请测一下stage环境下功能是否正确实现。

**Comment by Kvaya** [comment]
@William0911  stage环境下功能实现正确，很棒！

**Comment by William0911** [comment]
stage环境可测

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/53226468-0fe31980-36b6-11e9-9d65-45814a0ae9ce.png)
