### ISSUE TITLE
【Bug-学习】学习中心的教学视频链接，跳转不合理，需优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3762]
## The problem
学习中心的教学视频链接，跳转不合理，需优化

## Environment
* OS Info: Window10
* browser Info: chrome   72.0.3626.109 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  学习中心->教学视频

## Step To Reproduce Issue [ Good To Have ]
* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入学习中心，选择教学视频，分别选择不同的类别进行查看，观察跳转页面是否合理

* Expected Result:
1.页面跳转合理
* Actual Result:
1.页面跳转不合理
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/a09a1d3e-e236-4f9b-a1ba-d0ac6967fec5)

**Comment by DDXY1230** [comment]
release环境
