### ISSUE TITLE
【Education】导师服务页面，URL修改+文字排版调整

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3763]
1、URL修改

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/6c639a96-ba0e-45b1-942f-49520a48d193)

2、文字排版调整

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/8f7e88dc-dd90-4908-a97f-b3229526fc8f)

以上红框中的文字排版请使用如下形式

 ![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/afd45729-6378-4c58-8be7-2064240ce59e)

**Comment by shirleyluo1130** [comment]
UI见：
![image](https://user-images.githubusercontent.com/40385277/53162168-698c0b00-3606-11e9-9ad4-784b63bed4a6.png)

**Comment by ZhangKaitlyn** [comment]
文字排版调整中文版测试地址： [https://keepwork.com/official/paracraft/learn/mentor_service-test](https://keepwork.com/official/paracraft/learn/mentor_service-test)
文字排版调整英文版测试地址：[https://keepwork.com/official/paracraft/learn/mentor_service-test_EN](https://keepwork.com/official/paracraft/learn/mentor_service-test_EN)
