### ISSUE TITLE
【Education】教学视频页面，内容调整。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3764]
## 1、教学视频-动画教学

* 注意 ：该页面的内容修改，不要在原始链接上改动，建议新建页面后修改。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/52d6acdc-267e-44c3-8d00-cd303f1e3007)

## 2、教学视频-编程教学

* 注意 ：该页面的内容修改，不要在原始链接上改动，建议新建页面后修改。

以下页面右侧的全部内容替换为 URL（https://keepwork.com/official/paracraft/CodeblockList
） 中的内容。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/84a4db88-a1e9-4d54-a70c-3428b9e17fae)

**Comment by DDXY1230** [comment]
release环境

**Comment by Sandu1213** [comment]
英语模式下看不到内容，请调整
![image](https://user-images.githubusercontent.com/21214285/53789064-7ee62b00-3f5e-11e9-9a85-4823e2c1b135.png)
