### ISSUE TITLE
【Bug-mod】使用退格键删除mod属性里的默认值时，会出现删除中断的情况，左侧自动切换为文件列表了，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3765]
## The problem
使用退格键删除mod属性里的默认值时，会出现删除中断的情况，左侧自动切换为文件列表了，请调整

## Environment

* OS Info: Window10
* browser Info: chrome   72.0.3626.109 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  mod

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.通过工具->网站编辑器，进入editor页面，然后新建一个页面，选择mix_layer或者mix_position mod
进行添加，添加完成后，对mod自身属性的默认值进行删除(如：标题/副标题/正文)
2.当使用退格键进行删除多次时，观察删除效果

* Expected Result:
1.可以正常删除，清空后可以正常输入
* Actual Result:
1.删除过程中，会出现mod属性页自动跳转为文件列表的情况，导致删除中断，请调整
 

## Attachments (eg:logs/video/screenshot)

**Comment by kevinxft** [comment]
问题修复，不过在markdown这个mod下操作左边的属性，依旧会出现这个问题，暂时没找到合适的方案解决

**Comment by Sandu1213** [comment]
问题还是存在(图文叠加，paracraft mod等)，只有是文本的输入框都有概率出现
