### ISSUE TITLE
PAC大赛 - 网站template

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#377]
@ZhangKaitlyn @azothli @uriage 
                                                                                            
经确认, pac网站暂时不需要做成网站模板，为不污染当前KeepWork代码，可以放到另一个repo中，可以把这个做出类似starter kit一样的东西。

目标：在5.5前有一个可以演示的版本（最晚5.10），至少完成网站登录注册和网站首页功能

**Comment by leopoldchen** [comment]
@uriage                         

pac
需要有更细致的需求。包括后端这边也想看一下设计稿，以便确认api是否够用

**Comment by uriage** [comment]
好的，设计稿已有，后台这边后端是用框架写还是自己搭建一个后台？麻烦相关人员与我这边对接。

**Comment by leopoldchen** [comment]
@uriage @wxaxiaoyao @ZhangKaitlyn @ouyc 

先review一下整体设计，然后拆分issue来实现。
@ZhangKaitlyn 顺便叫一下罗晓敏
