### ISSUE TITLE
【KeepWork dashboard】能对用户进行重置密码、查看用户详情、查看用户资料

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3779]
**问题：**
现后台不能对用户重置密码、查看用户详情

**解决方案：**
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/934be22e-901e-495e-8f34-23dc2616d96f)
1.操作列表中，把“编辑、删除”键去掉
2.增加“重置密码”、“查看主页”
其中“重置密码”的参考方案如下图：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/1022c28c-82e4-4451-a294-ca1072cfc602)

注：在后台点击“查看主页”直接跳转至keepwork官网该用户的个人主页；

**Comment by Sandu1213** [comment]
查询超时，无法验证，请排查。
![image](https://user-images.githubusercontent.com/21214285/53620490-2812e580-3c2e-11e9-9151-0c580ee97cad.png)

**Comment by DDXY1230** [comment]
stage环境测

**Comment by Sandu1213** [comment]
stage验证通过。但需要注意样式问题
![image](https://user-images.githubusercontent.com/21214285/53707810-7b25ac00-3e6b-11e9-920d-247d43654b87.png)
