### ISSUE TITLE
【Bug-editor】网站编辑器里，新建网页时，输入完信息，无法通过回车键快速进行新建，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3782]
## The problem
网站编辑器里，新建网页时，输入完信息，无法通过回车键快速进行新建，请优化

## Environment

* OS Info: Window10
* browser Info: chrome   72.0.3626.109 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  editor->新建网页

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入编辑器页面，选中任意一个网站进行新建网页操作，待输入完成后，点击回车键，
观察新建结果

* Expected Result:
1.新建网页成功，页面显示正常
* Actual Result:
1.页面会自动刷新，新建页面不成功
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/c78ade16-859c-4b9c-bbf1-fe8332773e3f)

**Comment by kevinxft** [comment]
![GIF.gif](https://images.zenhubusercontent.com/59edff22a468affe6df7caf6/d0738b94-7d21-4b19-a619-bc3696b0c964)

线上环境没复现出来，因为这里有个敏感词检查，回车后会有短暂延迟，测试大大看看是否这个问题

**Comment by Sandu1213** [comment]
问题依然存在

**Comment by Sandu1213** [comment]
release环境已经验证
