### ISSUE TITLE
【海外版】登录注册调整

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#379]
@azothli commented on [Sat Apr 28 2018](https://github.com/tatfook/wikicraft/issues/1765)

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/ea542cb8-342c-4ea7-bb30-3d38bf2697b6)

手机验证调整为输入email不验证

**Comment by yuanoook** [comment]
和香安确定方案细节如下：
1. 后端无需调整
2. 前端需要根据国际化版本，发送邮箱和用户名到后端，用户名不能为邮箱，因为不能带 . @ 符号
3. 用户名不能为邮箱，这里需要和李宇确定最终方案

**Comment by yuanoook** [comment]
上面的图有问题，用户名跟邮箱没关系。用户名是独立于邮箱单独设置的。
