### ISSUE TITLE
【海外版】第三方登录支持

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#380]
@azothli commented on [Sat Apr 28 2018](https://github.com/tatfook/wikicraft/issues/1766)

海外版支持的第三方账号调整为

facebook、google、twitter、github
需要进行相关的资质申请

---

@ExerciseBook commented on [Sat Apr 28 2018](https://github.com/tatfook/wikicraft/issues/1766#issuecomment-385148042)

#1087

**Comment by Sandu1213** [comment]
facebook和google account 都不能登录，请排查
![image](https://user-images.githubusercontent.com/21214285/40960710-26d8b296-68d3-11e8-8c39-0800291d3828.png)

**Comment by azothli** [comment]
twitter  技术难度大，可以暂缓开发，等海外的需求反馈再做调整。

**Comment by Sandu1213** [comment]
google/facebook在https协议下验证通过
