### ISSUE TITLE
【npl-bug】结束时间比开始时间晚

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#3803]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/d035357a-3997-4732-a9fc-d9ff1a16bebc)

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/53478956-fa556180-3ab2-11e9-991a-b639d59e1f25.png)
