### ISSUE TITLE
【Paracraft.cn】官网首页设计

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3813]
背景：
Paracraft设计官网，方便市场推广，to b客户能了解我们产品更多些。
首页设计

解决方案：
官网原型：
![image](https://user-images.githubusercontent.com/39363297/53868887-fa64dc80-4031-11e9-8553-bffbc2a30946.png)

设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/54179099-bf9bf200-44d2-11e9-8229-da8536ce5616.png)

首页中“作品是最好的老师”那块的视频和作者名称对应的文档在：
![image](https://user-images.githubusercontent.com/39363297/54403424-ecd2e500-470a-11e9-9378-cb28fc2d1143.png)

价格处，编程课程服务版块中，计算器要算出勾选的项目的总价。
其中，学生数量的计算公式是：
试学账号5个：免费
学生数量（0-100）单个学生费用2000元/年 （2000N）
学生数量（100-500）新加入学生费用为1800元/年 （20万 + 1800*（N-100））
学生数量（> 500） 新加入学生费用为1500元/年 （92万+ 1500*(N-500)）

计算器参考建议：
计算器可以用http://element.eleme.io/#/zh-CN/component/slider 组件做；
效果可以参考https://www.upyun.com/pricing 这样的排版布局来

**Comment by Kvaya** [comment]
补充：
官网轮播切换是每4秒进行切换

**Comment by Kvaya** [comment]
价格计算器方案：
![image](https://user-images.githubusercontent.com/39363297/54525195-9be31b00-49ae-11e9-81a7-c0ebf6e2cd1a.png)

**Comment by Kvaya** [comment]
“作品是最好的老师”上传的视频素材中去掉“荔园小学”

**Comment by Kvaya** [comment]
细节调整：
https://note.youdao.com/ynoteshare1/index.html?id=5278f239ff8a335f3b8d56eab4f1446c&type=note

**Comment by Sandu1213** [comment]
请先按照细节调整后再回归验证

**Comment by Kvaya** [comment]
“作品是最好的老师”那处新增每个作品类型，类型参考：
![image](https://user-images.githubusercontent.com/39363297/54903223-5eced980-4f16-11e9-8191-5f6d1476e980.png)
![image](https://user-images.githubusercontent.com/39363297/54903274-7e660200-4f16-11e9-934d-e50970a2ad61.png)

**Comment by DDXY1230** [comment]
@Kvaya 剩下的修改和问题请归入文档汇总，重新建issue，统一做处理。

**Comment by Kvaya** [comment]
好的
