### ISSUE TITLE
【NPL大赛】首页，补充几条规则。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3816]
1、在“作品获奖资格标准”处，补充以下几条规则：

每期大赛截止日期前，作品可随时提交。未在截止日期前提交的作品，可参与下届比赛。
报名及作品提交中，请填写真实的个人信息，以方便组委会第一时间联系。
作品评分时间自作品提交开始，自本期大赛截止终止。
作品评分分为主动评分类型及被动系统邀请类型。
为获得客观评分，参赛选手可尽早提交作品邀请他人为自己评分。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/f337eb37-9e41-4994-8adc-e0582c829e57)

2、如下图，有几处文字修改 

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/8ba47324-e02f-4a0e-9a94-6ab2a7c44a36)

**Comment by DDXY1230** [comment]
release环境
