### ISSUE TITLE
editor中能删除网站

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3819]
问题：
现editor不能删除网站

解决方案：
单击“设置”弹出“网站设置”页面：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/f75e012b-7b42-418c-99c7-03ef377d9ac7)

单击“删除网站”，如图显示：
![image](https://user-images.githubusercontent.com/39363297/55461469-1656a080-5627-11e9-9c3c-0d6e14585ad3.png)

且项目主页中显示：
![image](https://user-images.githubusercontent.com/39363297/55461502-28384380-5627-11e9-97aa-1710b4c8c696.png)

**Comment by Kvaya** [comment]
补充：
1.假设该网站不是editor中直接创建，而是在创建项目时关联的网站，则该项目保留，并在项目主页中，"编辑网站“改为“重新设定网站”，弹窗内“将已有网站加入项目”逻辑跟现在的一样；

**Comment by Kvaya** [comment]
英文翻译：
您确定要删除网站吗？ Are you sure you want to delete the website?

我知道网站删除后将清除相关的全部数据，且连接到该网站的URL都将失效。如果该网站是某个项目的一部分，将会影响该项目的访问。

After the website is deleted, all the relevant data will be cleared and the URL that connects to the site will be invalid. And the project cannot be accessed if the website is part of it.

删除网站  Delete Website

**Comment by DDXY1230** [comment]
release环境

**Comment by Kvaya** [comment]
release环境体验情况：
1.在editor中已删除该项目之前设定的网站，返回到项目主页去，项目主页上还显示“编辑网站”，并点击“编辑网站”能进去editor。
![image](https://user-images.githubusercontent.com/39363297/55534383-dbb43d00-56e6-11e9-8705-2b4506983e7f.png)

2.建议“重新设定网站”弹窗中“提示”二字去掉

3.“删除网站”弹窗中，建议“如果该网站....访问”这一句话，在第二行

**Comment by Sandu1213** [comment]
1.英文版问题
![image](https://user-images.githubusercontent.com/21214285/55533754-e66dd280-56e4-11e9-8494-f7b186a13e31.png)

2.重设网站功能
![image](https://user-images.githubusercontent.com/21214285/55534530-42d1f180-56e7-11e9-973e-249a54de8132.png)

3.项目主页
![image](https://user-images.githubusercontent.com/21214285/55534648-8dec0480-56e7-11e9-9460-9fe6ac71c0bc.png)

**Comment by Kvaya** [comment]
抱歉，补充：
1.“重新设定网站”弹窗后，显示下面内容
![image](https://user-images.githubusercontent.com/39363297/55535359-934a4e80-56e9-11e9-8956-85da31cc2780.png)
备注：保留创建新网站选项

2.editor中“删除网站”弹窗中，
![image](https://user-images.githubusercontent.com/39363297/55535471-f20fc800-56e9-11e9-8f20-038bc772528b.png)
这句话是正常黑色就好，并勾选“单选按钮”后，该段文字也不变色，是正常黑色

**Comment by Sandu1213** [comment]
- 问题1：
![image](https://user-images.githubusercontent.com/21214285/55545125-217cff80-56ff-11e9-83e8-ab80cdbbd4eb.png)
- 问题2：
