### ISSUE TITLE
【海外版】实名制验证去除

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#382]
@azothli commented on [Sat Apr 28 2018](https://github.com/tatfook/wikicraft/issues/1768)

去除必须手机号验证实名才可以发内容的限制

---

@ExerciseBook commented on [Sat Apr 28 2018](https://github.com/tatfook/wikicraft/issues/1768#issuecomment-385148119)

不知海外版是否和国内版使用同一平台。 【感觉不行。

**Comment by yuanoook** [comment]
www\wiki\helpers\config.page 配置文件添加 locale 变量， zh_CN or en_US ，
zh_CN 表示国内版， en_US 表示国际版

**Comment by Sandu1213** [comment]
待环境OK后进行验证

**Comment by Sandu1213** [comment]
请屏蔽
![image](https://user-images.githubusercontent.com/21214285/40958079-939aca58-68ca-11e8-98d4-52815e70a58f.png)

另外：
![image](https://user-images.githubusercontent.com/21214285/40958155-d4bb42e2-68ca-11e8-8404-7d0298169946.png)

**Comment by Sandu1213** [comment]
stage环境验证通过
