### ISSUE TITLE
editor中通过网盘插入图片，能对该图片进行宽度、高度的调整

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3820]
**背景：**
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/4f17066a-0971-4dc7-8623-279e0d25e153)

**问题：**
通过网盘插入图片，目前是不能对图片进行宽度、高度的调整

**解决方案：**
![image](https://user-images.githubusercontent.com/39363297/53402254-5acd9b80-39ec-11e9-8331-4a77882d0384.png)

**备注：**
bigfile只是图片格式的才有此需求

**Comment by ouyc** [comment]
Issue moved to [tatfook/KeepWorkDesgin #102](https://github.com/tatfook/KeepWorkDesgin/issues/102) via [**ZenHub**](https://www.zenhub.com/)
