### ISSUE TITLE
keepwork网盘入口更改

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3832]
背景：
![3_9RAH~~}WZ6FP0)W`J0LS0.jpg](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/f9017290-83ad-40c6-a34b-ef469cce39ac)

解决方案：
1.在个人头像下的“我的网盘”去掉；
2.把“我的网盘”移至在“工具”下，名称为“网盘”；
3.在“工具”下，网盘位置在“网站编辑器”和“Paracraft创意空间”中间，功能和现在一样，点击“网盘”弹出网盘窗口

**Comment by DDXY1230** [comment]
release环境测试
