### ISSUE TITLE
【Paracraft.cn】官网下载页设计

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3836]
背景：
paracraft设计官网，方便市场推广，to b客户能了解我们产品更多些。
下载页开发

解决方案：
官网原型：
![image](https://user-images.githubusercontent.com/39363297/53869782-d7d3c300-4033-11e9-94ce-e8ddde76e7b7.png)

下载页文档：
免费的3D可视化编程教学工具
7岁以上用户可以用Paracraft创作3D动画和电影，学习和编写计算机程序，支持积木式编程和代码编程一键切换，界面操作简单，老师和学生都能快速上手。

设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/53930410-1e74fc00-40cc-11e9-930c-4cc30091e10d.png)

**Comment by Sandu1213** [comment]
Mac版的直接下载，点击后无反应，请调整

**Comment by Kvaya** [comment]
现下载页调整至：http://paracraft.keepwork.com/download?lang=zh
（因新的版本发布还是更新在这页，新的下载页新的版本未更新）
