### ISSUE TITLE
editor增加历史记录功能

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3844]
@Kvaya commented on [Thu Feb 28 2019](https://github.com/tatfook/KeepWorkDesgin/issues/103)

背景：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/2647c957-0570-4080-a116-48f9515524e5)

问题：
editor现没有历史记录功能，并不能访问历史记录，恢复历史数据

解决方案：
![image](https://user-images.githubusercontent.com/39363297/55793393-5de09f00-5af5-11e9-86d6-052017a2e373.png)

**Comment by Kvaya** [comment]
建议补充：把从editor中“keepwork”下拉浮窗中的“帮助”移至“历史记录”后面

**Comment by Kvaya** [comment]
英文环境下，各英文翻译：
历史版本 Old versions 
恢复到此版本 Recover this version 
vXX来自vXX恢复  vXX recovered from vXX

**Comment by Kvaya** [comment]
editor 历史版本功能原型地址：
![image](https://user-images.githubusercontent.com/39363297/53783384-4f2e2780-3f4c-11e9-8910-cd667a7a2b8e.png)

**Comment by Kvaya** [comment]
历史记录设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/54586279-8b3aaf80-4a57-11e9-947a-5a42abb80655.png)

**Comment by Kvaya** [comment]
![image](https://user-images.githubusercontent.com/39363297/55696212-80d45b80-59ee-11e9-9d22-486261a23772.png)

左侧历史版本列表，一页显示24条；滚动条上下滑动，不做翻页；往下滑动时，刷新10条

**Comment by dalin00** [comment]
![image](https://user-images.githubusercontent.com/24222876/55854946-b2892600-5b98-11e9-98db-fde647ca47bf.png)

**Comment by Kvaya** [comment]
补充：
![image](https://user-images.githubusercontent.com/39363297/55950684-0f173e80-5c88-11e9-9ba2-7686fb964560.png)
版本  Version No.
操作人   Operator
更新时间 Update at

**Comment by Sandu1213** [comment]
@Kvaya  请设计一个方便快速使用的入口
![image](https://user-images.githubusercontent.com/21214285/56179070-04b5c580-6037-11e9-822b-87e737001ed3.png)

**Comment by Kvaya** [comment]
![image](https://user-images.githubusercontent.com/39363297/56179570-c15c5680-6038-11e9-97f0-5d74f627f557.png)
