### ISSUE TITLE
【Education】学习中心（学生页），支持输入课程ID进入课程学习。如下图：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3845]
文字按下图调整下，同时支持输入课堂ID和课程ID。同时，需判定课堂ID、课程ID是否存在。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/c503b524-0fad-4122-a4e6-ebd301376c32)

**Comment by wxaxiaoyao** [comment]
![image](https://user-images.githubusercontent.com/11922085/53611540-f1c36f00-3c09-11e9-878f-9b98f1cf6415.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/53620965-e125ef80-3c2f-11e9-8dab-64d60667cf7f.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/53621260-ed5e7c80-3c30-11e9-96cb-7c8df6853d15.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/53706383-149d8f80-3e65-11e9-998c-24cab4b5f3a2.png)

**Comment by shirleyluo1130** [comment]
英文翻译：
快速进入课程学习    Quick entry learning 
请输入课堂ID或课程ID   Class ID or Lesson ID

**Comment by Sandu1213** [comment]
翻译问题待处理

**Comment by Sandu1213** [comment]
stage环境验证通过
