### ISSUE TITLE
【Bug-项目主页】当成员名称过长时，项目主页的项目成员信息显示不合理，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3849]
## The problem
当成员名称过长时，项目主页的项目成员信息显示不合理，请优化

## Environment
* OS Info: Window10
* browser Info: chrome   72.0.3626.109 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  大文件

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入项目主页[1251](https://keepwork.com/pbl/project/1251/),观察项目成员信息显示是否合理

* Expected Result:
1.成员信息显示合理
* Actual Result:
1.成员信息显示不合理，创建者标识样式错乱
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/77f2318b-100e-403e-8bcf-03c95a28c1da)

**Comment by DDXY1230** [comment]
release环境测
