### ISSUE TITLE
【Bug-敏感词】目前敏感词的处理方式不合理，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3861]
## The problem
目前敏感词的处理方式不合理，请调整

## Environment
* OS Info: Window10
* browser Info: chrome   72.0.3626.109 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  敏感词校验

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.创建一个新项目，输入名称“贩毒”，观察页面处理方式
2.进入编辑器里，选择文件进行编辑，输入敏感词“杀人”等，观察页面处理情况
3.进入搜索页面，选择任一一个项目进行评论，输入敏感词“AV”，观察页面显示情况

* Expected Result:
1.内容都可以正常输入，但保持以后，敏感词都替换为“*”
* Actual Result:
1.目前敏感词都无法保存或者输入成功，且用户无法感知
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/2505bf27-1708-4865-b1e3-ebd3d084b7d8)

**Comment by LiXizhi** [comment]
@azothli 
产品需要确定一下方案

**Comment by azothli** [comment]
这个记得之前交流过
可以采用这种替换提示的方式，可以安排开发

**Comment by kevinxft** [comment]
目前只针对部分文本比较长的地方做替换提醒处理，其余文字比较简短的部分依旧以直接弹框提示的方式，如果有什么地方需要替换文本的方式提示用户，可以单独列出来以后再做调整。

**Comment by kevinxft** [comment]
PBL里面修改的比较多，其余地方没怎么调整

**Comment by Sandu1213** [comment]
其他页面再另外跟进
