### ISSUE TITLE
【bug-dashboard】npl大赛-作品统计-作品得分，有评分的要显示出来

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#3869]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/ac8ca372-e1ae-4158-8b50-8a8c7494f35e)
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/fbbb7efa-8543-41c0-ab32-0b5a48c9453b)

**Comment by wxaxiaoyao** [comment]
不清楚测试步骤, 无法排查bug.... 请补充测试步骤.

**Comment by DDXY1230** [comment]
在大赛期间的评分会显示，大赛结束，过期了，再次评分也就没用了，不再显示

**Comment by DDXY1230** [comment]
已经向产品确认，大赛过期的评分不在算数。该issue可以关闭了。
