### ISSUE TITLE
【NPL大赛】首页文字调整，如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3874]
**如下图，文字修改为：**

本次未获奖作品，在修改完善后重新提交获取新ID，以新ID参加下一届NPL大赛评比。

![NPL大赛-文字修改png.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/8af96328-abf5-4495-bb94-f9cb89ad7c7c)

**Comment by duting1993** [comment]
已上线

![image](https://user-images.githubusercontent.com/28430070/53786752-9a016c80-3f57-11e9-8481-d079d1ff0bce.png)
