### ISSUE TITLE
【Bug-视频】首页的视频经常无法播放或出现网络错误，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3889]
## The problem
首页的视频经常无法播放或出现网络错误，请调整

## Environment
* OS Info: Window10
* browser Info: chrome   72.0.3626.109 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  视频

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入keepwork首页，观察首页的视频播放情况
2.选择还有视频的教学页面，如[编程教学](https://keepwork.com/l/student/allteachingvideo/program),观察视频的播放情况
3.访问其他含有视频的页面，观察视频播放情况

* Expected Result:
1.视频能正常播放，对用户有比较合理的提示(如：当前加载遇到问题，请稍后重试)
* Actual Result:
1.视频无法播放，偶尔还会出现网络错误信息
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/f6bdf8d5-ddb1-4a75-a9df-e2c8ddc52f45)

**Comment by Sandu1213** [comment]
换成vedio.js的解决方案

**Comment by kevinxft** [comment]
现在就是video.js的解决方案😀
