### ISSUE TITLE
【Education-机构】dashboard-机构管理

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3890]
dashboard中，增加机构管理模块，配置机构专属的登录url，有效期限、课程包使用权限及可添加的用户数等信息。原型见：

![image](https://user-images.githubusercontent.com/40385277/54337828-16d4ca80-466b-11e9-953f-493ee4bde5a3.png)

**Comment by LiXizhi** [comment]
@Kvaya  dashboard需要补充机构登记申请的信息，应该是在同一个类别下

**Comment by LiXizhi** [comment]
@shirleyluo1130 应该需要添加机构管理员的管理功能

**Comment by Kvaya** [comment]
好的

**Comment by shirleyluo1130** [comment]
机构登录url，采用手动输入的方式进行配置，需保证唯一性。

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/54667385-2f3f5c00-4b27-11e9-92b0-4cf72490d385.png)

加一下邮箱信息的录入
![image](https://user-images.githubusercontent.com/28430070/54667420-4120ff00-4b27-11e9-8660-266e36199f21.png)

邮箱信息在列表中也显示下
![image](https://user-images.githubusercontent.com/28430070/54667442-51d17500-4b27-11e9-84a9-bdaaff2765b0.png)

**Comment by Sandu1213** [comment]
1.URL设置重复了，提示语不合理
2.课程包勾选未显示选中效果
3.联系电话缺少校验(应该纯数字)
