### ISSUE TITLE
keepwork页面Web打印优化

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/keepwork#3891]
![image.png](https://images.zenhubusercontent.com/5925484051aa2c30577f488d/8e1c249d-512d-42b2-b45e-c1dbd9d98043)

- 1. 每页都会出现多余的TOP

![image.png](https://images.zenhubusercontent.com/5925484051aa2c30577f488d/b7db8767-dc08-4291-8982-02e3fbcab2d4)
- 2. 上面这行， 尤其是编辑，分享按钮对PDF来说用处不大， 可以去掉， 影响美观

**Comment by Sandu1213** [comment]
请查看 [例子](https://keepwork.com/dukes/summary/vim)，移除打印无用的图标信息

**Comment by Sandu1213** [comment]
release环境验证通过
