### ISSUE TITLE
Keepwork Editor, 导航菜单mod建议增加竖排显示的样式。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3895]
## 背景 
目前，Editor的导航菜单均为横排样式 
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/a53bce9b-8daf-49c4-8e35-bba166ddf888)

无法实现如下图所示的样式呈现：
 ![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/54272091-3cf4-417f-98b6-f09be3e928f0)

可否增加竖排显示的样式？

**Comment by Kvaya** [comment]
解决方案：
![image](https://user-images.githubusercontent.com/39363297/53949924-0e7a0e00-4106-11e9-8868-b6e083656654.png)

**Comment by leopoldchen** [comment]
目前左右分栏的layout只有一种，即全屏左右分栏。可能需要添加一种居中式的左右分栏。
![image](https://user-images.githubusercontent.com/1396883/54974869-6a7ed680-4fd0-11e9-99e0-93239451f406.png)

**Comment by Sandu1213** [comment]
release环境验证通过，menu可正常竖排显示
![image](https://user-images.githubusercontent.com/21214285/54976061-21c91c80-4fd4-11e9-88d7-1695d83ae9b7.png)
