### ISSUE TITLE
【Paracraft.cn】提交表单开发

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3898]
背景：
Paracraft设计官网，方便市场推广，to b客户能了解我们产品更多些。
提交表单开发

解决方案：
官网原型：
![image](https://user-images.githubusercontent.com/39363297/53869782-d7d3c300-4033-11e9-94ce-e8ddde76e7b7.png)

设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/53928956-0b136200-40c7-11e9-92fd-e95241c2464c.png)

**Comment by Kvaya** [comment]
表单进一步优化，原型地址在：
![image](https://user-images.githubusercontent.com/39363297/54170491-e695fc00-44b1-11e9-9c10-6ff30380d04b.png)

**Comment by Sandu1213** [comment]
1.标签页图标显示问题
![image](https://user-images.githubusercontent.com/21214285/54503416-13db2200-496a-11e9-8add-341f32386f9d.png)

2.邮箱必填是假的，缺少校验
![image](https://user-images.githubusercontent.com/21214285/54504801-235d6980-4970-11e9-9905-5251a79c516a.png)

3.邮箱格式和手机格式未正确校验
4.反馈信息模板问题   @Kvaya 请确认是否需要如此调整。
![image](https://user-images.githubusercontent.com/21214285/54505053-463c4d80-4971-11e9-8c5f-8ae1752f4642.png)

5.没有正确的发送邮件
6.重新打开应该全部初始化，而不需要记录上次的操作内容。
7.文字描述问题，请保持一致  @Kvaya 请核对后回复
![image](https://user-images.githubusercontent.com/21214285/54505287-32ddb200-4972-11e9-842e-94875a72ff7d.png)
8.描述布局显示问题
![image](https://user-images.githubusercontent.com/21214285/54505354-70423f80-4972-11e9-8f51-a36a3be3159e.png)

**Comment by Kvaya** [comment]
4，反馈信息模板按建议的优化

**Comment by Kvaya** [comment]
细节调整：
1.“合作咨询”弹窗处：
1）“所属单位名称”是必填项
2）在“所属单位名称”下新增“所在城市”一项，效果参考
3）
![image](https://user-images.githubusercontent.com/39363297/54891376-1993b300-4ee8-11e9-871f-09a4507d169f.png)

改成：
表单提交成功后我们将立即发送“下载与体验”的资料，并将于1-3个工作日与您联系
