### ISSUE TITLE
【KeepWork.com】增加下载Paracraft入口

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3901]
背景：
【KeepWork.com】增加下载Paracraft入口，让下载入口没那么隐蔽

解决方案：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/27bbd08e-0d41-4725-9500-829ead621bdd)

**Comment by dalin00** [comment]
![首页-加下载按纽-未登录](https://user-images.githubusercontent.com/24222876/55767897-51385880-5aad-11e9-87f6-39328fa4ffbe.jpg)
![首页-加下载按纽-已登录](https://user-images.githubusercontent.com/24222876/55767912-5c8b8400-5aad-11e9-922d-04457047ba76.jpg)

登录后，“下载Paracraft" 按纽自适应上移到”免费加入“按纽的位置
