### ISSUE TITLE
【Bug-editor】当用户正在绘图板里进行输入时，自动保存功能应该不启用，目前会启用，导致编写的内容丢失

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3903]
## The problem
当用户正在绘图板里进行输入时，自动保存功能应该不启用，目前会启用，导致编写的内容丢失

## Environment
* OS Info: Window10
* browser Info: chrome   72.0.3626.121 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  editor->board mod

## Step To Reproduce Issue [ Good To Have ]
* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入编辑器页面，创建一个新页面A，然后添加board
2.给board添加图形后，添加text文本说明，输入中文内容，观察页面是否会自动保存

* Expected Result:
1.当存在输入时，页面处于活跃状态，就不会自动进行保存
* Actual Result:
1.连续输入英文状态下，不会自动保存，但输入中文就会自动保存，导致写的内容出现偏差
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/8be5cae2-b1c0-48cb-8466-0d49cd786ddd)

**Comment by onedou** [comment]
现在情况是英文输入法也会自动保存，但是如果在中文输入下，无法做到时间捕获。英文输入已经修复

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/54007490-05884b80-419d-11e9-9c28-3b539f832295.png)
可以用这两个时间捕获中文输入法事件，但是不是每个浏览器都兼容

**Comment by Sandu1213** [comment]
目前处理了英文输入法连续输入自动保存的问题，中文输入法暂时没有处理，请知悉。
stage环境验证通过。

**Comment by Sandu1213** [comment]
@onedou  big，请将自动保存功能停用，目前自动保存已经验证影响到使用了，请知悉。(已和产品进行沟通确认)

**Comment by Sandu1213** [comment]
目前自动保存功能已移除，请知悉。（stage环境验证通过）
