### ISSUE TITLE
【Education-机构】登录页面

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3905]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/283501e0-9247-48d5-b994-ca5aa5c7965a)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/54897759-b3695900-4f04-11e9-83b6-fe5d9a60d006.png)

**Comment by leopoldchen** [comment]
是否需要有注册流程？ @shirleyluo1130

**Comment by shirleyluo1130** [comment]
补充：
机构登录页面，加下 “注册”  和  “忘记密码”  的入口，如下（UI补充设计中）：
![image](https://user-images.githubusercontent.com/40385277/54977995-e893ab00-4fd9-11e9-8f00-99e4c67af813.png)

点击“去注册”，新窗口打开“注册”页面：
![image](https://user-images.githubusercontent.com/40385277/54978089-33adbe00-4fda-11e9-828a-aba5ec54e09f.png)

点击“忘记密码”，新窗口打开“重置密码”页面：
![image](https://user-images.githubusercontent.com/40385277/54978125-52ac5000-4fda-11e9-9561-b9ba35e29b53.png)

**Comment by shirleyluo1130** [comment]
UI见：
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/a60cdf0e-b76a-44e2-8c73-e97ca2213fbe)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/ae6bb0eb-0dca-42ec-9654-3449e6827b0e)
