### ISSUE TITLE
【Education-机构】机构管理员身份-设置

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3908]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/a9763c23-4a5c-44c5-8b69-88be220653e5)

**Comment by Sandu1213** [comment]
已调整为如下实现：
![image](https://user-images.githubusercontent.com/21214285/54899317-5d97af80-4f0a-11e9-8a49-c63a84c84e34.png)

具体功能验证，待教师端实现后验证
