### ISSUE TITLE
【Education-机构】教师身份-上课

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3909]
[Uploading... image.png ]

**Comment by Sandu1213** [comment]
1.已上课的课程，切出课程之外后，再切回去无法继续上课
![image](https://user-images.githubusercontent.com/21214285/54978134-56d86d80-4fda-11e9-8b32-01895327fbff.png)

2.同一课程在不同课程包里的记录状态不合理
![image](https://user-images.githubusercontent.com/21214285/54978232-a4ed7100-4fda-11e9-8bc1-6132faaad44b.png)

**Comment by wxaxiaoyao** [comment]
课程是否已,之前逻辑就这是这样, 若有需求变更先给产品, 补充原型说明. 补好后知会开发, 开发或修复
