### ISSUE TITLE
【Education-机构】教师身份-我的班级

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3913]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/e42faa87-986b-4190-a733-da423e307113)

**Comment by Sandu1213** [comment]
缺少编辑功能，是允许编辑的。
![image](https://user-images.githubusercontent.com/21214285/54985864-9b6d0480-4fec-11e9-8924-9012d8cae918.png)
