### ISSUE TITLE
【Education-机构】学生身份-主页

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#3914]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/667e851f-1efc-437e-9d20-bc0f7d0b4c51)

**Comment by shirleyluo1130** [comment]
显示正在上课的课堂信息时，补充显示课堂ID，如下

![image](https://user-images.githubusercontent.com/40385277/54575129-df309e80-4a2d-11e9-81d8-7af0dec32a6d.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/54985380-aa06ec00-4feb-11e9-9b34-fd8114740da3.png)
