### ISSUE TITLE
【Paracraft.cn】Paracraft.cn提交表单后在dashboard中可以看到已提交的数据

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3922]
背景：
Paracraft设计官网，方便市场推广，to b客户能了解我们产品更多些。
客户在官网上提交表单后，可以在后台中看到数据，并提供给市场人员进行联系。

解决方案：
在dashboard中“机构管理”类别中，新增“机构基本信息”页面，功能如下图：
![image](https://user-images.githubusercontent.com/39363297/54171303-d7647d80-44b4-11e9-8cdf-25a43f1217a4.png)

后台地址：http://dashboard.keepwork.com/#/projects/projectsManage

**Comment by Sandu1213** [comment]
待前端paracraft.cn 页面出来后验证，目前Dashboard stage环境已经存在相关统计

**Comment by Sandu1213** [comment]
stage环境验证通过

**Comment by Kvaya** [comment]
建议：
1.后台中“机构申请”更名为“合作申请”；
2.列表中“电话”更名为“联系手机”；
3.列表中“备注”更名为“描述”

**Comment by Kvaya** [comment]
在https://biz.keepwork.com/上提交的表单后的数据需存储在http://dashboard.keepwork.com 的“合作申请”那一页
