### ISSUE TITLE
【Paracraft.cn】官网首页设计跟进

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3954]
背景：
Paracraft设计官网，方便市场推广，to b客户能了解我们产品更多些。
之前首页设计基本修改了，还有些细节调整

后续细节调整：
https://note.youdao.com/ynoteshare1/index.html?id=c814ccd314ebf467806418f82d4ab460&type=note

**Comment by Kvaya** [comment]
跟进（#3813）

**Comment by Kvaya** [comment]
优化跟进：
http://note.youdao.com/noteshare?id=5cd76c9a6cac6b3df541c44fd768f4cd

**Comment by dalin00** [comment]
![pracraft网站-道页](https://user-images.githubusercontent.com/24222876/55214186-d2335c80-5230-11e9-9c63-5b81b61c4e34.jpg)

如果有些地方与 线上有差异，以线上为准

**Comment by Kvaya** [comment]
计算器优化：
![image](https://user-images.githubusercontent.com/39363297/55219502-05311c80-5240-11e9-8376-997c91fc58a4.png)

**Comment by Kvaya** [comment]
首页优化跟进：
https://note.youdao.com/ynoteshare1/index.html?id=f46fd60099e837087e8c4c0fa690d753&type=note

**Comment by Kvaya** [comment]
优化跟进：
http://note.youdao.com/noteshare?id=c4df3f756014765ef68caf1ea2271a70

**Comment by Kvaya** [comment]
未解决的详细：
1.手机判断需判断：1）手机号是否为空？2）手机号格式是否正确？
2. http://biz.keepwork.com/ceo_letter 中点击《Paracraft编程入门》后跳转至http://cdn.keepwork.com/paracraft/book/paracraft_book_sample.pdf，浏览器链接显示少了“http://”；
3.“用户作品欣赏”处：鼠标mouse over单个作品时，单个作品整个卡片会整体放大一些些
4.底部导航栏“宣传页下载”后的文件名需是：paracraft_biz_brochure.pdf；
5.“我们的教学成果”处“使用Paracraft开发的《魔法哈奇》注册用户500万”文案改成“使用Paracraft开发的《魔法哈奇》注册用户超过500万”；
6.“我们的优势”处“丰富的师资培训方案”中“支持学长制，导师制，课堂教学等多种模式，提升PBL项目式学习效率”应改成：支持学长制、导师制、课堂教学等多种模式，提升PBL项目式学习效率；
7.
![image](https://user-images.githubusercontent.com/39363297/55449749-5570fb80-55ff-11e9-9f57-65c97b09e55a.png)

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/55455600-dbe50780-5616-11e9-998b-863f663673d6.png)
这个没毛病

**Comment by Kvaya** [comment]
3.“用户作品欣赏”处：鼠标mouse over单个作品时，单个作品整个卡片会整体放大一些些

这个mouse over时，加了阴影，放大可不做

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/55457459-83b10400-561c-11e9-89f2-336937dbd626.png)
这个w我改不了，这个代码不在我这边，
