### ISSUE TITLE
【Paracraft.cn】在线计算器设计

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3955]
背景：
在官网中课程服务处有相关的人数和金额提供，提供在线计算器，让客户可估算成本，进一步达成咨询合作。

课程服务价格明细：
我们按照学生数目收取年费
1. 5人以内免费
2. 学生数量100以内，单个学生费用2000元/年
3. 学生数量100到500之间，新加入的学生费用为1800元/年
4. 学生数量大于500，新加入的学生费用为1500元/年

计算公式：
试学账号5个：免费
学生数量（0-100）单个学生费用2000元/年 （2000N）
学生数量（100-500）新加入学生费用为1800元/年 （20万 + 1800*（N-100））
学生数量（> 500） 新加入学生费用为1500元/年 （92万+ 1500*(N-500)）

计算器参考建议：
计算器可以用http://element.eleme.io/#/zh-CN/component/slider 组件做；
效果可以参考https://www.upyun.com/pricing 这样的排版布局来

价格计算器方案：
![image](https://user-images.githubusercontent.com/39363297/55322431-ed130480-54ae-11e9-9f00-adb8a4854468.png)

**Comment by Kvaya** [comment]
设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/54978719-1ed22a00-4fdc-11e9-8eb5-8448a1098ac9.png)
计算器设计稿在"首页.psd"源文件里面

**Comment by Kvaya** [comment]
（#3813）跟进

**Comment by Sandu1213** [comment]
人数应该没有上限的，请确认

**Comment by Sandu1213** [comment]
功能已验证通过
