### ISSUE TITLE
【Paracraft.cn】官网手机端适配跟进

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#3963]
背景：
Paracraft设计官网，方便市场推广，to b客户能了解我们产品更多些。
手机端适配之前已更改了很多，还有些细节需调整

后续细节调整：
https://note.youdao.com/ynoteshare1/index.html?id=02dee9fe538fd08a7661f6b703887e5b&type=note

**Comment by Sandu1213** [comment]
价格预算在小屏手机上展示不合理
![image](https://user-images.githubusercontent.com/21214285/55228530-4a137e00-5255-11e9-9d77-e920adca1dbc.png)
