### ISSUE TITLE
【Bug-mod】imgloop mod添加多个后，数据会出现混乱的情况，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#398]
## The problem
imgloop mod添加多个后，数据会出现混乱的情况，请调整

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor ->mod

## Step To Reproduce Issue [ Good To Have ]
* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.添加多个imgloop mod，分别在mod 里设置不同的图片地址信息，观察设置是否成功

* Expected Result:
1.可以设置成功
* Actual Result:
1.设置存在问题，数据共享了，会出现混乱的情况

**Comment by duting1993** [comment]
stage已验证
