### ISSUE TITLE
【Bug-机构】学生页面缺少的功能，请补充

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3981]
## The problem
学生页面缺少的功能，请补充

## Environment
* OS Info: Window10
* browser Info: chrome    73.0.3683.86
* URL: [机构地址](https://release.keepwork.com/org/growth) 
* Model: 机构学生页面

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.可正常登录机构页面
2.存在学生的账号

* Details:
1.学生登录机构页面后，选择课程进行自学，观察是否存在快速进入下一课的入口
2.学习完成后，技能点是否存在统计

* Expected Result:
1.存在快速进入下一课的入口
2.技能点有正确的统计

* Actual Result:
1.缺少相应功能

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/3aed16c0-d5d3-4520-80ce-fcba8cc0bfdf)

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/55383199-2eacb980-555a-11e9-9366-31ffc71ea608.png)
