### ISSUE TITLE
【Bug-机构】学生进入课堂时及教师端学生状态下统计的学生姓名显示不对

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3984]
## The problem
学生进入课堂时及教师端学生状态下统计的学生姓名显示不对

## Environment
* OS Info: Window10
* browser Info: chrome    73.0.3683.86
* URL: [机构地址](https://release.keepwork.com/org/growth) 
* Model: 机构学生页面及机构教师页面

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.可正常登录机构页面
2.存在学生和教师的账号

* Details:
1.教师A给班级A的学生开启了课程A，课堂ID为C000001
2.通过课堂ID进行学习，观察学生端及教师端学生状态下的学生姓名显示情况

* Expected Result:
1.姓名显示正确

* Actual Result:
1.姓名显示不对

## Attachments (eg:logs/video/screenshot)
![image](https://user-images.githubusercontent.com/21214285/55150090-65638800-5186-11e9-911c-27bc8beec588.png)

**Comment by kevinxft** [comment]
好的，雪梨

**Comment by Sandu1213** [comment]
🤣

**Comment by Sandu1213** [comment]
guys,你漏了学生端的处理。
![image](https://user-images.githubusercontent.com/21214285/55314770-728db900-549d-11e9-8c03-bbe23bec9c11.png)
