### ISSUE TITLE
【Bug-机构】教师端数据统计问题

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#3986]
## The problem
教师端数据统计问题

## Environment
* OS Info: Window10
* browser Info: chrome    73.0.3683.86
* URL: [机构地址](https://release.keepwork.com/org/growth) 
* Model: 机构教师页面

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.可正常登录机构页面
2.存在教师的账号

* Details:
1.教师A同时拥有2个班的授课权，但只有A班进行了授课，B班没有授课
2.进入数据统计里，按班级查看授课情况

* Expected Result:
1.授课情况统计正确

* Actual Result:
1.授课情况统计不对

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/f62c71ee-6e68-406c-b1ec-2f90c40859bd)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/55306872-4fa4da00-5488-11e9-8c96-7019bdb0ea65.png)

**Comment by Sandu1213** [comment]
排序与图标的对应反了，请再调整下

**Comment by DDXY1230** [comment]
图标箭头指向最新上课时间，不对吗

**Comment by DDXY1230** [comment]
已改，箭头指向最旧的上课时间
