### ISSUE TITLE
【Education-机构】需求调整：同一个机构，一个用户可以属于多个身份：管理员、教师、学生。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4015]
同一个机构，一个用户可以属于多个身份：管理员、教师、学生。

需对应调整的页面：

1、机构url登录页：增加身份选择

2、管理员-班级信息管理：取消“同一个机构，一个用户只能属于一种身份”的限制

3、教师-我的班级：取消“同一个机构，一个用户只能属于一种身份”的限制

**Comment by leopoldchen** [comment]
@shirleyluo1130 进入机构的时候是否可以选身份？选了身份后是否可以切换？

**Comment by shirleyluo1130** [comment]
1、机构url登录页，可以选择身份：
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/a77dadfb-1741-4351-9f8a-11e8219c04c9)

2、登录进入后，不需要进行身份切换。

**Comment by Sandu1213** [comment]
1.学生身份查看课程包进行自学时，会跳转到管理员的页面
2.教师端对学生或者自身进行添加操作时，出现校验失败的情况
3.学生端查看课堂总结的分享时，显示内容不对
4.
