### ISSUE TITLE
【Bug-机构】教师端下课后，在学生状态与学习总结里切换，会导致进度条显示不对

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4030]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/de4dc084-627b-4f27-8b11-7fcba0903bf6)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/93c4c99d-2d1a-409f-be54-7e5d377323da)

**Comment by shirleyluo1130** [comment]
当前下课后，显示为：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/9be3c145-6b7b-4cb8-8c15-02d98514cee5)

建议按如下显示：
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/f8755096-9c61-4ce8-8f7e-787840b93cf3)
