### ISSUE TITLE
【bug-机构】学生的课程详情页，如下图，

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4047]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/8860322f-0fa7-4567-a53d-19d05f47f21d)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/3a03d630-ed98-4a7d-9a4e-4ee7ce0a65ef)

**Comment by Sandu1213** [comment]
已调整
