### ISSUE TITLE
【Bug-机构】教师端上课记录里最近上课时间统计不对，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4066]
## The problem
教师端上课记录里最近上课时间统计不对，请调整

## Environment
* OS Info: Window10
* browser Info: chrome    73.0.3683.86
* URL: [机构地址](https://release.keepwork.com/org/news) 
* Model: 机构学生页面及机构教师页面

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.可正常登录机构页面
2.存在学生和教师的账号

* Details:
1.教师分别对两个不同的课程包进行上课且上课多次，观察最近上课时间是否记录正确

* Expected Result:
1.最近上课时间记录正确

* Actual Result:
1.最近上课时间记录有误

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/ddfdaa34-c25d-4dda-813c-25c7b0684411)

**Comment by Sandu1213** [comment]
时间只能记录一次，后面缺少更新，请调整

**Comment by wxaxiaoyao** [comment]
fixed
