### ISSUE TITLE
【Paracraft.cn】官网提交表单后立即给提交表单者发一份邮件，邮件内容更改

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4071]
**背景：**
![image](https://user-images.githubusercontent.com/39363297/55457849-ca532e00-561d-11e9-9a8c-b7657fc70ed4.png)

### 解决方案：
_**邮件内容**_
您好！
 
我是Paracraft的作者李西峙。谢谢您对Paracraft的兴趣！
 
我们已经收到了您填写的信息，我们的工作人员会尽快跟您联系。

很感谢您选择Paracraft，获取更多素材请访问这里链接： 
https://biz.keepwork.com/ceo_letter?name=%E9%A9%AC%E5%B0%8F%E5%A7%90

1989年，7岁的我照着一本我父亲给我的书编写了我人生中第一个程序，并从此喜欢上了编程，小学期间我完成了大量个人作品，到了随心所欲的状态。通过Paracraft，我希望带给孩子们同我相似的学习体验。

期间您有任何技术问题也可以直接Email我 。

李西峙 
CEO & NPL语言和Paracraft创始人
lixizhi@paraengine.com

_**https://biz.keepwork.com/ceo_letter 内容**_
您好！
 
我是Paracraft的作者李西峙。谢谢您对Paracraft的兴趣！
 
我们已经收到了您填写的信息，我们的工作人员会尽快跟您联系。

1989年，7岁的我照着一本我父亲给我的书编写了我人生中第一个程序，并从此喜欢上了编程，小学期间我完成了大量个人作品，到了随心所欲的状态。通过Paracraft，我希望带给孩子们同我相似的学习体验。

期间您有任何技术问题也可以直接Email我 。

李西峙 
CEO & NPL语言和Paracraft创始人
lixizhi@paraengine.com

通过下面链接了解Paracraft：
•下载Paracraft： 推荐Windows版本
•《Paracraft编程入门》 ：预览版 PDF文档

**Comment by Kvaya** [comment]
其中：https://biz.keepwork.com/ceo_letter 内容，以下内容还是点击后跳转至原来的链接，UI效果一样

•下载Paracraft： 推荐Windows版本
•《Paracraft编程入门》 ：预览版 PDF文档

**Comment by Sandu1213** [comment]
这个漏了
![image](https://user-images.githubusercontent.com/21214285/55544567-f04fff80-56fd-11e9-89ad-f865af9c7786.png)

**Comment by Kvaya** [comment]
邮件和letter中内容中，“您好！”二字前加“提交表单者姓名”
