### ISSUE TITLE
【keepwork.com】中允许个人删除个人创建的项目

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4074]
背景：
现个人创建的项目不能被删除，添加“删除”功能是删除误建的项目

解决方案：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/356b92c8-f165-440f-a553-71964f04b79c)

补充：
当前项目只能是个人创建的才能被删除，否则不能被删除；
当前项目被删除后，跳转至首页

**Comment by dalin00** [comment]
![image](https://user-images.githubusercontent.com/24222876/55775956-b00dca00-5acd-11e9-8d8e-be4333caa820.png)

**Comment by Sandu1213** [comment]
- 问题1：i18n翻译问题
![image](https://user-images.githubusercontent.com/21214285/55860509-fb47db80-5ba6-11e9-9059-833fa628c5db.png)

- 问题2：每次删除完成后，总是先出现个人主页，在返回到主页（请去掉出现个人主页的跳转）

- 问题3：后台需要将无用的数据进行释放  @wxaxiaoyao 请调整一下，谢谢
![image](https://user-images.githubusercontent.com/21214285/55861274-95f4ea00-5ba8-11e9-988b-dbd60dec8fad.png)

**Comment by wxaxiaoyao** [comment]
已添加删除
