### ISSUE TITLE
【dashboard】中“机构申请”中增加管理员可对提交表单者的备注等操作

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4076]
@Kvaya commented on [Wed Apr 03 2019](https://github.com/tatfook/KeepWorkDesgin/issues/108)

背景：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/82e82d87-5e60-4810-b72b-b315c0ddc6df)

解决方案：
![image](https://user-images.githubusercontent.com/39363297/55527151-5cb10b80-56ca-11e9-9e30-a5c4a823e9a5.png)

**Comment by kevinxft** [comment]
@Kvaya 产品大大，后台管理是不是少了个地区的显示

**Comment by Sandu1213** [comment]
stage和release环境都不行

**Comment by Kvaya** [comment]
1.“标签”字眼变为“状态”;
2.编辑弹窗页中状态显示中：去掉“还没有”；
3.列表中“状态”那栏中，默认显示为空
