### ISSUE TITLE
PAC大赛-填写报名信息

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#408]
![5-](https://user-images.githubusercontent.com/38035998/39618737-ad9944ce-4fb7-11e8-8f12-8c3457af7530.png)

**Comment by Sandu1213** [comment]
目前的真实效果图：
![image](https://user-images.githubusercontent.com/21214285/40160215-35dd69a6-59df-11e8-9cba-6225a1781ff9.png)
