### ISSUE TITLE
【Bug-Dashboard】新增课程包时，选择用户耗时较长，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4099]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/7d925c75-9c2d-4d44-921a-3f8cbc72eded)

**Comment by Sandu1213** [comment]
Dashboard主要是内部人员使用，该问题可以稍后再调整。(调整的时候请一次调整到位)
![image](https://user-images.githubusercontent.com/21214285/55855305-c08b7680-5b99-11e9-8ee7-60cc5fb755c4.png)

**Comment by kevinxft** [comment]
测试前先清下缓存，release和master我都测过
