### ISSUE TITLE
前端 API Service 封装

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#41]
1. 后端API方法封装
* 保证在组件中的调用是基于service方法，而不是基于http 
* 拒绝回调地狱，使用async await
2. 测试
3. 文档

**Comment by leopoldchen** [comment]
需总结并制定流程规范

**Comment by onedou** [comment]
- [ ] user
- [ ] gitlab
- [ ]  comment
- [ ] elasticsearch
- [ ] qiniu

**Comment by Sandu1213** [comment]
@yuanoook 请确认一下，如果都完成了，请直接移到Release Queue，后续统一关闭
