### ISSUE TITLE
PAC大赛-用户已上传的作品

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#411]
1.我的作品-空
2.我的作品
![7-](https://user-images.githubusercontent.com/38035998/39619650-37709780-4fbb-11e8-8161-f216d1f01afa.png)

**Comment by ZhangKaitlyn** [comment]
新UI图 
![image](https://user-images.githubusercontent.com/18642919/40094089-8ad670e4-58f7-11e8-8249-5cfe8f0975b9.png)

**Comment by Sandu1213** [comment]
接口已经验证，待前端界面完成后再验证

**Comment by ZhangKaitlyn** [comment]
测试地址：http://iicc.stage.keepwork.com/#/mywork
