### ISSUE TITLE
调整：keepwork官网上项目封面时视频类的显示效果

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4113]
背景：
![image](https://user-images.githubusercontent.com/39363297/55716870-9e271b00-5a2a-11e9-9080-e0081ede0b6b.png)

在探索页面上，视频类的项目封面UI效果不佳，及点击该封面，并未在当前页播放视频，显示播放条、全屏等并未起到作用

解决方案：
1.在“首页、探索页、个人主页”页面中显示视频类的项目封面，封面上显示：视频播放按钮+播放时长+视频的第一帧，这三元素标明是视频类的封面，播放时长是让用户在播放视频前提前知道该视频的时长，增加可预见性；

2.项目主页中，视频类的项目封面保持现有情况；
不过从“首页、探索页、个人主页”这些页面点击项目封面后，进入项目主页中，视频是自动播放，而不是暂停状态

**Comment by dalin00** [comment]
![image](https://user-images.githubusercontent.com/24222876/55779231-7e016580-5ad7-11e9-8a00-a90be059be6f.png)

**Comment by Kvaya** [comment]
Issue moved to [tatfook/KeepWorkDesgin #109](https://github.com/tatfook/KeepWorkDesgin/issues/109) via [**ZenHub**](https://www.zenhub.com/)
