### ISSUE TITLE
PAC大赛-参赛作品

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#412]
![2- 1](https://user-images.githubusercontent.com/38035998/39619844-c9e34978-4fbb-11e8-90a9-56f6f73191ee.png)

**Comment by ZhangKaitlyn** [comment]
新的UI图：
![default](https://user-images.githubusercontent.com/18642919/40338279-c22e035a-5da6-11e8-8a2e-166b085c9989.png)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://iicc.stage.keepwork.com/#/all

**Comment by Sandu1213** [comment]
待补充不同类型的数据后再进行筛选验证
