### ISSUE TITLE
【Keepwork学习页重构】导航

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4132]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/21cb2914-bd2f-4a52-a4bd-6f75781a046c)

**Comment by duting1993** [comment]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/00f85159-6a63-4fc5-9c90-4e3988639a41)
