### ISSUE TITLE
【Keepwork学习页重构】主页

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4133]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/8ef01df8-8fbf-4a5f-9e18-55325d9df447)

**Comment by duting1993** [comment]
学习主页与设计图不符
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/2ac8e2ef-b7f7-4853-8dba-4857282cfe39)
