### ISSUE TITLE
【Keepwork学习页重构】课程

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4135]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/642f7c76-9157-479a-bed6-e982aeef1c11)

**Comment by duting1993** [comment]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/d50f4499-7683-4d41-9b64-f87fa24a49ee)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/56339755-12f41500-61e2-11e9-8fbf-af0d1764ed15.png)
