### ISSUE TITLE
【Keepwork学习页重构】Dashboard-课程标签管理

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4140]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/d2bf0545-6531-42c8-b9aa-5ec7a360ce52)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/56106509-0d919300-5f74-11e9-8273-04b511e58859.png)

**Comment by kevinxft** [comment]
带不上，么得办法
