### ISSUE TITLE
【Keepwork学习页重构】Dashboard-课程包：增加设置课程标签的功能

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4141]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/51d4d19c-61f6-4e28-8550-ed975933b8a0)

**Comment by kevinxft** [comment]
暂时无法做到根据课程标签筛选

**Comment by Sandu1213** [comment]
- 过滤问题
![image](https://user-images.githubusercontent.com/21214285/56106447-c1465300-5f73-11e9-9297-61acbddc1def.png)

- 排版问题
![image](https://user-images.githubusercontent.com/21214285/56106463-d58a5000-5f73-11e9-97c7-d04e78164307.png)

-

**Comment by kevinxft** [comment]
这些都不是问题，特别是排序，无法做到，过滤那个更不用说了，匹配到就不错了，要啥自行车

**Comment by Sandu1213** [comment]
价格相关后台保留，请补上
![image](https://user-images.githubusercontent.com/21214285/56178043-4fcdd980-6033-11e9-84ae-42217eb105e8.png)

**Comment by Sandu1213** [comment]
过滤问题及标签排版问题暂时忽略
