### ISSUE TITLE
【Bug-机构】管理员页面课程包信息显示不合理，请调整 (Hot Fix)

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4162]
## The problem
管理员页面课程包信息显示不合理，请调整

## Environment
* OS Info: Window10
* browser Info: chrome    73.0.3683.86
* URL: [机构地址](https://keepwork.com/org/visit) 
* Model: 机构管理员页面

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.可正常登录机构页面
2.机构管理员页面

* Details:
1.管理员登录成功后，进入课程包管理页面，对课程信息进行查看‘
’
* Expected Result:
1.可以正常查看课程内容信息

* Actual Result:
1.课程包内容丢失了

## Attachments (eg:logs/video/screenshot)

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/c11f3418-dfa8-4b5e-8c82-b53a81dbce9a)

**Comment by wxaxiaoyao** [comment]
前置条件:
 存在机构A, 管理员UserA,  机构引用课程包PA
测试步骤:
1 使用管理员登录机构, 查看机构课程包PA
2. 删除课程包PA, 使用管理员进入机构查看课程包PA
期望结果:
1 课程包PA正常显示
2 机构其它课程包正常显示  并且不存在PA课程包
实际结果:
1 课程包PA正常显示  符合期望值 
2 页面崩溃  不符合期望值

**Comment by wxaxiaoyao** [comment]
fixed: 删除课程包同时会删除课程包相关引用
