### ISSUE TITLE
【bug】keepwork 探索页网页类别中，搜索关键词后，会有相同结果的项

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4168]
问题：
在keepwork 探索页网页类别中，搜索关键词后，比如：paracraft，会有相同结果的项：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/47a95b69-2275-42fb-a1bc-d87a63da464f)
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/504bff2c-3234-46a7-a817-693283051b3d)

期望：
确保搜索出来的结果，相同链接的结果项是唯一的。

**Comment by William0911** [comment]
推断是official这个帐号内的某些老旧问题，已跑脚本修复

**Comment by Sandu1213** [comment]
keepwork上目前验证都是唯一的
