### ISSUE TITLE
keepwrok官网增加下载入口

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4173]
背景：
paracraft软件增加下载入口，明显些，让用户随时都可以找到下载入口

解决方案：
![ZK5T(E$Y0Z~A)O Q6HN~3YJ](https://user-images.githubusercontent.com/39363297/56032480-dee9a180-5d54-11e9-993f-299e2b74db95.jpg)

**Comment by enya-i** [comment]
![image](https://user-images.githubusercontent.com/37529364/56270128-03b09100-6128-11e9-92eb-8d9b70351c73.png)
![image](https://user-images.githubusercontent.com/37529364/56270156-0f03bc80-6128-11e9-9949-a6415c27cf78.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/56334479-057f6080-61cb-11e9-98d2-a520b0202501.png)
