### ISSUE TITLE
【Bug-mod】imgloop mod,将默认图片全部移除后进行保存，反正轮播里还是存在图片

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#419]
## The problem
imgloop mod,将默认图片全部移除后进行保存，反正轮播里还是存在图片

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor ->mod

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor页面后，添加imgloop mod，添加成功后，将默认图片都删掉后进行保存，然后在新页面进行打开查看

* Expected Result:
1.页面没有轮播图
* Actual Result:
1.页面还是会存在默认的图片
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/23e1f88f-466e-4a9e-aac5-31fc2cc398d1)

**Comment by duting1993** [comment]
stage验证通过
