### ISSUE TITLE
ADI mod重构

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#42]
1. 遵循新的规范书写

* 基础组件与mod分离
* 使用栅栏式布局
* 使用jss
* 保证代码简洁

**Comment by onedou** [comment]
- [] ModHeader 
- [] ModTitle 
- [] ModBoard 
- [] ModImgLoop 
- [] ModText 
- [] ModParacraft 
- [] ModQQ 
- [] ModMixPosition 
- [] ModVipRead 
- [] ModComment

**Comment by leopoldchen** [comment]
- [ ] TOC Mod
