### ISSUE TITLE
【bug】学习-我创建的课程-点击课程名称，提示未创建网页，创建过后，保存，在点击该课程名称，还是提示，未创建网页内容

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#4207]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/1e9524a9-de06-4d85-8340-f0988bd1f30f)
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/436a035a-91fd-4485-9ee1-513dd4f8fbdf)

**Comment by DDXY1230** [comment]
stage环境
