### ISSUE TITLE
【Bug-Board mod】Board mod创建时，需要去掉一些不必要的请求链接，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4216]
## The problem
Board mod创建时，需要去掉一些不必要的请求链接，请调整

## Environment
* OS Info: Window10
* browser Info: chrome    73.0.3683.86
* URL: [stage.keepwork.com](https://stage.keepwork.com) 
* Model:  editor ->mod

## Step To Reproduce Issue [ Good To Have ]
* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入编辑器，选择board mod进行添加操作，观察新增是否可以成功

* Expected Result:
1.新增成功，请求正确
* Actual Result:
1.存在不合理的请求
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/0d6fb546-4d18-4637-b944-2f21a0686b5b)

**Comment by ZhangKaitlyn** [comment]
需要去除这7个请求
![image](https://user-images.githubusercontent.com/18642919/56653069-71783200-66bf-11e9-9499-9eeee2bd2be9.png)

**Comment by Sandu1213** [comment]
stage环境验证通过
