### ISSUE TITLE
【Bug-default link】早期的默认链接清理不完整，默认没显示，但点击后还是跳转到“keepwork"页了。

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#423]
## The problem
早期的默认链接清理不完整，默认没显示，但点击后还是跳转到“keepwork"页了。

## Environment
* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor ->mod

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor页面后，分别添加不同的mod，mod的属性里不设置链接地址
2.新页面打开已经添加的mod，观察是否会进行跳转

* Expected Result:
1.不会跳转，与实际设置的情况一致  
* Actual Result:
1.会进行跳转，设置为空，与设置不符  （涉及mod: img mod/imgloop/title 等，请一同排查）

**Comment by duting1993** [comment]
stage已验证
