### ISSUE TITLE
【Education-机构功能优化一】管理员端-学生邀请码管理：生成邀请码、打印邀请码

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4256]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/80fb94e5-02c4-4bd0-ab14-5d5358b275ee)

**Comment by shirleyluo1130** [comment]
@DDXY1230   “打印邀请码”页面的UI需要再加工下，定稿后会在这里回复。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/ade25aae-0762-4bd7-82bc-4e5291bd4a67)

**Comment by DDXY1230** [comment]
打印功能等定稿后再做，我已经单独建了一个issue，#4274
