### ISSUE TITLE
【Education-机构功能优化一】Paracraft客户端支持匿名Class ID，详情见

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4258]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/14da7c78-9d0a-4dbb-9c71-9af8baf294d6)

**Comment by Sandu1213** [comment]
目前存在的问题：
1.会出现正确的课堂ID判断有误的情况
![image](https://user-images.githubusercontent.com/21214285/56893321-d9aa8780-6ab4-11e9-9d60-1c719b56f8c2.png)

2.从客户端里再次加载同一个课堂会概率出现习题内容无法显示的情况
![image](https://user-images.githubusercontent.com/21214285/56893345-f9da4680-6ab4-11e9-8542-415729986a7e.png)
