### ISSUE TITLE
【bug】editor中历史版本功能页面中，一些功能mouse over不显示或显示效果跟整体UI不一致

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4259]
问题：
历史版本页面中，一些功能mouse over不显示或显示效果跟整体UI不一致；

解决方案：
1.所有mouse over效果统一为![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/edf8a6b5-1433-4ca6-800b-c931f97a8308)这样的效果；
2.
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/e97ed7d5-cffe-4b1b-b448-de6c1c7c8663)mouse over时显示为：恢复到此版本；

3.
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/a0862373-42c0-48b0-85ed-1ca15498b707)
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/18b73ea5-3739-435e-858d-9acdfe09fc69)
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/4fd89c12-eae1-487b-a462-0cfb4d30e563)
这三者mouse over显示如图

**Comment by Kvaya** [comment]
英文环境下，各英文翻译：
历史版本 Old versions 
恢复到此版本 Recover this version 
vXX来自vXX恢复  vXX recovered from vXX
仅显示预览  Show preview only
同时显示  Show both
仅显示代码  Show code only

**Comment by Sandu1213** [comment]
stage环境验证通过
