### ISSUE TITLE
【bug】窗口缩小后，keepwork导航的 搜索框  被覆盖了。如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4261]
PC上，把窗口缩小后，长这样：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/24c7e633-be94-446f-ae7a-3ae8aed16f51)

**Comment by ZhangKaitlyn** [comment]
![SW5}$()KCH`L1G19XCMEFC5](https://user-images.githubusercontent.com/18642919/56861430-3a619380-69d3-11e9-82ec-71db2877194d.png)

**Comment by Sandu1213** [comment]
release环境验证通过
