### ISSUE TITLE
【dashboard】权限管理，新增对市场角色的权限发放

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4269]
背景：
现市场人员能对dashboard的部分页面进行访问，并可对访问的页面中的一些功能进行操作。

期望：
市场人员能对dashboard的部分页面进行访问并可操作，而有的页面禁止访问，确保数据得到最大限度的安全保障。

解决方案：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/ea2a7fd8-83d8-4514-b165-4a980878f782)

补充：
原稿地址：
![image](https://user-images.githubusercontent.com/39363297/56779110-07b96e80-680c-11e9-990c-58df45973754.png)

**Comment by Kvaya** [comment]
补充：后台用户头像下的“管理员”页面禁止“市场人员”角色访问

**Comment by Sandu1213** [comment]
stage环境验证通过
