### ISSUE TITLE
邀请码打印

### ISSUE THREAD

**Issue by DDXY1230** [tatfook/keepwork#4274]
管理员端学生邀请码打印

**Comment by shirleyluo1130** [comment]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/0003d91d-9146-4631-bc47-0cb42ef40d80)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/56879183-14e39100-6a8a-11e9-8fea-d3d4794f8ed7.png)
