### ISSUE TITLE
【Bug-editor】目前必须修改主区域才能触发保存，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#428]
问题描述：
设置layout后，如果修改的是非main区域，则会出现修改的内容无法保存的情况，请调整优化  
[image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/18977329-c8
f9-4068-a5b8-0a39431d23b2)

**Comment by leopoldchen** [comment]
@azothli 
这个需要调整交互

**Comment by azothli** [comment]
1.当前区域有变动就应该允许保存
2.在进行layout编辑区域切换的时候触发自动保存

**Comment by duting1993** [comment]
stage已验证
