### ISSUE TITLE
【Education-机构功能优化一】从客户端进入课堂学习，在world页，点击“课程内容查看”按钮时，需加一个无查看权限的页面。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4282]
从客户端进入课堂，现在都可以进入世界。只是在查看课程内容时，区分是否有权限。

若无查看权限，则提示需向机构购买，参考自学时无查看权限的处理方式。

注：页面上需显示对应的课堂ID信息。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/ebc152bd-327c-412e-86c8-cd897e2e7416)

**Comment by kevinxft** [comment]
- 页面采用自学页面
在这基础上会多个弹框提示
- 1.课堂id正确但不是该班级的学 ->  提示不是该班级学生
- 1.课堂id错误的情况下 -> 提示班级不存在

**Comment by Sandu1213** [comment]
1.课堂id正确但不是该班级的学生 -> 提示不是该班级学生  
-- 已验证通过
2.课堂id错误的情况下 -> 提示班级不存在
-- 课堂id错误的情况下，客户端进入不了课堂，则不用考虑从客户端过来的情况
