### ISSUE TITLE
【Education-机构功能优化二】管理员端-班级信息管理：“创建班级”页、“班级详情”页、“班级编辑”页，增加开班时间的设置和显示。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4286]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/12dc2c73-4240-4200-8deb-7a7bcb5ca324)

**Comment by ZhangKaitlyn** [comment]
在issue #4252 处理了 @shirleyluo1130
