### ISSUE TITLE
【Education-机构功能优化二】管理员端-班级信息管理：教师页，若教师所在班级已到期，则该教师的班级信息中，不显示这个到期的班级。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4287]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/8379a309-8e7c-42f7-8fba-883710cb53cb)

**Comment by ZhangKaitlyn** [comment]
在 issue #4253 处理了， release可测 @shirleyluo1130
