### ISSUE TITLE
【Education-机构功能优化二】管理员端-历史数据：增加“历史数据”模块

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4291]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/27b11f37-4420-48c4-a2f9-0ffc86916c80)

**Comment by Sandu1213** [comment]
1.班级数不对，不是1
![image](https://user-images.githubusercontent.com/21214285/57432636-f8550f00-7268-11e9-83e8-a68e75ea035a.png)


2.详情页面里的学生信息不对
![image](https://user-images.githubusercontent.com/21214285/57432415-6947f700-7268-11e9-8aed-71a7ad66e72c.png)

**Comment by Sandu1213** [comment]
补充3：教师和学生人数统计不对
![image](https://user-images.githubusercontent.com/21214285/57438857-67d1fb00-7277-11e9-89cd-1f4f73e8ef1a.png)
