### ISSUE TITLE
【keepwork学习页】文档页，优化需求。详情见下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4303]
## 背景说明：

从keepwork学习页，点击“文档”菜单，

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/5702b4b2-1ba4-4c0b-ab4c-aaf49b0dadfb)

会跳转到文档页（如下图）

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/42d0cc2d-151b-4927-8f65-215bb1d87b4d)

## 优化需求如下：

需求一：文档页，加上keepwork学习页的导航。（需求一暂不处理）

需求二：菜单mod优化：① 选中某个菜单查看内容时，左侧选中的菜单高亮，同时只刷新右侧内容区即可；② 需支持不同分辨率下查看

**Comment by shirleyluo1130** [comment]
需求一，请开发评估实现方式。

需求二，请 @Kvaya  提 菜单mod优化方案。

**Comment by Sandu1213** [comment]
需求三：当菜单未配置链接地址时，点击菜单默认展开下一级(如：子菜单或者页面)
![image](https://user-images.githubusercontent.com/21214285/56874273-70eaed00-6a6b-11e9-964b-135c615f314b.png)

**Comment by Kvaya** [comment]
需求三：
解决方案：当主菜单未配置链接地址时，点击该主菜单，默认展开该主菜单所有子菜单，并右边内容显示的是该主菜单下有链接地址的内容，优先显示有链接的第一个。并右边展示内容，左侧菜单列表中的对应菜单项需高亮

**Comment by Kvaya** [comment]
需求二：
① 选中某菜单的子菜单，该子菜单高亮表明为选中状态，并右侧内容显示的同时，左侧选中菜单所属的主菜单下所有菜单是展开状态，而不是收起状态；
② 需支持不同分辨率下查看分两种情况：
1）在pc端，浏览器窗口调大调小；

**Comment by Kvaya** [comment]
https://release.keepwork.com环境目前显示如下:
![image](https://user-images.githubusercontent.com/39363297/57284414-b353a000-70e3-11e9-94ff-64ad38b7ebbc.png)
