### ISSUE TITLE
【Bug-学习】学习页面存在错别字及打开链接方式需要优化的问题

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4315]
## The problem
学习页面存在错别字及打开链接方式需要优化的问题

## Environment

* OS Info: Window10
* browser Info: chrome    73.0.3683.86
* URL: [keepwork.com](https://keepwork.com) 
* Model:  学习->在线课程

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.用户进入学习->在线课程页面，选择基础标签页下面的课程进行学习
2.分别点击课程包封面和课程包描述对该课程包进行查看

* Expected Result:
1.课程信息描述正确，无错别字
2.都可以正常进入课程包列表页面
* Actual Result:
1.学习页面介绍存在错别字
2.点击描述相关区域，无响应
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/b00de049-e882-47a7-a29a-00ca0b6441f8)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/6a2ab265-22c4-4326-81a0-9b08ee3ac17c)

**Comment by DDXY1230** [comment]
release环境
