### ISSUE TITLE
【Bug-加入班级】使用邀请码加入班级时，如果用户之前输入名字，后续都会优先显示该名字

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4329]
## The problem
使用邀请码加入班级时，如果用户之前输入名字，后续都会优先显示该名字

## Environment

* OS Info: Window10
* browser Info: chrome    73.0.3683.86
* URL: [机构页面](https://release.keepwork.com/org/news) 
* Model:  学生机构页面->加入班级

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问机构页面
2.已存在账号且账号已登录
* Details:
1.学生从未加入任何班级，当输入邀请码及姓名后，加入班级成功，再加入另外一个班级时，观察姓名是否会自动填写上
2.学生通过老师已经加入班级A，再通过邀请码加入班级B时，观察姓名是否自动添加上了

* Expected Result:
1.姓名会自动填充上去
* Actual Result:
1.姓名没有自动填充上去
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/383192c0-f351-4023-bdfa-1c01fea4dc5c)

**Comment by wxaxiaoyao** [comment]
fixed in release

**Comment by Sandu1213** [comment]
release环境验证，问题依旧
