### ISSUE TITLE
【bug】keepwork editor，导航菜单mod，如下

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4334]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/843ed1e6-d15d-47a8-a082-931a87723c16)

**Comment by Sandu1213** [comment]
问题依旧：
![image](https://user-images.githubusercontent.com/21214285/58315773-be793080-7e44-11e9-9e71-7018d6bee365.png)
