### ISSUE TITLE
【bug】学生被加入某个班级后，进入学生页查看，不显示该班级下的课程包。如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4338]
学生页：（该班级下有7个课程包）

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/1c85cc64-6e50-4918-91e7-35f95aea7114)

**Comment by wxaxiaoyao** [comment]
![image](https://user-images.githubusercontent.com/11922085/56939700-6cdad000-6b3c-11e9-8ba4-ef8daace11ad.png)
