### ISSUE TITLE
【paracraft.cn】新增课程体系页面

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4351]
背景：
在to B网站上新增课程体系页面，市场人员在外拓展时可与客户讲我们有哪些课程，课程体系的内容是什么？

解决方案：
原型地址：
![image](https://user-images.githubusercontent.com/39363297/57187657-edc30e80-6f24-11e9-8976-84fbf932b83e.png)

设计稿地址：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/cd1a9988-ea9f-49e3-b2e2-8d361f9e455e)

**Comment by DDXY1230** [comment]
手机版我已经单独建issue了，先上网页版，下周上手机版

**Comment by Sandu1213** [comment]
功能已验证，但入口太不明显了，等产品回复

**Comment by Kvaya** [comment]
pc端在2580宽度的显示屏，UI效果需优化

**Comment by Sandu1213** [comment]
调整好UI效果 后再移入测试
