### ISSUE TITLE
【dashboard】“作品统计”页面上增加“备份”功能

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4361]
背景：
参赛者的作品已获得名次，但参赛者把作品删掉了，已获得名次被后面的名次者替换了，这个不合理

解决方案：
在http://dashboard.keepwork.com/#/NPL/works 页面上加“备份”按钮，运营人员对当前获奖作品选中后，进行备份，保留当前获奖状态

补充1：作品保留这些数据
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/8261977b-0157-44a8-92f9-da107102414b)
包括名次、项目封面、项目名称、参数者、当前获奖时间、是否招募中、项目类型、浏览量、点赞数、评论数、参数者头像

补充2：点击该项目，进入项目主页显示“404”

**Comment by leopoldchen** [comment]
建议在参赛作品的记录里冗余存储一下作品的一些信息，确保作品被删除后依然有信息显示；
或者作品只做软删除

**Comment by wxaxiaoyao** [comment]
```
POST gameWorks/snapshoot  
```
输入: 
- ids  array(number) 作品id列表
输出
- 无

dashboard 选中 备份 调此接口,  keepwork前端无需改动.  会将作品的项目相关信息projects备份至作品对象的extra.projects 中, 拉取的数据时,若被删除会用备份数据还原相关信息.

由于是将项目备份至作品的extra, dashboard也可以调通用修改接口,自行填充(dashboard展示时应已拉取相关信息, 填充修改即可)

**Comment by wxaxiaoyao** [comment]
@kevinxft @DDXY1230 你们俩谁在dashboard中加下这个功能

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/57218205-52ff2880-7027-11e9-9409-c0a8df9552fe.png)

**Comment by kevinxft** [comment]
没有问题，请用准确的数据测试。也没有什么取消备份的功能，提交人姓名和机构都是正确的。
