### ISSUE TITLE
【Paracraft.cn】页面上文案更改

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4367]
背景：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/fc37f286-beb2-47f6-9999-a5548a9c60a5)

详细：
1.“下一代的Minecraft”改为“比Minecraft更进一步”；
2.“动画人物”改为“动画角色”
3.![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/fa75ae22-df94-458a-8ca0-d37428ad6979)“Paracraft”字母中的“p”改为大写“P”

**Comment by DDXY1230** [comment]
![image](https://user-images.githubusercontent.com/32215445/57208775-20920300-7008-11e9-8068-c80920a49f6d.png)

**Comment by duting1993** [comment]
https://biz.keepwork.com/
已修改
