### ISSUE TITLE
【paracraft.cn】首页新增“全国比赛”模块

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4369]
背景：
![RSQ7JNGB2HM]~XKSS8VL4ZK.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/06cbfd6f-9e49-4593-ba51-bc8b855000bd)

解决方案：
在https://biz.keepwork.com/ “用户作品欣赏”下增加一个模块，模块文案内容：
用Paracraft制作作品可参加哪些全国性竞赛？
教育部办公厅印发《关于公布2019年度面向中小学生的全国性竞赛活动的通知》，确定29项竞赛活动为2019年度面向中小学生开展的全国性竞赛活动。其中使用Paracraft制作的动画与编程作品能参加的全国性竞赛活动共计6项，包括：
全国青少年科技创新大赛1项--计算机科学，
全国中小学科学影像节1项--科普动画，
全国中小学信息技术创新与实践大赛4项--动画创作、微视频创作、移动端网页创作、3D 智能作品创作。

Paracraft除了能参加编程类比赛，还可以参加创意动画类比赛。Paracraft可以方便的制作3D动画，比其它Flash等2D动画工具优势大。

补充：
![YJ%B~ OJ1M4I1FBL7%(C192](https://user-images.githubusercontent.com/39363297/57192020-77430280-6f5e-11e9-9b2e-6b451dabb804.png)

**Comment by Kvaya** [comment]
设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/57218471-f6503d80-7027-11e9-8a20-475d71783682.png)

**Comment by duting1993** [comment]
biz-release.keepwork.com
