### ISSUE TITLE
【bug】课程包的课程目录，排序不对。如下

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4374]
## 问题描述：

第一步：用户创建了课程包“编程基础”，提交审核并通过后，继续为该课程包添加新的课程，并调整课程排序。保存成功。如下图：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/ef651a39-6015-4b15-912e-b49334ee2365)

第二步：进入前端用户的课程包详情页，课程目录应该按照最新的课程排序展示，但实际效果是，与设置的课程排序不一致，如下图：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/ea19a8e7-923f-4c74-9889-3a9d23bc9f0f)

## 解决方案

前端用户看到的课程包详情页，课程目录应该按照创建者设置的课程排序展示。（若创建者修改了课程排序，也需相应修改。）

**Comment by wxaxiaoyao** [comment]
看不懂bug....   文字描述下功能及问题吧  @shirleyluo1130

**Comment by Sandu1213** [comment]
问题依旧

**Comment by kevinxft** [comment]
重新分配课程包才能保证顺序

**Comment by Sandu1213** [comment]
请再调整 一下哈子
