### ISSUE TITLE
【keepwork首页+探索页】课程显示调整

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4378]
## 问题描述

结合目前的销售模式（主要做to B市场，课程授权给学校和培训机构），keepwork首页和探索页显示课程信息不合理。

## 解决方案：
1、keepwork首页，热门课程去掉；2、探索页，课程tab去掉

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/ce83ee0c-08c0-4e4f-808d-60c30f951af2)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/eb682d41-e4d4-4265-b6d3-c8422c581ff2)

**Comment by Sandu1213** [comment]
@shirleyluo1130 这里请考虑网页内容是否允许搜查出课程内容呢？(因目前学习模块只能看到课程包里的课程列表，而看不到课程明细)

**Comment by Sandu1213** [comment]
隐藏功能验证通过
