### ISSUE TITLE
paracraft to b网站课程系统，手机版

### ISSUE THREAD

**Issue by DDXY1230** [tatfook/keepwork#4382]

**Comment by Kvaya** [comment]
手机版显示时， 课程体系内容过长的话，课程表那块显示可以参考：
https://mp.weixin.qq.com/s/H2ghx2WgLmLKDbNFDDusJQ  中
![image](https://user-images.githubusercontent.com/39363297/57266576-11b25b80-70af-11e9-81cf-036b9091de09.png)
效果

**Comment by Sandu1213** [comment]
release环境已经验证
