### ISSUE TITLE
【bug】设置layout之后，要刷新

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#439]

**Comment by ouyc** [comment]
![image](https://user-images.githubusercontent.com/38035998/39735920-4e2014ea-52b0-11e8-9592-c571463f05a4.png)

**Comment by Sandu1213** [comment]
网站和网页都是需要刷新才能生效，请优化

**Comment by Sandu1213** [comment]
回归验证不通过，请再排查
![layoutissues](https://user-images.githubusercontent.com/21214285/39987916-9c53c5c0-5798-11e8-9e7f-2a161fcab57b.gif)
