### ISSUE TITLE
【bug】学生端：学生未加入任何班级，页面显示如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4413]
机构url：https://keepwork.com/org/visit  

学生账号：shirley001/shirley123456

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/54bc4f23-afee-4844-8762-ff1da9a42548)

**Comment by kevinxft** [comment]
教师端，学生端获取当前课堂，如果课堂未下课，但班级已经过期，则返回课堂已经结束
