### ISSUE TITLE
【bug-editor】竖行菜单中选中某菜单不高亮，不展开

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4423]
The  problem：
1.浏览竖行菜单网页时，选中某菜单不高亮，情况是在该菜单链接名称是中文，假如菜单链接是英文，则选中菜单，高亮；
2.选中菜单下的子项时，该主菜单不展开，收起了；
3.竖行菜单的属性面板进行编辑时，偶尔会一片空白；

情况图：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/e016e678-1816-4785-8ead-d75b6805a627)
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/c4051f81-7ac9-4bc7-aab7-efd0db6146d6)

Expected Result:
1.允许菜单链接是中文的情况下，选中菜单高亮并展开

**Comment by Sandu1213** [comment]
参考链接:{here](https://keepwork.com/junjun0517/test0409/index)

**Comment by Sandu1213** [comment]
stage环境已经验证。验证地址：[这里](https://stage.keepwork.com/test2019/notes/%E8%8B%B1%E6%96%87)

**Comment by Kvaya** [comment]
stage环境测试情况如下：
1.选中”发现“主菜单，主菜单不高亮，没表明是选中状态；
