### ISSUE TITLE
【课堂功能优化】同一个班级开了多个课堂，学生端页面只显示一个课堂。不合理。详情如下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4425]
## 场景描述：
step1：机构A下，班级B（班级B未过期）的老师C1开了一个课堂（课堂ID：C166947）后，忘记关闭该课堂。

step2：之后该班级下老师C2开了另一个课堂（课堂ID：C172508），

step3：此时，该班级的学生D页面只显示了老师C1开的课堂。如下图
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/2bd522b8-1d88-430d-a1db-99e20b0a86c9)

## 解决方案：** （以下2个方案都要实现）** 

1、对课堂做时限控制，开课后48小时未关闭，则系统自动关闭课堂；
2、允许同一个班级，多个课堂同时进行；此时，学生端显示全部课堂提醒。

**Comment by wxaxiaoyao** [comment]
![image](https://user-images.githubusercontent.com/11922085/57517131-bac7b300-7348-11e9-8c04-b70a93a01405.png)

**Comment by Sandu1213** [comment]
stage环境已验证
1，目前运行同一个班级的多个课堂同时进行。
2，课堂时长还在验证中，以2天为一个节点去判断校验，并不是真正意义上的48小时，请知悉
