### ISSUE TITLE
【paracraft.cn】课程体系链接地址改为：https://biz.keepwork.com/curriculum

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4427]
背景：
![image](https://user-images.githubusercontent.com/39363297/57514191-75a08280-7342-11e9-8bc8-775968502803.png)

解决方案：
“https://biz.keepwork.com/lessonSystem” 改为 “https://biz.keepwork.com/curriculum”

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/57598413-b20ff080-7585-11e9-8cb5-3a7dea6908a4.png)
