### ISSUE TITLE
【paracraft.cn】首页优势图之一图更改

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4429]
背景：
优势图之某一图是跟现《Paracraft编程入门》书籍中来的，现书籍图的内容更新了，现to b网站内容及时更新

解决方案：
![image](https://user-images.githubusercontent.com/39363297/57516181-d5992800-7346-11e9-88bb-ecf8f8f64337.png)

**Comment by Kvaya** [comment]
设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/57517875-59a0df00-734a-11e9-96e3-82762d0eb64e.png)

**Comment by Sandu1213** [comment]
已验证通过。
@Kvaya 因为学习版本改版，目前keepwork不再具有教学功能，教学功能都是转到机构教学了，这里有2个相应的宣传图是否同步调整一下。

**Comment by Kvaya** [comment]
to b官网根据反馈这个地方也需要改：
![image](https://user-images.githubusercontent.com/39363297/57678630-346ae400-765c-11e9-9654-5b463343894d.png)
最新设计稿在：
![image](https://user-images.githubusercontent.com/39363297/57678672-53697600-765c-11e9-8550-2272f09f1d24.png)
