### ISSUE TITLE
【bug】管理员端-班级信息管理：修改班级的开班时间，重新选择结束时间后，会自动把开始时间也改掉。不合理。详情见下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4431]
## 场景描述：
某机构管理员创建了一个班级，并设置好了开班时间。

之后，想将该班级时间延长，在“编辑班级信息”页面，重新选择了结束时间后，系统自动把开始时间也改成了结束时间同一天。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/524f8107-ceb4-442b-b653-6a0af2997ad2)

## 解决方案：
若只修改结束时间，则开始时间应保持不变；若只修改开始时间，则结束时间应保持不变。

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/57668522-33c15600-763a-11e9-8900-c445177e794e.png)
![image](https://user-images.githubusercontent.com/21214285/57668612-784cf180-763a-11e9-8242-e00bf1bc99db.png)
