### ISSUE TITLE
【editor】去掉网站设置中的“拒绝”权限，“浏览”“编辑”权限不变

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4443]
背景：
网站设有公用或私有或对指定账号设有“编辑”、“浏览”、“拒绝”权限时，指定账号对该网站的操作情况。

Expected result：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/535207c0-c9ba-4771-9bd9-4601106c8487)
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/bd207b5c-6174-42c2-a988-187a07771a38)
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/ee680e3b-aac9-4954-b3b3-03f81a9f1e29)

Actual Result:
公有网站，对指定账号设定拒绝权限，指定账号打开该网站下某网页，还是可以浏览，但不能编辑。应该是没有访问权限。

解决方案：
去掉网站设置中的“拒绝”权限，“浏览”“编辑”权限不变

**Comment by Sandu1213** [comment]
stage已ok
