### ISSUE TITLE
【优化-机构】学生端，文字调整。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4449]
某个课程包学完后，显示为如下：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/9e8539ac-e205-4454-9053-ae24c8a4a8ad)

**学完了！**    太口语化，建议调整为    **已学完！**

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/57830533-fea53700-77e4-11e9-9ce4-819bac4d8694.png)
