### ISSUE TITLE
【优化-机构】导航条，“退出”按钮，调整为“退出登录”，且加上确认弹框。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4450]
导航条上，按钮“退出”，名称上容易引起歧义，特别是在学生课堂状态时，“退出”易理解为“退出课堂”。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/39147956-1f4f-4bd9-a083-afb6120f4b6d)

## 解决方案：

退出   修改为    退出登录；且，点击该按钮，加上确认弹框，避免误操作。提示文字为：

确定退出课程系统吗？

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/57746809-71d77c00-7705-11e9-8f3a-96b133974165.png)
