### ISSUE TITLE
【Bug-editor待优化部分】图片上传提示

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#446]
### 问题：
- 1.markdown区域上传较大图片时，缺少上传进度，整体体验不好，请增加上传进度

**Comment by leopoldchen** [comment]
@azothli  是否有相关设计

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/41347055-1aeba466-6f3b-11e8-9034-b1f7132d66c7.png)
可以先显示
[文件上传中，请稍后......  已上传：15MB（84%） ]
后面是已经上传文件的大小与比例。
技术是否可以实现?

**Comment by ZhangKaitlyn** [comment]
目前markdown区域的文件是上传到gitlab，没办法获取到上传进度。跟 @azothli 商量后确定，先按照目前的方式不修改，所以issue先关闭
