### ISSUE TITLE
【Bug-兼容性问题】QQ浏览器打开新版editor，直接显示白屏，无法打开，请排查

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#447]
## The problem
QQ浏览器打开新版editor，直接显示白屏，无法打开，请排查

## Environment
* OS Info: Window10
* browser Info: QQ浏览器9.7 
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:  website->editor

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.打开QQ浏览器，进入最新的editor页面进行编辑

* Expected Result:
1.可以正常进入并编辑成功
* Actual Result:
1.页面显示空白，无法进行编辑
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/4a457797-5414-45f6-911d-39c1af466ea1)

**Comment by kevinxft** [comment]
@Sandu1213 最新版的QQ浏览器已经不存在这个问题，不过IE11还是存在🤔
