### ISSUE TITLE
【bug】操作预览，同时显示，仅代码，编辑器会出现预览与代码显示不一样内容

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#4477]
操作步骤：第一步，点击文件A，点击仅显示代码，或者同时显示，或者仅预览
第二步，点击文件b，点击仅显示代码，或者同时显示，或者仅预览
显示结果：编辑器显示，A文件的内容，B文件的代码
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/c8a5f312-58f5-4e74-9e9a-6e737de6f6c3)

**Comment by Sandu1213** [comment]
release环境验证通过
@duting1993  这是个好问题呀~:cool
