### ISSUE TITLE
【Bug-editor】editor内编辑的内容缺少版本管理及版本回退功能，后续请补充上

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#448]
### 问题：
 目前网站如果是多个用户同时进行编辑操作的话，会出现文件直接清空的情况，请添加版本管理及版本回滚功能。
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/54bb59a8-8a0b-436a-9ecd-7bf65c259bf3)

**Comment by leopoldchen** [comment]
待git gateway完成后再做
