### ISSUE TITLE
教材页需做手机端适配

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4483]
背景：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/8b90bc02-dcf4-4cf5-aaa6-0390248e4663)

解决方案：
购买页面做手机适配

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/57849183-3cb65100-780d-11e9-93f8-a6902e9b09c6.png)
![image](https://user-images.githubusercontent.com/21214285/57849213-4f308a80-780d-11e9-8a26-f4bf3bc2345f.png)
