### ISSUE TITLE
【bug】学生端，课程包的排序规则不生效了。详情见下

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4488]
## 学生端，课程包的排序规则为：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/23c9cc58-6ae7-4334-acbc-9f4083ac314c)

## 以上规则没有生效，如下图，请根据规则进行调整。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/8e4b41da-6f5f-4c32-97d7-ce05e8315fe4)

**Comment by Sandu1213** [comment]
4种状态：
未学完（由新到旧）>未开始>已学完（由新到旧）>已结业（无论是否学习完成）

**Comment by Sandu1213** [comment]
QQ浏览器上样式问题：
![image](https://user-images.githubusercontent.com/21214285/58220383-36f6c900-7d41-11e9-8fdf-51866165074a.png)
