### ISSUE TITLE
【Bug-editor】editor 增加未保存提示

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#449]
### 问题：
1.editor内编辑的文件内容需要增加本地缓存，自动保存的功能

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/9741b071-2cd1-4f38-8443-6d8c79ce3914)

**Comment by yuanoook** [comment]
本地缓存已经开启，未保存提示，设计正在跟进

**Comment by Sandu1213** [comment]
未保存设计已完成，请一同更新后走给测试回归

**Comment by Sandu1213** [comment]
关联issue #472

**Comment by duting1993** [comment]
header和footer自动保存，正文手动保存
