### ISSUE TITLE
投诉页面dashboard

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#4492]
![hhh.png](https://images.zenhubusercontent.com/5ac352dc4b5806bc2bcd6b02/f45dc47f-b414-450f-819d-85ab7ca6dedb)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/58231557-e6479600-7d69-11e9-9844-c12d5a80fe6e.png)

**Comment by Sandu1213** [comment]
stage 已验证
