### ISSUE TITLE
【bug】文本+标点符号调整。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4494]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/43dbf9da-0c57-4926-8b74-a5953e012e0b)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/ceec36c9-0210-4c0d-9a2e-63998ea36943)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/ded18477-b6dd-427b-a863-1752bbd31b77)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/7898320e-77b6-420f-93b7-2f7b06a32fef)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/a0ea0406-eb38-4334-9007-6ab250a54725)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/58145866-5977dc00-7c86-11e9-8621-52eec8bdda4c.png)
