### ISSUE TITLE
【Bug-机构】学生对课程包进行学习，通过“继续”按钮跟进的学习顺序不对，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4495]
## The problem
学生对课程包进行学习，通过“继续”按钮跟进的学习顺序不对，请调整

## Environment
* OS Info: Window10
* browser Info: chrome    73.0.3683.86
* URL: [机构地址](https://release.keepwork.com/org/news) 
* Model: 机构学生页面

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.可正常登录机构页面
2.存在学生的账号

* Details:
1.学生A所在的班级有课程包A(该课程包包含8个课程),先选择课程5进行学习，学习完成后，可以正常查看学习总结
2.再返回课程包列表页，通过“继续”按钮进行学习，观察下一课显示是否正确

* Expected Result:
1.应该是已学完课程的下一课且下一课未学习过(如此进行循环)，这里应该是课程6

* Actual Result:
1.目前下一课的顺序不对

## Attachments (eg:logs/video/screenshot)

**Comment by Sandu1213** [comment]
验证不通过，请再优化

**Comment by shirleyluo1130** [comment]
## “继续”按钮的原有逻辑为：

点击“继续”，若上一次某课程未学习完成，则进入该课程学习；若上一次某课程学习完成，则进入下一个未学课程。

上述逻辑是基于“允许学习者根据自身情况合理安排课程学习顺序”的需求，虽然每个课程包下有固定的课程目录排序，也允许学习者跳跃着学习，例如，学习了课程1后，直接跳过课程2去学习课程3，之后学习课程4……

## 目前的实现方式是：

点击“继续”，进入对应课程包下，第一个未学课程。例如，某课程包A，共有6个课程（课程1、2、3、4、5、6），若课程1未学，课程2、3均已学完。本次学习了课程4（无论是否学完），下一次点击“继续”，则进入课程1学习；之后多次，通过“继续”按钮都只能去到课程1的学习页（若课程1未学完的话）

## 解决方案：

目前的实现方式，没有达到预期的效果，会对学习者造成困扰，导致必须去目录中选择对应课程才可实现跳跃学习，建议参照原有逻辑实现。

** 开发回复无法判断上一次学习的课程是哪个课程，请 @leopoldchen  评估下。** 

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/4c210f57-a89c-4b35-b5ba-b558abf6c2da)

**Comment by Sandu1213** [comment]
课程序号存在问题，需要排查，请调整

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/58236770-362c5a00-7d76-11e9-917b-0516fc365940.png)

待后端排查后再验证

**Comment by Sandu1213** [comment]
通过 #4573 进行跟进
