### ISSUE TITLE
【bug】文本与绘图板问题

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#450]
操作步骤：1.添加文本与绘图板，添加成功后，默认选中正文，打开绘图板
2.编辑，绘图，关闭之后，文本框里显示如图二
![image](https://user-images.githubusercontent.com/28430070/39794942-8a29f4ea-537f-11e8-89cf-599880f5bd25.png)
图二
![image](https://user-images.githubusercontent.com/28430070/39794964-ab22d8a6-537f-11e8-9b31-dca0e9c39664.png)

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/39795394-66a37fde-5382-11e8-8dee-a400a8cfc836.png)
建议在卡片激活时才能打开绘图板
