### ISSUE TITLE
【Bug-删除文件夹】删除文件夹优化建议

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#451]
有两点请优化：
- 1.删除文件的提示语不是很合理
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/cf8205ed-c4a1-4275-babc-3c5d35af714e)

- 2.如果删除的文件夹过多，会出现隔几秒才会响应的情况，建议增加交互给用户感知，体验要好些

**Comment by Sandu1213** [comment]
@azothli 宇哥，请帮忙定义提示语和交互效果

**Comment by azothli** [comment]
提示语“**删除**文件夹及其中的**所有内容**么？”

2，可否加一个类似loading的转圈？

**Comment by kevinxft** [comment]
已经修改提示语和删除的loading状态😀

**Comment by duting1993** [comment]
stage已验证
