### ISSUE TITLE
【优化-机构】管理员端-班级信息管理，UI调整+文字优化

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4523]
管理员端，“班级信息管理-学生”页面，
1、班级筛选功能不明显，建议作如下UI优化，见下图①处
2、“可添加学生数”位置处，增加联系方式，方便机构需要提高学生数上限时，可联系我们处理。见下图②处

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/50c1e9cd-728a-4daa-b1e6-7213a6a1295d)

**Comment by shirleyluo1130** [comment]
UI设计中

**Comment by shirleyluo1130** [comment]
UI见：
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/bcc66b22-3966-43a0-a722-d36da9a7801e)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/58143755-81fbd800-7c7e-11e9-9a84-53e67425fd84.png)
