### ISSUE TITLE
PAC大赛-Paracraft mod 创意空间 style

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#453]
Paracraft mod 创意空间 style

**Comment by enya-i** [comment]
分享-sdk版本
![-sdk](https://user-images.githubusercontent.com/37529364/39803218-f5c77f2e-53a2-11e8-9c34-25e241c8dbb1.jpg)

分享-sdk-手机版
![-sdk - jpg](https://user-images.githubusercontent.com/37529364/39803223-f93cdfdc-53a2-11e8-87bb-ee53bca7ba72.png)

分享-社区版
![-](https://user-images.githubusercontent.com/37529364/39803228-fc2b48b4-53a2-11e8-9ee7-67b76a52f3d0.jpg)

分享-社区版-手机版
![- - jpg](https://user-images.githubusercontent.com/37529364/39803231-ff1dfb20-53a2-11e8-87cb-bda32aa7b29b.png)
