### ISSUE TITLE
Editor - 多人在线同时编辑

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/keepwork#4539]
### 背景

现有版本如果文件被他人编辑，用户无法感知变化，容易造成文件被覆盖等各种问题

### 解决方案

基于socket和diff插件，首先，在有用户提交保存的情况下，自动把保存的内容push给所有正在打开编辑的用户，告知用户文件已经被编辑；然后通过diff，让其他用户知道文件有哪些地方被修改了，然后快速做merge操作

**Comment by leopoldchen** [comment]
@kevinxft 界面交互 @Kvaya 会做，届时等她做好再实现界面交互

**Comment by Kvaya** [comment]
解决方案：
![image](https://user-images.githubusercontent.com/39363297/59335777-d6e7b700-8d2f-11e9-99b1-dba66ef847e9.png)

**Comment by Kvaya** [comment]
设计稿地址：
![0%FUN$_H})EXWZU0V~X%OUM](https://user-images.githubusercontent.com/39363297/59420423-73c55580-8dff-11e9-84d5-82551a0aaf7e.png)

**Comment by Kvaya** [comment]
提示建议按下面优化，且对应的英文翻译：
1.
![image](https://user-images.githubusercontent.com/39363297/60497193-ec288380-9ce6-11e9-98d8-02dbdb65d210.png)
提示语：
网页内容有更新
**keep1013**更新了keep1013/SharedProjects/index.md的内容

英文：
Web content has been updated
**Keep1013** updated the contents of keep1013/SharedProjects/index.md

补充：
![image](https://user-images.githubusercontent.com/39363297/60497878-3d854280-9ce8-11e9-9eb5-c27b85db467a.png)；

2.
![image](https://user-images.githubusercontent.com/39363297/60498591-7bcf3180-9ce9-11e9-9d2c-5be7a02fe5d1.png)
改为：
![image](https://user-images.githubusercontent.com/39363297/60498672-a3be9500-9ce9-11e9-9e4f-e07f85514da4.png)
更新
mouse over显示：网页内容有更新，点击更新

英文：
Update
Web content is updated, click update.

3.
![image](https://user-images.githubusercontent.com/39363297/60498734-bb961900-9ce9-11e9-923b-1f80767c7af3.png)
建议改为：
网页被删除
**keep1013**删除了keep1013/SharedProjects/index.md

英文：
Web was deleted
keep1013 deleted keep1013/SharedProjects/index.md

4.keep1013于2019-07-02 16:00更新了内容,请先⇜合并再保存

规则备注：账号 于 时间更新了内容，请先⇜合并再保存

英文翻译：
Keep1013 updated the content at 2019-07-02 16:00, please ⇜ merge and save it first.

**Comment by Kvaya** [comment]
颜色排版参考：
![image](https://user-images.githubusercontent.com/39363297/60500643-462c4780-9ced-11e9-9e3f-f7aa3f57d9c4.png)

**Comment by Sandu1213** [comment]
除了多次编辑后再次megre有些问题外，其他都正常
