### ISSUE TITLE
【Bug-editor】图文叠加mod当选择文字靠下的样式后，显示不合理，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4542]
## The problem
图文叠加mod当选择文字靠下的样式后，显示不合理，请调整

## Environment

* OS Info: Window10
* browser Info: chrome  74.0.3729.157 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  editor ->mixposition

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入编辑器页面，创建一个新文件，然后添加图文叠加的mod，分别选择不同的样式进行添加，观察页面显示情况
2.切换到English模式下，再观察页面显示情况

* Expected Result:
1.页面显示合理
* Actual Result:
1.英语模式下，最后3种样式会出现下拉框，与页面显示不搭
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/5991da8d-25b2-46e4-bfc8-46f55699e839)

**Comment by Kvaya** [comment]
解决方案：
1.图文叠加文字在下方的样式，正文高度最高是到图片底部，正文文字数量在这范围内不显示滚动条；
2.当文字数量超出图片底部，超出部分用省略号显示。

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/58308297-c9779500-7e33-11e9-8cb0-b54defac37e8.png)
是的，应该是底锁定，向上扩展

**Comment by Sandu1213** [comment]
问题依旧
![image](https://user-images.githubusercontent.com/21214285/58694676-32c44e80-83c6-11e9-8112-d4d1ab8608f3.png)

**Comment by Sandu1213** [comment]
目前文字位于中部和顶部又出现了问题，建议先按图片的高度排列，当超过指定高度后，就是图文分离显示了
