### ISSUE TITLE
【Paracraft创意空间】在keepwork官网上删除项目后，Paracraft软件中还存在之前的项目ID数据

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4547]
背景：
现keepwork官网允许删除个人创建的项目，删除某个Paracraft类型的项目后，再次在Paracraft创意空间点击“上传并分享”后的弹窗浏览框处还是显示之前的项目链接，并登录页面中也是显示项目ID,而keepwork官网中并没有这个项目。
![_AE5FF%X}S2{PO4L4NOMQMM.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/6e47810d-8de4-4d0c-85eb-0a590108424e)
![GHWQJ7B7NFP$HF85UEMRN69.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/8a173c2a-5b2e-4f91-94b8-21a040c9eaad)
![1H{_ IMU@~S3U7H0KWSUSZK](https://user-images.githubusercontent.com/39363297/58090063-fd1aab00-7bf8-11e9-997d-64d45221e17f.png)

解决方案：
假设在keepwork官网删掉个人创建的Paracraft类型的项目，Paracraft创意空间中同步删除项目数据。

**Comment by onedou** [comment]
MAC 版本测试

**Comment by Sandu1213** [comment]
MAC版本验证不通过，请再排查
![image](https://user-images.githubusercontent.com/21214285/60245658-9e2f0c80-98ef-11e9-94bd-f0bfe3c2deb5.png)

**Comment by Kvaya** [comment]
先处理project keepwork被删除，paracraft客户端在线登录，项目世界数据同步问题；
