### ISSUE TITLE
Mod adapter - 兼容旧版mod

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#456]
### 背景

如果新版上线，有很多旧版mod会直接失效，特别是paracraft mod，如果部分用户没有升级客户端，那么还是会继续创建基于旧版mod的分享网页。因此，需要针对性的解决兼容问题。

### 目标
兼容主要mod，编写adapter

### 指标
- [ ] paracraft mod
- [ ] board mod

**Comment by LiXizhi** [comment]
It is important to add adapter, and automatically upgrade on next open in editor
