### ISSUE TITLE
【机构优化】激活码打印页面，文字优化。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4565]
## 需求说明：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/f85c40dd-ccb9-4336-b7b3-e3150c917148)

## 解决方案：
激活码打印页面，操作说明中写明 用浏览器打开网址。文本内容增加后，UI上也相应做了一些调整。详见：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/6d79c276-722c-4da3-a5f9-c3e41a8092ef)

**Comment by Sandu1213** [comment]
邀请码管理页面的“打印”，显示还是不对
![image](https://user-images.githubusercontent.com/21214285/58237007-bb177380-7d76-11e9-9629-01692fce3206.png)
