### ISSUE TITLE
【Bug-网站删除】编辑器页面的网站删除功能不可用，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#459]
## The problem
编辑器页面的网站删除功能不可用，请调整

## Environment
* OS Info: Window10
* browser Info: chrome  66.0.3359.139
* URL: [stage.keepwork.com](http://stage.keepwork.com) 
* Model:   editor

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor页面后，对无用的网站进行删除操作，观察删除结果

* Expected Result:
1.删除成功
* Actual Result:
1.删除失败
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/5a4ca11c-0add-4ef7-9428-9fac828ea4ef)

**Comment by kevinxft** [comment]
@Sandu1213 本来就没有删除网站的功能的，我不小心加上这个按钮了，我把它去掉

**Comment by Sandu1213** [comment]
stage环境已验证通过
