### ISSUE TITLE
【Bug-消息推送】消息推送前端问题记录

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4594]
- 问题1：首次登陆，系统消息查看不到的问题
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/0c5a06af-9558-4dda-9020-5b2324223851)

- 问题2：分页按钮太小
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/5d62c684-d2d7-4210-a2ca-075aaadee3bd)

**Comment by Sandu1213** [comment]
问题依旧

**Comment by kevinxft** [comment]
fix

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/58447841-56726500-8138-11e9-84e5-44528ccff507.png)

**Comment by Sandu1213** [comment]
新注册的用户不用接受之前旧的消息，该场景待调整后再验证一下
