### ISSUE TITLE
【Bug-机构】班级的结束时间应该不小于开始时间，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4598]
## The problem
班级的结束时间应该不小于开始时间，请调整

## Environment
* OS Info: Window10
* browser Info: chrome   74.0.3729.157 
* URL: [机构地址](https://release.keepwork.com/org/news) 
* Model: 机构管理员页面

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.可正常登录机构页面
2.存在管理员的账号

* Details:
1.管理员去将班级A的结束时间改的比开始时间小，观察修改结果

* Expected Result:
1.无法进行设置，结束时间必须不小于开始时间

* Actual Result:
1.结束时间可以小于开始时间

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/72731d71-28ca-4c93-8f4a-652bac9d0e80)

**Comment by DDXY1230** [comment]
release环境

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/58405012-10b28f80-8099-11e9-97da-6ecce8ffe93e.png)

**Comment by kevinxft** [comment]
release 已经fix
