### ISSUE TITLE
【editor】有“侧边栏+主内容”的网站布局页面UI效果调整

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4599]
背景：
![image](https://user-images.githubusercontent.com/39363297/58323386-60eddf80-7e56-11e9-820d-976eafcab542.png)
假设侧边栏加的是menu，跟主内容中间的间距是0，UI效果很挤，效果不佳
问题效果参考：https://keepwork.com/junjun0517/test1/index

解决方案：
1.主内容左右加边距
2.需进行调整的网站布局样式有9个：
![image](https://user-images.githubusercontent.com/39363297/58322037-621d0d80-7e52-11e9-8e4d-bb002edd5abb.png)
![image](https://user-images.githubusercontent.com/39363297/58322045-68ab8500-7e52-11e9-988a-c8221accfefe.png)
![image](https://user-images.githubusercontent.com/39363297/58322048-6cd7a280-7e52-11e9-9966-e0df87c732da.png)

**Comment by enya-i** [comment]
![image](https://user-images.githubusercontent.com/37529364/58456005-a14ea580-8155-11e9-9064-81c7e127a60c.png)
![image](https://user-images.githubusercontent.com/37529364/58456031-add2fe00-8155-11e9-93b2-588fd5b4cf54.png)

**Comment by Kvaya** [comment]
设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/58456752-98f76a00-8157-11e9-98bd-0bbdafe95187.png)
