### ISSUE TITLE
【keepwork footer】footer改版，详情见下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4601]
原型及UI见：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/4ebbf84b-5c11-47a6-a729-41a424c8e22c)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/4644c430-7378-4443-8320-60b19cf65ebf)

**Comment by shirleyluo1130** [comment]
@DDXY1230   @enya-i 

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/5fdb905b-1544-460f-9d00-729f66d37ad4)

**Comment by shirleyluo1130** [comment]
以上footer是keepwork官网上的footer

对于Editor编辑的页面，footer使用精简版。由issue #4643 跟进

机构页面，footer也使用精简版。由issue #4644 跟进

**Comment by Sandu1213** [comment]
@shirleyluo1130  以下问题请进行评估：
1.链接在新页面打开的title名显示不合理（一些显示英文的，一些没有设置，都是Keepwork，建议统一，能快速区分）
![image](https://user-images.githubusercontent.com/21214285/58690858-1a036b00-83bd-11e9-9d22-a8c3625d363a.png)

@DDXY1230 以下问题请进行调整：
1.二级菜单栏移除问题
![image](https://user-images.githubusercontent.com/21214285/58691089-a1e97500-83bd-11e9-957f-c3ce14772250.png)
![image](https://user-images.githubusercontent.com/21214285/58691365-4d92c500-83be-11e9-837d-e3b4e33fa45a.png)

2.i18n问题
![image](https://user-images.githubusercontent.com/21214285/58691385-669b7600-83be-11e9-8116-d150388eca95.png)

**Comment by shirleyluo1130** [comment]
关于title名显示不一致（中英混杂）的问题，暂时不用处理。如需处理，会另外其他issue给出方案。

关于联系方式调整的问题，需要UI重新出图。待出图后，我会进行调整。

**Comment by shirleyluo1130** [comment]
联系方式已调整完毕。

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/58787329-33eeb900-861c-11e9-8040-963fc05d2773.png)

**Comment by shirleyluo1130** [comment]
### footer英文版：（请对应调整）

教育理念 Educational ideas 
解决方案 Solutions 
写给父母们的话 To parents 
致教育工作者 To educators 
致开发者 To developers 
对爱好编程的你说 To programming fans 
关于自主学习 Self-directed learning 

社区 Community 
项目和作品 Projects & Works 
学员反馈 Students’ feedback  
员工博客 Staff blog 
家长博客 Parents blog 

学习 Learn 
Paracraft网络课程 Paracraft online lessons
Paracraft线下导引课 Paracraft offline training
文档 Documents 
常见问题 Frequently asked questions
下载Paracraft     Download Paracraft

Paracraft家族    Paracraft family 
NPL语言   NPL language
NPL CAD    
魔法哈奇   Haqi
魔法哈奇2  Haqi 2
Paracraft幼儿智能积木 Paracraft intelligent building blocks for children

商务合作  Business cooperation 
商务 Business 
合作伙伴 Partners 

关于 About 
公司 Company
加入我们 Join us
问题反馈 Feedback
