### ISSUE TITLE
【机构有效期】管理员端：班级信息管理-班级页面

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4606]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/715c1bd9-a6cf-4e07-8dc6-b51be159b4ff)

**Comment by Sandu1213** [comment]
- 问题1：
![image](https://user-images.githubusercontent.com/21214285/58693175-bed47700-83c2-11e9-9d29-969d4327a53b.png)
