### ISSUE TITLE
【Bug-历史数据】历史数据里切换每页显示条目数不生效

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4616]
## The problem
历史数据里切换每页显示条目数不生效

## Environment
* OS Info: Window10
* browser Info: chrome   74.0.3729.157 
* URL: [机构地址](https://release.keepwork.com/org/news) 
* Model: 机构管理员页面

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.可正常登录机构页面
2.存在管理员的账号

* Details:
1.管理员对历史数据进行查看，分别选中不同的页面显示条数，观察页面显示情况

* Expected Result:
1.页面内容显示正确且合理

* Actual Result:
1.页面内容显示不合理，每次都是10条

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/9c554a9d-9646-4513-ba44-e0963d68e9a3)

**Comment by DDXY1230** [comment]
stage环境
