### ISSUE TITLE
PAC大赛 - iicc 首页不同浏览器的兼容

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#462]

**Comment by leopoldchen** [comment]
@azothli 需要兼容哪些浏览器，需要一个列表

**Comment by azothli** [comment]
Chrome
firefox
ie
qq
2345
uc
360
以上为常用

**Comment by Sandu1213** [comment]
- Chrome  v66.0.3359.181（验证通过）
- firefox    v60.0.1 （验证通过）
- ie  v11.48.17134.0 (验证通过）
- qq  v9.7  (极速模式: 验证通过/兼容模式IE11：验证通过）
- 2345
- uc
- 360 v9.1.0.362  (极速模式: 验证通过/兼容模式IE11：验证通过）
另外补充验证了 avast browser v65.0.411.162(验证通过）
