### ISSUE TITLE
keepwork.com 设置中心 ->账户安全->手机解绑，图片验证码没有

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#463]
![image.png](https://images.zenhubusercontent.com/5ac352dc4b5806bc2bcd6b02/7344402d-596a-477c-aec4-8ac858643c7a)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/39857868-70062f28-5467-11e8-96a3-e168625240d8.png)

**Comment by Sandu1213** [comment]
已找大伟处理好了，该问题关闭
