### ISSUE TITLE
【Bug-board】新建board失败，旧board修改后无法进行保存

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4668]
## The problem
新建board失败，旧board修改后无法进行保存

## Environment

* OS Info: Window10
* browser Info: chrome  74.0.3729.157 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  board

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入编辑器里，选择已存在board的文件进行编辑，编辑board，观察是否可以保存成功
2.新建一个页面，然后新增一个新的board，再进行保存，观察是否可以保存成功

* Expected Result:
1.可以保存成功
* Actual Result:
1.保存失败
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/a92838fe-9017-4127-abbf-da6332bc5a61)

**Comment by William0911** [comment]
线上已hot fix，请测试
