### ISSUE TITLE
【keepwork】新用户注册后，首次登录，我们系统会发送一条消息给首次登录者

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4672]
文案：
欢迎来到 keepwork，%username%！
我们很荣幸有你的参与！通过keepwork，你可以创建自己的3D动画项目、编程项目、网站项目，并将你的作品分享给大家。
接下来呢？
[创建自己的项目](https://keepwork.com/create)
[下载Paracraft](http://paracraft.keepwork.com/download?lang=zh)
[获得更多学习资料](http://keepwork.com/s)
[欣赏优秀项目](http://keepwork.com/ranking)

备注：蓝色字链接是可以点击跳转至相应的链接去。

**Comment by wxaxiaoyao** [comment]
![image](https://user-images.githubusercontent.com/11922085/58680042-b2d3bf80-8398-11e9-9fa6-260372a98a10.png)

**Comment by Sandu1213** [comment]
stage 验证通过
