### ISSUE TITLE
管理员客服我遇到了一个问题。

### ISSUE THREAD

**Issue by polarlitchi** [tatfook/keepwork#4689]
就是我以前的米米号绑定在了keepwork账号上
现在我忘了这个keepwork账号了
我的米米号是58847668
能帮忙找一下吗？

**Comment by azothli** [comment]
要大伟帮着查数据库的

**Comment by Sandu1213** [comment]
@polarlitchi 你好，你对应的keepwork账号是lizihe123 ，建议尽快绑定手机号或者邮箱，以便后续快速找回账号。
