### ISSUE TITLE
【bug】新版编辑器，缺少，打开Git文件

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#469]
![image](https://user-images.githubusercontent.com/28430070/39980277-a603e35e-577d-11e8-9528-812ebeef50fd.png)
![image](https://user-images.githubusercontent.com/28430070/39980291-b7d29b5c-577d-11e8-9a11-f19a01cf71a1.png)

**Comment by Sandu1213** [comment]
已经有 #448 进行跟进，该issue关闭
