### ISSUE TITLE
【keepwork】 https://keepwork.com/official/docs/lessons_guide 用markdown编辑器按美术效果优化

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4697]
背景：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/71d620e7-cdcf-4383-986a-776e6d91c534)

解决方案：
1.该页https://keepwork.com/official/docs/lessons_guide   用编辑器按美术稿优化下;
2.左侧菜单菜单栏的菜单名称超出区域后，用省略号显示超出部分，并鼠标hover名称上时，显示菜单名称。

**Comment by enya-i** [comment]
![image](https://user-images.githubusercontent.com/37529364/58848848-97c7bf00-86ba-11e9-8c2b-b9a6bccec490.png)

**Comment by Kvaya** [comment]
设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/58925563-9c53ac80-877a-11e9-945d-ba6cf20a747e.png)

**Comment by leopoldchen** [comment]
@ZhangKaitlyn 看一下是否是需要添加新的layout
