### ISSUE TITLE
【dashboard】首页精选页面优化

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4701]
背景：
现首页精选项目不能一键批量取消精选；
不能一次性添加多个项目ID

解决方案：
1.在“首页精选”页面导航栏处，增加“取消首页精选”按钮，下面全选或单选项目后，可点击“取消首页精选”按钮，一键取消

2.点击“添加首页精选”按钮，弹窗中“项目ID”输入框中，用“，”隔开的方式，一次性可以添加多个补充：一次性添加多个后，在首页顺序还是按现dashboard的排列顺序为准

**Comment by kevinxft** [comment]
@Kvaya stage 和 release均可以体验

**Comment by Sandu1213** [comment]
release环境，单个取消和批量取消木有效果

**Comment by kevinxft** [comment]
release环境，很好使
