### ISSUE TITLE
【keepwork赛事入口】大赛页

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#4709]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/7add5c43-9cf0-45e8-a201-f43c00942852)

**Comment by duting1993** [comment]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/85e22c8b-2544-4ad0-9065-72ffa87241d7)
该链接应该跳转![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/a701e28c-100d-4780-abc6-fd85cb0632aa)
