### ISSUE TITLE
【keepwork】keepwork官网导航栏优化

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4732]
背景：
现keepwork官网导航栏处，不熟悉功能的人，在不点击该图标情况下并不知道该图标标识的是什么？点击后可以展示什么页面给他看

解决方案：
![image](https://user-images.githubusercontent.com/39363297/59823987-75909b00-9362-11e9-80aa-76296a794b1e.png)

鼠标mouse over 1-3处时，分别如下：
1.直接显示
![image](https://user-images.githubusercontent.com/39363297/59017545-55e37800-8876-11e9-9520-7df870eef039.png)，且icon+文字变蓝；
2.直接显示
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/9d5d9972-5258-4da3-b85e-ace7c58f7b23)，且icon+文字变蓝；
3.直接显示
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/0a309b13-b17a-46b8-b4e7-e8a32757dfa1)，且icon+文字变蓝；

备注：
1.以上是登录时的情况；未登录时，显示“排行榜、下载”两个icon和相应文字；
2.mouse over “排行榜、下载、消息、工具”时icon和文字变蓝；
2.mouse over时显示的下拉框统一为带有向上箭头的UI效果，如：
![image](https://user-images.githubusercontent.com/39363297/59017504-419f7b00-8876-11e9-8b59-5c324b6696ab.png)

**Comment by enya-i** [comment]
![image](https://user-images.githubusercontent.com/37529364/59825046-7d9e0a00-9365-11e9-9c88-49853960a41c.png)
![image](https://user-images.githubusercontent.com/37529364/59825077-90b0da00-9365-11e9-81a9-01d0b45b67e7.png)
