### ISSUE TITLE
【bug】标题分类问题

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#474]
![image](https://user-images.githubusercontent.com/28430070/39980770-0de0689c-5780-11e8-8ff3-4fc5c41a97d2.png)

**Comment by leopoldchen** [comment]
@azothli  分类清单调整好后和 @LiXizhi 沟通一下吧

**Comment by leopoldchen** [comment]
@onedou 

等调整确定后，再做更改

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/40102585-795c5c86-591d-11e8-9404-6aae358d9a7e.png)

**Comment by LiXizhi** [comment]
- 常用
  - 文本（markdown）
  - 绘图板
- 导航
  - 网站头部导航
  - 菜单
  - 目录TOC

剩下的我没有看， 后面可继续优化。

**Comment by LiXizhi** [comment]
@azothli @leopoldchen @onedou
