### ISSUE TITLE
【bug】ctrl+z后出现空页面，能否默认用files

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#476]
![image](https://user-images.githubusercontent.com/28430070/39981088-87889f88-5781-11e8-9f0c-4383603ea5e4.png)

**Comment by Sandu1213** [comment]
![pages](https://user-images.githubusercontent.com/21214285/39987005-07e8ace0-5796-11e8-802e-4c4fffd489a1.gif)

**Comment by kevinxft** [comment]
这个跟 #480 应该是同一个问题
