### ISSUE TITLE
未保存提示

### ISSUE THREAD

**Issue by yuanoook** [tatfook/keepwork#479]
![xx.png](https://images.zenhubusercontent.com/59ed5968a468affe6df7b5aa/929ee43a-ae26-41a6-ae9f-554053be9376)

**Comment by Sandu1213** [comment]
首次进入编辑器页面，不需要显示这样的提醒，当打开文件有正式的操作后再根据情况判断
![image](https://user-images.githubusercontent.com/21214285/40040242-fe569550-584b-11e8-803f-c9a70c746da6.png)
