### ISSUE TITLE
KP Mod编辑器

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#48]
1. Mod样式编辑
2. 普通MOD制作（无复杂后端逻辑）

**Comment by wxaxiaoyao** [comment]
## 模块编辑器
> 模块编辑器一款类photoshop,dreamweaver，boostrapit等网页模板编辑工具

### 特性
1. 基于基本的html标签和vue组件搭建界面， 基于基本标签可以搭建出任意静态页面， 基于组件可搭建动态页
2. 对于已编辑好的网页模板可以做二次编辑修改或新增， 减少重复创作
3. 视图与数据分离。对网页模板里的数据进行提取，在编辑器使用模板直接编辑数据即可

### 意义
1. 快捷高效的模板创作， 创作共享，彼此互用。
2. 个性化，多样化的页面展示，模板具有多样化和通用性，足以搭建出各类页面

### TODO
1. 使用体验优化
2. 网页爬取智能转换
3. 基本元素智能组装Mod和搭建页面

### 效果图

#### 模块构建效果图
![](http://git.keepwork.com/gitlab_rls_xiaoyao/keepworkxiaoyao/raw/master/xiaoyao_images/img_1523158318067.png)
#### 模块使用效果图
![](http://git.keepwork.com/gitlab_rls_xiaoyao/keepworkxiaoyao/raw/master/xiaoyao_images/img_1522736290813.png)
#### keepwork adi模块编辑图
![](http://git.keepwork.com/gitlab_rls_xiaoyao/keepworkxiaoyao/raw/master/xiaoyao_images/img_1523158432425.png)


### 进度
模块编辑器需求是为KEEPWORK ADI模块提供视图编辑并导出adi模块相关模板与样式文件，但由于两者模块编辑器，ADI设计同步开发，且模块编辑器不仅仅是adi的模块编辑器导致设计与实现上更偏向模块编辑器本身， 而将ADI模块作为辅助功能实现。

实现的主要功能有:
1. 模块编辑器，实现基于html与组件搭建模块， 导出模块功能。    
2. 增强版markdown编辑器，包含使用模块编辑器导出的模块。
3. 简易版基于ADI模块二次编辑并输出编辑的ADI相关文件。

### DEMO
[MD编辑器](http://10.27.3.3/wwww/editor) 
[TAG模块编辑器](http://10.27.3.3/wwww/tagmods)
[ADI模块编辑器](http://10.27.3.3/wwww/modeditor)

### 备注
大体功能基本完成，细节功能无法评定待完善。 基于独立项目实现，避免对正式产品产生影响，提供快速搭建原型环境，新实现思路尝试与实践。
