### ISSUE TITLE
【keepwork】keepwork.com首页“大家都觉得赞”处项目封面是为空，效果不佳

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4809]
背景：
keepwork.com首页“大家都觉得赞”处项目封面是为空，效果不佳；

解决方案：
keepwork.com首页“大家都觉得赞”的排序规则变更为：首先按七天点赞量倒序排序来，如果相同按总点赞量倒序排序，如果总点赞量还是相同，按更新时间最新排序。

**Comment by William0911** [comment]
首页使用了core service的接口，转 xiaoyao
