### ISSUE TITLE
【bug】新版编辑器，点击中间的模块，没有对应右边的代码

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#481]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/f2d4a938-e7ec-4e26-9990-b7774c8c0339)
操作步骤：新版编辑器：1.添加多个模块，点击模块。
结果显示：点击模块，没有对应右边的代码
老版编辑器：添加多个模块，点击模块，对应相应的代码

**Comment by Sandu1213** [comment]
旧版的是定位整个代码块，不是只定位第一行的。而且Markdown mod的标识建议做下特殊处理
