### ISSUE TITLE
【keepwork】keepwork.com探索各类别页中的项目封面是为空，效果不佳

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4810]
背景：
【keepwork】keepwork.com探索各类别页中的项目封面是为空，效果不佳

解决方案：
综合维度，项目总分除以1000，把没有项目封面的排到末位去；
最新维度，项目加一个条件，没有项目封面的的排到末位去；
热门维度，项目加以条件，没有项目封面的排到末位去。

**Comment by William0911** [comment]
没有项目封面的项目已排到末位， release环境可测
综合维度因还没有开始计算分数，暂时按与最新、热门相同方法进行排序
