### ISSUE TITLE
【editor】新增一个默认展开菜单样式

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4815]
背景：
先的editor的菜单样式所有的模式是不展开的，现需增加一个默认展开菜单样式

解决方案：
在导航菜单mod的样式中新增一个菜单样式：默认展开，包括它的所有层级；菜单样式颜色是白色；可以在“导航菜单”样式中添加

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/60082265-f6d29e00-9765-11e9-9d74-f8c9eb361727.png)
![image](https://user-images.githubusercontent.com/18642919/60082289-00f49c80-9766-11e9-8298-bec4c7698fca.png)
