### ISSUE TITLE
【editor】editor中大文件直接插入时，新增视频和PDF大文件属性面板中的宽高度大小可调整

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4832]
背景：
现editor大文件插入后，只有图片格式大文件有宽高度大小调整
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/36ff987d-5b2b-42e8-9e02-cdc0e96305e2)

解决方案：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/ad510394-1331-4197-80d8-11e6b1533ab7)
上面图中的大文件格式都需要支持属性面板可对宽高度大小进行调整

**Comment by DDXY1230** [comment]
stage环境

**Comment by Kvaya** [comment]
stage环境，谷歌浏览器，功能上没有问题

**Comment by Sandu1213** [comment]
stage环境验证通过
