### ISSUE TITLE
【bug-探索】页码没有刷新

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#4842]
操作步骤：点击探索，点击最下面页面，最后一点，点击综合下拉框选择最新或者热门，下面页码为最后一页。
结果：页面内容为第一页，页码是最后一页
![image](https://user-images.githubusercontent.com/28430070/60251609-6c23a780-98fb-11e9-8fa4-a58b57562079.png)

**Comment by Sandu1213** [comment]
stage验证通过
