### ISSUE TITLE
【Biz网站】公司介绍页面中公司简介类别页中的“详见：发展历程》”增加链接

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4865]
背景：
![image](https://user-images.githubusercontent.com/39363297/60407088-d4200980-9beb-11e9-9c9c-842405486c21.png)

解决方案：
“详见：发展历程 >>”跳转至：https://keepwork.com/official/company/roadmap

**Comment by Sandu1213** [comment]
@Kvaya 请去确认首页的发展历程问题，提醒相关人员进行调整
![image](https://user-images.githubusercontent.com/21214285/60489411-e4f97980-9cd6-11e9-8e18-be994f3fe9a0.png)

**Comment by Sandu1213** [comment]
首页问题另外跟进

**Comment by Kvaya** [comment]
首页问题等收到反馈后，另外建issue跟进
