### ISSUE TITLE
【dashboard】dashboard中项目管理页中对项目添加系统标签，系统标签显示项显示不对

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4868]
背景：
添加系统标签，应该显示：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/41136e9d-f758-452c-b244-efa7735be53f)

现显示的是：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/9a36d8c6-1cf7-4286-b5a7-7add1d2d52c7)

解决方案：
添加系统标签，标签来源于“系统标签页”中的设置好的标签

**Comment by Sandu1213** [comment]
stage环境验证不通过
![image](https://user-images.githubusercontent.com/21214285/60489830-deb7cd00-9cd7-11e9-9539-7fb8eb4896bc.png)

**Comment by Sandu1213** [comment]
release环境ok
