### ISSUE TITLE
【汉字大赛】汉字大赛页优化跟进

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4882]
背景：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/f1205eae-cac9-4f69-bdfe-26754abc86b1)

期望结果：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/216a97d5-570d-4fe7-bf90-38556167d11c)

另外补充：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/a0fb4ea2-6159-4c88-9df4-1b36e0556142)

**Comment by DDXY1230** [comment]
stage环境

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/60488486-aebafa80-9cd4-11e9-995b-d52a0d4a32f3.png)

**Comment by Kvaya** [comment]
补充;
![image](https://user-images.githubusercontent.com/39363297/60566310-25213080-9d99-11e9-821b-425df8d286f0.png)
