### ISSUE TITLE
【汉字大赛】汉字大赛报名表链接更改

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4892]
背景：
汉字大赛报名表之前是在私人账号，后更换成在一网乾坤那边的公开账号下。链接需更换。

期望结果:
公开组链接：http://qwijb4z0yf0b35zg.mikecrm.com/rO6zuJC ；
学生组链接：http://qwijb4z0yf0b35zg.mikecrm.com/ptz6tbX 。

**Comment by DDXY1230** [comment]
release环境

**Comment by Sandu1213** [comment]
release验证通过
