### ISSUE TITLE
【paracraft.org】paracraft.org网站To Developers页开发

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4905]
背景：
对国外市场推广做辅助工作

解决方案：
1.首页中
![image](https://user-images.githubusercontent.com/39363297/60643485-cfff2080-9e65-11e9-928c-bcd82c645f70.png)
和footer中的“To Developers”页都是跳转至开发的To Developers页；

2.设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/60638493-2d3ca700-9e51-11e9-9694-448eeaaf8c4b.png)
按这个模板开发，文案内容： https://github.com/LiXizhi/ParaCraftSDK/wiki/LetterToDevelopers ；

3.To Developers页的标题：logo+ To Developers | Paracraft;

**Comment by ZhangKaitlyn** [comment]
直接采用  https://github.com/LiXizhi/ParaCraftSDK/wiki/LetterToDevelopers
