### ISSUE TITLE
【dashboard】后台中可以参看绑定邮箱及修改绑定手机号、绑定邮箱等绑定账号

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4922]
背景:
现哈奇用户那边经常忘记密码，时有更换手机号

期望结果：
dashboard中"帐户/用户管理“页中的，用户列表中能记录及修改下面图的信息：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/1519af65-8fe5-4e42-9cdf-c683590e8326)

解决方案：
1.在用户列表中记录上面图中的6个信息内容；
2.操作栏中，分别添加”修改绑定微信、修改绑定微博、修改绑定QQ、修改绑定Github、修改绑定邮箱、修改绑定手机“，点击修改绑定按钮，弹出”修改绑定“窗口，重置绑定信息。
假设以”修改绑定微信“为例，在操作栏中点击”修改绑定微信“按钮，弹出
![image](https://user-images.githubusercontent.com/39363297/60796639-5d14e300-a1a0-11e9-8527-9b8b8738533e.png)

**Comment by Sandu1213** [comment]
这四个重置绑定功能没有提供，其他可以正常绑定及解绑
![image](https://user-images.githubusercontent.com/21214285/61207766-7da4e600-a728-11e9-8360-fc377cbcd010.png)
