### ISSUE TITLE
【Bug-在线展厅】在线展厅的条件筛选项顺序需要调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4929]
## The problem
在线展厅的条件筛选项顺序需要调整

## Environment

* OS Info: Window10
* browser Info: chrome  74.0.3729.157 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  在线展厅

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入在线展厅页面，根据不同的筛选项，对大赛项目进行筛选查看，观察显示情况

* Expected Result:
1.筛选项里“全部”总是显示在最前
* Actual Result:
1.“全部”显示顺序不对
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/5f24a925-586f-47a0-b70f-8d1697d750e8)

**Comment by Sandu1213** [comment]
问题依然存在
![image](https://user-images.githubusercontent.com/21214285/61210262-8993a680-a72e-11e9-8255-3cabeeb787de.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/61433873-08732400-a967-11e9-986b-b47340b96df3.png)

**Comment by DDXY1230** [comment]
release 环境
