### ISSUE TITLE
【Feature-机构使用问题】需要提供一个批量生成账号或者直接使用手机号添加学生的功能，请评估

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4944]
### Details:
   目前有机构使用人员反馈，因小学生不会或者不方便注册keepwork账号，希望可以提供批量生成keepwork账号的功能，然后他们将账号发给小学生再进行手机号绑定即可。或者添加学生时，能够提供根据手机号添加的功能，因为keepwork账号学生容易忘记，但手机号不会忘记。

   **请进行评估，并给出具体解决方案后转开发实现，谢谢。**

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/09f76456-11c4-4731-ba90-281a2d48c5e1)

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/7d535d0a-c0b8-49fb-912a-b1da8e40108a)

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/61202199-77f3d400-a719-11e9-945c-5eaf6ef9c906.png)
添加学生的时候，“用户名”调整为“用户名/手机号/邮箱”
纯数字认为是手机号，去查询关联的账号填入数据
有at符号，认为是邮箱，去查询关联的账号填入数据

因为需要实名认证，学生的手机号是必填的，我们的手机号是可以直接登录的

**Comment by Sandu1213** [comment]
手机号的判断建议严格一些，以“1”开头，长度为11位。
因为早期的一批哈奇玩家，有一大部分的纯数字账号转成了keepwork账号。

**Comment by Sandu1213** [comment]
请尽快实现，以便提供给机构客户使用。

**Comment by kevinxft** [comment]
release 环境测试，只做了可以以手机号，邮箱，账号添加学生的功能

**Comment by Sandu1213** [comment]
如果先输入学生名，则会出现添加不成功的情况，请调整
