### ISSUE TITLE
【Features-机构】机构负责人反馈需要批量生成学生账号及可以管理学生账号的功能，请补充

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4976]
### pre-condtion:         
>   目前机构负责人反馈说，学生注册账号不方便，建议增加批量生成学生账号的功能，同时，希望可以
>   自主为忘记密码的学生重置密码。

产品请评估后给出解决方案，涉及：
- 批量生成账号方案
- 教师可以给学生重置密码的功能
- 学生毕业后涉及的实名问题

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/61364949-5d586100-a8b9-11e9-9042-54b01b0cb4e0.png)
功能release结束，转ui设计

**Comment by dalin00** [comment]
![image](https://user-images.githubusercontent.com/24222876/61516191-07112c80-aa37-11e9-9566-af4fbc9ad3cf.png)
