### ISSUE TITLE
keepwork 支持 iframe

### ISSUE THREAD

**Issue by yuanoook** [tatfook/keepwork#498]
1. 支持 iframe 嵌入子项目的网站（lesson.keepwork.com)
2. 支持 iframe 外部样式调整
3. 支持 iframe 读取登陆信息

**Comment by leopoldchen** [comment]
@wxaxiaoyao 已经在解决了这个问题，是否 已经合并到主版本里了？

**Comment by wxaxiaoyao** [comment]
这个bug，我写了一种解决方式，发了一个到dev的pr， 后续还是前端的小伙伴基于新的方式做出合理的解决吧。 暂时转给 @yuanoook @leopoldchen

**Comment by leopoldchen** [comment]
@Sandu1213 

此外还新增了@IFrame mod，可以设置宽度高度，目前样式图片不正确，直接使用了markdown的图片

**Comment by Sandu1213** [comment]
~~1.支持 iframe 嵌入子项目的网站（lesson.keepwork.com)~~    --**验证通过**  
~~2.支持 iframe 外部样式调整~~    --**验证通过**  
3.支持 iframe 读取登陆信息    --**待验证**

**Comment by Sandu1213** [comment]
@wanglin727  麻烦帮忙提供一下iframe的样式图
