### ISSUE TITLE
【Bug-机构】新用户自主找到机构后，购买引导说明需要调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#4980]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/055dab73-9c84-4dcf-8f3a-509444056116)

**Comment by Sandu1213** [comment]
@azothli 帮忙评估一下

**Comment by azothli** [comment]
可以的，增加到管理员的设置中吧
![image](https://user-images.githubusercontent.com/22001356/62450492-00a4e380-b79f-11e9-90f1-20a08233876a.png)
