### ISSUE TITLE
【Biz网站】biz.keepwork.com提交表单中增加“机构规模”选项

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4988]
背景：
![`UD~G]S6V9@7RY_O`4_7N1R.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/e7e254b2-a96d-4860-95a3-90ca3c7f8dcd)

解决方案：
![((W4KZ)9$E5JJ%A5J5C{JEI.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/cd84ff4a-ca77-46bf-9bde-e7a1b75cff3e)
1.在表单中，“所在城市”后面添加“机构规模”选项，选填，输入框中，默认提示语：请输入单位或机构的规模人数。
补充：默认提示语的字体颜色跟表单上面其他输入框中的默认提示语颜色一致。

2.dashboard中“合作申请”页面，合作申请机构列表中增加一属性“机构规模”，记录表单填入的机构规模数据；操作栏中的“编辑”，点击编辑，弹出窗中增加“机构规模”项，选填，是想让相关人员问到机构规模后，之前没有填的，后续我们可自己填上去；目前编辑权限是管理员，后续可再增加对人员编辑权限的设置。

**Comment by Sandu1213** [comment]
Dashboard里的“机构规模”项，无法进行编辑，请调整

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/61940907-f4fc3480-afc8-11e9-897d-790207b4a4c6.png)
