### ISSUE TITLE
【keepwork.com】keepwork.com网站底部的“keepwork”能被点击

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4996]
背景：
收到反馈，希望keepwork.com网站底部的“keepwork”能被点击，跳转至keepwork.com首页

解决方案：
![image](https://user-images.githubusercontent.com/39363297/61626785-c4f31f80-acb0-11e9-9978-418c56aef116.png)
点击红色框内的“keepwork”跳转至：https://keepwork.com/

**Comment by Sandu1213** [comment]
stage环境验证通过
