### ISSUE TITLE
【Biz】Biz网站申请表单后，我们部分相关人员会收到一封邮件，该邮件增加记录“机构规模”该项

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#4999]
背景：
Biz网站申请表单后，我们部分相关人员会收到一封邮件；
现表单增加了“机构规模”一项。

解决方案：
![image](https://user-images.githubusercontent.com/39363297/61775382-71591100-ae2b-11e9-9e33-ae3cc2c87f39.png)

**Comment by Sandu1213** [comment]
@Kvaya 因无法收到对应邮件，请验证一下。3Q

**Comment by Kvaya** [comment]
http://biz-release.keepwork.com/ 环境测试，邮件显示结果如下：
![image](https://user-images.githubusercontent.com/39363297/61785261-e7667380-ae3d-11e9-97ee-e006132e456e.png)
效果按需求来了
