### ISSUE TITLE
【Bug-Dashboard】无法进行消息发送，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5007]
## The problem
无法进行消息发送，请调整

## Environment

* OS Info: Window10
* browser Info: chrome  74.0.3729.157 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  Dashboard->消息

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入Dashboard后台，选择消息对指定人员进行消息发送，观察发送结果

* Expected Result:
1.消息发送成功
* Actual Result:
1.消息发送失败
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/02a159f6-aecf-4e43-be23-dbac5bb49a5f)

**Comment by kevinxft** [comment]
表单验证部分的问题，没有找到合适的解决方法，暂时先把表单验证去掉，
