### ISSUE TITLE
【Paracraft to c】Paracraft to c 网站首页开发

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#5013]
背景：
为了推广paracraft，开发paracraft to c网站，首页开发

解决方案：
![image](https://user-images.githubusercontent.com/39363297/62028733-8b239b00-b213-11e9-8a87-314ab527878f.png)

设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/62028549-181a2480-b213-11e9-8b68-747eb6ebc025.png)

补充：底部需统计当天当前时间当页的访问量

**Comment by Sandu1213** [comment]
访问量总结不对，总是1

**Comment by wxaxiaoyao** [comment]
nginx 配置需要将客户端IP 传到server端
