### ISSUE TITLE
【Paracraft to c】Paracraft to c 网站下载页开发 

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#5014]
背景：
为了推广paracraft，开发paracraft to c网站，下载页开发

解决方案：
![image](https://user-images.githubusercontent.com/39363297/62028733-8b239b00-b213-11e9-8a87-314ab527878f.png)

设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/62028834-d047cd00-b213-11e9-93fc-544eca5a1d44.png)

补充：底部需统计当天当前时间当页的访问量

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/62757814-09532d80-baaf-11e9-816b-8ea40497741f.png)

**Comment by wxaxiaoyao** [comment]
nginx 配置需要将客户端IP 传到server端
