### ISSUE TITLE
【Paracraft to c】Paracraft to c 网站更多页开发 

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#5015]
背景：
为了推广paracraft，开发paracraft to c网站，更多页开发

解决方案：
![image](https://user-images.githubusercontent.com/39363297/62028733-8b239b00-b213-11e9-8a87-314ab527878f.png)
期望结果：
http://paracraft.keepwork.com/home/what-is-paracraft?lang=zh 该链接内容的header和footer跟现在开发的to c网站的header和footer一样。

补充：底部需统计当天当前时间当页的访问量

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/62757556-3ce18800-baae-11e9-9d3a-c28ca7553c10.png)
