### ISSUE TITLE
网络安全 - 账号信息问题

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#5052]
![image.png](https://images.zenhubusercontent.com/59bb76d4b0222d5de477d44e/666847ba-1194-4c61-8701-ec20fab122b3)

问题api：user的detail api会返回用户详情信息
问题：
1、此api可以通过用户id访问，因此很容易遍历所有用户
2、此api返回的信息过于丰富，包括用户手机、邮箱、余额等非必要信息

解决方案：
1. 禁止用id访问数据
2. 精简返回数据，只返回有需要的数据

**Comment by Sandu1213** [comment]
users接口，release环境已经验证，目前返回信息已移除手机/邮箱/余额等信息
