### ISSUE TITLE
【Bug-学习总结分享】通过QQ进行学习总结分享时，分享失败，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5061]
### Details:
1.学生进入机构自学完成后，将学习总结通过QQ进行分享，观察分享结果

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/6a20238f-a553-4d34-bc9d-616151582248)
![image](https://user-images.githubusercontent.com/21214285/62450508-04d10100-b79f-11e9-8114-aeb44ec8f965.png)

**Comment by leopoldchen** [comment]
@shirleyluo1130  
根据新的设计，这个功能应该可以关闭了把

**Comment by shirleyluo1130** [comment]
课程教学流程调整，关闭该功能
