### ISSUE TITLE
keepwork网站注册调整

### ISSUE THREAD

**Issue by azothli** [tatfook/keepwork#5076]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/c2f90794-cffb-46b1-8574-8536ce8b2770)

注册时，实名变成可选
实名与绑定不再有相关逻辑（取消以前的自动绑定）
新增密保提醒

**Comment by ZhangKaitlyn** [comment]
![R(KR1I9 CPV~7IJ18EN_E(T](https://user-images.githubusercontent.com/18642919/63071041-2759db80-bf50-11e9-97f7-0464876042ba.png)

**Comment by ZhangKaitlyn** [comment]
[需要检测实名的位置.docx](https://github.com/tatfook/keepwork/files/3508707/default.docx)
![image](https://user-images.githubusercontent.com/18642919/63154138-91eb4400-c042-11e9-8e05-cd970598602a.png)

**Comment by Sandu1213** [comment]
1.通过个人设置页进到实名认证页面，无法进行认证
![image](https://user-images.githubusercontent.com/21214285/63252331-36b78c80-c2a2-11e9-9057-51c6aba3f1ba.png)
2.可通过路由跳过验证，进入编辑器，可创建网站成功
3.可在个人设置页正常使用网盘
