### ISSUE TITLE
lesson：机构激活码生成调整

### ISSUE THREAD

**Issue by azothli** [tatfook/keepwork#5082]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/f88564ad-1257-4c1e-b0d7-1c75ce14b2c2)

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/da8ab570-3feb-44fb-b0fc-a88008868f8a)

**Comment by kevinxft** [comment]
@azothli  没有找到新的激活码设计图

**Comment by kevinxft** [comment]
release 环境测试

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/63256870-2061fe80-c2ab-11e9-9737-0b5ecce67db3.png)
![image](https://user-images.githubusercontent.com/21214285/63256948-4d161600-c2ab-11e9-9088-65c6acac1321.png)
![image](https://user-images.githubusercontent.com/21214285/63257519-88651480-c2ac-11e9-8caf-c1da5fcd4536.png)

**Comment by Sandu1213** [comment]
待样式优化完成后再验证
