### ISSUE TITLE
lesson：机构日志

### ISSUE THREAD

**Issue by azothli** [tatfook/keepwork#5085]
只有管理员与老师有
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/1dfa705a-4bff-4a3f-b8fd-42e5d75c7a43)

分类与提醒
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/e16c9930-0e98-4149-abd3-ca0d20071b55)

**Comment by Sandu1213** [comment]
@azothli 宇哥，请帮忙确认回复一下。
@duting1993 测试的时候请关注。
![image](https://user-images.githubusercontent.com/21214285/63745073-d47b0f00-c8d3-11e9-9862-4255505f0547.png)

**Comment by wxaxiaoyao** [comment]
尽量别做完啦提一推需求确认的问题。。。。

**Comment by Kvaya** [comment]
Q1.日志都需要记录操作者的信息及操作时间，
A1：采纳建议，记录相关keepwork账号、操作时间

Q2：这里的添加记录是教师的账号名名称，而不是姓名。建议都记录，如：添加老师：陈老师-chenbing(姓名-账号名）移除建议同步调整
A2：采纳建议，添加/移除老师用(姓名-账号名）

Q3：如果编辑时未进行任何修改，是否会保存日志？
A3：不保存日志，因没做任何更改

Q4：如果同时修改班级名称、班级有效期及课程包信息，则是否一次性记录成3条？(可能会产生大量日志）
A4:生成3条记录；方便日志查询，可读性强、清晰

Q5：目前生成邀请码，可以根据学生姓名来生成，则按学生姓名生成时，也是记录生成个数？
A5：按个数生成，记录个数；
按学生姓名生成，记录学生姓名

Q6：这些操作是否还是指记录老师。自学只能记录学生端
A6：进入课程、返回课堂记录老师和学生的；自学记录学生端；离开课堂记录学生
