### ISSUE TITLE
lesson：班级首页调整

### ISSUE THREAD

**Issue by azothli** [tatfook/keepwork#5088]
增加本班同学最新更新

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/2ba44db8-884b-4a64-acdc-20bee8fac5ea)

增加本班成员显示
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/bd674576-f441-4206-ba34-6273af6dfeb5)

最新更新，全部更新，显示每个人的更新内容
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/66ae206c-e390-4268-8998-7d00aa4a8a3e)

**Comment by shirleyluo1130** [comment]
增加班级切换功能。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/3a8a7db0-f727-444c-b04c-a0a209493dd4)
