### ISSUE TITLE
【keepwork.com】keepwork.com网站footer鼠标移入时，可点击跳转的菜单项，字体颜色变化

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#5089]
背景：
keepwork.com网站footer鼠标移入时，可点击跳转的菜单项，字体颜色变色，表明该项是可以点击跳转的

解决方案：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/f25ce4fe-e81a-4542-8c78-b08a1dd42655)
上面红色框内的菜单项，鼠标移入时，字体颜色变色

**Comment by duting1993** [comment]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/e049e0d8-b18b-4500-9e4f-0c7cae0ad231)显示结果如图

**Comment by Kvaya** [comment]
底部变亮，效果可以
