### ISSUE TITLE
【paracraft to c】http://pa.keepwork.com/download 下载数据没加上真实的数据

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#5090]
背景：
http://pa.keepwork.com/download 下载量这边设了一个初始值，103200人，后续下载量是在初始值累加的
实际下载量是后续累加的下载量

问题：
现页面没有加上真实下载量

**Comment by wxaxiaoyao** [comment]
已修复

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/62757666-a5306980-baae-11e9-88f2-6e57883fb6a5.png)
@Kvaya 确认后回复一下，如果不需要，则验证通过。

**Comment by Kvaya** [comment]
![image](https://user-images.githubusercontent.com/39363297/62848174-d6a67080-bd0c-11e9-9806-bd0e22b559bc.png)
