### ISSUE TITLE
【Paracraft to c】Paracraft to c 网站中英文切换

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#5093]
背景：
![image](https://user-images.githubusercontent.com/39363297/62772296-bdfe4680-bad1-11e9-99b0-bc1cbb5bfda1.png)

期望结果：
1.在网页上header上有个中英文切换按钮，进行切换中英文环境，英文环境链接：https://paracraft.org

2.检测到对方是非中文系统，弹出弹窗，如下图：
![image](https://user-images.githubusercontent.com/39363297/62844198-2b88bd80-bcf2-11e9-8fe7-31b803570890.png)
3.刷新情况：
1）之前是中文环境，刷新网址，还是中文环境；
2）之前是英文环境，刷新网址，还是英文环境。

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/62771794-9c508f80-bad0-11e9-9dd4-3b1cf5f5e236.png)
![image](https://user-images.githubusercontent.com/33826048/62771836-b1c5b980-bad0-11e9-9303-524e9bd0830e.png)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/62772452-28af8200-bad2-11e9-8f03-7cc9bfbf6e8f.png)

**Comment by Kvaya** [comment]
http://pa-stage.keepwork.com/ 环境，谷歌浏览器语言改成英文，情况如下：
