### ISSUE TITLE
【paracraft.org】paracraft.org下载页优化

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#5096]
背景：
![0 B)RP7W`%K BCW@9FQLQQ4](https://user-images.githubusercontent.com/39363297/62922882-15a4f680-bddf-11e9-822b-30ce2ab4a0d8.png)
现重做了to c网站，而to c网站的下载页是中文版的，切换英文，跳转至paracraft.org网站，一点download又重新跳转至之前的http://paracraft.keepwork.com/download ，效果不佳

解决方案：
http://paracraft.keepwork.com/download 英文环境下的正文内容放在在http://paracraft.org/ 域名下，header和footer跟http://paracraft.org/ 保持一致

备注：
![image](https://user-images.githubusercontent.com/39363297/62931297-b18b2e00-bdf0-11e9-8ce3-ac097562eb76.png)
这四处链接在 #5094 中的后台更改后，http://paracraft.org/ 的下载页各个版本的链接也会实时更新；
其中生成二维码图片的那个链接是根据dashboard中“Android版手机APK安装包”链接实时更新

**Comment by dalin00** [comment]
![paracraft org下载页面](https://user-images.githubusercontent.com/24222876/62935973-1f3c5780-bdfb-11e9-9d3c-54cc4fa83fbf.png)

![image](https://user-images.githubusercontent.com/24222876/62936025-409d4380-bdfb-11e9-8129-55d693e8fea6.png)

**Comment by Kvaya** [comment]
点击跳转情况：
1.
![image](https://user-images.githubusercontent.com/39363297/63076310-5def2080-bf67-11e9-84d4-c85968f6fece.png)，跳转链接：
https://www.evernote.com/shard/s177/client/snv?noteGuid=f876e8cb-4563-4b26-ba23-55524609b79d&noteKey=89b1fed1ca2e1eb1&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs177%2Fsh%2Ff876e8cb-4563-4b26-ba23-55524609b79d%2F89b1fed1ca2e1eb1&title=%2523%2523%2BParaCraft%2BChange%2BLog%2B2019

2.

**Comment by Kvaya** [comment]
http://release.paracraft.org/download 环境，
![image](https://user-images.githubusercontent.com/39363297/63242223-41b1f300-c289-11e9-9b1f-effcd8daa483.png)
链接地址应是：https://github.com/LiXizhi/ParaCraftSDK/wiki/ParacraftFeatures

**Comment by Kvaya** [comment]
![image](https://user-images.githubusercontent.com/39363297/63405453-72289700-c419-11e9-9920-e9dba83427cd.png)
上面标红处，之前没有协商好，现结果是统一跳转至https://keepwork.com/official/docs/Resource_en/intro

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/63491709-7ffa1d00-c4ea-11e9-809d-275b0b70fc6a.png)
