### ISSUE TITLE
作品详情页需要Paracraft的视频，在worldshare上传时生成

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#510]
请产品先过一下，看看需求

**Comment by azothli** [comment]
直接生成对应世界的视频应该是不现实的，这个需要用户压缩生成才行。
默认我们可以用一个paracraft的宣传短片或者片头来做占位，鼓励用户替换。
类似：
![image](https://user-images.githubusercontent.com/22001356/41449355-394746d2-7093-11e8-9d5b-d434c5685a27.png)

**Comment by onedou** [comment]
请提供默认视频的地址

**Comment by Sandu1213** [comment]
类似效果：
https://stage.keepwork.com/testv2/paracraf/index

**Comment by Sandu1213** [comment]
已找宇哥确认过，请在worldshare里实现。  @onedou
