### ISSUE TITLE
【to c】https://pa.keepwork.com/download 下载页面中的安卓版的扫二维码出现的链接更改

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#5100]
背景：
现微信和QQ扫二维码出现的链接跳转至华为应用商店，不便于为我们Paracraft APP带来流量

解决方案：
1.扫二维码后，跳转链接变为手机apk链接；
2.手机apk链接根据dashboard中版本链接中的设置的手机apk链接实时更新；
3.微信扫二维码后，可能会出现一片空白（没有任何提示），请弹出提示，参考原型：
![image](https://user-images.githubusercontent.com/39363297/63089711-5b062700-bf8b-11e9-9563-86df7c2b366d.png)

**Comment by dalin00** [comment]
![画板-1](https://user-images.githubusercontent.com/24222876/63141043-ccd78280-c016-11e9-925d-ba2775bcc338.png)

![image](https://user-images.githubusercontent.com/24222876/63141371-05c42700-c018-11e9-90ff-aed7a2cd273f.png)
