### ISSUE TITLE
【bug-机构招生】管理员端-表单管理：表单URL页，排版未居中。如下

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5109]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/aa9392fe-5dc9-48f1-9dc1-c9a4a87f5502)

**Comment by duting1993** [comment]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/47ccc368-b2de-4d98-bbe1-89c6bdff3ee5)
