### ISSUE TITLE
【bug-机构招生】管理员端-表单管理：报名表单，停止收集后，提交按钮缺失。详情如下

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5111]
建议：停止收集后，还是保留提交按钮。点击的时候，提示：该表单已停止收集。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/69f66a89-b75c-43ee-9f7b-3176c1a85a2b)

**Comment by duting1993** [comment]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/1262983f-1c2b-4513-bd94-ba5646dead63)
显示结果如下
