### ISSUE TITLE
【bug-机构招生】登录url页面，文字调整，如下

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5114]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/cb980020-c7a3-49a3-8106-4a669224b304)

**Comment by duting1993** [comment]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/12d57a2a-4e0c-4b96-85d7-8b9432666eda)
