### ISSUE TITLE
【bug-机构招生】管理员端-表单管理：预览表单内容时，预览页会覆盖掉当前编辑页。预览后无法回到之前的编辑状态。不合理。建议新窗口打开预览页。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5116]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/e6d3c8c6-6983-4690-9427-a582434abed4)

**Comment by kevinxft** [comment]
修改前:
![image.png](https://images.zenhubusercontent.com/59edff22a468affe6df7caf6/a0206665-edbf-4082-90a1-9d6fb5055414)

修改后:
![image.png](https://images.zenhubusercontent.com/59edff22a468affe6df7caf6/81632998-729a-4fc8-9725-57dd007e0115)
