### ISSUE TITLE
【优化-机构招生】管理员端-表单管理：删除表单时，缺少提醒。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5139]
如下图，删除表单时，建议加上删除提醒。确定删除该表单吗？ 
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/9ebad5a1-85b1-426d-bc8a-53873383d338)

**Comment by duting1993** [comment]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/38d7507e-3bf4-4431-ade8-92166944f5d6)
