### ISSUE TITLE
【海外版】 facebook登录

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#515]

**Comment by Sandu1213** [comment]
**海外版问题记录：**   ---（针对地址：stage-en.keepwork.com）  
1.google 授权登录不成功
2.facebook 授权登录不成功
3.个人设置中心->实名认证功能需要移除
4.编辑器页面，空白页创建新网站功能不可用  ---stage环境已修改，同步即可
5.很多页面涉及中英文混合的（例如：新建网站，修改网站设置提醒等等）
6.涉及到支付模块的还未调整（应该不仅仅支持支付宝和微信）
7.网盘管理（涉及上传的文件，还是上传回国内的七牛云？）
8.用户分享功能，应该需要对接facebook和Twitter（目前是QQ，wechat,微博）
9.首页及配套相关的网站是否需要英文版？----需要产品确定
![image](https://user-images.githubusercontent.com/21214285/40777739-4a10206c-6501-11e8-8e75-c2a3fc27804a.png)

**Comment by azothli** [comment]
9 需要

**Comment by Sandu1213** [comment]
@leopoldchen @azothli 请明确下6/7/8这几个问题，具体实现是？

**Comment by leopoldchen** [comment]
@Sandu1213 @azothli 
支付和分享等功能应该暂时都屏蔽吧，并没有针对海外版开发这部分功能
网盘暂时也只能传七牛，对接国外云存储也应该需要一定时间

**Comment by azothli** [comment]
6.涉及到支付模块的还未调整（应该不仅仅支持支付宝和微信）  海外支付途径还没有开通，需要什么待定
7.网盘管理（涉及上传的文件，还是上传回国内的七牛云？）  这个要测试下，国内的七牛是否可以海外使用，再做判断
8.用户分享功能，应该需要对接facebook和Twitter（目前是QQ，wechat,微博）   是的

**Comment by Sandu1213** [comment]
~~1.google 授权登录不成功~~  --- Https下验证通过  
~~2.facebook 授权登录不成功~~ --- Https下验证通过  
~~3.个人设置中心->实名认证功能需要移除~~  --- stage环境已经调整  
4.编辑器页面，空白页创建新网站功能不可用 ---同编辑器无法新建网站问题一同跟进  
5.很多页面涉及中英文混合的（例如：新建网站，修改网站设置提醒等等） ---由 #777 跟进  
6.涉及到支付模块的还未调整（应该不仅仅支持支付宝和微信） ---已有单跟进  
7.网盘管理（涉及上传的文件，还是上传回国内的七牛云？）  ---已有单跟进 
8.用户分享功能，应该需要对接facebook和Twitter（目前是QQ，wechat,微博） ---待屏蔽  
9.首页及配套相关的网站是否需要英文版？  ---需要逐步调整，稍后提单单独跟进
