### ISSUE TITLE
PPT mod 

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5184]
## 需求描述：
由于课程模式调整，每个课程包含教案、课件、视频。课件以PPT的形式进行展示，目前Editor中的mod无法完成课件的制作。需增加 PPT mod

## 具体方案如下：

1、属性编辑区：（初始状态）
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/59c9164d-cbaa-46ce-bc81-5585afd561da)

2、样式编辑区：（暂时只提供一种样式，纯黑背景）
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/45d90be0-697b-4f49-9e1f-97fd97dc1662)

3、添加 图片/视频，调用网盘功能，支持批量添加
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/0ecac0f7-7b47-4bab-90c1-f098696a8f28)

4、属性编辑区：（添加图片/视频后）
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/7c641c7c-7f0d-485d-a945-477ce8e8f097)

**Comment by shirleyluo1130** [comment]
PPT支持全屏播放

**Comment by leopoldchen** [comment]
全屏简单设计一下吧 @shirleyluo1130

**Comment by leopoldchen** [comment]
预览区直接渲染ppt，并在ppt之上添加全屏按钮 @kevinxft
