### ISSUE TITLE
【Bug-注册】注册时，提示信息不明确，不便用户进行使用

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5189]
## The problem
注册时，提示信息不明确，不便用户进行使用

## Environment
* OS Info: Window10
* browser Info: chrome  74.0.3729.157 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  Register

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面

* Details:
1.进入Keepwork首页，进行注册操作
2.注册的时候，填写账户名为“字母+特殊字符+字母”，观察是否可以注册成功
3.注册的时候，账户名含敏感词，观察是否可以注册成功
4.注册的时候，账户名为纯数字账号，观察是否可以注册成功
5.注册的时候，账户名为重复账户名，观察是否可以注册成功
6.注册的时候，使用字母+数字组合进行注册，观察是否可以注册成功

* Expected Result:
除了第6条可以正常注册外，其他都注册失败，且提示语信息明确合理
* Actual Result:
提示语不明确，都是提醒“注册失败”，不清楚哪里出问题了
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/879550e8-1be8-4193-8a09-52b68246425d)

**Comment by duting1993** [comment]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/0c200bf3-f9a7-454f-a33e-0c14d10524bf)
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/72547d35-7637-4d7c-86ec-c9ea4cae8c5a)
