### ISSUE TITLE
【bug-机构】添加教师修改为配置老师

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#5200]
![image](https://user-images.githubusercontent.com/28430070/63936051-7e53ca80-ca91-11e9-9da8-dd1babc6a601.png)

**Comment by shirleyluo1130** [comment]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/9f1b9d13-163e-4a5e-a73a-5399060fd686)
