### ISSUE TITLE
【优化-表单管理】“表单url页 - 扫一扫，手机继续看”，在手机上的视觉效果不好，需要做下适配。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5207]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/ddaa4633-0341-45cf-a626-f7eeec8d2012)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/4df4cff0-a6de-4949-b2b1-0f53f862a588)

**Comment by duting1993** [comment]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/26bef867-a2fc-4f13-91be-6642d884d4c2)
