### ISSUE TITLE
【Bug-班级管理】配置老师页面，对老师进行移出操作，实现不合理

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5210]
## Detail:

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/345341ea-ac34-41ec-829d-417c45fa236e)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/48b5b3fa-c2bc-4deb-be92-d5c999e2532d)

**Comment by ZhangKaitlyn** [comment]
![UHMBI(Y4IX~_GLMT3JN}$E2](https://user-images.githubusercontent.com/18642919/64245173-0546ee00-cf3d-11e9-8f73-930f141b4087.png)
