### ISSUE TITLE
【网盘】单选模式、多选模式

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#5213]
![image.png](https://images.zenhubusercontent.com/59df33a4b0222d5de47b5b3c/66f6f4b6-a80f-4e13-a51e-eddeadf7eb34)

**Comment by duting1993** [comment]
ppt可多选
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/6aff55fb-93b8-4a9e-b069-466b97aca79e)
