### ISSUE TITLE
【Bug-注册】注册时，用户输入手机号，不自动绑定账号，待用户手动去绑定

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5217]
### Details:
    1.新用户注册时，直接输入手机号进行注册，注册完成后去设置中心进行查看
    2.观察手机号是否已经绑定 

   **Expected Result:**
    1.手机号没有绑定，有弹窗提醒用户去绑定

  **Actual Result:**
    1.目前程序自动帮忙绑定了，请调整一下

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/7b732660-7e14-4cfb-97f3-26e7ef0f67c9)

**Comment by wxaxiaoyao** [comment]
Why?
