### ISSUE TITLE
【Bug-第三方绑定】第三方绑定失效，请排除(提示绑定成功，实际绑定失败)

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5266]
## The problem
第三方绑定失效，请排除(提示绑定成功，实际绑定失败)

## Environment

* OS Info: Window10
* browser Info: chrome  74.0.3729.157 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  第三方绑定

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入个人设置中心，对QQ/wechat/weibo进行绑定操作，观察绑定结果

* Expected Result:
1.可以正常绑定成功
* Actual Result:
1.绑定失败(提示绑定成功，实际绑定失败)
 

## Attachments (eg:logs/video/screenshot)

**Comment by wxaxiaoyao** [comment]
复现不出来的....
