### ISSUE TITLE
【Bug-样式问题】页面导航路径栏里的私有网站的图标显示样式有误，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5268]
## The problem
页面导航路径栏里的私有网站属性显示样式有误，请调整

## Environment
* OS Info: Window10
* browser Info: chrome  74.0.3729.157 
* URL: [keepwork.com](https://keepwork.com) 
* Model: 样式问题

## Step To Reproduce Issue [ Good To Have ]
* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.登录账号后，打开自己创建的网站，在新页面进行查看
2.从页面导航路径栏里进行切换，观察私有网站的属性图标显示是否正确

* Expected Result:
1.显示合理，名称后面紧随图标标识
* Actual Result:
1.显示不美观
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/83085acd-1847-4e47-bb92-dc5d8b6d5957)

**Comment by duting1993** [comment]
测试地址dev
