### ISSUE TITLE
探索调整：需要过滤掉未实名作者的作品

### ISSUE THREAD

**Issue by azothli** [tatfook/keepwork#5270]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/b0c2f943-8271-469d-aca7-a01ce831b54a)
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/99118ab3-613a-4094-9999-7971114f6a32)

未实名的作品大家无法查看，不适合展示，允许搜索，默认不展示（可以丢到最后去）

**Comment by duting1993** [comment]
测试环境，线上
