### ISSUE TITLE
【feedback-网盘】网盘如何保障不重名的问题

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5272]
### Details:

     
   网盘设计时，要求不能上传重名文件，但目前可以通过ctrl+c复制粘贴的方式，在代码区进行上传，上传的文件会是重名的。例如：image.png
       请评估一下如何调整

**Comment by azothli** [comment]
参考windows的文件名重复处理
@Kvaya

**Comment by Kvaya** [comment]
1.网盘和代码上传文件时，文件名称获取文件本身名称；
2.假设上传名称与网盘的文件名重复，可以参考windows的自动重命名机制，也可以自动在上传文件名称后加个（1）
