### ISSUE TITLE
【bug】账号退出问题

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#528]
操作步骤：
1.注册账号-注册成功-跳转到个人主页-设置中心-解绑手机号-解绑成功
2.在设置中心，头像下来框，退出账号
![image](https://user-images.githubusercontent.com/28430070/40151575-78ad95b6-59b3-11e8-854e-94ee8d8489fe.png)
结果：无法退出账号，若点头像下拉框，我的个人主页，重新退出，方可退出账号，
![image](https://user-images.githubusercontent.com/28430070/40151699-103a054a-59b4-11e8-8e81-ccf05b1ade58.png)

测试环境：stage.keepwork.com

**Comment by leopoldchen** [comment]
duplicate
