### ISSUE TITLE
【机构教学流程调整】我创建的课程 - 课程：去掉“课程名称”的点击效果及mouse over 提示。课程名称，不可点击。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5293]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/449bcede-8e5b-4b4c-ba78-e8836975ad88)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/f717e4ff-7bbf-482e-a2af-d0e29ced73e5)

**Comment by duting1993** [comment]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/4eb62f00-163e-4cb9-95b8-73de43dff5c8)
