### ISSUE TITLE
【机构日志】机构表单有的项显示内容少，有的多，内容多的未显示全

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#5309]
## Step To Reproduce Issue 

* Pre-conditions:
1.环境：Paracraft试学体验馆（对内）
2.身份：管理员、老师

* Details:
1.进入机构日志页面，浏览机构日志表单

* Expected Result:
1.“时间”“事件类型”“内容”“姓名”每列内容尽量显示全

* Actual Result:
1.“内容”项内容多，未显示全
![image](https://user-images.githubusercontent.com/39363297/64750432-7db83b00-d54b-11e9-8050-365b05cfa853.png)

* Solution:

“内容”项，字符多；“事件类型”项，字符少
可按下面两种方式来调整：
方式一：表单中，事件类型与内容两列之间的那条线，可以左移一些
![image](https://user-images.githubusercontent.com/39363297/64750449-8d378400-d54b-11e9-81a0-9c9410eb418f.png)

方式二：保证表单整体框架大小不变，中间2条线变为可以左右自由调节，鼠标hover时做提示，标识可左右移动线
![image](https://user-images.githubusercontent.com/39363297/64750475-a3454480-d54b-11e9-9bc4-2db1d15f54d2.png)

**Comment by ZhangKaitlyn** [comment]
1. 线上 hover后已经有显示了
![O VQO50)NV`@)K_$1{LR`A7](https://user-images.githubusercontent.com/18642919/65004976-e549fe00-d930-11e9-9046-984dd1f9922a.png)
2. 线上 表格头部的区域也是可以拖拽调整宽度的
![XZA8L29Y0$T7Q6KCWKC4L@5](https://user-images.githubusercontent.com/18642919/65004981-eb3fdf00-d930-11e9-83f9-61b7ad64b98f.png)

**Comment by Kvaya** [comment]
![LS 4WI6FE{7ULOUYS)U8DKV](https://user-images.githubusercontent.com/39363297/65014973-cb211780-d952-11e9-8e90-88f3f47d6065.png)
