### ISSUE TITLE
【机构日志】时间选择可选某一段时间

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#5312]
## The problem
1.时间组件，选定某一个固定开始时间，点“确定”，表单没有任何变化
2.选某一段时间，不能选择
3.时间点未显示全

## Step To Reproduce Issue 
* Pre-conditions:
1.环境：Paracraft试学体验馆（对内）
2.身份：管理员、老师

* Details:
1.进入机构日志页面，选择时间，想看某一段时间的机构日志详情
2.时间组件，选中9月12日，点“确定”按钮，再点“搜索”按钮，表单内容是所有日志显示
3.时间点未显示全

* Expected Result:
1.进入机构日志页面，选择时间，能选择某一段时间，看这段时间的日志显示
2.选定某固定开始时间，表单内容是从这个开始时间开始的
3.时间点显示全

* Actual Result:
1.进入机构日志页面，选择时间，不能选择某一段时间，
2.选定某固定开始时间，表单显示是所有时间的日志
3.时间点未显示全（可缩小“事件类型”组件宽度，增大“开始时间”组件宽度）

**Comment by wanglin727** [comment]
![日志搜索](https://user-images.githubusercontent.com/33826048/65111069-244d8180-da0d-11e9-9d70-68c382a03313.png)
