### ISSUE TITLE
【Bug-机构日志】机构日志显示建议精确到秒，以便操作后更准确的进行查看

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5334]
## The problem
机构日志显示建议精确到秒，以便操作后更准确的进行查看

## Environment

* OS Info: Window10
* browser Info: chrome  74.0.3729.157 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  机构日志

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入机构页面，添加老师，然后对老师进行改名操作，观察日志记录情况

* Expected Result:
1.日志记录正确
* Actual Result:
1.日志排序容易混淆，请调整
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/95b45475-27bc-4484-ba4f-d0894ef1cc6d)

**Comment by Kvaya** [comment]
建议前端UI显示，可以不精确到秒，排序规则后端 精选到秒倒序排序
