### ISSUE TITLE
【Bug-注册】注册时，创建用户账号失败，不应该直接返回“创建git用户失败”，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5341]
## The problem
注册时，创建用户账号失败，不应该直接返回“创建git用户失败”，请优化

## Environment

* OS Info: Window10
* browser Info: chrome  74.0.3729.157 
* URL: [keepwork.com](https://keepwork.com) 
* Model:  注册

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面

* Details:
1.注册用户时，输入用户名“Captain1099”,然后输入密码及手机号，输入错误的验证码，观察注册结果

* Expected Result:
1.注册失败，会提示“验证码错误”
* Actual Result:
1.注册失败，提示“创建git用户失败”，这个属于程序内部错误，不应该直接对用户展示，请调整
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/332828c5-daf9-46ab-9c53-3f955333025a)

**Comment by Sandu1213** [comment]
@wxaxiaoyao  请先排查下为什么会出现创建git用户失败的情况，正常情况下都应该是创建成功的。
@ZhangKaitlyn  请把提示优化一下，具体可以找产品一起敲定下。

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/69506539-08fd7600-0f6a-11ea-8912-8b88f96ee247.png)

-1 发生了一个未知错误，请重试（-1）
0 服务器繁忙，请重试（0）
1 账号火密码错误，请重试（1）
2 该用户名不可用（2）
3 该用户名不可用（3）
4 验证码过期，请重试（4）
5 验证码错误，请检查（5）
6 发生创建异常，请重试（6）
8 该用户名不可用（8）
