### ISSUE TITLE
【机构日志】日志表单，表头“姓名”改为“操作者”

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#5347]
## The problem
在测试搜索功能时，在输入框“操作者”输入表单下的“姓名”列的姓名，会不确定该姓名是否在这输入框搜索

##  solution
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/7dae7336-5fa3-45b5-8491-7f394ca02a5a)

**Comment by Sandu1213** [comment]
dev环境已修复
