### ISSUE TITLE
【Feature-项目】目前无法快速区分项目哪些是公有的，哪些是私有的，请设计一下

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5364]
### Details:
   目前我们的私有项目虽然不在搜索页面展示，但当用户自己创建的项目多了以后，无法快速区分出哪些项目是私有的，哪些是公有的，请参考网站类型进行设计。

[之前的设计](https://github.com/tatfook/KeepWorkDesgin/issues/98)

**Comment by Sandu1213** [comment]
@azothli 之前的设计是否定稿了，如果可以了，请回复下，稍后开发可以直接进行调整。
@ZhangKaitlyn  请关注设计图

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/69690569-3e8b9600-1107-11ea-85e4-5d2d81e6bbac.png)
![image](https://user-images.githubusercontent.com/33826048/69690847-0a64a500-1108-11ea-9ef5-f32e25758fb1.png)
icon，公司官方iconfont上
