### ISSUE TITLE
【bug】第三方登录问题

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#537]
![image](https://user-images.githubusercontent.com/28430070/40164994-8e4037b4-59ed-11e8-856d-d47fb0cf290b.png)
![image](https://user-images.githubusercontent.com/28430070/40165183-ed82bb16-59ed-11e8-939f-44b3c4301770.png)

操作步骤：1.release.keepwork.com登录页面，点击GitHub。2.授权。3.点击右上方登录，如图二，会出现如图一情况

**Comment by Sandu1213** [comment]
问题依然存在，需要调整
![image](https://user-images.githubusercontent.com/21214285/41227947-3fbd2690-6da9-11e8-904e-05e808ae3faa.png)

**Comment by Sandu1213** [comment]
目前线上的第三方登录都不可用了，请一同调整下：
![image](https://user-images.githubusercontent.com/21214285/41414596-13668fe2-7019-11e8-929f-17c79ca7c72a.png)

**Comment by yuanoook** [comment]
样式已经调整，登陆注册问题统一到 #792
