### ISSUE TITLE
【Bug-课程内容页】当课程没有配置视频时，点击封面应该无响应

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5387]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/6ae212ba-6ed5-4868-8a7d-7cef02607486)

**Comment by shirleyluo1130** [comment]
去掉“点击封面图打开视频”的功能。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/c43f4698-4dd2-4de7-8fe5-a2d8ebd37943)
