### ISSUE TITLE
【bug】文件展开目录问题

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#540]
图一
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/3b39d2d6-8b1c-4ae8-9fc6-f8648481e6bb)
图二![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/faef2fc3-36bd-44cb-ada5-ef0c71bbb004)
操作步骤：1.点开几个文件，如图一 。2.点击刷新，文件折叠，且按钮还是向下，如图2。3.再次点开之前打开的文件，点一次无法打开，点第二次，才打开

**Comment by Sandu1213** [comment]
stage环境验证通过，当文件数量大于100的时候还是存在问题，由 #603 跟进。
