### ISSUE TITLE
【bug-机构】课程序号显示不对，详情见下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5406]
课程包“动画基础”下，第2-9课，课程序号显示不对，如下图：

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/6f0d15c4-447a-47c1-9a74-c7ecd86af39c)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/1ffb0dd8-904e-4191-af73-c5be840ef86d)

**Comment by kevinxft** [comment]
没有复现出来

**Comment by shirleyluo1130** [comment]
复现步骤：

### 1、以管理员身份进入机构

机构名称：南山Paracraft创意空间
身份类型：管理员
课程包名称：动画基础

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/be39ef5c-72fa-4ae1-85eb-18a812f427d5)

### 2、进入“动画基础”课程包，点击“教案”、“课件”按钮进入查看

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/34e0b733-07eb-45a3-9f4f-fe5bfe6a6a37)

### 3、发现：第2-9课，课程序号显示不对

**Comment by kevinxft** [comment]
应该是之前的遗留问题，重新分配一次，以后就不会出现了
