### ISSUE TITLE
【UI优化-机构】邀请码打印，文字与图标覆盖了，观感不好。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5449]
### 文字与图标覆盖了，观感不好。
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/0e3f084b-807e-4d0b-9040-83961048f394)

### 按如下样式优化：
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/8ee00265-36c2-41d8-b865-5c731e8d6d2b)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/b0f42bc8-09d3-4eac-a11a-67b143ab806a)

**Comment by kevinxft** [comment]
release 环境才有

**Comment by shirleyluo1130** [comment]
stage环境的文本内容是不对的。

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/72934e86-bfc9-4a5c-8740-50cb375d560b)


正确的文本内容是：
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/d95dc127-26f1-45e2-a2c2-e5abc6012aeb)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/75c3b387-123e-4165-bda9-7a1abfbb1f94)
