### ISSUE TITLE
keepwork dashnoard：vip与T的管理

### ISSUE THREAD

**Issue by azothli** [tatfook/keepwork#5456]
增加 查询、管理的功能

vip：查询
t：查询、删改

@Kvaya 做个设计

**Comment by Kvaya** [comment]
思路：
![image](https://user-images.githubusercontent.com/39363297/66734589-49130880-ee96-11e9-9698-2d84ccc8fb67.png)

dashboard用户管理页面参考：
![image](https://user-images.githubusercontent.com/39363297/66734624-6647d700-ee96-11e9-966f-e8811db97fa4.png)

以上设计图地址：
![image](https://user-images.githubusercontent.com/39363297/66734646-76f84d00-ee96-11e9-88ef-bdc5576a7e00.png)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/67186104-dff13f00-f419-11e9-820c-a7abe89586af.png)
![image](https://user-images.githubusercontent.com/33826048/67186111-e5e72000-f419-11e9-97ae-a841a1285f71.png)

**Comment by Sandu1213** [comment]
@azothli @Kvaya 感觉教师等级应该默认是T1，然后往上升，T0的感觉有点奇怪。请评估下

**Comment by Sandu1213** [comment]
![图片](https://api.keepwork.com/storage/v0/siteFiles/8153/raw#1573719416614image.png)

**Comment by Kvaya** [comment]
1.教师等级为T0，该用户是普通用户，没有教师身份。用户表单处，教师等级那一列，教师等级为T0时，建议保留显示为T0，方便查询。
2.编辑功能也保留T0选项。

**Comment by Sandu1213** [comment]
@OwenLittleWhite  管理员也按教师的等级一样处理下，请知悉。

**Comment by wanglin727** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
多种情况下vip和等级

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/69123153-9b6dc780-0adb-11ea-84f8-1c14afe19612.png)
![image](https://user-images.githubusercontent.com/33826048/69123163-a4f72f80-0adb-11ea-9ad6-d8d3bfc3971b.png)
![image](https://user-images.githubusercontent.com/33826048/69123174-a9bbe380-0adb-11ea-8c9c-b98e559cd134.png)
![image](https://user-images.githubusercontent.com/33826048/69123182-b0e2f180-0adb-11ea-9e6f-39005fa4a183.png)
不同场景下

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/70107668-20cbad00-1682-11ea-8586-dfdf5b026b88.png)
帕拉卡vip
