### ISSUE TITLE
页面文件切换导航条渲染优化

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#5469]
目前打开一个md页面，顶部导航条会自动加载数据，导致页面一加载就会自动向后端发起诸多请求，会对后端服务造成不必要的访问压力，占用请求资源。而在通常的使用场景中，主要目的是为了查看页面内容，而不是为了频繁切换。

因此，建议在点击切换菜单时才去读取下拉数据，即在需要的时候才请求。

![image.png](https://images.zenhubusercontent.com/59bb76d4b0222d5de477d44e/7db4c9be-76b3-4797-a03a-a78aebf0e95c)

**Comment by ZhangKaitlyn** [comment]
跟issue #5391 重复了
