### ISSUE TITLE
【Feature】目前项目无法进行改名，请增加项目改名功能

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5476]
### Details:     

目前有部分用户反馈，想给已经创建的世界进行改名操作，但目前Keepwork及paracraft都不支持，请评估如何实现一下。

**Comment by Sandu1213** [comment]
@beyondliu  @LiXizhi 请这里讨论跟进

**Comment by beyondliu** [comment]
应该是一开始设计的时候就要考虑到这个数据项是否会被改动

**Comment by Sandu1213** [comment]
@ZhangKaitlyn 目前paracraft端已经可以改名了，Keepwork这边请配合进行调整。
![image](https://user-images.githubusercontent.com/21214285/67762378-44e30f80-fa80-11e9-9ef2-8dc3916c4a05.png)

**Comment by Sandu1213** [comment]
改名涉及的地方修改不全，还需要再优化
