### ISSUE TITLE
【优化-表单】管理员端 - 表单管理：表单的预览图看不清。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5560]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/9aa3afbf-c07e-4441-8af3-6e29a61b1ccc)

**Comment by shirleyluo1130** [comment]
预览图以弹框的形式显示

**Comment by shirleyluo1130** [comment]
@wanglin727   帮忙出张图 ，以弹框形式显示预览图 

![image](https://user-images.githubusercontent.com/40385277/68280979-9fe4ba00-00b1-11ea-8f96-baa1682a8283.png)

**Comment by wanglin727** [comment]
[图片]占比屏幕60% 上下留20%

**Comment by shirleyluo1130** [comment]
补充：
### 问题描述
未创建表单时，点击图一的“创建”按钮，进入图二页面

图一
![image](https://user-images.githubusercontent.com/40385277/68290674-4be2d100-00c3-11ea-9acb-9d95e283763f.png)


图二
![image](https://user-images.githubusercontent.com/40385277/68290785-8482aa80-00c3-11ea-920c-f32902c60ea3.png)

### 建议方案

将图一“创建”按钮改为“预览”，点击“预览”，打开对应模板的弹框即可。
