### ISSUE TITLE
【bug-评估】教师端-评估报告-班级点评详情，显示问题

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#5572]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/499883b7-a491-4b4f-beed-26a3e2dd4963)

**Comment by duting1993** [comment]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/ab3230d8-8f8c-4c87-94a2-f25be90e925e)

**Comment by ZhangKaitlyn** [comment]
接口1：
http://api-rls.kp-para.cn/lessonapi/v0/evaluationReports?classId=34&name=&roleId=64&days=30
接口2： http://api-rls.kp-para.cn/lessonapi/v0/evaluationReports/classReport?classId=34&days=30

**Comment by jacksparrow68** [comment]
两个接口都返回teacherName
