### ISSUE TITLE
【bug】管理员端-历史数据，更改开班时间，点击保存，提示班级更新失败，没有提示因为什么更新失败

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#5579]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/142b31bc-2d44-4841-95e1-97400cc24ff7)

**Comment by shirleyluo1130** [comment]
延长开班时间时，若超过了当前可添加的学生数，则提示：

该班学生人数过多，不能完成延期操作。请联系Keepwork客服处理：support@paraengine.com

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/a0446da0-6790-41e1-93e0-06fbaf2ee8d3)
