### ISSUE TITLE
mod：编号21 	文本与绘图板 	text_board

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#558]
@azothli commented on [Tue Jan 16 2018](https://github.com/tatfook/wikicraft/issues/1420)

![image](https://user-images.githubusercontent.com/22001356/35023368-4a3db554-fb75-11e7-906d-1413d38785b9.png)

编号21
	文本与绘图板
		绘图板
		文本
	text_board
	样式
		样式1
			左文，右图
		样式2
			右文，左图
		样式3
			上文，下图
		样式4
			下文，上图

---

@azothli commented on [Wed Jan 17 2018](https://github.com/tatfook/wikicraft/issues/1420#issuecomment-358225465)

说明
	带文字说明的绘图板

---

@wanglin727 commented on [Tue Feb 06 2018](https://github.com/tatfook/wikicraft/issues/1420#issuecomment-363283403)

![image](https://user-images.githubusercontent.com/33826048/35837749-d77790ea-0b22-11e8-9226-e0ddc895e016.png)

设计图已完成  待开发

---

@duting1993 commented on [Mon May 07 2018](https://github.com/tatfook/wikicraft/issues/1420#issuecomment-386977273)

stage已验证

**Comment by Sandu1213** [comment]
😥 ，这个没有验证过就已经发外网了。。。。。。

**Comment by Sandu1213** [comment]
stage验证通过
