### ISSUE TITLE
【bug、需求】MD的文本， 预览框鼠标放上去就是一个大大的蓝色罩住整个屏幕

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#559]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/061fa970-dbdc-47e9-b60e-69ed135fbf7f)

**Comment by duting1993** [comment]
@azothli

**Comment by ouyc** [comment]
Issue moved to [tatfook/KeepWorkDesgin #68](https://github.com/tatfook/KeepWorkDesgin/issues/68) via [**ZenHub**](https://www.zenhub.com/)
