### ISSUE TITLE
【优化-机构】学生页，设置家长手机号，验证码是否发送成功无提示，不方便操作。详情见下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5614]
### 问题描述：
如下列2张图所示，点击“发送验证码”按钮后，页面上无任何提示，用户无法感知验证码是否发送成功。
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/1cd975af-2052-4eca-9263-5edf126bd48b)

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/c16da6da-782e-4d72-bd49-035869fade5e)

### 建议方案：
建议参考keepwork注册时发送验证码的处理方式，如下图，

![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/79094702-f811-46cd-acf5-4125c5c5d032)

**Comment by ZhangKaitlyn** [comment]
和 issue #5589 重复
