### ISSUE TITLE
【bug - 评估】教师端 - 评估报告：目前，已发送的评估报告不能再次发送给家长，不合理。建议修改为，已发送的报告也可以再次发送。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5615]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/15ac174a-6653-4f41-9203-0ebca9888527)

**Comment by Sandu1213** [comment]
目前发送会出现收不到短信的情况，release环境再观察
