### ISSUE TITLE
【bug】Index page editor中无法显示 ： https://keepwork.com/lixizhi/note/index

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#562]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/ce280193-d27e-4786-86ab-ee51a55110dc)

操作步骤：1.之前老网站，创建的index页面
https://keepwork.com/lixizhi/note/index
打开此链接：左边目录没有index页面

**Comment by Sandu1213** [comment]
无法重现，先关闭
