### ISSUE TITLE
【bug-评估】UI样式调整，详情见下

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5628]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/d82b41c1-cbfa-4f65-b710-afc1f853aa60)

**Comment by shirleyluo1130** [comment]
@wanglin727    看下怎么调

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/68189968-71021180-ffe7-11e9-945b-51b166abbf9a.png)
