### ISSUE TITLE
【Bug-Dashboard】项目管理里无法通过系统标签进行筛选查询，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5661]
### Environment:
**Address:**  [dashboard](http://dashboard-dev.kp-para.cn)
**Version:** v1.3.3
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

### Details:
**Steps:**
1.进入后，选择项目->项目管理，通过系统标签对项目进行筛选查询，如：
查询标签为“动画”的项目，观察查询结果

**Expected Result:**
1.查询成功，显示正确

**Actual Result:**
1.查询失败

**Attachment Files:**
![image](https://user-images.githubusercontent.com/21214285/68649304-538bf500-055d-11ea-8a47-b982b2eaaec4.png)

**Comment by kevinxft** [comment]
现已经禁用系统标签进行筛选查询，完美解决。
