### ISSUE TITLE
【机构消息】管理员端-校园OA：首页

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5681]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/ddd76c12-40d7-4ad5-b456-0c3c372cd73a)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/69697187-c5973900-111c-11ea-98dd-f66ab595972b.png)
