### ISSUE TITLE
【bug-机构】用户为默认头像时，其评估报告页的头像不显示。详情见下：

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5693]
用户头像为：![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/aecd3adf-c1b8-4185-9da9-f0b55f5759fc)

评估报告页显示为：
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/843bf8a5-33ce-4024-addf-1fb7bd369c35)

**Comment by kevinxft** [comment]
VIP头像上线后就不会有这问题
