### ISSUE TITLE
编辑器 - 图片管理器

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#571]
参考旧 的图片管理器

@wanglin727 
请把新的设计添加到这边

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/40355021-f2a7287c-5de7-11e8-9d31-3f72bd4a2633.png)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/40355251-82498736-5de8-11e8-8d12-12f7b74efc6a.png)
svn--源文件

**Comment by yuanoook** [comment]
还需要进度条调整，上传界面调整

**Comment by Sandu1213** [comment]
@azothli  请帮忙解答下问题1和问题2的困惑。
@yuanoook  问题3请处理
![image](https://user-images.githubusercontent.com/21214285/40963669-c51a0f74-68db-11e8-8b88-d813707a7d22.png)

**Comment by azothli** [comment]
1. 文件名 或 类型，可以尝试帮助用户定位
2.准备引入7牛的自动审核，不存在未审核的了。
