### ISSUE TITLE
【Bug-搜索】项目改名后，搜索对应项目，改名前的项目应该过滤掉且搜索到的项目需要高亮显示

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5722]
### Description:
9000改名前，项目名是00，9000那个应该显示高亮；
para_1111T改名前是para_2000, 应该过滤掉，只取最新的数据，

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/96896eb2-df10-420b-a1db-908c0108dd84)

**Comment by azothli** [comment]
名称与显示名称 均可作为搜索匹配的关键字，因为该处为显示名，可能无高亮提示的部分，无妨。
