### ISSUE TITLE
【汉字大赛】显示弹窗

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#5775]
预期结果：
检测到用户在https://keepwork.com/han 域名下，显示弹窗一次，关闭弹窗不再显示，不管用户登录或未登录，都只是显示一次。

弹窗内容：logo+文字
文字内容：重磅！“汉字大赛”入选深圳第十五届“创意十二月”重点项目
其他说明：
1.一天同一台电脑任意浏览器浏览汉字大赛，弹窗显示一次；
2.用户关闭弹窗后，该弹窗内容以小图浮窗效果显示在网页右侧，鼠标点击小图，显示弹窗；
3.用户进入汉字大赛页=》显示弹窗=》关闭弹窗=》清除浏览器缓存，显示弹窗

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/69928102-86d6f980-14f5-11ea-8740-782dd7690ef4.png)
