### ISSUE TITLE
pac数据统计 百度统计

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#578]

**Comment by ZhangKaitlyn** [comment]
![tim 20180521094411](https://user-images.githubusercontent.com/18642919/40286747-907b6044-5cdb-11e8-831d-92caa285cbf5.jpg)

**Comment by Sandu1213** [comment]
除报名人数统计外，百度统计基本上可以满足以上的需求了。报名人数需要后续由后台来支持
https://tongji.baidu.com/web/25637531/source/all?siteId=12052065
