### ISSUE TITLE
【消息中心】补充空白页展示。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/keepwork#5785]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/bb2b7f6d-8627-42e0-9ffa-7dc25e40188a)

**Comment by shirleyluo1130** [comment]
@wanglin727    麻烦补一下UI

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/69935119-e68dce80-150e-11ea-884b-9711743c47a0.png)
