### ISSUE TITLE
【Bug-Dashboard】给指定人员发送消息，发现发送的消息内容丢失了，同时列表里有关人员的记录缺失

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5786]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/d0c61d35-41f0-4e56-b403-826d30da0e01)

**Comment by kevinxft** [comment]
release 已经可以显示消息内容和操作者，但是接受者还需要等后端提供新的接口。
