### ISSUE TITLE
keepwork添加paracraft项目数量限制

### ISSUE THREAD

**Issue by azothli** [tatfook/keepwork#5788]
svn://10.27.2.210/Release/keepwork/keepwork%E4%B8%ADparacraft%E9%A1%B9%E7%9B%AE%E6%95%B0%E9%87%8F%E9%99%90%E5%88%B6.rp

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/69846324-9a445380-12ae-11ea-864e-56473af12688.png)
keepwork端用设计稿。

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/69846673-c1e7eb80-12af-11ea-8f2e-bcfb8f3227e7.png)
帕拉卡端用软件现有的弹窗样式。
