### ISSUE TITLE
【Bug-插入mod】在```之上添加mod模块，会引起语法错误及显示错误，请处理

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#580]
## The problem
在```之上添加mod模块，会引起语法错误，请处理

## Environment

* OS Info: Window10
* browser Info: chrome  65.0.3325.146
* URL: [keepwork.com](http://keepwork.com) 
* Model:  editor ->mod

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor编辑器，添加mod后，将光标切换到第一行，然后插入新的mod，观察显示样式

* Expected Result:
1.mod可以正常插入，显示正确，无异常
* Actual Result:
1.显示存在问题
 

## Attachments (eg:logs/video/screenshot)
![insertmod](https://user-images.githubusercontent.com/21214285/40287046-6cf9e972-5cdd-11e8-95d1-92d51f1cce71.gif)

**Comment by duting1993** [comment]
stage已验证
