### ISSUE TITLE
【Bug-mod】添加mod后，mod的显示位置不对，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5886]
### Details:
1.打开编辑器，新建页面后，添加不同类型的mod，然后在页首的位置添加新mod，观察添加后的显示情况

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/5373bed2-e497-400e-932e-4d3a9970d0d6)

**Comment by kevinxft** [comment]
relese没发现该问题
