### ISSUE TITLE
【Bug-历史版本】文件历史版本里的记录编号错误，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5912]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/c9dfc016-ed43-4131-b189-9cd2d35c1f27)

**Comment by kevinxft** [comment]
不是bug

**Comment by Sandu1213** [comment]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/a8e830ca-40ae-473c-96f7-9257afb89f79)

**Comment by kevinxft** [comment]
现在没有这么花里胡哨的东西，那个版本号都是前端弄个假的给你看看而已

**Comment by Sandu1213** [comment]
@OwenLittleWhite  看看好不好加，好处理的话加一下。
