### ISSUE TITLE
【Bug-大文件】PDF文件无法打开，因为路径有误，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5914]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/72d4e307-d08b-45cc-b2f1-a8988d9e780d)

**Comment by kevinxft** [comment]
那这关我啥事

**Comment by Sandu1213** [comment]
:)

**Comment by Sandu1213** [comment]
@OwenLittleWhite  owen,帮忙看看这里

**Comment by kevinxft** [comment]
![image.png](https://images.zenhubusercontent.com/59edff22a468affe6df7caf6/6abcfa32-7acb-4780-8616-9f2d0241c62d)
PDF只有测试环境会有这个问题，看截图，是https的问题

**Comment by Sandu1213** [comment]
好吧，等线上环境验证

**Comment by kevinxft** [comment]
后端大兄弟已经fix
