### ISSUE TITLE
【Bug-网盘】网盘无法进行批量下载，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5915]
### Environment:

**Address:**  [rls](http://rls.kp-para.cn)
**Version:** v1.3.6
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

### Details:
**Steps:**
 1.进入editor页面，然后打开网盘,全选所有文件，进行批量下载，观察下载结果
2.进行批量删除，观察删除结果

**Expected Result:**
1.文件下载和批量删除功能都正常

**Actual Result:**
1.批量下载时仅第一个下载成功，其他失败

**Attachment Files:**

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/a896c3bf-9b74-44e1-a3b8-25f075d4b1da)

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/71404350-476f7900-266d-11ea-8725-8d448ab02056.png)
出现该问题的原因是 弹窗被拦截，暂时没有解决方案。
用户允许弹窗后，下载多个文件就会正常
