### ISSUE TITLE
【Bug-删除网站】删除网站时应该先判断是否存在网站文件被打开的情况，如果存在建议先进行提醒或者优化处理方式

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5916]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/62cccad5-ccc4-4ef7-8366-2c2326bdcdd5)

**Comment by azothli** [comment]
不用询问，直接删除即可。
在存盘的时候会出错，提醒用户“页面文件已删除，是否关闭？【是】【否】”
是则直接关闭，否的话保留打开，不存盘，就那么本地放着。
