### ISSUE TITLE
【Bug-多人编辑】当多人编辑同一个文件时，存在内容不同时，目前缺少了提醒，请补充

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5919]
### Environment:

**Address:**  [rls](http://rls.kp-para.cn)
**Version:** v1.3.6
**Devices:**  chrome  browser
**Pre-condtion:**
  存在用户A和用户B

### Details:
**Steps:**
 1.进入editor页面，用户A对文件A进行编辑
2.用户B也打开文件进行编辑
3.用户A先进行保存，保存后用户B又编辑了一些，想进行保存，观察存在文件内容变更冲突提醒

**Expected Result:**
1.存在相应的提醒，用户可以根据情况自行调整

**Actual Result:**
1.缺少提醒，目前保存直接覆盖了

**Attachment Files:**

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/58b744a2-e07d-4fa6-9446-3a0ecc77de85)

**Comment by kevinxft** [comment]
现在没有了版本号，解决不了
