### ISSUE TITLE
【Bug-精选项目】精选项目数量与Dashboard配置不符

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5928]
### Environment:

**Address:**  [rls](http://rls.kp-para.cn)
**Version:** v1.3.6
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

### Details:
**Steps:**
 1.进行Dashboard,对项目->精选项目数量进行查询，观察显示数量
2.再到release环境里，观察精选项目数量

**Expected Result:**
1.项目数量一致

**Actual Result:**
1.项目数量不一致

**Attachment Files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/365108ba-9c35-4cb8-a203-8ccc4cb6f8fb)

**Comment by OwenLittleWhite** [comment]
搜索服务有个条件：当作品无封面或者无视频时，过滤
1. 请核对下这几个红圈的是否是这种情况，cover、video字段均为空字符
2. 确认是此情况后，再确认下此处的逻辑要不要调整

**Comment by Sandu1213** [comment]
嗯，确认过，数据是对的。
精选的条件是：
1.设置精选
2.非私有
3.已实名的用户创建
4.作品存在封面图
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/764f78b2-e8bd-4994-a9b4-2e979133dd29)
