### ISSUE TITLE
【Bug-图文拼接mod】当删除图文拼接mod中的第一个后，再去编辑后面的，发现显示不对

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5943]
### Environment:

**Address:**  [rls](http://rls.kp-para.cn)
**Version:** v1.3.6
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

### Details:
**Steps:**
 1.进入editor页面，然后添加图文拼接mod，对其中一个进行删除，然后对后面一个进行隐藏操作，观察显示情况

**Expected Result:**
1.页面显示正常

**Actual Result:**
1.页面显示不合理

**Attachment Files:**

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/ce338529-15ad-4e99-9943-65035a4f520e)

**Comment by kevinxft** [comment]
按照操作，没有复现出bug

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/71571092-a15fbb00-2b13-11ea-80d0-23a74024aef4.png)
