### ISSUE TITLE
【Bug-keepwork首页】大家都觉得很赞，目前排序逻辑不对，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5946]
### Environment:

**Address:**  [rls](http://rls.kp-para.cn)
**Version:** v1.3.6
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

### Details:
**Steps:**
 1.进入keepwork首页，分别对几个喜爱的项目进行点赞操作，观察首页的“大家都觉得赞",排序是否正确
**Expected Result:**
1.排序正确

**Actual Result:**
1.排序不是很合理

**Attachment Files:**

**Comment by Sandu1213** [comment]
理论排序规则为：
1.已实名用户的项目
2.最近一周内获得赞的数量排名，由高到低，如果出现赞的数量相同，则按最新的更新时间降序排列。

**Comment by OwenLittleWhite** [comment]
对应接口：http://yapi.kp-para.cn/project/32/interface/api/937

传参只需加上分页参数`x-per-page`和`x-page`

返回的数据格式同之前接口一致，不用做修改

@ZhangKaitlyn @kevinxft

**Comment by kevinxft** [comment]
dev环境
