### ISSUE TITLE
【Bug-Dashboard】添加敏感词添加不成功，请排查

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#5959]
### Environment:

**Address:**  [dashboard](http://dashboard-rls.kp-para.cn)
**Version:** v1.3.6
**Devices:**  chrome  browser
**Pre-condtion:**
  用户已登录

### Details:
**Steps:**
 1.进入dashboard，打开敏感词，添加新的敏感词，观察添加结果

**Expected Result:**
1.添加非重复的成功

**Actual Result:**
1.添加非重复的不成功

**Attachment Files:**

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/ce92b176-7697-4016-9720-d5e966d96604)

**Comment by OwenLittleWhite** [comment]
前端参数有误，按用户名排序传参为
```JSON
{
  "where": {},
  "include": [
    {
      "all": true
    }
  ],
  "order": [
    [
      {
        "$model$": "users"
      },
      "username",
      "desc"
    ]
  ],
  "distinct": true,
  "limit": 20,
  "offset": 0
}
```

按系统标签排序传参为：

```JSON
{
  "where": {},
  "include": [
    {
      "all": true
    }
  ],
  "order": [
    [
      {
        "$model$": "systemTags"
      },
      "tagname",
      "desc"
    ]
  ],
  "distinct": true,
  "limit": 20,
  "offset": 0
}

```

**Comment by OwenLittleWhite** [comment]
@kevinxft 前端没有发请求，直接报的错
