### ISSUE TITLE
【调整】adi编辑区增加当前编辑模块的类型名称

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#598]
@azothli commented on [Thu Apr 26 2018](https://github.com/tatfook/KeepWorkDesgin/issues/19)

现在不好确认我编辑的是什么模块

---

@azothli commented on [Thu Apr 26 2018](https://github.com/tatfook/KeepWorkDesgin/issues/19#issuecomment-384496126)

![image](https://user-images.githubusercontent.com/22001356/39283134-5f4841cc-493f-11e8-8687-cb958a1ab8a4.png)

---

@wanglin727 commented on [Mon May 21 2018](https://github.com/tatfook/KeepWorkDesgin/issues/19#issuecomment-390566864)

![image](https://user-images.githubusercontent.com/33826048/40293703-bb431334-5d04-11e8-9ecf-808362d943ba.png)
设计稿已完成  待开发

---

@wanglin727 commented on [Mon May 21 2018](https://github.com/tatfook/KeepWorkDesgin/issues/19#issuecomment-390566958)

![image](https://user-images.githubusercontent.com/33826048/40293717-d06dcd80-5d04-11e8-9fbb-63a344647ff3.png)
svn--源文件

**Comment by Sandu1213** [comment]
release环境验证通过
