### ISSUE TITLE
【Paracraft】客户端优化

### ISSUE THREAD

**Issue by Kvaya** [tatfook/keepwork#5985]
背景：
在使用Paracraft客户端时，有一些思考，进一步优化Paracraft

思路：
https://keepwork.com/junjun0517/paracraft/user_experience_report

**Comment by azothli** [comment]
Issue moved to [tatfook/KeepWorkDesgin #121](https://github.com/tatfook/KeepWorkDesgin/issues/121) via [**ZenHub**](https://www.zenhub.com/)
