### ISSUE TITLE
【调整】adi 模块：多行文编辑功能优化

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#599]
@azothli commented on [Thu May 03 2018](https://github.com/tatfook/KeepWorkDesgin/issues/32)

多行文本编辑，属于用户主要的内容创建行为。
在多行文本的编辑中，现在需要视觉一直盯着左侧的adi编辑区，不友好。
在多行文本编辑状态（多行文本控件、md控件等），增加一个弹出按钮。
点击后，在视觉中心展开编辑窗口，让用户可以轻松的创作。

---

@wanglin727 commented on [Mon May 21 2018](https://github.com/tatfook/KeepWorkDesgin/issues/32#issuecomment-390567319)

![image](https://user-images.githubusercontent.com/33826048/40293801-25c25634-5d05-11e8-8a8c-5ebb4f8414e0.png)
设计稿已完成   待开发

---

@wanglin727 commented on [Mon May 21 2018](https://github.com/tatfook/KeepWorkDesgin/issues/32#issuecomment-390567380)

![image](https://user-images.githubusercontent.com/33826048/40293818-33fd418c-5d05-11e8-9b79-f3a273f0b6b7.png)
svn--源文件

**Comment by leopoldchen** [comment]
@azothli  @ZhangKaitlyn 
同时加多一个操作，双击viewport markdown内容区域，可以直接触发弹窗。
具体实现可以参考board。

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/41705318-397f28ae-756b-11e8-8fca-1a792688a00f.png)

**Comment by azothli** [comment]
md 双击编辑的功能 优秀！
