### ISSUE TITLE
【需求、设计】重置按钮，加一个提示

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#604]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/cc687943-0b84-491e-9462-3c0593004272)
目前点击之后，没有反应也没有任何提示

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/40411261-805c949e-5ea2-11e8-824a-1afd85d8f218.png)

源文件svn
