### ISSUE TITLE
【bug】键盘快捷键ctrl+s保存，有时会出现两个相同的文件

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#611]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/a7a5ef5e-b7c6-4aba-afdf-7b6324a281b6)
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/f87fd7e1-db1d-49dc-b2cb-30f58bf06eb6)

**Comment by Sandu1213** [comment]
stage环境验证通过
