### ISSUE TITLE
Delay Service - Git Page 存储与解析

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#618]
整合Kafka、GitAPI、ES Gateway和redis等服务，完成异步的git page存储与解析

**Comment by leopoldchen** [comment]
@William0911 
es依然可以放在delay service中，只是与git应该属于不同的channel，es可以以比较快的频率消费。
在gitGateway那边，对于每次git更新，都往git page队列里添加记录，但是es不需要每次都推，只要一条即可。

**Comment by William0911** [comment]
已上线
