### ISSUE TITLE
【bug】mix_position和img mod组合使用的问题，请优化调整

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#627]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/5e41777a-4a22-47f9-84ef-a7fd56c73a5e)
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/b8d16f88-00c0-4e2b-8326-a5c04153a9f8)
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/004341b4-8060-44d3-b7d9-f97fd15f18c8)

**Comment by Sandu1213** [comment]
## 操作：
1.进入编辑器，编辑haqi网页，添加mix_position mod,添加成功后，修改左侧的属性值，观察中间mod的显示情况
2.切换到样式页，观察样式实时渲染情况
3.保存修改，去新页面打开修改的haqi页面，观察修改结果
**实际结果:**
1.修改左侧的属性值，中间没有变化，还是初始值
2.切换到样式页，发现最下面两个页面没有进行渲染
3.去新打开页面，发现页面显示是初始化，预期是显示修改后的值

**Comment by Sandu1213** [comment]
操作，可参考下图：
![mixerror](https://user-images.githubusercontent.com/21214285/40412425-e52832a4-5ea5-11e8-8aba-ac0087dcbc7d.gif)

**Comment by Sandu1213** [comment]
图3的问题，具体操作是：
1.复制一个图片的url链接，然后使用Img mod进行添加，添加成功后，图片正常展示
2.观察中间预览的显示效果，然后打开新页面，对比新页面的显示效果
**预期**：图片显示一致，而不是新页面出现的较大拉伸效果

**Comment by Sandu1213** [comment]
图1，图2的问题已经解决；图3的问题，稍后会增加新的图片mod进行处理，该问题先关闭。
