### ISSUE TITLE
支持iframe页面高度自适应

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#644]
### 背景

当前有诸多第三方应用以iframe的形式嵌套在KeepWork页面中，由于页面高度各有不同，因此需要做一个适配，防止在页面中出现多个滚动条

### 目标

iframe嵌套的div会随着iframe内部内容的高度做动态自适应

### 指标

1. 提供事件规范，第三方应用需要通过事件告知KeepWork窗口其实际高度
2. KeepWork全局自动事件响应iframe高度变化

**Comment by Sandu1213** [comment]
使用<iframe>标签已经验证；stage环境验证通过
