### ISSUE TITLE
Title mod 新增样式以支持创意空间官网

### ISSUE THREAD

**Issue by onedou** [tatfook/keepwork#658]
![image.png](https://images.zenhubusercontent.com/59df2959b0222d5de47b59a3/d4c659ce-528f-4aec-b8b6-749df118b728)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/41216580-8cfa6cfa-6d87-11e8-9ad7-edc5b2292194.png)

问题3需要宇哥确认 @azothli

**Comment by Sandu1213** [comment]
menu菜单处理还有问题，请排查：
![image](https://user-images.githubusercontent.com/21214285/41586561-a81f5abe-73df-11e8-862a-4e965c0381f1.png)

**Comment by onedou** [comment]
新问题，请看#940
