### ISSUE TITLE
权限管理

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#667]
![default](https://user-images.githubusercontent.com/18642919/40602086-11eb2d68-628a-11e8-8398-d25d12b656df.png)
![default](https://user-images.githubusercontent.com/18642919/40602147-1f31347c-628a-11e8-828b-4fec48ca24b0.png)
![default](https://user-images.githubusercontent.com/18642919/40602153-2492753e-628a-11e8-891d-73dfe229bf1e.png)

**Comment by Sandu1213** [comment]
- 已授权的人建议不要再有网站权限操作
![image](https://user-images.githubusercontent.com/21214285/48477011-73e67e00-e83b-11e8-9fe1-49b6270a926e.png)

- 分组较多或者授权较多时，排版问题
![image](https://user-images.githubusercontent.com/21214285/48477060-98daf100-e83b-11e8-949c-7a3c14fa7afc.png)

- 保存按钮是否有用
![image](https://user-images.githubusercontent.com/21214285/48477102-ad1eee00-e83b-11e8-8558-43a650fbc32a.png)

- 分组名需要过滤敏感词 
![image](https://user-images.githubusercontent.com/21214285/48477252-169efc80-e83c-11e8-894e-de32b3129c1c.png)

- 拒绝权限没有大于编辑权限(拒绝权限没有生效)
![image](https://user-images.githubusercontent.com/21214285/48477353-55cd4d80-e83c-11e8-8ce9-7fa664c0c031.png)

- 设置网站私有不生效
![image](https://user-images.githubusercontent.com/21214285/48477803-895ca780-e83d-11e8-92a4-0754ca1f409a.png)
