### ISSUE TITLE
数据源设置

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#668]
![default](https://user-images.githubusercontent.com/18642919/40602195-4514fb60-628a-11e8-9b6f-4eb3a3c45292.png)
![default](https://user-images.githubusercontent.com/18642919/40602206-4e785986-628a-11e8-8f63-9c97f31d1c04.png)
![default](https://user-images.githubusercontent.com/18642919/40602211-53d8f80e-628a-11e8-8e48-ec8ebf2fb629.png)

**Comment by leopoldchen** [comment]
这个功能先不做吧，先不支持设定数据源

**Comment by azothli** [comment]
暂时挂起，目前主打学生教育产品，对于网站的应用，鼓励更加流畅稳定的本地数据源。
