### ISSUE TITLE
新增 categoryList mod

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#672]

**Comment by Sandu1213** [comment]
CategoryList mod issue:
- 中英文显示不一致问题：
![image](https://user-images.githubusercontent.com/21214285/41272973-16e473e4-6e4a-11e8-8dc0-3068309ac1cd.png)

- 属性开关存在不可用的情况
![category_mod](https://user-images.githubusercontent.com/21214285/41272997-2c4380fe-6e4a-11e8-9efb-bfb5c47f75e8.gif)

**Comment by Sandu1213** [comment]
中英文显示的问题依然存在，不过不影响使用了
