### ISSUE TITLE
新增 pagePath mod

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#673]

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/41276958-642a4e5e-6e58-11e8-88a2-c41f48b921df.png)

**Comment by Sandu1213** [comment]
请确认是否要调整成这样？
![image](https://user-images.githubusercontent.com/21214285/41957585-0617f7ee-7a1a-11e8-80b3-fc3a658a16b9.png)
