### ISSUE TITLE
新增 pageSwitching mod

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#675]

**Comment by Sandu1213** [comment]
PageSwitching mod issue:
- 中英文显示不一致问题 (属性名需调整)
- mod开关有误问题


- mod 存在yaml expection error
- 疑惑：
  - 每个页面显示的数据是多少？
  - 如果超过100页如何处理？

**Comment by Sandu1213** [comment]
会出现多页面或者少页面的情况，请排查

**Comment by onedou** [comment]
之前es接口出错了，现在应该已经修复，请测试

**Comment by Sandu1213** [comment]
问题还是存在，请排查
![image](https://user-images.githubusercontent.com/21214285/41639915-64dbd864-7492-11e8-9f79-a2d38e9888b5.png)

**Comment by onedou** [comment]
fix 请测试

**Comment by Sandu1213** [comment]
stage环境验证通过
