### ISSUE TITLE
【Bug-editor】ctrl+z 操作针对mod内容时，mod每次都会收起，体验不是很好，考虑是否优化一下

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#679]
## 操作：
1.当用户很熟悉mod指令后，直接通过markdown进行编写，编写错误了，希望通过
ctrl+z进行撤销操作时，每次mod块都会收起，请考虑是否优化

附,操作动图：
![crtl_z](https://user-images.githubusercontent.com/21214285/40636038-acb633ba-632f-11e8-93e9-9155061b1bb3.gif)

**Comment by leopoldchen** [comment]
@kevinxft 
目前已在undo manager中存储了行号，所以可以考虑undo时对于当前行号所处的mod做特殊处理

**Comment by Sandu1213** [comment]
stage验证通过
