### ISSUE TITLE
【调整】考虑mouseover才显示操作按钮，现在太乱

### ISSUE THREAD

**Issue by ouyc** [tatfook/keepwork#713]
@azothli commented on [Thu May 17 2018](https://github.com/tatfook/KeepWorkDesgin/issues/39)

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/53dead49-66db-4082-bae6-15d90aacc35f)

---

@wanglin727 commented on [Thu May 24 2018](https://github.com/tatfook/KeepWorkDesgin/issues/39#issuecomment-391567817)

开始设计就是mouseover 出现icon，转开发

**Comment by Sandu1213** [comment]
stage环境验证通过
