### ISSUE TITLE
Git Gateway - repo tree managment

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#717]
### 目标

添加repo的管理

### 指标

- [x] 集成gitlab（读）和redis（写cache）
- [x] 实现相关api
- [x] 对接kafka
- [x] 对接delay service

**Comment by leopoldchen** [comment]
已集成gitlab project和tree的读取

**Comment by leopoldchen** [comment]
转向使用nodejs开发

**Comment by William0911** [comment]
已上线
