### ISSUE TITLE
【Bug-editor】editor编辑器优化问题

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#720]
## The problem
editor编辑器优化问题

## Environment
* OS Info: Window10
* browser Info: chrome  66.0.3359.181
* URL: [release.keepwork.com](http://release.keepwork.com) 
* Model:  editor ->file menu

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor编辑器里，当未打开文件时，观察左侧文件树情况
2.打开多个文件，观察文件显示情况及左侧文件树的情况

* Expected Result:
1.当未打开文件时，不显示“已打开”菜单项
2.当打开多个文件后，左侧已打开文件里也有高亮标识，便于用户快速识别操作的文件

* Actual Result:
1.已打开文件列一直显示，需要调整
2.缺少高亮标识
 

## Attachments (eg:logs/video/screenshot)
![file_list2.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/c80e1515-dbd8-4f2c-9704-2be2ef0985a9)

**Comment by kevinxft** [comment]
😂

**Comment by Sandu1213** [comment]
已打开数量暂时不限制，高亮效果已实现
