### ISSUE TITLE
【Bug-layout】当给“我参与的网站”进行设置layout后，进行查看，发现无法正常查看网站，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#729]
## The problem
当给“我参与的网站”进行设置layout后，进行查看，发现无法正常查看网站，请调整

## Environment

* OS Info: Window10
* browser Info: chrome  66.0.3359.181
* URL: [keepwork.com](https://keepwork.com) 
* Model:  layout

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入editor编辑器，打开“我参与的网站”对layout进行设置，设置完成后，去新页面查看设置的效果

* Expected Result:
1.页面可以正常打开，显示效果与设置的一致
* Actual Result:
1.页面无法正常打开

**Comment by duting1993** [comment]
测试账号：release1
密码：123456
@yuanoook
