### ISSUE TITLE
【Bug-导航路径】当网站的网页文件过多时，通过导航路径进行快速筛选，显示不合理，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#731]
## question:
1.打开含有多个网页文件的网站进行查看，通过导航路径进行筛选时，观察页面显示效果

![pageshow0.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/38d535ea-e2b0-4744-bba5-64edf6a9288c)

**Comment by leopoldchen** [comment]
@azothli 需要设计

**Comment by azothli** [comment]
@wanglin727  设定长度，然后加滚动条吧

**Comment by wanglin727** [comment]
屏幕中显示高度380px。内容多做滚动处理

**Comment by Sandu1213** [comment]
上下空白页是否可以做优化？ @ZhangKaitlyn 
![image](https://user-images.githubusercontent.com/21214285/41278995-de01129e-6e5d-11e8-967c-e4376e92bec1.png)
