### ISSUE TITLE
【需求】网站文件重命名

### ISSUE THREAD

**Issue by wanglin727** [tatfook/keepwork#737]
@ouyc commented on [Tue May 15 2018](https://github.com/tatfook/KeepWorkDesgin/issues/35)

@leopoldchen commented on [Fri Apr 13 2018](https://github.com/tatfook/keepwork/issues/207)

@azothli commented on [Mon Dec 04 2017](https://github.com/tatfook/wikicraft/issues/1096)

已经创建的文件，需要提供重命名功能

---

@leopoldchen commented on [Mon May 14 2018](https://github.com/tatfook/keepwork/issues/207#issuecomment-388735665)

@azothli 这个交互上是怎样的，有加过设计吗？                       

---

@azothli commented on [Tue May 15 2018](https://github.com/tatfook/keepwork/issues/207#issuecomment-389063034)

![image](https://user-images.githubusercontent.com/22001356/40041133-91b2300e-584f-11e8-82ed-0c81dfb210af.png)
文件夹、文件 增加一个 重命名的按钮
点击后，目录树中的对应项变为文本输入模式，显示当前的文件名
![image](https://user-images.githubusercontent.com/22001356/40041219-d7a7bc28-584f-11e8-9506-6b41cff9a11b.png)
用户可以修改其中的文件名，在回车或者切换焦点的时候保存（检测是否合法：命名规则、是否有重名，如果不是合法可用的，不进行修改，同时在系统提示区域给出修改失败与原因的提示）

---

@wanglin727 commented on [Fri Jun 01 2018](https://github.com/tatfook/KeepWorkDesgin/issues/35#issuecomment-393775751)

![image](https://user-images.githubusercontent.com/33826048/40824934-8c753620-65a8-11e8-8737-b5891e3eae2d.png)

![image](https://user-images.githubusercontent.com/33826048/40824948-9739901a-65a8-11e8-8d79-e01a439932c2.png)
源文件  svn

**Comment by kevinxft** [comment]
存在有时候会错误提示未保存文件，就是#807的的bug，不用再开新的issue @Sandu1213

**Comment by Sandu1213** [comment]
## question:
1.已打开列表里也需要支持
2.还需要支持文件夹的改名
3.提示语建议也调整下样式
![image](https://user-images.githubusercontent.com/21214285/41154934-720cf434-6b4e-11e8-905c-5d4df116a269.png)

**Comment by Sandu1213** [comment]
- 问题1：还未解决 
- 问题2：文件夹改名失败
![image](https://user-images.githubusercontent.com/21214285/41280211-f9bf8df0-6e60-11e8-873b-e5b57787a53b.png)

**Comment by Sandu1213** [comment]
样式问题，请调整
![image](https://user-images.githubusercontent.com/21214285/41338085-ac2b68c0-6f23-11e8-917c-8a754e5115c2.png)

**Comment by Sandu1213** [comment]
release环境验证通过
