### ISSUE TITLE
图片管理器---图片上传进度

### ISSUE THREAD

**Issue by wanglin727** [tatfook/keepwork#739]
@wanglin727 commented on [Fri Jun 01 2018](https://github.com/tatfook/KeepWorkDesgin/issues/48)

---

@wanglin727 commented on [Fri Jun 01 2018](https://github.com/tatfook/KeepWorkDesgin/issues/48#issuecomment-393784077)

源文件 svn

---

@wanglin727 commented on [Fri Jun 01 2018](https://github.com/tatfook/KeepWorkDesgin/issues/48#issuecomment-393784164)

![image](https://user-images.githubusercontent.com/33826048/40826468-4343a252-65ad-11e8-9bb6-d80c60ccfed6.png)

---

@wanglin727 commented on [Fri Jun 01 2018](https://github.com/tatfook/KeepWorkDesgin/issues/48#issuecomment-393786519)

![image](https://user-images.githubusercontent.com/33826048/40826830-68b8d268-65ae-11e8-849e-3702d882166e.png)

svn--源文件

**Comment by Sandu1213** [comment]
大文件上传的还缺少进度条
