### ISSUE TITLE
Style预览组件

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#74]
### 背景

当前是样式预览方案是显示ui设计师提供的图片，考虑到将来有大量的mod和style，这部分的工作量会比较繁琐。如果使用实时预览，一方面可以免去这个制作图片的工作，另一方面也可以真正实现有效的预览，即预览的数据就是选择后会显示出的实际样式。

### 目标

开发一个组件，可以在选择样式时，预览显示其实时数据。

### 指标

1. 实现预览组件，基于实时数据预览。（注：在新建mod时，使用default数据）
2. 预览结果与组件加入viewport之后的显示是一致的。
3. 支持pc和手机两种模式

**Comment by Sandu1213** [comment]
1.QQ text关闭时，显示不合理
![image](https://user-images.githubusercontent.com/21214285/39512783-b88ebd26-4e24-11e8-8ff2-a8ab4f29bc01.png)
2.mix_layer 去掉背景图后，字体颜色太淡
![image](https://user-images.githubusercontent.com/21214285/39512866-fe2f184e-4e24-11e8-9acd-c34f717aa574.png)
3.mix_position 预览样式问题
![image](https://user-images.githubusercontent.com/21214285/39512991-62ae396c-4e25-11e8-95af-275ed5654704.png)
4.VIP mod显示样式不一致
![image](https://user-images.githubusercontent.com/21214285/39513201-24ee73c0-4e26-11e8-9081-c1e2bf819493.png)

**Comment by Sandu1213** [comment]
问题依然存在，请调整；
问题3：主要是指选中“上图下文的”样式后，再切换到样式列查看，显示不符
问题4：
- 开启状态时，描述内容显示不一致
- 关闭后，建议参考comment mod的实现，直接显示空白很奇怪

**Comment by onedou** [comment]
此issue关闭，将新开issue单独处理

**Comment by onedou** [comment]
https://app.zenhub.com/workspace/o/tatfook/keepwork/issues/401
