### ISSUE TITLE
【Bug-大文件】编辑器里插入文件，插入非图片文件，显示不合理，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#744]
### question:
操作：
1.直接插入文件到编辑器里，观察显示情况
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/89ba07c6-14bc-4005-bc63-b43f53bb860e)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/40909949-7403c698-681d-11e8-8b7c-c4f914687487.png)
插入文件时，建议插入一个换行在插入

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/40910003-92e58f88-681d-11e8-807f-0dfe650ac355.png)
插入MP4后，在插入PDF，docx，保存文件，新连接打开，没有显示MP4
![image](https://user-images.githubusercontent.com/28430070/40910050-b529fb1a-681d-11e8-8512-2c2d105a28e6.png)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/40910090-ce209566-681d-11e8-8d20-2fe0680f610a.png)
插入文件，右边显示部分，如何显示，找产品确认
