### ISSUE TITLE
【Bug-contributed website】目前参与网站信息显示不够明确，建议增加相关的用户信息与网站关联

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#745]
### Steps:
1.用户A和用户B 分别都有网站keepwork；两个网站拥有共同的参与者C，
2.登陆用户C 的账号，登陆成功后，观察“我参与的网站”里列表显示情况，是否可以快速进行区分

**Expected Result:**
1.可以快速区分网站的归属和详情

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/39350cfb-454d-4588-a6e8-90a380e0165a)

**Comment by leopoldchen** [comment]
@azothli 修改好后请添加回复

**Comment by azothli** [comment]
使用/username/siteurl（站点名称）
例如：
/liyu/mywork(李宇的工作记录)

**Comment by Sandu1213** [comment]
stage环境验证通过
![image](https://user-images.githubusercontent.com/21214285/41579128-2f5c8cf8-73c8-11e8-8b4d-874d3da7396e.png)
