### ISSUE TITLE
网站模板&网页模板 技术解决方案

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#754]
准备在新版KeepWork里添加网站模板和网页模板支持。
暂定的方案是和以前相似，在KeepWork里编辑和设计网站模板或者网页模板。
新建网站或者新建网页时也需要有相关的支持

**Comment by yuanoook** [comment]
可以考虑把网站模板数据（文件）存储到用户的默认仓库里面。用户可以把现有网站/页面保存为模板，在模板管理里面可以增删查改。新建网站/页面的时候，要采用模板的，直接拷贝模板文件就行了。

**Comment by yuanoook** [comment]
同李宇确认，网页模板功能同网站模板类似。模板内容和图标需要李宇和设计提供。
