### ISSUE TITLE
面包屑设计

### ISSUE THREAD

**Issue by enya-i** [tatfook/keepwork#760]
@enya-i commented on [Mon Jun 04 2018](https://github.com/tatfook/KeepWorkDesgin/issues/53)

![`%Z5769PU9({CTH0XO}A0E5.png](https://images.zenhubusercontent.com/5aaf5b544b5806bc2bcb5c1a/ff633047-a1ad-43ce-a1c9-f45af960510c)

---

@enya-i commented on [Mon Jun 04 2018](https://github.com/tatfook/KeepWorkDesgin/issues/53#issuecomment-394267495)

![default](https://user-images.githubusercontent.com/37529364/40905379-4ebd47b8-6810-11e8-8f7a-315bd9d07752.png)

**Comment by enya-i** [comment]
https://assets.npl.lan:4403/svn/UI_resource/ADI--界面效果图  wl/新版  ADI/面包屑设计 #760

**Comment by Sandu1213** [comment]
重复问题，通过 #751 进行跟进。
