### ISSUE TITLE
【Bug-layout】Keepwork的网站在手机上的样式显示都不对，会出现正文无法显示的情况

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#761]
## Steps:
1.先在电脑端创建具有不同样式的网站
2.再打开手机，在手机浏览器上进入keepwork网站进行查看，观察内容和样式是否显示正确

![layout_moblie](https://user-images.githubusercontent.com/21214285/40910441-bae46c10-681e-11e8-9c42-950a9135c6a1.png)

**Comment by Sandu1213** [comment]
@azothli  @wanglin727 请尽快提供手机上的layout样式图

**Comment by azothli** [comment]
Issue moved to [tatfook/KeepWorkDesgin #57](https://github.com/tatfook/KeepWorkDesgin/issues/57) via [**ZenHub**](https://www.zenhub.com/)
