### ISSUE TITLE
【Bug-mod】图片轮播mod还未实现图片选择功能，请完善

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#762]
## Operation:
1.进入editor页面，选择添加图片轮播mod，添加完成后，对图片进行设置，观察是否可以正常的
选择图片

**Expected Result:**
1.可以正常的选择图片进行添加或者修改

**Actual Result:**
1.目前还是无法选择图片

![loopimg_filter.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/4a187d03-ca99-44e3-b9c7-45a46d42e28c)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/41228644-a7aeab1e-6dab-11e8-82f4-0407c5b39406.png)
 
![image](https://user-images.githubusercontent.com/33826048/41228649-ad4bd3ee-6dab-11e8-8dc8-59936d33b2c4.png)
![image](https://user-images.githubusercontent.com/33826048/41228658-b1758b2c-6dab-11e8-963a-6fedf261b472.png)


设计稿 svn
![image](https://user-images.githubusercontent.com/33826048/41228747-ff429fc0-6dab-11e8-82ef-e1614d4662be.png)

**Comment by Sandu1213** [comment]
删除按钮鼠标移入的时候请标记为红色
