### ISSUE TITLE
【Bug-私有网站】直接访问私有网站，页面处理不合理去，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#773]
## The problem
直接访问私有网站，页面处理不合理去，请调整

## Environment
* OS Info: Window10
* browser Info: chrome  66.0.3359.181
* URL: [keepwork.com](https://keepwork.com) 
* Model:  website -> private site

## Step To Reproduce Issue [ Good To Have ]
* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号
* Details:
1.用户未登录时，直接访问私有网站进行查看，如：https://keepwork.com/keepwork/pwiki
2.用户登录后，再次访问私有网站进行查看，观察显示情况

* Expected Result:
1.未登录时，提示用户需要进行登录才能查看（引用常规登录窗口，而不是小窗口）
2.用户已登录，判断用户是否有访问查看权限，如果有，则正常展示内容，否则，提示请开通VIP
* Actual Result:
1.弹窗窗口不合理
2.显示一片空白

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/c0e49544-b192-4d44-8fdd-f2289e770acf)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/969bf697-c912-47a7-85df-f0f392c35185)

**Comment by Sandu1213** [comment]
@azothli  宇哥，请帮忙确认下，如果没有权限查看的时候，是直接提示“无权限访问”还是提醒“购买VIP后即可查看”？

**Comment by azothli** [comment]
无权限访问
这个跟付费无关，付费了也不能看的

**Comment by azothli** [comment]
调用404提示页面

**Comment by Sandu1213** [comment]
**目前处理还是不对,请调整**
**正确处理方式：1.未登录时进行查看，提示用户需要登陆
                             2.登陆成功后，如果有权限则正常显示页面，如果没有权限，则出现404提示页**
![image](https://user-images.githubusercontent.com/21214285/41462950-433edc48-70c7-11e8-977b-a8e854b2f672.png)
