### ISSUE TITLE
【Bug-editor】首次进入editor页面，URL 地址显示不合理，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#784]
## Issues:
the url address is invalid, when open the editor page first

## Reproduce:
1. login in , go to wikieditor page, obverse the value about the url

**Expected Result:**
1. the url address is empty,when open the page first

**Actual Result:**
1.the url address display unreasonable

**Attachment files:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/3b82705c-3139-491d-802b-245a18f79eb7)

**Comment by ZhangKaitlyn** [comment]
https://release.keepwork.com/wiki/vip
