### ISSUE TITLE
【Bug- 欢迎页】欢迎页样式显示不合理，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#785]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/22f2d1df-2aac-46af-acc9-05f98c5b088e)

**Comment by Sandu1213** [comment]
@wanglin727  请优化下该设计图

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/41086922-f85ce3dc-6a6d-11e8-98fa-2ddd069ce312.png)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/41087031-36fab2ea-6a6e-11e8-8129-08c70b2ea465.png)

设计稿  suv
