### ISSUE TITLE
【Bug-网盘】网盘浏览器兼容性调整及页面显示调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#791]
![image](https://user-images.githubusercontent.com/21214285/41076819-fecf016e-6a45-11e8-8592-0eaaaae54278.png)
![image](https://user-images.githubusercontent.com/21214285/41076883-64db7ece-6a46-11e8-9ef3-2786f270922c.png)

**Comment by yuanoook** [comment]
排序按钮，现在是采用的 ElementUI 的官方设计标准。好不好看这种【主观感受】，很难统一标准。

**Comment by yuanoook** [comment]
排序的两个箭头是指示，不是按钮，点击表头的字就可以排序了。
