### ISSUE TITLE
【Bug-第三方注册】目前第三方注册功能不可用，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#792]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/896c982b-20ba-4b9e-8939-97a9b08c66d3)

目前线上的第三方登录都不可用了，请一同调整下：
![image](https://user-images.githubusercontent.com/21214285/41414596-13668fe2-7019-11e8-929f-17c79ca7c72a.png)

**Comment by yuanoook** [comment]
第三方登陆，绑定老用户，点击没反应，已经修复
https://github.com/tatfook/wikicraft/pull/1841/files

其他问题后面继续跟踪。
