### ISSUE TITLE
【Bug-editor】editor 部分调优问题汇总

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#793]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/e79eb130-22a8-4fde-a38d-ad1e2e18062b)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/41151587-ca605afa-6b43-11e8-9cc0-b8e343df7257.png)
--- 这个问题还是未调整，请调整

**Comment by DDXY1230** [comment]
@Sandu1213 你可以看下issue#600，UI 那边调整了，你看看这个问题要不要关闭，，。。。

**Comment by azothli** [comment]
这里没有icon了就不用改了，不过我们做ui有一个原则
只要是能点的icon，mouseover都应该有文字提示
@Sandu1213

**Comment by Sandu1213** [comment]
收到，这里的都是可以点的 icon；
建议提示语分别：“文件列表“，“MOD”,"网盘管理”。
具体以产品定义为准 @DDXY1230

**Comment by DDXY1230** [comment]
文件，模块，网盘     。。。。。。。。。files，，modules，，networkDisk

**Comment by Sandu1213** [comment]
网盘 请调整为：CloudDrive
