### ISSUE TITLE
【Bug-mod】mod的归类分层不够明确，请完善

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#795]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/2c79e56e-5cb0-4df1-9da6-d312c0cb40fa)

**Comment by Sandu1213** [comment]
@azothli  @wanglin727  是否可以提供一个明确的层级设计图或者例子？

**Comment by onedou** [comment]
是否和 #806 相同？

**Comment by azothli** [comment]
不同，那个是调整内容与顺序
这个是美术样式

**Comment by onedou** [comment]
好的

**Comment by Sandu1213** [comment]
设计图地址：
https://assets.npl.lan:4403/svn/UI_resource/ADI--界面效果图  wl/新版  ADI/#42 目录 list

**Comment by onedou** [comment]
上面的设计图旧的
![image](https://user-images.githubusercontent.com/3422640/42250719-87b7bfd2-7f65-11e8-8195-91e0db3f25e7.png)

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/42252047-53cb9a2e-7f6d-11e8-8e3d-08a49a6e57b2.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/42262038-9e17fba2-7f9c-11e8-8295-99ee6c96cf23.png)

鼠标移入后才加黑；具体项不需要加粗加黑，只处理类别名
