### ISSUE TITLE
【Bug-删除弹窗】文件夹删除的时候，建议列出具体的删除内容

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#796]
### Issues:
   进入editor页面，对不用的文件夹进行删除操作，观察删除弹窗情况

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/8067ebda-f8c9-4205-bd17-2446594ff010)

**Comment by duting1993** [comment]
stage已验证

**Comment by azothli** [comment]
确定删除
/liyu/mywork/dadasd/asdasd/dfgsdfg/sdfghsdh/sdfgdg/asda
asda/sgdfg/fdsgdfg/sdfgd/sdfgsd/
及其中所有内容么？

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/41460283-c2caabc6-70be-11e8-8447-282bebba74f4.png)
