### ISSUE TITLE
【Bug-cache】编辑器缓存问题，请优先调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#798]
## Steps:

1.进入编辑器页面，打开多个文件，如：文件A、B、C
2.进入文件A里进行编辑，编辑完成后，切换到文件B进行编辑。
3.在未保存的情况下，直接关闭文件A，观察是否有弹窗提醒   ---目前缺少
4.如果弹窗提醒选择不保存，再次打开文件A，观察文件A的显示是否合理  --- 正常情况应该显示文件A原始不含编辑的信息(目前会出现再次打开文件A，无法切换过去的情况，即一直显示文件B)

**Comment by kevinxft** [comment]
#### 现在根据我的理解增加了点交互 ✍
- 关闭未保存文件会弹框提示
- 右上角X取消本次操作，还有不保存关闭，保存并关闭
- 如果当前页面处于编辑区，则关闭后激活其他已打开的文件
- 如果当前页面是最后一个，则直接关闭


![TIM截图20180614202328.png](https://images.zenhubusercontent.com/59edff22a468affe6df7caf6/48f4e5dc-6f1b-4cb1-b7fa-d994ea12b994)

**Comment by kevinxft** [comment]
![TIM截图20180614202328.png](https://images.zenhubusercontent.com/59edff22a468affe6df7caf6/873cbeef-2f9c-4ebc-ac3b-0bcaf0a19c0a)

**Comment by kevinxft** [comment]
![TIM截图20180614202328.png](https://images.zenhubusercontent.com/59edff22a468affe6df7caf6/410eb9e8-bc5c-47a5-bdeb-2799e2dc5f64)
