### ISSUE TITLE
【Bug-网盘管理】网盘管理的重命名存在问题，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#800]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/1844d5da-a342-4861-a860-00b287cdfe92)

**Comment by leopoldchen** [comment]
重命名没有做校验

**Comment by ZhangKaitlyn** [comment]
用户上传的文件不需要敏感词检测

**Comment by ZhangKaitlyn** [comment]
检测的特殊字符： / \ * ? | : < >
