### ISSUE TITLE
【调整】个人设置中心

### ISSUE THREAD

**Issue by wanglin727** [tatfook/keepwork#802]
@azothli commented on [Fri Jun 01 2018](https://github.com/tatfook/KeepWorkDesgin/issues/50)

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/34900d91-9338-4485-94c2-b1a18e0110d4)

---

@wanglin727 commented on [Thu Jun 07 2018](https://github.com/tatfook/KeepWorkDesgin/issues/50#issuecomment-395336315)

![image](https://user-images.githubusercontent.com/33826048/41087446-4e4f303c-6a6f-11e8-855f-71f156520d36.png)

---

@wanglin727 commented on [Thu Jun 07 2018](https://github.com/tatfook/KeepWorkDesgin/issues/50#issuecomment-395336987)

![image](https://user-images.githubusercontent.com/33826048/41087571-a50b9866-6a6f-11e8-859c-bc7e425391ab.png)
设计稿 svn

**Comment by leopoldchen** [comment]
应该可以拆成多个任务进行开发

**Comment by ouyc** [comment]
已拆分issues
