### ISSUE TITLE
【调整】系统header，个人菜单调整

### ISSUE THREAD

**Issue by wanglin727** [tatfook/keepwork#803]
@azothli commented on [Fri Jun 01 2018](https://github.com/tatfook/KeepWorkDesgin/issues/49)

![image](https://user-images.githubusercontent.com/22001356/40828727-0b5b7dfe-65b4-11e8-9cc4-b6d99768daa4.png)
![image](https://user-images.githubusercontent.com/22001356/40828874-6f6b93b0-65b4-11e8-8b1d-a76af2c53bf6.png)

---

@wanglin727 commented on [Thu Jun 07 2018](https://github.com/tatfook/KeepWorkDesgin/issues/49#issuecomment-395336384)

![image](https://user-images.githubusercontent.com/33826048/41087467-5d67ff18-6a6f-11e8-9823-baf63e080b66.png)

---

@wanglin727 commented on [Thu Jun 07 2018](https://github.com/tatfook/KeepWorkDesgin/issues/49#issuecomment-395337210)

设计稿 svn
![image](https://user-images.githubusercontent.com/33826048/41087627-be9e89e6-6a6f-11e8-96e3-82574f8b32c1.png)

**Comment by Sandu1213** [comment]
release上验证失败，请排查
