### ISSUE TITLE
【Bug-撤销】ctrl+z 最后一步总是撤销不了，请排查

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#807]
## Steps:

1.进入编辑器页面进行编辑操作，编辑后未保存，进行撤销操作，观察撤销情况

**Expected Result:**
1.可以正常撤销成功

**Actual Result:**
1.撤销到最后一步，无法执行下去

**Comment by kevinxft** [comment]
@Sandu1213 好像这个问题主要出现在新建的文件，只要这个文件改过了，就不会出现这个问题。

**Comment by Sandu1213** [comment]
release环境验证通过
