### ISSUE TITLE
【Bug-用户动态】个人首页里的用户动态信息显示有误，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#809]
## Operations:
1.用户A设置好头像后，去用户B的个人首页页面进行关注操作，观察完成后，观察用户B的个人动态情况

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/4422b2ae-1ba1-4dfd-9303-f06be8c86ed9)

**Comment by leopoldchen** [comment]
新版本设计里也有动态，不过应该会延后实现
