### ISSUE TITLE
【Bug-editor】editor右侧的菜单按钮排版问题，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#819]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/4a9b6f0b-cb21-4ff6-9f0f-1e5c45fd7207)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/41893839-9db33abc-794f-11e8-9424-368ce91f3b16.png)

**Comment by Sandu1213** [comment]
拖到viewport 后，菜单栏调整显示不合理
![image](https://user-images.githubusercontent.com/21214285/42316651-f2efeb22-807c-11e8-9a63-e817c765bacd.png)
