### ISSUE TITLE
【Bug-localstorage】当打开的文件较多且文件编辑的内容量较大时，再次进行保存很容易出现localstorage超限的问题，请调整优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#820]
## Questions:
1.进入编辑器页面，打开多个页面进行编辑操作，然后选择新建一个文件A，填写文件内容如附件；
2.添加完成后，进行保存操作，观察保存是否成功

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/b8d58744-2f51-4066-b45f-3ac41fba324d)
---
[file](https://app.zenhub.com/files/93549057/dfa7a7b4-6657-4d79-affb-83e20bfe2a6c/download)

**Comment by Sandu1213** [comment]
该问题影响很严重，会导致这个浏览器都卡死，稍后请优先处理

**Comment by leopoldchen** [comment]
之前应该已经修复

**Comment by Sandu1213** [comment]
stage环境已验证通过
