### ISSUE TITLE
wikicraft域名绑定

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#826]
由于还有诸多mod在新版本中没有实现，无法正常显示。
为方便做页面迁移，我们需要有可以查看旧设计的地方。
但是旧的网站对域名有严格要求，运维无法独立解决新域名下的网站使用问题，需要开发配合。

**Comment by leopoldchen** [comment]
@DreamAndDead                        

可直接改代码部署

**Comment by DreamAndDead** [comment]
尝试从 wikicraft 项目 master 分出 test 分支，部署 test.keepwork.com

修改了 由域名判断环境的代码，对接线上的数据库数据，部署于  https://test.keepwork.com

可以登陆，但是后续有一些接口不通，需要再调整 @leopoldchen @yuanoook
