### ISSUE TITLE
【海外版】汇总 New Editor Translation Problems

### ISSUE THREAD

**Issue by yuanoook** [tatfook/keepwork#836]
![image](https://user-images.githubusercontent.com/28430070/41215242-fdafef20-6d81-11e8-86d6-827e1cdee02e.png)
![image](https://user-images.githubusercontent.com/28430070/41215258-1a5de08c-6d82-11e8-9a27-9be8f9356e5c.png)
![image](https://user-images.githubusercontent.com/28430070/41215266-229b6e5e-6d82-11e8-9ae5-52774b355b2c.png)
![image](https://user-images.githubusercontent.com/28430070/41215274-2a954184-6d82-11e8-84f6-9fa3c225bde3.png)

@wanglin727  We need design support with the images

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/41274258-5d3087de-6e4f-11e8-8a99-1bbfedf016b0.png)
![image](https://user-images.githubusercontent.com/28430070/41274285-726ab2e6-6e4f-11e8-90e1-f8230c1ae5bc.png)
![image](https://user-images.githubusercontent.com/28430070/41274309-83d1beee-6e4f-11e8-9f21-fbbc1935f5c6.png)
![image](https://user-images.githubusercontent.com/28430070/41274339-996323b0-6e4f-11e8-863d-3ef091794468.png)
![image](https://user-images.githubusercontent.com/28430070/41274393-cab50014-6e4f-11e8-9918-f1188c2b6a75.png)
![image](https://user-images.githubusercontent.com/28430070/41274440-fb69913e-6e4f-11e8-8142-719ed7f49c4c.png)
![image](https://user-images.githubusercontent.com/28430070/41274460-0914701a-6e50-11e8-87d8-9cbfd0ce5b3e.png)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/41274530-4f6673ba-6e50-11e8-9ab8-af716a09f2e7.png)
![image](https://user-images.githubusercontent.com/28430070/41274557-69fd9d52-6e50-11e8-8cc3-a45eff751e75.png)
![image](https://user-images.githubusercontent.com/28430070/41274571-71adac4a-6e50-11e8-8261-580016076b16.png)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/41274615-9cc481ec-6e50-11e8-9887-8983a9781d57.png)
![image](https://user-images.githubusercontent.com/28430070/41274692-ec46f4f2-6e50-11e8-9787-170ea30d7708.png)
![image](https://user-images.githubusercontent.com/28430070/41274707-02aaa1f8-6e51-11e8-8c7c-c9d7be336ae3.png)

![image](https://user-images.githubusercontent.com/28430070/41274806-597c5b2a-6e51-11e8-9613-ab7181b8e983.png)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/41275128-773cbce4-6e52-11e8-855c-362d122430d6.png)

![image](https://user-images.githubusercontent.com/28430070/41275144-839480bc-6e52-11e8-8d2e-b62cce4df4e1.png)
海外版VIP此功能已屏蔽，网站设置中的有VIP，这些功能如何处理，需产品定义 @azothli

**Comment by Sandu1213** [comment]
![331](https://user-images.githubusercontent.com/21214285/41333238-a679acda-6f13-11e8-8f84-d6884b0c6482.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/41335850-d59862fa-6f1c-11e8-9c31-2e4deac33dfc.png)
![image](https://user-images.githubusercontent.com/21214285/41335908-0e7b661c-6f1d-11e8-9ac7-8444f9b92a78.png)

**Comment by Sandu1213** [comment]
@yuanoook  已和产品确认，涉及VIP的都需要调整，全部屏蔽

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/41390335-bb15270a-6fc7-11e8-9bf3-c3f229afdbe2.png)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/41640161-57ed72f6-7493-11e8-9af0-f295ef18eb24.png)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/41640197-75aa18c6-7493-11e8-8bb4-42683d585999.png)

**Comment by yuanoook** [comment]
大部分都已经改过了，新的问题请提新单

**Comment by duting1993** [comment]
https://github.com/tatfook/keepwork/issues/1134
此问题，关闭，修改根据新单
