### ISSUE TITLE
网盘服务 - 暂时取消审核限制

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#841]
初步审核考虑对接qiniu鉴黄鉴暴功能，但是暂时还没有时间去做这项工作；另外，目前运营团队没有组建，无人做后台审核。
因此，先去除审核机制，默认设置为审核通过。

**Comment by William0911** [comment]
测试环境: release

**Comment by Sandu1213** [comment]
旧用户及新用户都可以正常上传，无需审核，验证通过
