### ISSUE TITLE
【需求】请设计一个可以快速返回顶部的页面设计图

### ISSUE THREAD

**Issue by enya-i** [tatfook/keepwork#844]
@Sandu1213 commented on [Fri Jun 08 2018](https://github.com/tatfook/KeepWorkDesgin/issues/64)

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/bd0233ff-c58c-4d4d-a22b-9e37889d1431)

---

@enya-i commented on [Mon Jun 11 2018](https://github.com/tatfook/KeepWorkDesgin/issues/64#issuecomment-396132185)

![image](https://user-images.githubusercontent.com/37529364/41215254-141abd30-6d82-11e8-82ae-2c0df144f9e6.png)

**Comment by leopoldchen** [comment]
@azothli  @enya-i 
这个是全部页面都有的嘛？

**Comment by enya-i** [comment]
对，通用的！

**Comment by Sandu1213** [comment]
看不到效果，请确认是否合入？另外需要考虑旧的wikicraft项目，及home页也需要有快速回到顶部的按钮

**Comment by DDXY1230** [comment]
dev上面，往下拉动2160px之后才会出现

**Comment by Sandu1213** [comment]
release环境已验证；
目前新keepwork的项目已经添加（editor及新页面），旧的wikicraft项目没有添加（首页/个人主页等）
