### ISSUE TITLE
滚动条样式修改

### ISSUE THREAD

**Issue by enya-i** [tatfook/keepwork#847]
- 浏览器自带滚动条不太美观，与界面风格稍有不搭

![%JE}MWKD8Q0$D%)XCF6(R}5.png](https://images.zenhubusercontent.com/5aaf5b544b5806bc2bcb5c1a/524f42bb-6d66-4c5c-9028-7febf1804c2c)

- 建议修改成如下图的滚动条样式

![image.png](https://images.zenhubusercontent.com/5aaf5b544b5806bc2bcb5c1a/3f917b6b-2c3d-4885-81b9-ce58b8f2ed27)

**Comment by Sandu1213** [comment]
stage环境验证通过
