### ISSUE TITLE
编辑器中的 editMode 的值不准确，有时为 true 有时为 false

### ISSUE THREAD

**Issue by xiaop1ng** [tatfook/keepwork#857]
1. 在编辑器左侧选择 MOD 时：this.editMode 的值为 false
2. 在编辑器中间的预览框中切换 MOD 时： this.editMode 的值为 false @leopoldchen

**Comment by leopoldchen** [comment]
左侧选择mod的时候是不需要this.editMode的判断的，设置为true可以避免一些特殊情况下可能出现的问题。已在style selector里添加
