### ISSUE TITLE
【需求调整】需要出设计图的需求清单

### ISSUE THREAD

**Issue by enya-i** [tatfook/keepwork#864]
@Sandu1213 commented on [Thu Jun 07 2018](https://github.com/tatfook/KeepWorkDesgin/issues/60)

- 显示代码
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/b9be94ce-b529-4821-b2d6-7f70d43666a5)

- 颜色区分
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/8582c859-e105-4cfe-aa57-a2b8ce2bb4e1)

- 编辑器(我创建的网站)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/6183938a-0960-4c01-84f9-85d6a80ec6e5)

---
@enya-i commented on [Wed Jun 13 2018]
(https://github.com/tatfook/KeepWorkDesgin/issues/60#issuecomment-396891481)

以下为设计图

- switch  +  新建
![default](https://user-images.githubusercontent.com/37529364/41345945-a86691a6-6f37-11e8-99db-20a4b466fdea.png)

- zen mode
![zen mode](https://user-images.githubusercontent.com/37529364/41345955-b004453e-6f37-11e8-9da3-1dcc4d99bb5f.png)

**Comment by leopoldchen** [comment]
@azothli 

恢复仅显示代码？

**Comment by azothli** [comment]
是的，还是有这个需要的

**Comment by leopoldchen** [comment]
整体的交互问题呢？adi区域是否得禁用，是否会有其他影响？

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/42160805-25c29a8a-7e2b-11e8-9b8c-d29d9003f707.png)
增加一个互换左右的功能吧
@wanglin727

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/42270718-21107df6-7fb4-11e8-933f-bd281b86b6a9.png)


源文件 svn 
![image](https://user-images.githubusercontent.com/33826048/42270837-64aa03fc-7fb4-11e8-803b-e1b3d7aac20f.png)

**Comment by Kvaya** [comment]
“只有预览 同时显示 只有代码”功能目前不做，预览区和代码区需添加左右切换功能，解决方案如下，按这个来做;
![image](https://user-images.githubusercontent.com/39363297/45524517-6ee85c80-b801-11e8-8b69-d1e9bfb20148.png)

**Comment by Kvaya** [comment]
#864拆分成issue#2509、#2510、#2511、#2512
