### ISSUE TITLE
【Bug】投诉页面的展示信息不对且功能不可用

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#867]
@Sandu1213 commented on [Fri Oct 13 2017](https://github.com/tatfook/wikicraft/issues/761)

## The problem
投诉页面的展示信息不对且功能不可用

## Environment

* OS Info: Window10
* browser Info: chrome  61.0.3163.100
* URL: [keepwork.com](http://keepwork.com) 
* Model:  投诉本页

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.对网页底部的投诉本页进行点击操作，观察显示结果

* Expected Result:
1.投诉功能正常可用
* Actual Result:
1.投诉说明信息不合理且功能不可用
 

## Attachments (eg:logs/video/screenshot)
![default](https://user-images.githubusercontent.com/21214285/31532862-455164f8-b022-11e7-9554-e04ada8bda89.png)

**Comment by azothli** [comment]
1.系统页面 屏蔽该功能，不需要投诉
2.是用来投诉用户创建的非法内容

**Comment by leopoldchen** [comment]
新版本里还没加投诉功能，是否需要增加？

**Comment by leopoldchen** [comment]
@azothli @Kvaya 
是否直接通过qq客服来解决问题？

**Comment by azothli** [comment]
qq还是作为辅助比较好
全部的页面在footer里面都可以保留这个

**Comment by azothli** [comment]
现在知道之前的功能只是一个前端展示，后台什么都没有，现在重新进行设计，等方案出来的吧

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/57755084-90983b80-7722-11e9-904f-57e4a4959c8d.png)
![image](https://user-images.githubusercontent.com/22001356/57755093-95f58600-7722-11e9-85f4-2c2815dc7796.png)

**Comment by azothli** [comment]
后台：
![image](https://user-images.githubusercontent.com/22001356/57755119-a3ab0b80-7722-11e9-9da6-c89b6498bd7c.png)

**Comment by wxaxiaoyao** [comment]
![image](https://user-images.githubusercontent.com/11922085/57757999-49617900-7729-11e9-9c28-cd4c4488a6c2.png)
https://keepwork.com/keepwork/pwiki/dev/backend/keepworkAPI

**Comment by azothli** [comment]
原型图位置
svn://10.27.2.210/Release/keepwork/%E6%8A%95%E8%AF%89%E5%8A%9F%E8%83%BD/%E6%8A%95%E8%AF%89%E5%8A%9F%E8%83%BD.rp

**Comment by dalin00** [comment]
![投诉举报](https://user-images.githubusercontent.com/24222876/58063977-f9643580-7bb2-11e9-8270-148602e77939.jpg)
![image](https://user-images.githubusercontent.com/24222876/58064009-1d277b80-7bb3-11e9-92a6-4cb5eda98180.png)

**Comment by Sandu1213** [comment]
- 1.样式问题
![image](https://user-images.githubusercontent.com/21214285/58229882-628baa80-7d65-11e9-88db-14e48cd838ee.png)

- 2.缺少输入引导语
- 3.投诉举报页面定位不准且重新打开，需要重新初始化数据
![image](https://user-images.githubusercontent.com/21214285/58230103-efceff00-7d65-11e9-85c3-94985173ff61.png)
