### ISSUE TITLE
Viewport支持响应式

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#87]
### 背景

目前viewport无法根据当前真正的宽度来做响应，比如viewport宽度为手机宽度时，应该响应成手机的显示样式。
由于css的media响应是根据浏览器的整体宽度来处理的，与预期效果不一致。解决方案可以考虑iframe或者js实时计算宽度。

### 目标

使用iframe实现viewport的响应式预览

### 指标

- [ ] viewport在不同宽度下有对应的显示方式
- [ ] viewport区域与editor主区域的事件交互与现有版本保持一致
- [ ] 总结基于iframe下的事件交互方法，便于后续开发

**Comment by LiXizhi** [comment]
iframe is not an optimum solution. Is there other ways to do it.

**Comment by leopoldchen** [comment]
@LiXizhi  https://github.com/marcj/css-element-queries
