### ISSUE TITLE
【Bug-文件夹删除】文件夹删除需要具体到路径，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#874]
关联 issue #796
需要设计先出图，然后再做相应的调整

**Comment by Sandu1213** [comment]
设计稍后会补充图，将文件名进行高亮处理，具体以设计为准。

**Comment by kevinxft** [comment]
![TIM图片20180619161039.png](https://images.zenhubusercontent.com/59edff22a468affe6df7caf6/6600b467-9edf-40be-94ab-3807aa95d85d)
