### ISSUE TITLE
【Bug-layout】Keepwork的网站在手机上的样式显示都不对，会出现正文无法显示的情况

### ISSUE THREAD

**Issue by wanglin727** [tatfook/keepwork#894]
@azothli commented on [Wed Jun 06 2018](https://github.com/tatfook/KeepWorkDesgin/issues/57)

@Sandu1213 commented on [Mon Jun 04 2018](https://github.com/tatfook/keepwork/issues/761)

## Steps:
1.先在电脑端创建具有不同样式的网站
2.再打开手机，在手机浏览器上进入keepwork网站进行查看，观察内容和样式是否显示正确

![layout_moblie](https://user-images.githubusercontent.com/21214285/40910441-bae46c10-681e-11e8-9c42-950a9135c6a1.png)

---

@Sandu1213 commented on [Mon Jun 04 2018](https://github.com/tatfook/keepwork/issues/761#issuecomment-394296213)

@azothli  @wanglin727 请尽快提供手机上的layout样式图

---

@azothli commented on [Wed Jun 06 2018](https://github.com/tatfook/KeepWorkDesgin/issues/57#issuecomment-394953802)

为手机的layout设计一款样式吧，不同的变化，我们可以考虑只用一款手机版对应

---

@wanglin727 commented on [Fri Jun 15 2018](https://github.com/tatfook/KeepWorkDesgin/issues/57#issuecomment-397499725)

![image](https://user-images.githubusercontent.com/33826048/41448131-7a7d9884-708b-11e8-9905-76e32706c9f8.png)
![image](https://user-images.githubusercontent.com/33826048/41448195-c6e200de-708b-11e8-9e09-e30da6d97fdd.png)
设计稿--svn

**Comment by ZhangKaitlyn** [comment]
设计有误

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/41762426-4d05a0b6-762d-11e8-865a-af310b0a2b76.png)

![image](https://user-images.githubusercontent.com/33826048/41762882-d6e5b91e-762e-11e8-9736-0d11a247d84b.png)

**Comment by Sandu1213** [comment]
选中的样式不含slidebar，但配置的属性里有slidebar时，样式显示不美观，请优化下

**Comment by Sandu1213** [comment]
sidebar问题由 #1027 跟进，该问题验证通过
