### ISSUE TITLE
【editer】调整“我参与的网站”中对应的权限配置

### ISSUE THREAD

**Issue by wanglin727** [tatfook/keepwork#900]
@azothli commented on [Wed Jun 13 2018](https://github.com/tatfook/KeepWorkDesgin/issues/65)

对于其他管理员，调整为，退出管理员的界面
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/eda8bb9f-e771-47e3-bdd7-1841f922a1de)

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/cae2cbd3-49f7-4f6e-a91d-d449ed299a15)

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/c44cfb8a-f6e9-4077-a81a-e9607ba52ca6)

---

@wanglin727 commented on [Fri Jun 15 2018](https://github.com/tatfook/KeepWorkDesgin/issues/65#issuecomment-397522125)

![image](https://user-images.githubusercontent.com/33826048/41452435-9a43294a-70a4-11e8-9dcd-2f5319f110d7.png)

---

@wanglin727 commented on [Fri Jun 15 2018](https://github.com/tatfook/KeepWorkDesgin/issues/65#issuecomment-397526945)

![image](https://user-images.githubusercontent.com/33826048/41453565-d50644c8-70a8-11e8-91f9-bca5c5eb0149.png)
 svn--设计稿

**Comment by leopoldchen** [comment]
@azothli  @wxaxiaoyao 

以前有这个功能逻辑吗？

**Comment by azothli** [comment]
以前没有，是新增的

**Comment by leopoldchen** [comment]
这个issue需要一起讨论一下 @azothli  @wxaxiaoyao

**Comment by Kvaya** [comment]
目前没有管理员权限设置
