### ISSUE TITLE
【pac】banner图替换

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/keepwork#910]
把
![image.png](https://images.zenhubusercontent.com/59df33a4b0222d5de47b5b3c/be05af9f-0a91-420e-b2a2-0df867dbdd1f)
替换为
![image.png](https://images.zenhubusercontent.com/59df33a4b0222d5de47b5b3c/a7ae3a8a-ae1a-40d7-8c2a-805278bb003e)

**Comment by Sandu1213** [comment]
stage环境验证通过
