### ISSUE TITLE
图文混排--调整

### ISSUE THREAD

**Issue by wanglin727** [tatfook/keepwork#923]
@wanglin727 commented on [Tue Jun 19 2018](https://github.com/tatfook/KeepWorkDesgin/issues/70)

![image.png](https://images.zenhubusercontent.com/5a1298d08a75884b908813d2/7c13f229-83ad-4011-b56d-f94e1c4707cd)

![image.png](https://images.zenhubusercontent.com/5a1298d08a75884b908813d2/993a6121-6422-4380-973a-f9e7f41b5060)

例如：
![image](https://user-images.githubusercontent.com/33826048/41574365-bbcf7124-73b3-11e8-845a-3424d338c5ae.png)

**Comment by Sandu1213** [comment]
还是看不到效果，请确认：
1.图片没有做缩放
2.文字信息没有居中显示
