### ISSUE TITLE
海外版VIP此功能已屏蔽，网站设置中的有VIP，这些功能如何处理，需产品定义

### ISSUE THREAD

**Issue by yuanoook** [tatfook/keepwork#941]
![image](https://user-images.githubusercontent.com/28430070/41275128-773cbce4-6e52-11e8-855c-362d122430d6.png)

![image](https://user-images.githubusercontent.com/28430070/41275144-839480bc-6e52-11e8-8d2e-b62cce4df4e1.png)
海外版VIP此功能已屏蔽，网站设置中的有VIP，这些功能如何处理，需产品定义 @azothli

**Comment by ouyc** [comment]
Issue moved to [tatfook/KeepWorkDesgin #73](https://github.com/tatfook/KeepWorkDesgin/issues/73) via [**ZenHub**](https://www.zenhub.com/)
