### ISSUE TITLE
keepwork 存储服务对接

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#944]
@yuanoook @wxaxiaoyao 

后端已经阶段性完成存储服务的开发工作，可以与前端对接实现具体功能。

主要工作:
将现有的旧版api改为新版存储服务api

**Comment by yuanoook** [comment]
https://keepwork.com/keepwork/pwiki/design/storages
https://keepwork.com/keepwork/wiki/%E6%96%87%E6%A1%A3/storage

**Comment by Sandu1213** [comment]
问题3另外提单跟进，会与big的mod配合相关联

**Comment by yuanoook** [comment]
@Sandu1213 
问题 2 3 已经处理

**Comment by Sandu1213** [comment]
问题1：新上传的gif图片，插入可以正常显示（已上传的gif，文件格式未调整，故插入后还是文件非图片）
问题2：QQ mod的图片设置不成功，请调整
问题3：已经由#1162 进行跟进
问题4：已解决

**Comment by Sandu1213** [comment]
stage环境验证通过
