### ISSUE TITLE
文件管理器 - 以bigfile mod的形式插入文档

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#945]
注： bigfile mod已经可用，url需使用新版存储服务提供的url

**Comment by leopoldchen** [comment]
@azothli 

在编辑器中插入大文件应该有两个选项，一种是插入url（image），一种是插入bigfile mod（video）

**Comment by Sandu1213** [comment]
图片、视频、pdf文档会相应的直接显示；
其他文档格式直接以bigfile的形式显示。

**Comment by Sandu1213** [comment]
pdf暂时还是无法正常查看，请优化

**Comment by Sandu1213** [comment]
pdf暂时以文件的形式展示，稍后再处理
