### ISSUE TITLE
【bug-layout】方案添加 过长时，如图二，正确显示如图一

### ISSUE THREAD

**Issue by duting1993** [tatfook/keepwork#958]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/27a9f1d3-4a30-40d3-9957-26ecf9c9b818)

![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/b6d45866-35b7-4152-b638-b0cd0c9bdddf)

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/41885151-40ec6d38-7929-11e8-8657-afe365fae7d1.png)
