### ISSUE TITLE
【Bug-editor】关闭所有/保存所有功能存在问题，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#966]
![saveall.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/6550d113-8968-4356-80cd-7e634dbecca2)

![saveall2.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/6f995d15-95e1-4580-8198-c3282ee422b9)

**Comment by kevinxft** [comment]
在 release上
