### ISSUE TITLE
【需求】页面设置 新增 页面标题的设置

### ISSUE THREAD

**Issue by wanglin727** [tatfook/keepwork#994]
@azothli commented on [Tue Jun 19 2018](https://github.com/tatfook/KeepWorkDesgin/issues/71)

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/27f0b54c-9ac2-4e4b-bc73-a39daa65d93e)

---

@wanglin727 commented on [Fri Jun 22 2018](https://github.com/tatfook/KeepWorkDesgin/issues/71#issuecomment-399369975)

 
![image](https://user-images.githubusercontent.com/33826048/41767323-e2743488-763b-11e8-9b1e-42d76082a8c6.png)

![image](https://user-images.githubusercontent.com/33826048/41767254-b7468d6a-763b-11e8-94a5-7d65a7f663bf.png)

设计稿svn

**Comment by Sandu1213** [comment]
release验证通过
