### ISSUE TITLE
Lesson - Dashboard

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/keepwork#997]
admin用户管理；邀请码管理

**Comment by leopoldchen** [comment]
决定去除lesson系统里的admin表及相关功能，旧的功能实现不完整，没有做权限过滤。

新的方案将直接使用keepwork的admin机制，并将邀请码的管理界面转移到keepwork dashboard中。

**Comment by leopoldchen** [comment]
邀请码相关的api已经基于keepwork admin机制做好调整。

邀请码的管理界面也需要稍微做调整，生成后直接下载csv（[ng-csv](https://github.com/asafdav/ng-csv)）。

@William0911 邀请码界面你实现一下吧，先不发布，等lesson整体测试后再发布

**Comment by leopoldchen** [comment]
POST https://lessons-stage.keepwork.com/lessons/api/cdkey/build 

```
@params
 number ：Integer  (1-100) 生成数目

注： 需以form形式提交
```

GET https://lessons-stage.keepwork.com/lessons/api/cdkey/list

``` 
@params
psize : Integer 分页大小
pno : Integer 页码

```

**Comment by William0911** [comment]
已完成待lesson上线时发布

**Comment by shirleyluo1130** [comment]
redesign
